In [1]:
! ls /kaggle/input/ua-ru-scraper-simple/ua-ru-scraper-simple/

data	       global_vars.py		  parser_helpers.py
data_legacy    import_dates_using_web.py  reference_data
data_partial   insert_dates_into_df.py	  sandbox.py
df_cleaner.py  oryx_parser.py

In [2]:
! cd /kaggle/input/ua-ru-scraper-simple

In [3]:
import pandas as pd
import numpy as np

In [4]:
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# the performance is tolerable enough on cpu so I will not be wasting my t4 use times
device

device(type='cpu')

In [5]:
path = "/kaggle/input/ua-ru-scraper-simple/ua-ru-scraper-simple/"

In [6]:
! pip install "gymnasium>1.0.0" paddleocr paddlepaddle

Collecting gymnasium>1.0.0
  Downloading gymnasium-1.2.0-py3-none-any.whl.metadata (9.9 kB)
Collecting paddleocr
  Downloading paddleocr-3.1.1-py3-none-any.whl.metadata (22 kB)
Collecting paddlepaddle
  Downloading paddlepaddle-3.1.0-cp311-cp311-manylinux1_x86_64.whl.metadata (8.8 kB)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.11/dist-packages (from gymnasium>1.0.0) (1.26.4)
Requirement already satisfied: cloudpickle>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from gymnasium>1.0.0) (3.1.1)
Requirement already satisfied: typing-extensions>=4.3.0 in /usr/local/lib/python3.11/dist-packages (from gymnasium>1.0.0) (4.14.0)
Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from gymnasium>1.0.0) (0.0.4)
Collecting paddlex>=3.1.0 (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr)
  Downloading paddlex-3.1.4-py3-none-any.whl.metadata (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.2/78.2 kB 3.0 MB/s eta 0:00:00
Requirement already satisfied: PyYAML>=6 in /usr/local/lib/python3.11/dist-packages (from paddleocr) (6.0.2)
Requirement already satisfied: httpx in /usr/local/lib/python3.11/dist-packages (from paddlepaddle) (0.28.1)
Requirement already satisfied: protobuf>=3.20.2 in /usr/local/lib/python3.11/dist-packages (from paddlepaddle) (3.20.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from paddlepaddle) (11.2.1)
Requirement already satisfied: decorator in /usr/local/lib/python3.11/dist-packages (from paddlepaddle) (4.4.2)
Collecting opt_einsum==3.3.0 (from paddlepaddle)
  Downloading opt_einsum-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from paddlepaddle) (3.5)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>=1.21.0->gymnasium>1.0.0) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>=1.21.0->gymnasium>1.0.0) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>=1.21.0->gymnasium>1.0.0) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>=1.21.0->gymnasium>1.0.0) (2025.2.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>=1.21.0->gymnasium>1.0.0) (2022.2.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>=1.21.0->gymnasium>1.0.0) (2.4.1)
Requirement already satisfied: chardet in /usr/local/lib/python3.11/dist-packages (from paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (5.2.0)
Requirement already satisfied: colorlog in /usr/local/lib/python3.11/dist-packages (from paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (6.9.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (3.18.0)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.11/dist-packages (from paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (0.33.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (25.0)
Requirement already satisfied: pandas>=1.3 in /usr/local/lib/python3.11/dist-packages (from paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (2.2.3)
Requirement already satisfied: prettytable in /usr/local/lib/python3.11/dist-packages (from paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (3.16.0)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.11/dist-packages (from paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (9.0.0)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.11/dist-packages (from paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (2.11.7)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (2.32.4)
Collecting ruamel.yaml (from paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr)
  Downloading ruamel.yaml-0.18.14-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: ujson in /usr/local/lib/python3.11/dist-packages (from paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (5.10.0)
Requirement already satisfied: einops in /usr/local/lib/python3.11/dist-packages (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (0.8.1)
Collecting ftfy (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr)
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Collecting GPUtil>=1.4 (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr)
  Downloading GPUtil-1.4.0.tar.gz (5.5 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Jinja2 in /usr/local/lib/python3.11/dist-packages (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (3.1.6)
Collecting opencv-contrib-python==4.10.0.84 (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr)
  Downloading opencv_contrib_python-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting pypdfium2>=4 (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr)
  Downloading pypdfium2-4.30.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 2.6 MB/s eta 0:00:00
Requirement already satisfied: regex in /usr/local/lib/python3.11/dist-packages (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (2024.11.6)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.11/dist-packages (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (0.9.0)
Requirement already satisfied: imagesize in /usr/local/lib/python3.11/dist-packages (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (1.4.1)
Requirement already satisfied: langchain>=0.2 in /usr/local/lib/python3.11/dist-packages (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (0.3.26)
Collecting langchain-community>=0.2 (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr)
  Downloading langchain_community-0.3.27-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: langchain-core in /usr/local/lib/python3.11/dist-packages (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (0.3.66)
Collecting langchain-openai>=0.1 (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr)
  Downloading langchain_openai-0.3.30-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.11/dist-packages (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (5.4.0)
Requirement already satisfied: openai>=1.63 in /usr/local/lib/python3.11/dist-packages (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (1.91.0)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.11/dist-packages (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (3.1.5)
Collecting premailer (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr)
  Downloading premailer-3.10.0-py2.py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: pyclipper in /usr/local/lib/python3.11/dist-packages (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (1.3.0.post6)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (1.2.2)
Requirement already satisfied: shapely in /usr/local/lib/python3.11/dist-packages (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (2.1.1)
Requirement already satisfied: tokenizers>=0.19 in /usr/local/lib/python3.11/dist-packages (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (0.21.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (4.13.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx->paddlepaddle) (4.9.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx->paddlepaddle) (2025.6.15)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx->paddlepaddle) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx->paddlepaddle) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx->paddlepaddle) (0.16.0)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.8 in /usr/local/lib/python3.11/dist-packages (from langchain>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (0.3.8)
Requirement already satisfied: langsmith>=0.1.17 in /usr/local/lib/python3.11/dist-packages (from langchain>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (0.4.1)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.11/dist-packages (from langchain>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (2.0.41)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.11/dist-packages (from langchain-community>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (3.12.13)
Requirement already satisfied: tenacity!=8.4.0,<10,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from langchain-community>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (8.5.0)
Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in /usr/local/lib/python3.11/dist-packages (from langchain-community>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (0.6.7)
Collecting pydantic-settings<3.0.0,>=2.4.0 (from langchain-community>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr)
  Downloading pydantic_settings-2.10.1-py3-none-any.whl.metadata (3.4 kB)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain-community>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr)
  Downloading httpx_sse-0.4.1-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.11/dist-packages (from langchain-core->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (1.33)
Collecting packaging (from paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr)
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting langchain-core (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr)
  Downloading langchain_core-0.3.74-py3-none-any.whl.metadata (5.8 kB)
Collecting openai>=1.63 (from paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr)
  Downloading openai-1.100.1-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai>=1.63->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (1.9.0)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai>=1.63->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (0.10.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai>=1.63->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.11/dist-packages (from openai>=1.63->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.3->paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.3->paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.3->paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (2.5.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub->paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (2025.5.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub->paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (1.1.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (2.7)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.11/dist-packages (from ftfy->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (0.2.13)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from Jinja2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (3.0.2)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.21.0->gymnasium>1.0.0) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.21.0->gymnasium>1.0.0) (2022.2.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>=1.21.0->gymnasium>1.0.0) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>=1.21.0->gymnasium>1.0.0) (2024.2.0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.11/dist-packages (from openpyxl->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (2.0.0)
Collecting cssselect (from premailer->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr)
  Downloading cssselect-1.3.0-py3-none-any.whl.metadata (2.6 kB)
Collecting cssutils (from premailer->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr)
  Downloading cssutils-2.11.1-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: cachetools in /usr/local/lib/python3.11/dist-packages (from premailer->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (5.5.2)
Collecting ruamel.yaml.clib>=0.2.7 (from ruamel.yaml->paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr)
  Downloading ruamel.yaml.clib-0.2.12-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.7 kB)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (1.15.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (1.5.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (3.6.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (1.20.1)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.11/dist-packages (from dataclasses-json<0.7,>=0.5.7->langchain-community>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (3.26.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from dataclasses-json<0.7,>=0.5.7->langchain-community>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (0.9.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>=1.21.0->gymnasium>1.0.0) (2024.2.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.11/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (3.0.0)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /usr/local/lib/python3.11/dist-packages (from langsmith>=0.1.17->langchain>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (3.10.18)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from langsmith>=0.1.17->langchain>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (1.0.0)
Requirement already satisfied: zstandard<0.24.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith>=0.1.17->langchain>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (0.23.0)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.4.0->langchain-community>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr)
  Downloading python_dotenv-1.1.1-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3->paddlex>=3.1.0->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (1.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy<3,>=1.4->langchain>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (3.2.3)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.11/dist-packages (from cssutils->premailer->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (10.7.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain-community>=0.2->paddlex[ie,multimodal,ocr,trans]>=3.1.0->paddleocr) (1.1.0)
Downloading gymnasium-1.2.0-py3-none-any.whl (944 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 944.3/944.3 kB 19.3 MB/s eta 0:00:00

In [7]:
from paddleocr import PaddleOCR

# Based on code from this Hugging Face space:
# https://huggingface.co/spaces/pragnakalp/OCR-image-to-text/blob/main/app.py

# declare the OCR outside of func; we do not need to redeclare it every time we ocr
ocr = PaddleOCR(lang='en', use_textline_orientation=True,
                use_doc_unwarping=False,
                use_doc_orientation_classify=False,
                device='gpu',
                text_recognition_model_name='PP-OCRv5_server_rec')

/tmp/ipykernel_13/1108921163.py:7: UserWarning: `lang` and `ocr_version` will be ignored when model names or model directories are not `None`.
  ocr = PaddleOCR(lang='en', use_textline_orientation=True,
/usr/local/lib/python3.11/dist-packages/paddle/utils/cpp_extension/extension_utils.py:715: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
Creating model: ('PP-LCNet_x1_0_textline_ori', None)
Using official model (PP-LCNet_x1_0_textline_ori), the model files will be automatically downloaded and saved in /root/.paddlex/official_models.

Fetching 6 files:   0%|          | 0/6 [00:00<?, ?it/s]

config.json: 0.00B [00:00, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

inference.pdiparams:   0%|          | 0.00/6.74M [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

inference.json: 0.00B [00:00, ?B/s]

inference.yml:   0%|          | 0.00/735 [00:00<?, ?B/s]

E0819 04:51:48.662612    13 analysis_config.cc:169] Please use PaddlePaddle with GPU version.
Creating model: ('PP-OCRv5_server_det', None)
Using official model (PP-OCRv5_server_det), the model files will be automatically downloaded and saved in /root/.paddlex/official_models.

Fetching 6 files:   0%|          | 0/6 [00:00<?, ?it/s]

inference.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

inference.pdiparams:   0%|          | 0.00/87.9M [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

inference.yml:   0%|          | 0.00/903 [00:00<?, ?B/s]

E0819 04:51:50.276314    13 analysis_config.cc:169] Please use PaddlePaddle with GPU version.
Creating model: ('PP-OCRv5_server_rec', None)
Using official model (PP-OCRv5_server_rec), the model files will be automatically downloaded and saved in /root/.paddlex/official_models.

Fetching 6 files:   0%|          | 0/6 [00:00<?, ?it/s]

inference.yml: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

inference.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

inference.pdiparams:   0%|          | 0.00/84.4M [00:00<?, ?B/s]

E0819 04:51:52.683308    13 analysis_config.cc:169] Please use PaddlePaddle with GPU version.

In [8]:
def ocr_with_paddle(img: str) -> str:
  """
  Uses PaddleOCR to look for dates in an image.

  ## Parameters
  img: a link to an image on the Internet.

  ## Output
  one or more dates found in the image, separated by |.
  """
  result = ocr.predict(img)
  output = ""
  for thing in dict(result[0])["rec_texts"]: # see docstring for context
    if thing != "":
      if output != "":
        output += "|"
      output += thing
  if output == "":
    return None
  print(f"OCR returns: {output}")
  return output

In [9]:
UNSCANNED_LINK_KEYWORD = "UNSCANNED"

In [10]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
import time

TIMEOUT = 60

def ocr_dates_apply(inp):
  directproof = ""
  fulldate = ""
  start_time = time.perf_counter()
  #print(inp)
  if "postimg" not in inp["proof"]: # I am not bothering with twitter (or any other) links
    fulldate = None
    directproof = inp["proof"]
    print("Returning non-postimg link")
    return pd.Series([directproof, fulldate])
  # I need to save the direct links anyways
  #if "directproof" in inp.columns and 
  if pd.notna(inp["directproof"]):
    # we ran this code on this row before; skip
    print("Skipping an already-entered row")
    return pd.Series([inp["directproof"], inp["fulldate"]])
  try:
      r = requests.get(inp["proof"], timeout=TIMEOUT)
      soup = BeautifulSoup(r.content, 'html.parser')
      #print(soup)
      direct_img_link = soup.find("meta", attrs={"property": "og:image"}).get("content")
      directproof = direct_img_link
      end_time = time.perf_counter()
  except: # on the off chance that the webside loads nothing
      print("Requests timed out; returning None, None")
      return pd.Series([None, None])
  print(f"Grabbing the full link at {direct_img_link} took {end_time - start_time} seconds to run")
  if pd.notnull(inp["day"]): # do not disturb any existing dates
    fulldate = "" + str(int(inp["day"])) + "/" + str(int(inp["month"])) + "/" + str(int(inp["year"])+2000)
    return pd.Series([directproof, fulldate])
  else: # we need to try ocr
    start_time = time.perf_counter()
    try:
        fulldate = ocr_with_paddle(direct_img_link) # clean up multi-date-stacks later manually
        end_time = time.perf_counter()
        print(f"Running OCR on {direct_img_link} took {end_time - start_time} seconds to run")
        return pd.Series([directproof, fulldate])
    except:
        print("OCR failed for some reason (probably a timeout); returning link and unscanned link keyword")
        return pd.Series([directproof, UNSCANNED_LINK_KEYWORD])
# print(len(ru_losses)) # 19955; evidence where the proof is not twitter
# print(ru_losses[["day", "month", "year"]][:20])
# print(len(ru_losses[pd.notna(ru_losses["year"])])) # 13262; evidence where the ddmmyy is in the webpage and not img

In [11]:
import os

ru_losses = pd.read_csv(path+"data/ru_losses.csv")
ru_losses = ru_losses.replace(np.nan, None)

ua_losses = pd.read_csv(path+"data/ua_losses.csv")
ua_losses = ua_losses.replace(np.nan, None)

In [12]:
ru_losses_small = ru_losses.head(20)[14:20].reset_index(drop=True)
ru_losses_small[["directproof", "fulldate"]] = None

ru_losses_small

,id,name,type,status,day,month,year,manufacturer,manufacturer_abbr,user,user_abbr,proof,year_first_produced,directproof,fulldate
0,15,Unknown T-54/55,Tanks,damaged and abandoned,31.0,3.0,24.0,Soviet Union,USSR,Russia,RU,https://postimg.cc/KjbMBZLR,1946.0,None,None
1,16,T-62 Obr. 1967,Tanks,destroyed,11.0,2.0,24.0,Soviet Union,USSR,Russia,RU,https://postimg.cc/65Tqk5t6,1967.0,None,None
2,17,T-62 Obr. 1967,Tanks,destroyed,None,None,None,Soviet Union,USSR,Russia,RU,https://postimg.cc/52vJB77X,1967.0,None,None
3,18,T-62 Obr. 1967,Tanks,destroyed,29.0,9.0,24.0,Soviet Union,USSR,Russia,RU,https://postimg.cc/26dvvtZC,1967.0,None,None
4,19,T-62 Obr. 1967,Tanks,destroyed,9.0,10.0,24.0,Soviet Union,USSR,Russia,RU,https://postimg.cc/xT6m6jRd,1967.0,None,None
5,20,T-62 Obr. 1967,Tanks,captured,None,None,None,Soviet Union,USSR,Russia,RU,https://postimg.cc/yxw0SFD6,1967.0,None,None

In [13]:
for i in range(len(ru_losses_small)):
  snip = ru_losses_small.iloc[i]
  findings = ocr_dates_apply(snip)
  ru_losses_small.loc[i, ["directproof", "fulldate"]] = [findings.iloc[0], findings.iloc[1]]

ru_losses_small

Grabbing the full link at https://i.postimg.cc/KjbMBZLR/1106-unkn-t54-55-dam-aband-31-03-24.jpg took 0.3779253929999413 seconds to run
Grabbing the full link at https://i.postimg.cc/65Tqk5t6/1021-T-62-Obr-1967-destr-11-02-24.jpg took 0.3664544770000475 seconds to run
Grabbing the full link at https://i.postimg.cc/52vJB77X/1014-t62-obr1967.jpg took 0.36316455100006806 seconds to run

Connecting to https://i.postimg.cc/52vJB77X/1014-t62-obr1967.jpg ...
Downloading 1014-t62-obr1967.jpg ...
[==================================================] 100.00%

Running OCR on https://i.postimg.cc/52vJB77X/1014-t62-obr1967.jpg took 13.801393977999965 seconds to run
Grabbing the full link at https://i.postimg.cc/26dvvtZC/1020-T-62-Obr-1967-destr-29-09-24.jpg took 0.4696640369999159 seconds to run
Grabbing the full link at https://i.postimg.cc/xT6m6jRd/1023-T-62-M-destr-09-10-24.jpg took 0.3841854570000578 seconds to run

Connecting to https://i.postimg.cc/yxw0SFD6/1001-T-62-Obr-1967-capt.jpg ...
Downloading 1001-T-62-Obr-1967-capt.jpg ...
[=                                                 ] 2.23%

Grabbing the full link at https://i.postimg.cc/yxw0SFD6/1001-T-62-Obr-1967-capt.jpg took 0.4723806289999857 seconds to run

[==================================================] 100.00%

OCR returns: 13.11.2022
Running OCR on https://i.postimg.cc/yxw0SFD6/1001-T-62-Obr-1967-capt.jpg took 33.664578617000075 seconds to run

,id,name,type,status,day,month,year,manufacturer,manufacturer_abbr,user,user_abbr,proof,year_first_produced,directproof,fulldate
0,15,Unknown T-54/55,Tanks,damaged and abandoned,31.0,3.0,24.0,Soviet Union,USSR,Russia,RU,https://postimg.cc/KjbMBZLR,1946.0,https://i.postimg.cc/KjbMBZLR/1106-unkn-t54-55...,31/3/2024
1,16,T-62 Obr. 1967,Tanks,destroyed,11.0,2.0,24.0,Soviet Union,USSR,Russia,RU,https://postimg.cc/65Tqk5t6,1967.0,https://i.postimg.cc/65Tqk5t6/1021-T-62-Obr-19...,11/2/2024
2,17,T-62 Obr. 1967,Tanks,destroyed,None,None,None,Soviet Union,USSR,Russia,RU,https://postimg.cc/52vJB77X,1967.0,https://i.postimg.cc/52vJB77X/1014-t62-obr1967...,None
3,18,T-62 Obr. 1967,Tanks,destroyed,29.0,9.0,24.0,Soviet Union,USSR,Russia,RU,https://postimg.cc/26dvvtZC,1967.0,https://i.postimg.cc/26dvvtZC/1020-T-62-Obr-19...,29/9/2024
4,19,T-62 Obr. 1967,Tanks,destroyed,9.0,10.0,24.0,Soviet Union,USSR,Russia,RU,https://postimg.cc/xT6m6jRd,1967.0,https://i.postimg.cc/xT6m6jRd/1023-T-62-M-dest...,9/10/2024
5,20,T-62 Obr. 1967,Tanks,captured,None,None,None,Soviet Union,USSR,Russia,RU,https://postimg.cc/yxw0SFD6,1967.0,https://i.postimg.cc/yxw0SFD6/1001-T-62-Obr-19...,13.11.2022

In [14]:
if os.path.isfile(path+"/data_partial/ru_losses_ocr2.csv"):
    ru_losses_ocr = pd.read_csv(path+"/data_partial/ru_losses_ocr2.csv")
    print("Got RU losses from prev run of this notebook")
elif os.path.isfile("/kaggle/working/ru_losses_ocr2.csv"):
    ru_losses_ocr = pd.read_csv("/kaggle/working/ru_losses_ocr2.csv")
    print("Got RU losses from in-progress work")
elif os.path.isfile("/kaggle/working/ru_losses_ocr.csv"):
    ru_losses_ocr = pd.read_csv("/kaggle/working/ru_losses_ocr.csv")
    print("Got RU losses from work with 1000 results")
else:
    ru_losses_ocr = ru_losses.copy()

if os.path.isfile(path+"/data_partial/ua_losses_ocr2.csv"):
    ua_losses_ocr = pd.read_csv(path+"/data_partial/ua_losses_ocr2.csv")
    print("Got UA losses from prev run of this notebook")
elif os.path.isfile("/kaggle/working/ua_losses_ocr2.csv"):
    ua_losses_ocr = pd.read_csv("/kaggle/working/ua_losses_ocr2.csv")
    print("Got UA losses from in progress work")
elif os.path.isfile("/kaggle/working/ua_losses_ocr.csv"):
    ua_losses_ocr = pd.read_csv("/kaggle/working/ua_losses_ocr.csv")
    print("Got UA losses from a file that shouldn't exist")
else:
    ua_losses_ocr = ua_losses.copy()

# init the columns beforehand so I can replace values one at a time
if "directproof" not in ru_losses_ocr.columns:
    ru_losses_ocr["directproof"] = None
if "directproof" not in ua_losses_ocr.columns:
    ua_losses_ocr["directproof"] = None
if "fulldate" not in ru_losses_ocr.columns:
    ru_losses_ocr["fulldate"] = None
if "fulldate" not in ua_losses_ocr.columns:
    ua_losses_ocr["fulldate"] = None

Got RU losses from prev run of this notebook
Got UA losses from prev run of this notebook

In [15]:
testbegin = 0
for i in range(len(ru_losses_ocr)):
    #snip = ru_losses_ocr.iloc[i]
    if pd.isna(ru_losses_ocr.loc[i, "directproof"]):
        testbegin = i
        print(i)
        print(ru_losses_ocr.loc[i])
        break
testbegin, len(ru_losses_ocr)

22251
id                                           22252
name                               (Unknown) truck
type                   Trucks, Vehicles, and Jeeps
status                                   destroyed
day                                            NaN
month                                          NaN
year                                           NaN
manufacturer                                Russia
manufacturer_abbr                               RU
user                                        Russia
user_abbr                                       RU
proof                  https://postimg.cc/CL8Y7SQr
year_first_produced                            NaN
directproof                                    NaN
fulldate                                       NaN
Name: 22251, dtype: object

(22251, 22495)

In [16]:
testbegin = 0
for i in range(len(ua_losses_ocr)):
    #snip = ru_losses_ocr.iloc[i]
    if pd.isna(ua_losses_ocr.loc[i, "directproof"]):
        testbegin = i
        print(i)
        print(ua_losses_ocr.loc[i])
        break
testbegin, len(ua_losses_ocr)

7501
id                                               7502
name                                  P-18 'Malakhit'
type                   Surface-To-Air Missile Systems
status                                      destroyed
day                                              26.0
month                                             2.0
year                                             24.0
manufacturer                                  Ukraine
manufacturer_abbr                                  UA
user                                          Ukraine
user_abbr                                          UA
proof                     https://postimg.cc/8c0tXxpM
year_first_produced                               NaN
directproof                                       NaN
fulldate                                          NaN
Name: 7501, dtype: object

(7501, 9581)

In [17]:
ru_losses_ocr.loc[2999:3002]

,id,name,type,status,day,month,year,manufacturer,manufacturer_abbr,user,user_abbr,proof,year_first_produced,directproof,fulldate
2999,3000,T-80U,Tanks,destroyed,8.0,5.0,22.0,Russia,RU,Russia,RU,https://postimg.cc/MKGmY3nM,1985.0,https://i.postimg.cc/MKGmY3nM/1010-3x-t80u-des...,8/5/2022
3000,3001,T-80U,Tanks,destroyed,8.0,5.0,22.0,Russia,RU,Russia,RU,https://postimg.cc/MKGmY3nM,1985.0,https://i.postimg.cc/MKGmY3nM/1010-3x-t80u-des...,8/5/2022
3001,3002,T-80U,Tanks,destroyed,8.0,5.0,22.0,Russia,RU,Russia,RU,https://postimg.cc/MKGmY3nM,1985.0,https://i.postimg.cc/MKGmY3nM/1010-3x-t80u-des...,8/5/2022
3002,3003,T-80U,Tanks,destroyed,15.0,5.0,23.0,Russia,RU,Russia,RU,https://postimg.cc/2S2jvPs2,1985.0,https://i.postimg.cc/2S2jvPs2/1027-t80bv-destr...,15/5/2023

In [18]:
SAVE_INTERVAL = 250

In [19]:
# This is less efficient than apply() but as I described in a previous comment
# this lets me save my work every so often

# find the first unprocessed entry and continue
# Technically no need for this now that it auto-skips already inputed rows
begin = 0
for i in range(len(ru_losses_ocr)):
    #snip = ru_losses_ocr.iloc[i]
    if pd.isna(ru_losses_ocr.loc[i, "directproof"]):
        begin = i
        break

for i in range(len(ru_losses_ocr)):
  snip = ru_losses_ocr.iloc[i]
  if pd.notna(snip.loc["directproof"]):
      #print("Skipping entered row")
      continue
  print(i)
  try:
      findings = ocr_dates_apply(snip)
      ru_losses_ocr.loc[i, ["directproof", "fulldate"]] = [findings.iloc[0], findings.iloc[1]]
  except:
      ru_losses_ocr.loc[i, ["directproof", "fulldate"]] = ["BROKENLINK", "NA"]
  if i % SAVE_INTERVAL == 0 and i != 0:
    ru_losses_ocr.to_csv("/kaggle/working/ru_losses_ocr2.csv", index=False)
    print(f"Saved at index {i}")

ru_losses_ocr.to_csv("/kaggle/working/ru_losses_ocr2.csv", index=False)
print("Saved after completion")

22251
Grabbing the full link at https://i.postimg.cc/CL8Y7SQr/uuk7.jpg took 0.3867186439999841 seconds to run

Connecting to https://i.postimg.cc/CL8Y7SQr/uuk7.jpg ...
Downloading uuk7.jpg ...
[==================================================] 100.00%

OCR returns: 30.03.2022
Running OCR on https://i.postimg.cc/CL8Y7SQr/uuk7.jpg took 18.810574983000038 seconds to run
22252
Grabbing the full link at https://i.postimg.cc/fLgZ2Lsp/uuk12.jpg took 0.524827258000073 seconds to run

Connecting to https://i.postimg.cc/fLgZ2Lsp/uuk12.jpg ...
Downloading uuk12.jpg ...
[==================================================] 100.00%

OCR returns: 30.03.2022
Running OCR on https://i.postimg.cc/fLgZ2Lsp/uuk12.jpg took 15.32096182700002 seconds to run
22253
Grabbing the full link at https://i.postimg.cc/dQpwGL4T/uuk13.jpg took 0.38223067800004173 seconds to run

Connecting to https://i.postimg.cc/dQpwGL4T/uuk13.jpg ...
Downloading uuk13.jpg ...
[==================================================] 100.00%

OCR returns: 30.03.2022
Running OCR on https://i.postimg.cc/dQpwGL4T/uuk13.jpg took 15.178038786000002 seconds to run
22254
Grabbing the full link at https://i.postimg.cc/cLNW5Pqx/uuk14.jpg took 0.46856644199999664 seconds to run

Connecting to https://i.postimg.cc/cLNW5Pqx/uuk14.jpg ...
Downloading uuk14.jpg ...
[==================================================] 100.00%

OCR returns: 30.03.2022
Running OCR on https://i.postimg.cc/cLNW5Pqx/uuk14.jpg took 15.372283233000076 seconds to run
22255
Grabbing the full link at https://i.postimg.cc/3x1FYK47/1006-unkn-truck-destr.jpg took 0.40397134900001674 seconds to run

Connecting to https://i.postimg.cc/3x1FYK47/1006-unkn-truck-destr.jpg ...
Downloading 1006-unkn-truck-destr.jpg ...
[==================================================] 100.00%

OCR returns: 06.10.2022
Running OCR on https://i.postimg.cc/3x1FYK47/1006-unkn-truck-destr.jpg took 27.583396589999893 seconds to run
22256
Grabbing the full link at https://i.postimg.cc/XYBn065L/1031.jpg took 0.3657690960000082 seconds to run

Connecting to https://i.postimg.cc/XYBn065L/1031.jpg ...
Downloading 1031.jpg ...
[==================================================] 100.00%

OCR returns: YepHiriBcbKaopHoaiBKa.Penopa3WecToBuie 3poHi Cn Hn MaenooBn Ci|CyCnInbHE|YEPHHIB|WeCTOBNUS|20/04/2022|Shestovytsya,|Chernihiv|Oblast|1:57/3:55
Running OCR on https://i.postimg.cc/XYBn065L/1031.jpg took 34.548670539 seconds to run
22257
Grabbing the full link at https://i.postimg.cc/hjMxTDFD/1007.jpg took 0.3647914209999499 seconds to run

Connecting to https://i.postimg.cc/hjMxTDFD/1007.jpg ...
Downloading 1007.jpg ...
[==================================================] 100.00%

OCR returns: 08.07.2022
Running OCR on https://i.postimg.cc/hjMxTDFD/1007.jpg took 24.610159115999977 seconds to run
22258
Returning non-postimg link
22259
Grabbing the full link at https://i.postimg.cc/VNzNm95F/1002.jpg took 0.6038037259999101 seconds to run

Connecting to https://i.postimg.cc/VNzNm95F/1002.jpg ...
Downloading 1002.jpg ...
[==================================================] 100.00%

OCR returns: COB0|DGGG
Running OCR on https://i.postimg.cc/VNzNm95F/1002.jpg took 27.85625043899995 seconds to run
22260
Returning non-postimg link
22261
Grabbing the full link at https://i.postimg.cc/LsKNS1Rv/1017-unkn-truck-destr-25-07-23.jpg took 0.38065968399996564 seconds to run
22262
Returning non-postimg link
22263
Returning non-postimg link
22264
Grabbing the full link at https://i.postimg.cc/B6Mhp2Pw/241.png took 0.37863583800003653 seconds to run

Connecting to https://i.postimg.cc/B6Mhp2Pw/241.png ...
Downloading 241.png ...
[==================================================] 100.00%

OCR returns: 27/8/2023
Running OCR on https://i.postimg.cc/B6Mhp2Pw/241.png took 25.511248808999994 seconds to run
22265
Returning non-postimg link
22266
Returning non-postimg link
22267
Returning non-postimg link
22268
Returning non-postimg link
22269
Grabbing the full link at https://i.postimg.cc/52DSgGHw/1018-Unknown-truck-destr-17-02-24.jpg took 0.5550697520000085 seconds to run
22270
Returning non-postimg link
22271
Returning non-postimg link
22272
Returning non-postimg link
22273
Returning non-postimg link
22274
Grabbing the full link at https://i.postimg.cc/FK5jQCg4/1004.jpg took 0.5375210220001918 seconds to run

Connecting to https://i.postimg.cc/FK5jQCg4/1004.jpg ...
Downloading 1004.jpg ...
[==================================================] 100.00%

OCR returns: 08.07.2022
Running OCR on https://i.postimg.cc/FK5jQCg4/1004.jpg took 25.27960585699998 seconds to run
22275
Grabbing the full link at https://i.postimg.cc/7Y7b4hnh/1030-unkn-truck.jpg took 0.39376998500006266 seconds to run

Connecting to https://i.postimg.cc/7Y7b4hnh/1030-unkn-truck.jpg ...
Downloading 1030-unkn-truck.jpg ...
[==================================================] 100.00%

Running OCR on https://i.postimg.cc/7Y7b4hnh/1030-unkn-truck.jpg took 27.812517084000092 seconds to run
22276
Grabbing the full link at https://i.postimg.cc/CMtZfLGs/1002-unkn-afv-2x-kamaz-2x-unkn-truck.jpg took 0.3717431549998764 seconds to run

Connecting to https://i.postimg.cc/CMtZfLGs/1002-unkn-afv-2x-kamaz-2x-unkn-truck.jpg ...
Downloading 1002-unkn-afv-2x-kamaz-2x-unkn-truck.jpg ...
[==================================================] 100.00%

OCR returns: 30.08.2022|30.08.202207:28
Running OCR on https://i.postimg.cc/CMtZfLGs/1002-unkn-afv-2x-kamaz-2x-unkn-truck.jpg took 13.758613448000006 seconds to run
22277
Returning non-postimg link
22278
Grabbing the full link at https://i.postimg.cc/90G2S8K8/1004.jpg took 0.3741761910000605 seconds to run

Connecting to https://i.postimg.cc/90G2S8K8/1004.jpg ...
Downloading 1004.jpg ...
[==================================================] 100.00%

OCR returns: 22.07.2022
Running OCR on https://i.postimg.cc/90G2S8K8/1004.jpg took 20.984569133999912 seconds to run
22279

Connecting to https://i.postimg.cc/y88KpQVC/1009.jpg ...
Downloading 1009.jpg ...
[=                                                 ] 2.26%

Grabbing the full link at https://i.postimg.cc/y88KpQVC/1009.jpg took 0.36714301100005287 seconds to run

[==================================================] 100.00%

OCR returns: 25.07.2022|T.ME/OK_SPN|KAHANCNEUNARbHOFOHAZHAYEHNA
Running OCR on https://i.postimg.cc/y88KpQVC/1009.jpg took 21.324233413 seconds to run
22280
Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.4066332549998606 seconds to run

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.864601989999983 seconds to run
22281

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.43122584100001404 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.567676512999924 seconds to run
22282

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.4258663410000736 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.728625444000045 seconds to run
22283
Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.38315709099993 seconds to run

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.78434295199986 seconds to run
22284

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.3684752900001058 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.644516279000072 seconds to run
22285

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.6767392190001829 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.531428003999963 seconds to run
22286

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.43232805499997085 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.72547623200012 seconds to run
22287
Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.44122386799995184 seconds to run

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.83321820900005 seconds to run
22288

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.5337252879999141 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.46737536699993 seconds to run
22289

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.37319425800001227 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.871165346999987 seconds to run
22290

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.37892429199996513 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.624193288000015 seconds to run
22291

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.4889204769999651 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.633620790999885 seconds to run
22292

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.5062367219998123 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.311159250999935 seconds to run
22293

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.40979236599991964 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.574985393000134 seconds to run
22294

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.3654480529999091 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.880039477000082 seconds to run
22295

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.4756925440001396 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.742170837000003 seconds to run
22296

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.3974827590000132 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.53161017100001 seconds to run
22297

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.42968135000000984 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.500128671999846 seconds to run
22298

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.37377951600001325 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 34.95285106699998 seconds to run
22299

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 1.0749839970001176 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 47.326108919000035 seconds to run
22300

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.3781058560000474 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 30.05543061000003 seconds to run
22301

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.3791523990000769 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.711058041000115 seconds to run
22302

Connecting to https://i.postimg.cc/jqfkv75C/46.png ...
Downloading 46.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/jqfkv75C/46.png took 0.3656927730000916 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|19|23|18|福|22|国|21|窗|國|福|10|24|12|9|20|2
Running OCR on https://i.postimg.cc/jqfkv75C/46.png took 27.472487639000065 seconds to run
22303
Grabbing the full link at https://i.postimg.cc/k5PKNyWT/1017-Unknown-truck-destr-02-08-24.jpg took 0.517414486000007 seconds to run
22304
Grabbing the full link at https://i.postimg.cc/Y2GMHxpR/68.jpg took 0.5806696119998378 seconds to run

Connecting to https://i.postimg.cc/Y2GMHxpR/68.jpg ...
Downloading 68.jpg ...
[==================================================] 100.00%

OCR returns: 07.04.2022|国
Running OCR on https://i.postimg.cc/Y2GMHxpR/68.jpg took 28.481095028000027 seconds to run
22305
Grabbing the full link at https://i.postimg.cc/Y2GMHxpR/68.jpg took 0.41293776299994533 seconds to run

Connecting to https://i.postimg.cc/Y2GMHxpR/68.jpg ...
Downloading 68.jpg ...
[==================================================] 100.00%

OCR returns: 07.04.2022|国
Running OCR on https://i.postimg.cc/Y2GMHxpR/68.jpg took 27.918947527 seconds to run
22306

Connecting to https://i.postimg.cc/Y2GMHxpR/68.jpg ...
Downloading 68.jpg ...
[=                                                 ] 2.11%

Grabbing the full link at https://i.postimg.cc/Y2GMHxpR/68.jpg took 0.4299584910002068 seconds to run

[==================================================] 100.00%

OCR returns: 07.04.2022|国
Running OCR on https://i.postimg.cc/Y2GMHxpR/68.jpg took 27.41679883300003 seconds to run
22307

Connecting to https://i.postimg.cc/Y2GMHxpR/68.jpg ...
Downloading 68.jpg ...
[=                                                 ] 2.11%

Grabbing the full link at https://i.postimg.cc/Y2GMHxpR/68.jpg took 0.3797750740000083 seconds to run

[==================================================] 100.00%

OCR returns: 07.04.2022|国
Running OCR on https://i.postimg.cc/Y2GMHxpR/68.jpg took 27.860479286999862 seconds to run
22308
Grabbing the full link at https://i.postimg.cc/g2T21w49/1034-Unknown-truck-destr-06-09-22.jpg took 0.5706911939998918 seconds to run
22309
Grabbing the full link at https://i.postimg.cc/sXPHtgdQ/658.png took 0.5038512300000093 seconds to run

Connecting to https://i.postimg.cc/sXPHtgdQ/658.png ...
Downloading 658.png ...
[==================================================] 100.00%

OCR returns: 11.04.2022|11.04.2022|11.04.2022
Running OCR on https://i.postimg.cc/sXPHtgdQ/658.png took 13.666009195000015 seconds to run
22310

Connecting to https://i.postimg.cc/sXPHtgdQ/658.png ...
Downloading 658.png ...
[                                                  ] 0.39%

Grabbing the full link at https://i.postimg.cc/sXPHtgdQ/658.png took 0.38800527100011095 seconds to run

[==================================================] 100.00%

OCR returns: 11.04.2022|11.04.2022|11.04.2022
Running OCR on https://i.postimg.cc/sXPHtgdQ/658.png took 12.720416138000019 seconds to run
22311
Grabbing the full link at https://i.postimg.cc/sXPHtgdQ/658.png took 0.3772330350000175 seconds to run

Connecting to https://i.postimg.cc/sXPHtgdQ/658.png ...
Downloading 658.png ...
[==================================================] 100.00%

OCR returns: 11.04.2022|11.04.2022|11.04.2022
Running OCR on https://i.postimg.cc/sXPHtgdQ/658.png took 12.68282096300004 seconds to run
22312

Connecting to https://i.postimg.cc/sXPHtgdQ/658.png ...
Downloading 658.png ...
[                                                  ] 0.39%

Grabbing the full link at https://i.postimg.cc/sXPHtgdQ/658.png took 0.38924983800006885 seconds to run

[==================================================] 100.00%

OCR returns: 11.04.2022|11.04.2022|11.04.2022
Running OCR on https://i.postimg.cc/sXPHtgdQ/658.png took 12.534244043999934 seconds to run
22313

Connecting to https://i.postimg.cc/sXPHtgdQ/658.png ...
Downloading 658.png ...
[                                                  ] 0.39%

Grabbing the full link at https://i.postimg.cc/sXPHtgdQ/658.png took 0.8935040029998618 seconds to run

[==================================================] 100.00%

OCR returns: 11.04.2022|11.04.2022|11.04.2022
Running OCR on https://i.postimg.cc/sXPHtgdQ/658.png took 12.454469036000091 seconds to run
22314

Connecting to https://i.postimg.cc/sXPHtgdQ/658.png ...
Downloading 658.png ...
[                                                  ] 0.39%

Grabbing the full link at https://i.postimg.cc/sXPHtgdQ/658.png took 0.49342565500001 seconds to run

[==================================================] 100.00%

OCR returns: 11.04.2022|11.04.2022|11.04.2022
Running OCR on https://i.postimg.cc/sXPHtgdQ/658.png took 12.611198094999963 seconds to run
22315

Connecting to https://i.postimg.cc/sXPHtgdQ/658.png ...
Downloading 658.png ...
[                                                  ] 0.39%

Grabbing the full link at https://i.postimg.cc/sXPHtgdQ/658.png took 0.3837273130000085 seconds to run

[==================================================] 100.00%

OCR returns: 11.04.2022|11.04.2022|11.04.2022
Running OCR on https://i.postimg.cc/sXPHtgdQ/658.png took 12.829966516000013 seconds to run
22316

Connecting to https://i.postimg.cc/sXPHtgdQ/658.png ...
Downloading 658.png ...
[                                                  ] 0.39%

Grabbing the full link at https://i.postimg.cc/sXPHtgdQ/658.png took 0.4068512220001139 seconds to run

[==================================================] 100.00%

OCR returns: 11.04.2022|11.04.2022|11.04.2022
Running OCR on https://i.postimg.cc/sXPHtgdQ/658.png took 12.510724466000056 seconds to run
22317

Connecting to https://i.postimg.cc/sXPHtgdQ/658.png ...
Downloading 658.png ...
[                                                  ] 0.39%

Grabbing the full link at https://i.postimg.cc/sXPHtgdQ/658.png took 0.36587693199999194 seconds to run

[==================================================] 100.00%

OCR returns: 11.04.2022|11.04.2022|11.04.2022
Running OCR on https://i.postimg.cc/sXPHtgdQ/658.png took 12.300140127000077 seconds to run
22318

Connecting to https://i.postimg.cc/sXPHtgdQ/658.png ...
Downloading 658.png ...
[                                                  ] 0.39%

Grabbing the full link at https://i.postimg.cc/sXPHtgdQ/658.png took 0.5007516040000155 seconds to run

[==================================================] 100.00%

OCR returns: 11.04.2022|11.04.2022|11.04.2022
Running OCR on https://i.postimg.cc/sXPHtgdQ/658.png took 12.472086592999858 seconds to run
22319

Connecting to https://i.postimg.cc/sXPHtgdQ/658.png ...
Downloading 658.png ...
[                                                  ] 0.39%

Grabbing the full link at https://i.postimg.cc/sXPHtgdQ/658.png took 0.4189001210002061 seconds to run

[==================================================] 100.00%

OCR returns: 11.04.2022|11.04.2022|11.04.2022
Running OCR on https://i.postimg.cc/sXPHtgdQ/658.png took 12.71810786900005 seconds to run
22320

Connecting to https://i.postimg.cc/sXPHtgdQ/658.png ...
Downloading 658.png ...
[                                                  ] 0.39%

Grabbing the full link at https://i.postimg.cc/sXPHtgdQ/658.png took 0.36690222700008235 seconds to run

[==================================================] 100.00%

OCR returns: 11.04.2022|11.04.2022|11.04.2022
Running OCR on https://i.postimg.cc/sXPHtgdQ/658.png took 12.480414795999877 seconds to run
22321

Connecting to https://i.postimg.cc/sXPHtgdQ/658.png ...
Downloading 658.png ...
[                                                  ] 0.39%

Grabbing the full link at https://i.postimg.cc/sXPHtgdQ/658.png took 0.46754848499995205 seconds to run

[==================================================] 100.00%

OCR returns: 11.04.2022|11.04.2022|11.04.2022
Running OCR on https://i.postimg.cc/sXPHtgdQ/658.png took 12.555417555000076 seconds to run
22322

Connecting to https://i.postimg.cc/sXPHtgdQ/658.png ...
Downloading 658.png ...
[                                                  ] 0.39%

Grabbing the full link at https://i.postimg.cc/sXPHtgdQ/658.png took 0.6971166680000351 seconds to run

[==================================================] 100.00%

OCR returns: 11.04.2022|11.04.2022|11.04.2022
Running OCR on https://i.postimg.cc/sXPHtgdQ/658.png took 12.484922421999727 seconds to run
22323
Returning non-postimg link
22324
Returning non-postimg link
22325
Grabbing the full link at https://i.postimg.cc/L8C45Yqb/Unknown-truck-145547-deokupovana-Harkivshhyna-1159-scaled.jpg took 0.43878145200005747 seconds to run

Connecting to https://i.postimg.cc/L8C45Yqb/Unknown-truck-145547-deokupovana-Harkivshhyna-1159-scaled.jpg ...
Downloading Unknown-truck-145547-deokupovana-Harkivshhyna-1159-scaled.jpg ...
[==================================================] 100.00%

OCR returns: 16/09/2022|HPyPNKA
Running OCR on https://i.postimg.cc/L8C45Yqb/Unknown-truck-145547-deokupovana-Harkivshhyna-1159-scaled.jpg took 28.778983498999878 seconds to run
22326
Grabbing the full link at https://i.postimg.cc/L8C45Yqb/Unknown-truck-145547-deokupovana-Harkivshhyna-1159-scaled.jpg took 0.3656161290000455 seconds to run

Connecting to https://i.postimg.cc/L8C45Yqb/Unknown-truck-145547-deokupovana-Harkivshhyna-1159-scaled.jpg ...
Downloading Unknown-truck-145547-deokupovana-Harkivshhyna-1159-scaled.jpg ...
[==================================================] 100.00%

OCR returns: 16/09/2022|HPyPNKA
Running OCR on https://i.postimg.cc/L8C45Yqb/Unknown-truck-145547-deokupovana-Harkivshhyna-1159-scaled.jpg took 28.13943512600008 seconds to run
22327
Grabbing the full link at https://i.postimg.cc/Y9TcCPQj/2022-09-16-unk-x1.png took 0.573074920000181 seconds to run

Connecting to https://i.postimg.cc/Y9TcCPQj/2022-09-16-unk-x1.png ...
Downloading 2022-09-16-unk-x1.png ...
[==================================================] 100.00%

OCR returns: TikTok|16/09/2022|@roman_.967
Running OCR on https://i.postimg.cc/Y9TcCPQj/2022-09-16-unk-x1.png took 10.706085354000152 seconds to run
22328
Grabbing the full link at https://i.postimg.cc/Dw6tX019/2022-09-16-unk-x2.png took 0.44188050000002477 seconds to run

Connecting to https://i.postimg.cc/Dw6tX019/2022-09-16-unk-x2.png ...
Downloading 2022-09-16-unk-x2.png ...
[==================================================] 100.00%

OCR returns: TikTok|16/09/2022|@roman_.967
Running OCR on https://i.postimg.cc/Dw6tX019/2022-09-16-unk-x2.png took 11.091456229999949 seconds to run
22329

Connecting to https://i.postimg.cc/Dw6tX019/2022-09-16-unk-x2.png ...
Downloading 2022-09-16-unk-x2.png ...
[                                                  ] 0.64%

Grabbing the full link at https://i.postimg.cc/Dw6tX019/2022-09-16-unk-x2.png took 0.39011300799984383 seconds to run

[==================================================] 100.00%

OCR returns: TikTok|16/09/2022|@roman_.967
Running OCR on https://i.postimg.cc/Dw6tX019/2022-09-16-unk-x2.png took 10.278826622999986 seconds to run
22330
Returning non-postimg link
22331
Returning non-postimg link
22332
Grabbing the full link at https://i.postimg.cc/rFrpcfY9/43.jpg took 0.36853680799958966 seconds to run

Connecting to https://i.postimg.cc/rFrpcfY9/43.jpg ...
Downloading 43.jpg ...
[==================================================] 100.00%

OCR returns: 06.04.2022|@Blue_Sauron
Running OCR on https://i.postimg.cc/rFrpcfY9/43.jpg took 18.101686610999877 seconds to run
22333
Returning non-postimg link
22334
Returning non-postimg link
22335
Returning non-postimg link
22336
Grabbing the full link at https://i.postimg.cc/tCVhjMzP/uktru1.png took 0.48725208499990913 seconds to run

Connecting to https://i.postimg.cc/tCVhjMzP/uktru1.png ...
Downloading uktru1.png ...
[==================================================] 100.00%

OCR returns: 15/3/2022|TikTok|clideo.com|116 views|0:06/0:21
Running OCR on https://i.postimg.cc/tCVhjMzP/uktru1.png took 28.962663004000206 seconds to run
22337
Grabbing the full link at https://i.postimg.cc/T3DTtGMc/1023-Unknown-truck-destr-15-07-23.jpg took 0.4040909889999966 seconds to run
22338
Returning non-postimg link
22339
Grabbing the full link at https://i.postimg.cc/VNHPQg1S/u6.jpg took 0.3909081960000549 seconds to run

Connecting to https://i.postimg.cc/VNHPQg1S/u6.jpg ...
Downloading u6.jpg ...
[==================================================] 100.00%

OCR returns: 05.04.2022
Running OCR on https://i.postimg.cc/VNHPQg1S/u6.jpg took 12.995293821999894 seconds to run
22340
Grabbing the full link at https://i.postimg.cc/cJSHxJCV/33.jpg took 0.3857289839997975 seconds to run

Connecting to https://i.postimg.cc/cJSHxJCV/33.jpg ...
Downloading 33.jpg ...
[==================================================] 100.00%

OCR returns: 18.04.2022|0e
Running OCR on https://i.postimg.cc/cJSHxJCV/33.jpg took 22.86687180900026 seconds to run
22341

Connecting to https://i.postimg.cc/cJSHxJCV/33.jpg ...
Downloading 33.jpg ...
[==                                                ] 5.57%

Grabbing the full link at https://i.postimg.cc/cJSHxJCV/33.jpg took 0.5403585039998688 seconds to run

[==================================================] 100.00%

OCR returns: 18.04.2022|0e
Running OCR on https://i.postimg.cc/cJSHxJCV/33.jpg took 36.014285557999756 seconds to run
22342
Grabbing the full link at https://i.postimg.cc/0jnXSRjn/58.jpg took 0.4499654520000149 seconds to run

Connecting to https://i.postimg.cc/0jnXSRjn/58.jpg ...
Downloading 58.jpg ...
[==================================================] 100.00%

OCR returns: 16.04.2022|16.04.2022
Running OCR on https://i.postimg.cc/0jnXSRjn/58.jpg took 31.70317340099973 seconds to run
22343
Grabbing the full link at https://i.postimg.cc/PqVr1ySs/664.png took 0.409533386000021 seconds to run

Connecting to https://i.postimg.cc/PqVr1ySs/664.png ...
Downloading 664.png ...
[==================================================] 100.00%

OCR returns: 25/4/2022
Running OCR on https://i.postimg.cc/PqVr1ySs/664.png took 26.30991207900024 seconds to run
22344
Grabbing the full link at https://i.postimg.cc/x8DJBQB3/38.png took 0.37744080699985716 seconds to run

Connecting to https://i.postimg.cc/x8DJBQB3/38.png ...
Downloading 38.png ...
[==================================================] 100.00%

OCR returns: OTBeT HaKOMMeHTapu|vasilii_nemickin|OT Kyna kpa3?|08/3/2022|TikTok|@a.k_5566
Running OCR on https://i.postimg.cc/x8DJBQB3/38.png took 12.699832889999925 seconds to run
22345
Returning non-postimg link
22346
Grabbing the full link at https://i.postimg.cc/pL0YdJny/4311.jpg took 0.3696598870001253 seconds to run

Connecting to https://i.postimg.cc/pL0YdJny/4311.jpg ...
Downloading 4311.jpg ...
[==================================================] 100.00%

OCR returns: 30.04.2022
Running OCR on https://i.postimg.cc/pL0YdJny/4311.jpg took 13.744872579999992 seconds to run
22347
Returning non-postimg link
22348
Grabbing the full link at https://i.postimg.cc/ZKQzLKXv/1006.jpg took 0.37073939500032793 seconds to run

Connecting to https://i.postimg.cc/ZKQzLKXv/1006.jpg ...
Downloading 1006.jpg ...
[==================================================] 100.00%

OCR returns: 16.07.2022|A利
Running OCR on https://i.postimg.cc/ZKQzLKXv/1006.jpg took 29.009720626000217 seconds to run
22349
Grabbing the full link at https://i.postimg.cc/Ght1Ysg1/1007.jpg took 0.37135506999993595 seconds to run

Connecting to https://i.postimg.cc/Ght1Ysg1/1007.jpg ...
Downloading 1007.jpg ...
[==================================================] 100.00%

OCR returns: 13.07.22Bilohorivka,LuhanskRegion.|KRAKEN|158 views|0:16 / 2:17
Running OCR on https://i.postimg.cc/Ght1Ysg1/1007.jpg took 32.542128770999625 seconds to run
22350
Returning non-postimg link
22351
Returning non-postimg link
22352
Returning non-postimg link
22353
Returning non-postimg link
22354
Returning non-postimg link
22355
Returning non-postimg link
22356
Returning non-postimg link
22357
Returning non-postimg link
22358
Returning non-postimg link
22359
Returning non-postimg link
22360
Returning non-postimg link
22361
Grabbing the full link at https://i.postimg.cc/VkKvzbxb/479.png took 1.3253395079996153 seconds to run

Connecting to https://i.postimg.cc/VkKvzbxb/479.png ...
Downloading 479.png ...
[==================================================] 100.00%

OCR returns: 18/4/2023|3aMacKOBaHa|Bopoxa TexHiKa
Running OCR on https://i.postimg.cc/VkKvzbxb/479.png took 17.31722444099978 seconds to run
22362
Returning non-postimg link
22363
Returning non-postimg link
22364
Returning non-postimg link
22365
Returning non-postimg link
22366
Returning non-postimg link
22367
Returning non-postimg link
22368
Returning non-postimg link
22369
Returning non-postimg link
22370
Returning non-postimg link
22371
Returning non-postimg link
22372
Returning non-postimg link
22373
Grabbing the full link at https://i.postimg.cc/QMB1Hg9y/1001.jpg took 0.3835876990001452 seconds to run

Connecting to https://i.postimg.cc/QMB1Hg9y/1001.jpg ...
Downloading 1001.jpg ...
[==================================================] 100.00%

OCR returns: 14.07.2022
Running OCR on https://i.postimg.cc/QMB1Hg9y/1001.jpg took 31.24067938999997 seconds to run
22374
Grabbing the full link at https://i.postimg.cc/QMB1Hg9y/1001.jpg took 0.3882820349999747 seconds to run

Connecting to https://i.postimg.cc/QMB1Hg9y/1001.jpg ...
Downloading 1001.jpg ...
[==================================================] 100.00%

OCR returns: 14.07.2022
Running OCR on https://i.postimg.cc/QMB1Hg9y/1001.jpg took 30.907861097000023 seconds to run
22375

Connecting to https://i.postimg.cc/QMB1Hg9y/1001.jpg ...
Downloading 1001.jpg ...
[                                                  ] 1.08%

Grabbing the full link at https://i.postimg.cc/QMB1Hg9y/1001.jpg took 0.36973627299994405 seconds to run

[==================================================] 100.00%

OCR returns: 14.07.2022
Running OCR on https://i.postimg.cc/QMB1Hg9y/1001.jpg took 30.916823826999916 seconds to run
22376

Connecting to https://i.postimg.cc/QMB1Hg9y/1001.jpg ...
Downloading 1001.jpg ...
[                                                  ] 1.08%

Grabbing the full link at https://i.postimg.cc/QMB1Hg9y/1001.jpg took 0.49778288500010603 seconds to run

[==================================================] 100.00%

OCR returns: 14.07.2022
Running OCR on https://i.postimg.cc/QMB1Hg9y/1001.jpg took 31.065595435999967 seconds to run
22377
Returning non-postimg link
22378
Returning non-postimg link
22379
Returning non-postimg link
22380
Returning non-postimg link
22381
Returning non-postimg link
22382
Grabbing the full link at https://i.postimg.cc/s2632tjT/1104-unkn-truck-destr-01-03-22.jpg took 0.3737964810002268 seconds to run
22383
Grabbing the full link at https://i.postimg.cc/D0dF21qh/1060-Unknown-truck-destr-21-09-22.jpg took 0.36414111199974286 seconds to run
22384
Grabbing the full link at https://i.postimg.cc/pdhrhszk/1059-Unknown-truck-destr-06-09-23.jpg took 0.4240824899998188 seconds to run
22385
Grabbing the full link at https://i.postimg.cc/VLYkwZCS/1011-Unknown-truck-destr-03-06-24.jpg took 0.39534329199977947 seconds to run
22386
Grabbing the full link at https://i.postimg.cc/T312LyQf/1012-Unknown-truck-destr-03-06-24.jpg took 0.44155144799970003 seconds to run
22387
Grabbing the full link at https://i.postimg.cc/KjQ5TcBT/1011-Unknown-truck-destr-27-06-22.jpg took 0.3765288140002667 seconds to run
22388
Grabbing the full link at https://i.postimg.cc/prPZy5hx/1012-Unknown-truck-destr-27-06-22.jpg took 0.3985847889998695 seconds to run
22389
Grabbing the full link at https://i.postimg.cc/2jxGMGM5/1013-Unknown-truck-destr-27-06-22.jpg took 0.36519939200024965 seconds to run
22390
Grabbing the full link at https://i.postimg.cc/X77LbF6k/1014-Unknown-truck-destr-27-06-22.jpg took 0.37360966400001416 seconds to run
22391
Grabbing the full link at https://i.postimg.cc/WbWnb32L/1015-Unknown-truck-destr-27-06-22.jpg took 0.36479777899967303 seconds to run
22392
Grabbing the full link at https://i.postimg.cc/3xkZyTRy/1016-Unknown-truck-destr-27-06-22.jpg took 0.3673348669999541 seconds to run
22393
Grabbing the full link at https://i.postimg.cc/s2S9c45s/1017-Unknown-truck-destr-27-06-22.jpg took 0.43265457999996215 seconds to run
22394
Grabbing the full link at https://i.postimg.cc/t48NWMZB/1018-Unknown-truck-destr-27-06-22.jpg took 0.4026260190003086 seconds to run
22395
Grabbing the full link at https://i.postimg.cc/nzJKw917/1019-Unknown-truck-destr-27-06-22.jpg took 0.39479401399967173 seconds to run
22396
Grabbing the full link at https://i.postimg.cc/1tr0xRWd/1020-Unknown-truck-destr-27-06-22.jpg took 0.3736635059999571 seconds to run
22397
Grabbing the full link at https://i.postimg.cc/HnWwTGRk/1022-Unknown-truck-destr-27-06-22.jpg took 0.37305551500003276 seconds to run
22398
Grabbing the full link at https://i.postimg.cc/0jtpQW1d/1023-Unknown-truck-destr-27-06-22.jpg took 0.37569346600002973 seconds to run
22399
Grabbing the full link at https://i.postimg.cc/G2T2YXDx/1048-Unknown-truck-destr-12-06-24.jpg took 0.3871319230001973 seconds to run
22400
Grabbing the full link at https://i.postimg.cc/FKLJdZsq/1041-Unknown-truck-destr-06-06-22.jpg took 0.38185809600008724 seconds to run
22401
Grabbing the full link at https://i.postimg.cc/bJC4ftKM/1011-unkn-truck-destr-19-06-24.jpg took 0.9006122139999206 seconds to run
22402
Grabbing the full link at https://i.postimg.cc/QMWCPKC0/1006-Unknown-truck-destr-19-02-25.jpg took 0.3990431100000933 seconds to run
22403
Grabbing the full link at https://i.postimg.cc/wv8MdxsH/1007-Unknown-truck-destr-19-02-25.jpg took 0.3804281800003082 seconds to run
22404
Grabbing the full link at https://i.postimg.cc/wMvdp8Mt/1185-Unknown-truck-destr-08-03-25.jpg took 0.4286102830001255 seconds to run
22405
Grabbing the full link at https://i.postimg.cc/cH6F0bgM/1036-Unknown-truck-destr-22-05-25.jpg took 0.3866128140002729 seconds to run
22406
Grabbing the full link at https://i.postimg.cc/1tvh1QmQ/1010-Unknown-truck-destr-14-06-25.jpg took 0.3899591919998784 seconds to run
22407
Grabbing the full link at https://i.postimg.cc/bNBGZGVs/1012-Unknown-truck-destr-17-06-25.jpg took 0.381683024999802 seconds to run
22408
Grabbing the full link at https://i.postimg.cc/K834NwrF/67.jpg took 0.3904359799998929 seconds to run

Connecting to https://i.postimg.cc/K834NwrF/67.jpg ...
Downloading 67.jpg ...
[==================================================] 100.00%

OCR returns: 19.03.2022
Running OCR on https://i.postimg.cc/K834NwrF/67.jpg took 15.590270190999945 seconds to run
22409
Grabbing the full link at https://i.postimg.cc/K834NwrF/67.jpg took 0.4859815269996943 seconds to run

Connecting to https://i.postimg.cc/K834NwrF/67.jpg ...
Downloading 67.jpg ...
[==================================================] 100.00%

OCR returns: 19.03.2022
Running OCR on https://i.postimg.cc/K834NwrF/67.jpg took 15.460782989000109 seconds to run
22410
Grabbing the full link at https://i.postimg.cc/K834NwrF/67.jpg took 0.39632399099991744 seconds to run

Connecting to https://i.postimg.cc/K834NwrF/67.jpg ...
Downloading 67.jpg ...
[==================================================] 100.00%

OCR returns: 19.03.2022
Running OCR on https://i.postimg.cc/K834NwrF/67.jpg took 16.753633605999767 seconds to run
22411
Grabbing the full link at https://i.postimg.cc/k4Nng2QC/u3.jpg took 0.37227667099978135 seconds to run

Connecting to https://i.postimg.cc/k4Nng2QC/u3.jpg ...
Downloading u3.jpg ...
[==================================================] 100.00%

OCR returns: 07/03/2022
Running OCR on https://i.postimg.cc/k4Nng2QC/u3.jpg took 10.74799224599974 seconds to run
22412
Grabbing the full link at https://i.postimg.cc/TwvdxVWQ/u2.jpg took 0.3658424569998715 seconds to run

Connecting to https://i.postimg.cc/TwvdxVWQ/u2.jpg ...
Downloading u2.jpg ...
[==================================================] 100.00%

OCR returns: 07/03/2022
Running OCR on https://i.postimg.cc/TwvdxVWQ/u2.jpg took 10.826414553000177 seconds to run
22413
Returning non-postimg link
22414
Returning non-postimg link
22415
Grabbing the full link at https://i.postimg.cc/y8Q61MNj/1017-Unknown-truck-dam-04-04-24.jpg took 0.4154373050000686 seconds to run
22416
Grabbing the full link at https://i.postimg.cc/8knzLjj0/1029-unkn-truck-dam-20-04-24.jpg took 0.43959080400009043 seconds to run
22417
Grabbing the full link at https://i.postimg.cc/26pbyqvZ/v56.png took 0.384606127999632 seconds to run

Connecting to https://i.postimg.cc/26pbyqvZ/v56.png ...
Downloading v56.png ...
[==================================================] 100.00%

OCR returns: 02/3/2022
Running OCR on https://i.postimg.cc/26pbyqvZ/v56.png took 28.258096206999653 seconds to run
22418

Connecting to https://i.postimg.cc/26pbyqvZ/v56.png ...
Downloading v56.png ...
[                                                  ] 0.48%

Grabbing the full link at https://i.postimg.cc/26pbyqvZ/v56.png took 0.38448710700004085 seconds to run

[==================================================] 100.00%

OCR returns: 02/3/2022
Running OCR on https://i.postimg.cc/26pbyqvZ/v56.png took 28.340776981999625 seconds to run
22419
Grabbing the full link at https://i.postimg.cc/prhtMJt6/gg4.jpg took 0.3977427129998432 seconds to run

Connecting to https://i.postimg.cc/prhtMJt6/gg4.jpg ...
Downloading gg4.jpg ...
[==================================================] 100.00%

OCR returns: Po3rpoM HacTyny P HaCiBepcbKoMy oHui.YpaiHcbKǔ HacTyn Ha XapkiB,nHi? |yTycoB HABO15.|GyTyCCDB|nnioa|HAKNBO|SyTyCCBB|15.05.22near|Serebrianka,|Donetsk|Region.|nnIoc|Vehicle|onLuhansk|Region|side|of the river.|Play (k)|D|26:22/1:02:36|CC|HD
Running OCR on https://i.postimg.cc/prhtMJt6/gg4.jpg took 38.71714584500023 seconds to run
22420
Grabbing the full link at https://i.postimg.cc/XYgCL8QP/1017-Unknown-truck-dam-aband-24-05-25.jpg took 0.42341298300016206 seconds to run
22421
Grabbing the full link at https://i.postimg.cc/wBfs8BKc/1016-Unknown-truck-dam-aband-24-05-25.jpg took 0.39221377399962876 seconds to run
22422
Grabbing the full link at https://i.postimg.cc/VNsLBfRz/c2.png took 0.42686720200026684 seconds to run

Connecting to https://i.postimg.cc/VNsLBfRz/c2.png ...
Downloading c2.png ...
[==================================================] 100.00%

OCR returns: 09/3/2022|TikTok|557 views|@yuriyklepko|0:05/ 0:12|1
Running OCR on https://i.postimg.cc/VNsLBfRz/c2.png took 28.9523447749998 seconds to run
22423
Grabbing the full link at https://i.postimg.cc/c4S9qLZj/412.png took 0.37319255000011253 seconds to run

Connecting to https://i.postimg.cc/c4S9qLZj/412.png ...
Downloading 412.png ...
[==================================================] 100.00%

OCR returns: 15/3/2022
Running OCR on https://i.postimg.cc/c4S9qLZj/412.png took 13.804591131000052 seconds to run
22424
Returning non-postimg link
22425
Grabbing the full link at https://i.postimg.cc/mkhh21bQ/542.jpg took 0.38194896999993944 seconds to run

Connecting to https://i.postimg.cc/mkhh21bQ/542.jpg ...
Downloading 542.jpg ...
[==================================================] 100.00%

OCR returns: 23.06.2022
Running OCR on https://i.postimg.cc/mkhh21bQ/542.jpg took 10.54895775299974 seconds to run
22426
Grabbing the full link at https://i.postimg.cc/vHcNtwjD/g70.png took 0.37640389900025184 seconds to run

Connecting to https://i.postimg.cc/vHcNtwjD/g70.png ...
Downloading g70.png ...
[==================================================] 100.00%

OCR returns: 16/3/2022
Running OCR on https://i.postimg.cc/vHcNtwjD/g70.png took 9.606542754999737 seconds to run
22427
Grabbing the full link at https://i.postimg.cc/GtMVCs56/7i.jpg took 0.3639632569997957 seconds to run

Connecting to https://i.postimg.cc/GtMVCs56/7i.jpg ...
Downloading 7i.jpg ...
[==================================================] 100.00%

OCR returns: 22.03.2022
Running OCR on https://i.postimg.cc/GtMVCs56/7i.jpg took 23.86710014299979 seconds to run
22428
Grabbing the full link at https://i.postimg.cc/Y994gyQF/431.png took 0.5368258960002095 seconds to run

Connecting to https://i.postimg.cc/Y994gyQF/431.png ...
Downloading 431.png ...
[==================================================] 100.00%

OCR returns: 02/3/2022
Running OCR on https://i.postimg.cc/Y994gyQF/431.png took 13.905592791000345 seconds to run
22429
Grabbing the full link at https://i.postimg.cc/m27PXy1c/1005-truck.jpg took 0.45239347200003976 seconds to run

Connecting to https://i.postimg.cc/m27PXy1c/1005-truck.jpg ...
Downloading 1005-truck.jpg ...
[==================================================] 100.00%

OCR returns: 03.09.2022
Running OCR on https://i.postimg.cc/m27PXy1c/1005-truck.jpg took 7.692961491999995 seconds to run
22430
Grabbing the full link at https://i.postimg.cc/HWrVSBJQ/1029-unkn-truck.jpg took 0.5129953870000463 seconds to run

Connecting to https://i.postimg.cc/HWrVSBJQ/1029-unkn-truck.jpg ...
Downloading 1029-unkn-truck.jpg ...
[==================================================] 100.00%

OCR returns: 09.09.2022
Running OCR on https://i.postimg.cc/HWrVSBJQ/1029-unkn-truck.jpg took 24.02996154399989 seconds to run
22431
Grabbing the full link at https://i.postimg.cc/dQ4BZ4Q7/1003.jpg took 0.39870599000005313 seconds to run

Connecting to https://i.postimg.cc/dQ4BZ4Q7/1003.jpg ...
Downloading 1003.jpg ...
[==================================================] 100.00%

OCR returns: 11.09.2022|家|9320AP50
Running OCR on https://i.postimg.cc/dQ4BZ4Q7/1003.jpg took 52.00725055899966 seconds to run
22432
Grabbing the full link at https://i.postimg.cc/cLy31D99/557.png took 0.37765097700003025 seconds to run

Connecting to https://i.postimg.cc/cLy31D99/557.png ...
Downloading 557.png ...
[==================================================] 100.00%

OCR returns: 24/02/2022
Running OCR on https://i.postimg.cc/cLy31D99/557.png took 30.60330201900024 seconds to run
22433
Grabbing the full link at https://i.postimg.cc/L5WpLtHC/370.png took 0.5039954230001058 seconds to run

Connecting to https://i.postimg.cc/L5WpLtHC/370.png ...
Downloading 370.png ...
[==================================================] 100.00%

OCR returns: nearKharkiy,Ukraine|25/02/2022|0:31/1:13|☆
Running OCR on https://i.postimg.cc/L5WpLtHC/370.png took 29.181127755000034 seconds to run
22434
Grabbing the full link at https://i.postimg.cc/LsnQ4KZ5/1004-2x-unkn-veh-destr.jpg took 0.40964224699973784 seconds to run

Connecting to https://i.postimg.cc/LsnQ4KZ5/1004-2x-unkn-veh-destr.jpg ...
Downloading 1004-2x-unkn-veh-destr.jpg ...
[==================================================] 100.00%

OCR returns: 24.09.2022|IAWNHA|YNPABMIHH|HWNX|MAWNH
Running OCR on https://i.postimg.cc/LsnQ4KZ5/1004-2x-unkn-veh-destr.jpg took 23.331031862000145 seconds to run
22435
Grabbing the full link at https://i.postimg.cc/LsnQ4KZ5/1004-2x-unkn-veh-destr.jpg took 0.8615280310000344 seconds to run

Connecting to https://i.postimg.cc/LsnQ4KZ5/1004-2x-unkn-veh-destr.jpg ...
Downloading 1004-2x-unkn-veh-destr.jpg ...
[==================================================] 100.00%

OCR returns: 24.09.2022|IAWNHA|YNPABMIHH|HWNX|MAWNH
Running OCR on https://i.postimg.cc/LsnQ4KZ5/1004-2x-unkn-veh-destr.jpg took 22.47792445999994 seconds to run
22436
Grabbing the full link at https://i.postimg.cc/Qd0VGPhL/86.jpg took 0.3757052900000417 seconds to run

Connecting to https://i.postimg.cc/Qd0VGPhL/86.jpg ...
Downloading 86.jpg ...
[==================================================] 100.00%

OCR returns: 16.03.2022|X:56915|Y:63|X:56-90798|Y:63-80455|h:172|:124|16.03.2022|08:56:49|15032022
Running OCR on https://i.postimg.cc/Qd0VGPhL/86.jpg took 30.593480091999936 seconds to run
22437

Connecting to https://i.postimg.cc/Qd0VGPhL/86.jpg ...
Downloading 86.jpg ...
[=                                                 ] 2.51%

Grabbing the full link at https://i.postimg.cc/Qd0VGPhL/86.jpg took 0.38475425200022073 seconds to run

[==================================================] 100.00%

OCR returns: 16.03.2022|X:56915|Y:63|X:56-90798|Y:63-80455|h:172|:124|16.03.2022|08:56:49|15032022
Running OCR on https://i.postimg.cc/Qd0VGPhL/86.jpg took 29.68898372900003 seconds to run
22438

Connecting to https://i.postimg.cc/nLqV2cT1/43.jpg ...
Downloading 43.jpg ...
[=                                                 ] 2.30%

Grabbing the full link at https://i.postimg.cc/nLqV2cT1/43.jpg took 0.37796574599997257 seconds to run

[==================================================] 100.00%

OCR returns: 55-92666|16.03.2022|Y53-80681|h：113|X:56-90798|Y:63-80455|h124|16.03.2022|08:56:49|1503.2022
Running OCR on https://i.postimg.cc/nLqV2cT1/43.jpg took 29.44033751799998 seconds to run
22439

Connecting to https://i.postimg.cc/nLqV2cT1/43.jpg ...
Downloading 43.jpg ...
[=                                                 ] 2.30%

Grabbing the full link at https://i.postimg.cc/nLqV2cT1/43.jpg took 1.7957705710000482 seconds to run

[==================================================] 100.00%

OCR returns: 55-92666|16.03.2022|Y53-80681|h：113|X:56-90798|Y:63-80455|h124|16.03.2022|08:56:49|1503.2022
Running OCR on https://i.postimg.cc/nLqV2cT1/43.jpg took 29.750236152999605 seconds to run
22440

Connecting to https://i.postimg.cc/nLqV2cT1/43.jpg ...
Downloading 43.jpg ...
[=                                                 ] 2.30%

Grabbing the full link at https://i.postimg.cc/nLqV2cT1/43.jpg took 0.420639428999948 seconds to run

[==================================================] 100.00%

OCR returns: 55-92666|16.03.2022|Y53-80681|h：113|X:56-90798|Y:63-80455|h124|16.03.2022|08:56:49|1503.2022
Running OCR on https://i.postimg.cc/nLqV2cT1/43.jpg took 29.37145291099978 seconds to run
22441
Returning non-postimg link
22442
Returning non-postimg link
22443
Grabbing the full link at https://i.postimg.cc/fR5ZtPph/3327.png took 0.5038097470001048 seconds to run

Connecting to https://i.postimg.cc/fR5ZtPph/3327.png ...
Downloading 3327.png ...
[==================================================] 100.00%

OCR returns: 20.03.2022
Running OCR on https://i.postimg.cc/fR5ZtPph/3327.png took 8.441527794999729 seconds to run
22444
Returning non-postimg link
22445
Returning non-postimg link
22446
Returning non-postimg link
22447
Returning non-postimg link
22448
Grabbing the full link at https://i.postimg.cc/ZnRCbMfF/1023-unkn-vehicle-destr-26-10-23.jpg took 0.4077353640000183 seconds to run
22449
Grabbing the full link at https://i.postimg.cc/d0xcjjZr/1011-unkn-veh.jpg took 0.4380945449997853 seconds to run

Connecting to https://i.postimg.cc/d0xcjjZr/1011-unkn-veh.jpg ...
Downloading 1011-unkn-veh.jpg ...
[==================================================] 100.00%

OCR returns: 13.09.2022|囍
Running OCR on https://i.postimg.cc/d0xcjjZr/1011-unkn-veh.jpg took 24.51513620200012 seconds to run
22450
Grabbing the full link at https://i.postimg.cc/VL9BV8Zm/4g.jpg took 0.38231424700006755 seconds to run

Connecting to https://i.postimg.cc/VL9BV8Zm/4g.jpg ...
Downloading 4g.jpg ...
[==================================================] 100.00%

OCR returns: 03.04.2022|BT|DE84E|2a207A|二| 3
Running OCR on https://i.postimg.cc/VL9BV8Zm/4g.jpg took 21.3976781639999 seconds to run
22451
Returning non-postimg link
22452
Returning non-postimg link
22453
Returning non-postimg link
22454
Returning non-postimg link
22455
Returning non-postimg link
22456
Grabbing the full link at https://i.postimg.cc/ncRpJFx5/1045-Unknown-vehicle-destr-05-06-24.jpg took 0.4994896969997171 seconds to run
22457
Grabbing the full link at https://i.postimg.cc/P5S9Lv7S/1053-Unknown-vehicle-destr-22-12-24.jpg took 0.6056176840002081 seconds to run
22458
Returning non-postimg link
22459
Returning non-postimg link
22460
Grabbing the full link at https://i.postimg.cc/FHRKPbyg/1053-Unknown-vehicle-destr-31-05-22.jpg took 0.533943790000194 seconds to run
22461
Returning non-postimg link
22462
Returning non-postimg link
22463
Returning non-postimg link
22464
Returning non-postimg link
22465

Connecting to https://i.postimg.cc/sg443ntt/1001-unkn-vehicle.jpg ...
Downloading 1001-unkn-vehicle.jpg ...
[                                                  ] 1.62%

Grabbing the full link at https://i.postimg.cc/sg443ntt/1001-unkn-vehicle.jpg took 0.9354373920000398 seconds to run

[==================================================] 100.00%

OCR returns: 12.08.2022|MAXAR|T-72sizedobjectdirectlybycharringonrunway|BREM-1recovery vehicle|Deployedmobile|crane
Running OCR on https://i.postimg.cc/sg443ntt/1001-unkn-vehicle.jpg took 30.746796003000327 seconds to run
22466
Returning non-postimg link
22467
Grabbing the full link at https://i.postimg.cc/x8QqdvKd/1003-unkn-vehicle-destr-02-02-23.jpg took 0.38890130400022827 seconds to run
22468
Grabbing the full link at https://i.postimg.cc/sX1MYLSB/r1.png took 0.3836418139999296 seconds to run

Connecting to https://i.postimg.cc/sX1MYLSB/r1.png ...
Downloading r1.png ...
[==================================================] 100.00%

OCR returns: 26/3/2023|厂|©|©|-6.8C|A ni ac Hi p 3  Hi|#Cby|#C5y|ninnn Bi M-3
Running OCR on https://i.postimg.cc/sX1MYLSB/r1.png took 16.633875002999957 seconds to run
22469
Grabbing the full link at https://i.postimg.cc/P5z2LSms/76h.png took 0.3939521140000579 seconds to run

Connecting to https://i.postimg.cc/P5z2LSms/76h.png ...
Downloading 76h.png ...
[==================================================] 100.00%

OCR returns: DO|品|26/3/2023|O|#Cby|#C5y|#C5y
Running OCR on https://i.postimg.cc/P5z2LSms/76h.png took 12.255977178000194 seconds to run
22470
Grabbing the full link at https://i.postimg.cc/YqCnygYC/1023-Unknown-vehicle-destr-22-06-23.jpg took 0.4085477050002737 seconds to run
22471
Grabbing the full link at https://i.postimg.cc/05Tnz61Z/1025-unkn-vehicle-destr-13-07-23.jpg took 0.38734251000005315 seconds to run
22472
Grabbing the full link at https://i.postimg.cc/sXQx68zP/1018-unkn-vehicle-destr-06-10-23.jpg took 0.419115789999978 seconds to run
22473
Grabbing the full link at https://i.postimg.cc/GpqZxrVq/1007-unkn-vehicle-destr-19-11-23.jpg took 0.9232050709997566 seconds to run
22474
Grabbing the full link at https://i.postimg.cc/pV9LkKCf/1018-Unknown-vehicle-destr-17-02-24.jpg took 0.4735257399997863 seconds to run
22475
Grabbing the full link at https://i.postimg.cc/XN9bGnGc/1061-Unknown-vehicle-destr-05-04-24.jpg took 0.44710549799992805 seconds to run
22476
Grabbing the full link at https://i.postimg.cc/8PfkYCVj/1055-Unknown-truck-destr-28-07-24.jpg took 0.46511087499993664 seconds to run
22477
Grabbing the full link at https://i.postimg.cc/wBXXHbQ1/1013-Unknown-vehicle-destr-04-09-24.jpg took 0.48226966599986554 seconds to run
22478
Grabbing the full link at https://i.postimg.cc/hGWLkqTF/1036-Unknown-vehicle-destr-05-09-24.jpg took 0.5285145769998962 seconds to run
22479
Grabbing the full link at https://i.postimg.cc/d0jb8B92/1021-Unknown-vehicle-destr-14-09-24.jpg took 0.6558837860002313 seconds to run
22480
Grabbing the full link at https://i.postimg.cc/pXdcFXZC/1011-Unknown-vehicle-destr-20-09-24.jpg took 0.4328274459999193 seconds to run
22481
Grabbing the full link at https://i.postimg.cc/rs5VnR7V/1026-Unknown-vehicle-destr-22-08-24.jpg took 0.4047029759999532 seconds to run
22482
Grabbing the full link at https://i.postimg.cc/1z6T1XPt/1036-Unknown-vehicle-destr-13-12-24.jpg took 0.4020542419998492 seconds to run
22483
Grabbing the full link at https://i.postimg.cc/zXsWb4hP/1003-Unknown-vehicle-destr-09-04-25.jpg took 0.3660070720002295 seconds to run
22484
Grabbing the full link at https://i.postimg.cc/DZp42NF6/1064-Unknown-vehicle-destr-15-01-25.jpg took 0.3928095369997209 seconds to run
22485
Grabbing the full link at https://i.postimg.cc/L6Qh1bcD/1070-Unknown-vehicle-destr-06-04-25.jpg took 0.3940781060000518 seconds to run
22486
Grabbing the full link at https://i.postimg.cc/hP1CwtHb/1000-Unknown-vehicle-destr-10-04-25.jpg took 0.41200795199983986 seconds to run
22487
Grabbing the full link at https://i.postimg.cc/d0RnpGdN/1010-Unknown-vehicle-destr-02-12-24.jpg took 0.3884655390002081 seconds to run
22488
Grabbing the full link at https://i.postimg.cc/JzH3Q21H/1011-Unknown-vehicle-destr-24-06-25.jpg took 0.41602188700016995 seconds to run
22489
Returning non-postimg link
22490
Returning non-postimg link
22491
Returning non-postimg link
22492
Returning non-postimg link
22493
Returning non-postimg link
22494
Returning non-postimg link
Saved after completion

In [20]:
begin = 0
for i in range(len(ua_losses_ocr)):
    #snip = ru_losses_ocr.iloc[i]
    if pd.isna(ua_losses_ocr.loc[i, "directproof"]):
        begin = i
        break

for i in range(len(ua_losses_ocr)):
  snip = ua_losses_ocr.iloc[i]
  if pd.notna(snip.loc["directproof"]):
      #print("Skipping entered row")
      continue
  print(i)
  try:
      findings = ocr_dates_apply(snip)
      ua_losses_ocr.loc[i, ["directproof", "fulldate"]] = [findings.iloc[0], findings.iloc[1]]
  except:
      ua_losses_ocr.loc[i, ["directproof", "fulldate"]] = ["BROKENLINK", "NA"]
  print(i)
  if i % SAVE_INTERVAL == 0 and i != 0:
    ua_losses_ocr.to_csv("/kaggle/working/ua_losses_ocr2.csv", index=False)
    print(f"Saved at index {i}")

ua_losses_ocr.to_csv("/kaggle/working/ua_losses_ocr2.csv", index=False)
print("Saved at the end")

7501
Grabbing the full link at https://i.postimg.cc/8c0tXxpM/2029-18-Malakhit-early-warning-VHF-radar-destr-26-02-24.jpg took 0.43217699700016965 seconds to run
7501
7502
Grabbing the full link at https://i.postimg.cc/0QmDL0p3/2007-P-18-Malakhit-destr-12-03-24.jpg took 0.4236775670001407 seconds to run
7502
7503
Grabbing the full link at https://i.postimg.cc/bwFVYf2C/2004-P-18-Malakhit-25-03-24.jpg took 0.37760486400020454 seconds to run
7503
7504
Grabbing the full link at https://i.postimg.cc/Dw57qtf1/2010-P-18-Malakhit-early-warning-radar-destr-01-11-24.jpg took 0.45995820999996795 seconds to run
7504
7505
Grabbing the full link at https://i.postimg.cc/wBydDw6x/2003-1-RL131-P-18-Terek-early-warning-radar-dam-25-04-24.jpg took 0.3834404750000431 seconds to run
7505
7506
Grabbing the full link at https://i.postimg.cc/tgvn0Zwh/2012-1-RL131-P-18-Terek-early-warning-radar-dam-14-05-24.jpg took 0.4180893510001624 seconds to run
7506
7507
Grabbing the full link at https://i.postimg.cc/0yLgprHM/470.png took 0.40844475299991245 seconds to run

Connecting to https://i.postimg.cc/0yLgprHM/470.png ...
Downloading 470.png ...
[==================================================] 100.00%

OCR returns: 17/4/2022|1653.85RUB（17%）
Running OCR on https://i.postimg.cc/0yLgprHM/470.png took 11.228534363999643 seconds to run
7507
7508
Grabbing the full link at https://i.postimg.cc/c1Pv1brn/2011-MR-18-Mobile-3-D-Surveillance-Radar-destr-22-05-24.jpg took 0.3826772140000685 seconds to run
7508
7509

Connecting to https://i.postimg.cc/gjmtgKPy/470.png ...
Downloading 470.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/gjmtgKPy/470.png took 0.3668355469999369 seconds to run

[==================================================] 100.00%

OCR returns: 02/5/2022|RVvoenkor|RusVesna SU
Running OCR on https://i.postimg.cc/gjmtgKPy/470.png took 23.892763620000096 seconds to run
7509
7510
Grabbing the full link at https://i.postimg.cc/TYvPhkLK/2011-79-K6-Pelikan-3-D-surveillance-radar-destr-02-04-23.jpg took 0.3674577749998207 seconds to run
7510
7511
Grabbing the full link at https://i.postimg.cc/dQzZ7rJ4/2006-79-K6-Pelikan-surveillance-radar-destr-20-04-24.jpg took 0.3681697349998103 seconds to run
7511
7512
Grabbing the full link at https://i.postimg.cc/Fs0MczYL/2008-79-K6-Pelikan-surveillance-radar-destr-29-06-24.jpg took 0.35983834900025613 seconds to run
7512
7513
Grabbing the full link at https://i.postimg.cc/rFLc0GPq/2001-80-K6-M-Mobile-3-D-Radar-destr-28-11-23.jpg took 0.4245858940003018 seconds to run
7513
7514
Grabbing the full link at https://i.postimg.cc/G2SG2d2W/578.png took 0.3708686220002164 seconds to run

Connecting to https://i.postimg.cc/G2SG2d2W/578.png ...
Downloading 578.png ...
[==================================================] 100.00%

OCR returns: AHTOHOBCKNN|MOCT.|25.02.22|akTyanbHag|AP|no|nOBOAy|cuTyaunn.|TikTok|@andriiboiko93kh
Running OCR on https://i.postimg.cc/G2SG2d2W/578.png took 30.115324688999863 seconds to run
7514
7515

Connecting to https://i.postimg.cc/brWJX4NL/2022-11-12-BMP-2.jpg ...
Downloading 2022-11-12-BMP-2.jpg ...
[                                                  ] 0.90%

Grabbing the full link at https://i.postimg.cc/brWJX4NL/2022-11-12-BMP-2.jpg took 0.4318693670002176 seconds to run

[==================================================] 100.00%

OCR returns: DJIM30T|2022-11-1214:20:42|MAVERICK|MAVERICK|12/11/2022|KhersonAirport
Running OCR on https://i.postimg.cc/brWJX4NL/2022-11-12-BMP-2.jpg took 29.13411793599971 seconds to run
7515
7516
Grabbing the full link at https://i.postimg.cc/WpShQwBk/5547.png took 0.43259916499982864 seconds to run

Connecting to https://i.postimg.cc/WpShQwBk/5547.png ...
Downloading 5547.png ...
[==================================================] 100.00%

OCR returns: 24/02/2022
Running OCR on https://i.postimg.cc/WpShQwBk/5547.png took 22.243078451999736 seconds to run
7516
7517

Connecting to https://i.postimg.cc/kG7k6sVR/47.png ...
Downloading 47.png ...
[                                                  ] 0.28%

Grabbing the full link at https://i.postimg.cc/kG7k6sVR/47.png took 0.38288827099995615 seconds to run

[==================================================] 100.00%

OCR returns: 02/5/2022|RVvoenkor|RusVesna SU
Running OCR on https://i.postimg.cc/kG7k6sVR/47.png took 24.184844559999874 seconds to run
7517
7518

Connecting to https://i.postimg.cc/pXwx79Lj/557.png ...
Downloading 557.png ...
[                                                  ] 0.60%

Grabbing the full link at https://i.postimg.cc/pXwx79Lj/557.png took 0.37623584499988283 seconds to run

[==================================================] 100.00%

OCR returns: 24/02/2022
Running OCR on https://i.postimg.cc/pXwx79Lj/557.png took 14.648018949999823 seconds to run
7518
7519
Grabbing the full link at https://i.postimg.cc/tC3V1Gxg/2007-PRV-13-Odd-Pair-height-finder-radar-destr-28-02-22.jpg took 0.397948925000037 seconds to run
7519
7520

Connecting to https://i.postimg.cc/K8PQrnB2/360.png ...
Downloading 360.png ...
[                                                  ] 0.18%

Grabbing the full link at https://i.postimg.cc/K8PQrnB2/360.png took 0.4299222260001443 seconds to run

[==================================================] 100.00%

OCR returns: 05/9/2022
Running OCR on https://i.postimg.cc/K8PQrnB2/360.png took 30.635439561000112 seconds to run
7520
7521
Grabbing the full link at https://i.postimg.cc/GtzvXxgF/2001-Old-UA-loss-from-25-02-2022-Destroyed-PRV-16-Thin-Skin-B.jpg took 0.4125351980001142 seconds to run
7521
7522
Returning non-postimg link
7522
7523
Grabbing the full link at https://i.postimg.cc/nrvJTvyP/2034-PRV-16-Thin-Skin-B-destr-01-10-23.jpg took 0.40148169999974925 seconds to run
7523
7524

Connecting to https://i.postimg.cc/SRjk0C96/6659.png ...
Downloading 6659.png ...
[                                                  ] 0.52%

Grabbing the full link at https://i.postimg.cc/SRjk0C96/6659.png took 0.38485929499984195 seconds to run

[==================================================] 100.00%

OCR returns: 24/02/2022
Running OCR on https://i.postimg.cc/SRjk0C96/6659.png took 22.247658409999985 seconds to run
7524
7525
Grabbing the full link at https://i.postimg.cc/250CWHfJ/1028-1-L22-Parol-destr-28-02-22.jpg took 0.4752059080001345 seconds to run
7525
7526
Grabbing the full link at https://i.postimg.cc/c40FKCjm/2009-1-L22-Parol-destr-24-02-22.jpg took 0.44165951600007247 seconds to run
7526
7527

Connecting to https://i.postimg.cc/MpBxPfrf/57.png ...
Downloading 57.png ...
[                                                  ] 0.34%

Grabbing the full link at https://i.postimg.cc/MpBxPfrf/57.png took 0.43238449899990883 seconds to run

[==================================================] 100.00%

OCR returns: 24/02/2022
Running OCR on https://i.postimg.cc/MpBxPfrf/57.png took 41.73996506000003 seconds to run
7527
7528

Connecting to https://i.postimg.cc/jqHGyDrQ/390.png ...
Downloading 390.png ...
[                                                  ] 0.73%

Grabbing the full link at https://i.postimg.cc/jqHGyDrQ/390.png took 0.5208284300001651 seconds to run

[==================================================] 100.00%

OCR returns: 02/5/2022|RVvoenkor|RusVesna Su
Running OCR on https://i.postimg.cc/jqHGyDrQ/390.png took 13.62461081399988 seconds to run
7528
7529
Grabbing the full link at https://i.postimg.cc/sXxMypFn/2009-1-L22-Parol-ground-based-IFF-interrogator-capt-10-03-22.jpg took 0.3637971359999028 seconds to run
7529
7530
Grabbing the full link at https://i.postimg.cc/m2kp8gCH/4fj.png took 0.36542598099958923 seconds to run

Connecting to https://i.postimg.cc/m2kp8gCH/4fj.png ...
Downloading 4fj.png ...
[==================================================] 100.00%

OCR returns: afrontline.Russia UkraineWar20220225|1300|1300.1|AHTOHOBCKNN|MOCT.|AHTOHOBCKNN MOCT|25.02.22|akTyanbHan|25.02.22|akTyanbHag|AHOPr|no|NOBOAy|AHPOPMrn|no|nOBOAy|cnTyaunn.|cnTyaunn.|TikTok|@andriiboiko93kh|@andriiboiko93kh
Running OCR on https://i.postimg.cc/m2kp8gCH/4fj.png took 33.42462544900036 seconds to run
7530
7531
Grabbing the full link at https://i.postimg.cc/QM6YtDQ5/57.png took 0.40073816599988277 seconds to run

Connecting to https://i.postimg.cc/QM6YtDQ5/57.png ...
Downloading 57.png ...
[==================================================] 100.00%

OCR returns: 02.05.2022|RVvoenkor|RusVesna SU
Running OCR on https://i.postimg.cc/QM6YtDQ5/57.png took 24.24992432700037 seconds to run
7531
7532

Connecting to https://i.postimg.cc/PJzGKLv0/2002.jpg ...
Downloading 2002.jpg ...
[                                                  ] 1.86%

Grabbing the full link at https://i.postimg.cc/PJzGKLv0/2002.jpg took 0.3982600399999683 seconds to run

[==================================================] 100.00%

OCR returns: TikTok|23.07.2022|@romashtrih|nyraHcbka/AoHeuska|abnacri
Running OCR on https://i.postimg.cc/PJzGKLv0/2002.jpg took 20.00511593200008 seconds to run
7532
7533
Returning non-postimg link
7533
7534
Returning non-postimg link
7534
7535
Returning non-postimg link
7535
7536
Grabbing the full link at https://i.postimg.cc/v8LhvyX1/2008-36-D6-Tin-Shield-destr-10-11-22.jpg took 0.46715577699978894 seconds to run
7536
7537
Grabbing the full link at https://i.postimg.cc/q7tnGHnd/2008-36-D6-Tin-Shield-destr-19-12-22.jpg took 0.4287059660000523 seconds to run
7537
7538
Grabbing the full link at https://i.postimg.cc/43gKXVp9/2005-1-L220-UK-Zoopark-3-destr-26-04-23.jpg took 0.3783638479999354 seconds to run
7538
7539
Grabbing the full link at https://i.postimg.cc/QdHRgTqs/2011-36-D6-Tin-Shield-destr-26-04-23.jpg took 0.4224315179999394 seconds to run
7539
7540
Grabbing the full link at https://i.postimg.cc/Qtv2x8WV/2010-36-D6-Tin-Shield-destr-29-05-23.jpg took 0.4948862569999619 seconds to run
7540
7541
Grabbing the full link at https://i.postimg.cc/05z6ss2v/2007-36-D6-ST-68-U-surveillance-radar-destr-20-05-24.jpg took 0.4676370809997934 seconds to run
7541
7542
Returning non-postimg link
7542
7543
Grabbing the full link at https://i.postimg.cc/vB6KVH55/2021-36d6-radar-dam-13-07-23.jpg took 0.4611964489999991 seconds to run
7543
7544
Grabbing the full link at https://i.postimg.cc/Qdt5X3Qc/2011-36-D6-Tin-Shield-3-D-surveillance-radar-dam-14-03-24-jpg.jpg took 0.4324497570000858 seconds to run
7544
7545
Grabbing the full link at https://i.postimg.cc/Yqssmzzz/5549.png took 0.40681575799999337 seconds to run

Connecting to https://i.postimg.cc/Yqssmzzz/5549.png ...
Downloading 5549.png ...
[==================================================] 100.00%

OCR returns: 30/3/2022
Running OCR on https://i.postimg.cc/Yqssmzzz/5549.png took 28.852479972999845 seconds to run
7545
7546

Connecting to https://i.postimg.cc/HL6xTdWb/776.jpg ...
Downloading 776.jpg ...
[=                                                 ] 3.97%

Grabbing the full link at https://i.postimg.cc/HL6xTdWb/776.jpg took 0.40385695500026486 seconds to run

[==================================================] 100.00%

OCR returns: 07-04-2022|24|nyrAHCK|17/3/2022|2|HCK|nyrAHCK|myrAHCK|ArAHCK|lo|me/UkrcM|nyrAHC|YEAHCK24
Running OCR on https://i.postimg.cc/HL6xTdWb/776.jpg took 20.76880408499983 seconds to run
7546
7547
Grabbing the full link at https://i.postimg.cc/J4bbwxcQ/431.png took 0.382781901999806 seconds to run

Connecting to https://i.postimg.cc/J4bbwxcQ/431.png ...
Downloading 431.png ...
[==================================================] 100.00%

OCR returns: 04/4/2022
Running OCR on https://i.postimg.cc/J4bbwxcQ/431.png took 18.10667324399992 seconds to run
7547
7548
Grabbing the full link at https://i.postimg.cc/vHQBPwXb/43g.png took 0.3662940379999782 seconds to run

Connecting to https://i.postimg.cc/vHQBPwXb/43g.png ...
Downloading 43g.png ...
[==================================================] 100.00%

OCR returns: 04/4/2022|凤网|WAR|GONZO|20.4Kviews|0:04/1:32
Running OCR on https://i.postimg.cc/vHQBPwXb/43g.png took 29.099924299999657 seconds to run
7548
7549
Returning non-postimg link
7549
7550
Grabbing the full link at https://i.postimg.cc/1t8xmKF8/448.png took 0.368886762999864 seconds to run

Connecting to https://i.postimg.cc/1t8xmKF8/448.png ...
Downloading 448.png ...
[==================================================] 100.00%

OCR returns: 18/8/2022
Running OCR on https://i.postimg.cc/1t8xmKF8/448.png took 27.21444989299971 seconds to run
7550
7551

Connecting to https://i.postimg.cc/wxX9gVxs/2002-5-N63-S-Flap-Lid-A-Engagement-and-Fire-Control-Radar-for-the-S-300-PS.jpg ...
Downloading 2002-5-N63-S-Flap-Lid-A-Engagement-and-Fire-Control-Radar-for-the-S-300-PS.jpg ...
[                                                  ] 1.30%

Grabbing the full link at https://i.postimg.cc/wxX9gVxs/2002-5-N63-S-Flap-Lid-A-Engagement-and-Fire-Control-Radar-for-the-S-300-PS.jpg took 0.5473883090003255 seconds to run

[==================================================] 100.00%

OCR returns: 08.10.2022|08.10.2022
Running OCR on https://i.postimg.cc/wxX9gVxs/2002-5-N63-S-Flap-Lid-A-Engagement-and-Fire-Control-Radar-for-the-S-300-PS.jpg took 17.136511976000293 seconds to run
7551
7552
Grabbing the full link at https://i.postimg.cc/YSrpj5TY/1014-5-N63-S-Flap-Lid-B-for-S-300-destr-24-02-22.jpg took 0.3839641300000949 seconds to run
7552
7553
Grabbing the full link at https://i.postimg.cc/0jwvLPJR/1015-5-N63-S-Flap-Lid-B-for-S-300-destr-24-02-22.jpg took 0.40081412300014563 seconds to run
7553
7554
Grabbing the full link at https://i.postimg.cc/5N2RwqKh/46h.png took 0.40599698400001216 seconds to run

Connecting to https://i.postimg.cc/5N2RwqKh/46h.png ...
Downloading 46h.png ...
[==================================================] 100.00%

OCR returns: 27/3/2023
Running OCR on https://i.postimg.cc/5N2RwqKh/46h.png took 24.452130529999977 seconds to run
7554
7555
Grabbing the full link at https://i.postimg.cc/tTHwHmGC/2002-S-300-PS-launcher-and-5-N63-S-Flap-Lid-B-for-the-S-300-destr-30-04-23.jpg took 1.4325283760003913 seconds to run
7555
7556
Grabbing the full link at https://i.postimg.cc/JztXwrZ5/2004-5-N63-S-Flap-lid-B-destr-19-06-23.jpg took 0.4557978859998002 seconds to run
7556
7557
Returning non-postimg link
7557
7558
Grabbing the full link at https://i.postimg.cc/VkpM2PHT/2003-5-N63-S-engagement-radar-and-a-5-P85-S-TEL-destr-24-08-23.jpg took 0.3895191019996673 seconds to run
7558
7559
Grabbing the full link at https://i.postimg.cc/HWMT9Sr6/2013-5-P85-S-TEL-and-5-N63-S-destr-05-03-24.jpg took 0.39082686900019326 seconds to run
7559
7560
Grabbing the full link at https://i.postimg.cc/TPKhvXJQ/2009-5-N63-S-target-acquisition-radar-for-75-R6-S-300-PS-destr-06-01-25.jpg took 0.4485676340000282 seconds to run
7560
7561
Grabbing the full link at https://i.postimg.cc/44bJNTm8/2012-5-N63-target-acquisition-radar-on-40-V6-M-mast-for-S-300-dam-18-04-24.jpg took 0.38514495899971735 seconds to run
7561
7562
Grabbing the full link at https://i.postimg.cc/5y4pn97Q/2007-5-N63-Flap-Lid-A-target-engagement-radar-on-40-V6-M-mast-for-S-300-destr-31-03-24.jpg took 0.3868726370001241 seconds to run
7562
7563
Grabbing the full link at https://i.postimg.cc/TP7pTWkj/2008-5-N63-target-acquisition-radar-on-40-V6-M-mast-for-S-300-destr-20-04-24.jpg took 0.3870588109998607 seconds to run
7563
7564
Grabbing the full link at https://i.postimg.cc/MT1HCkNn/2012-5-N63-target-acquisition-radar-on-40-V6-M-mast-for-70-P6-S-300-PT-destr-12-06-24.jpg took 0.40321907399993506 seconds to run
7564
7565
Grabbing the full link at https://i.postimg.cc/pLZ3GSYV/2001-5-N63-target-acquisition-radar-on-40-V6-M-mast-for-70-P6-S-300-PT-dam-28-06-24.jpg took 0.3790284850001626 seconds to run
7565
7566

Connecting to https://i.postimg.cc/8kvsqvdC/d7.jpg ...
Downloading d7.jpg ...
[=                                                 ] 2.04%

Grabbing the full link at https://i.postimg.cc/8kvsqvdC/d7.jpg took 0.45039680699983364 seconds to run

[==================================================] 100.00%

OCR returns: 30/03/2022
Running OCR on https://i.postimg.cc/8kvsqvdC/d7.jpg took 26.82007432699993 seconds to run
7566
7567
Grabbing the full link at https://i.postimg.cc/rmCdwFbg/2044-5-N66-M-Clam-Shell-on-40-V6-M-mast-for-S-300-PT-destr-24-02-22.jpg took 0.3736330229999112 seconds to run
7567
7568
Grabbing the full link at https://i.postimg.cc/gJ5dSnjH/1013-5-N66-M-Clam-Shell-on-40-V6-M-mast-for-S-300-PT-aband-24-02-22.jpg took 0.38802551299977495 seconds to run
7568
7569
Grabbing the full link at https://i.postimg.cc/yd3VHh08/564.jpg took 0.3625094250000984 seconds to run

Connecting to https://i.postimg.cc/yd3VHh08/564.jpg ...
Downloading 564.jpg ...
[==================================================] 100.00%

OCR returns: K|30/03/2022
Running OCR on https://i.postimg.cc/yd3VHh08/564.jpg took 14.78709883800002 seconds to run
7569
7570
Grabbing the full link at https://i.postimg.cc/ZRFnM10z/2032-9-S32-1-radar-for-9-K81-1-S-300-V1-destr-23-02-25.jpg took 0.36270684200007963 seconds to run
7570
7571
Grabbing the full link at https://i.postimg.cc/Prswr5Nc/2006-P-37-Mech-early-warning-radar-capt-28-02-22.jpg took 0.36631169700012833 seconds to run
7571
7572
Grabbing the full link at https://i.postimg.cc/G2RBm0Rp/ff3.jpg took 0.3638623340002596 seconds to run

Connecting to https://i.postimg.cc/G2RBm0Rp/ff3.jpg ...
Downloading ff3.jpg ...
[==================================================] 100.00%

OCR returns: 02.04.2022|EE
Running OCR on https://i.postimg.cc/G2RBm0Rp/ff3.jpg took 23.44959862399992 seconds to run
7572
7573
Grabbing the full link at https://i.postimg.cc/vBgWF77N/473.png took 1.057629119000012 seconds to run

Connecting to https://i.postimg.cc/vBgWF77N/473.png ...
Downloading 473.png ...
[==================================================] 100.00%

OCR returns: 17/12/2022|3KCKAH3MBbI CBO
Running OCR on https://i.postimg.cc/vBgWF77N/473.png took 22.31052146600041 seconds to run
7573
7574

Connecting to https://i.postimg.cc/c4DVgZbq/224.png ...
Downloading 224.png ...
[                                                  ] 0.21%

Grabbing the full link at https://i.postimg.cc/c4DVgZbq/224.png took 0.3860867160001362 seconds to run

[==================================================] 100.00%

OCR returns: @smotri_media|07/3/2022|27views|0:26/0:38
Running OCR on https://i.postimg.cc/c4DVgZbq/224.png took 27.717865119999715 seconds to run
7574
7575

Connecting to https://i.postimg.cc/T1D2X7fy/jm.png ...
Downloading jm.png ...
[                                                  ] 0.31%

Grabbing the full link at https://i.postimg.cc/T1D2X7fy/jm.png took 0.4442777659996864 seconds to run

[==================================================] 100.00%

OCR returns: 05|13/4/2022
Running OCR on https://i.postimg.cc/T1D2X7fy/jm.png took 16.97663843600003 seconds to run
7575
7576
Returning non-postimg link
7576
7577
Grabbing the full link at https://i.postimg.cc/bv1t5zMz/2012-radar-ST-68-U-destr-16-02-23.jpg took 0.4195361430001867 seconds to run
7577
7578
Grabbing the full link at https://i.postimg.cc/gc78HLrw/2004-radar-ST-68-U-destr-16-08-23.jpg took 0.440991072000088 seconds to run
7578
7579
Returning non-postimg link
7579
7580
Grabbing the full link at https://i.postimg.cc/bJzL8vcF/2007-ST-68-U-3-D-Radar-destr-24-11-23.jpg took 0.3840827200001513 seconds to run
7580
7581
Grabbing the full link at https://i.postimg.cc/P51q3GDj/2013-ST-68-U-Radar-destr-08-03-24.jpg took 0.3794556249999914 seconds to run
7581
7582
Grabbing the full link at https://i.postimg.cc/7hSjYm8M/2004-36-D6-ST-68-U-surveillance-radar-destr-01-08-24.jpg took 0.4199242210002012 seconds to run
7582
7583
Grabbing the full link at https://i.postimg.cc/9fbLXSkB/2039-36-D6-ST-68-U-surveillance-radar-destr-23-09-24.jpg took 0.4014879649998875 seconds to run
7583
7584
Grabbing the full link at https://i.postimg.cc/MKgpC6qD/2073-36-D6-ST-68-U-surveillance-radar-destr-25-08-24.jpg took 0.4042341619997387 seconds to run
7584
7585
Grabbing the full link at https://i.postimg.cc/SxCMgrsY/2002-36-D6-ST-68-U-surveillance-radar-destr-13-07-25.jpg took 1.4342234840000856 seconds to run
7585
7586
Grabbing the full link at https://i.postimg.cc/Sxb2mjBK/2005-1-L220-UK-Zoopark-3-dam-01-08-23.jpg took 0.41356087899976046 seconds to run
7586
7587
Returning non-postimg link
7587
7588
Grabbing the full link at https://i.postimg.cc/13nggD3m/2002-P-18-ML-early-warning-radar-destr-31-05-24.jpg took 0.4333577970000988 seconds to run
7588
7589
Grabbing the full link at https://i.postimg.cc/HLbVzHMF/2009-P-18-ML-early-warning-radar-destr-04-06-24.jpg took 0.47237799300000916 seconds to run
7589
7590
Returning non-postimg link
7590
7591
Grabbing the full link at https://i.postimg.cc/Kv0jSDqD/2020-P-18-ML-early-warning-radar-dam-10-06-24.jpg took 0.3980529850000494 seconds to run
7591
7592
Grabbing the full link at https://i.postimg.cc/kXQMd72Y/2002-AN-MPQ-64-Sentinel-destr-06-07-23.jpg took 0.42077285200002734 seconds to run
7592
7593
Grabbing the full link at https://i.postimg.cc/VvQHFDfW/2010-TRML-4-D-multi-functional-radar-for-IRIS-T-SLM-destr-03-06-25.jpg took 0.4025726309996571 seconds to run
7593
7594
Returning non-postimg link
7594
7595
Grabbing the full link at https://i.postimg.cc/1tXHxcH7/2015-ANTPQ-36-Firefinder-Counter-battery-radar-destr-20-08-23.jpg took 0.3946385280000868 seconds to run
7595
7596
Grabbing the full link at https://i.postimg.cc/G2L9TMH1/2007-AN-TPQ-36-destr-06-03-24.jpg took 0.39596577399970556 seconds to run
7596
7597
Grabbing the full link at https://i.postimg.cc/wMxybj5W/2004-AN-TPQ-36-Firefinder-counter-battery-radar-destr-21-05-24.jpg took 0.39893343399990044 seconds to run
7597
7598
Grabbing the full link at https://i.postimg.cc/q7HzdCh5/2004-AN-TPQ-36-Firefinder-counter-battery-radar-destr-16-06-24.jpg took 0.42182764500012127 seconds to run
7598
7599
Grabbing the full link at https://i.postimg.cc/9FT9TckY/2001-AN-TPQ-36-Firefinder-counter-battery-radar-destr-24-06-24.jpg took 0.7027159439999195 seconds to run
7599
7600
Returning non-postimg link
7600
7601
Grabbing the full link at https://i.postimg.cc/brRhXbFg/2019-AN-TPQ-36-dam-07-11-23.jpg took 0.3967529699998522 seconds to run
7601
7602
Grabbing the full link at https://i.postimg.cc/hGKNfkkM/2025-AN-TPQ-36-radar-dam-08-05-24.jpg took 0.3773917589996927 seconds to run
7602
7603
Returning non-postimg link
7603
7604
Grabbing the full link at https://i.postimg.cc/mDTy1GR8/2015-ANTPQ-37-lightweight-counter-mortar-radar-destr-28-02-23.jpg took 0.4343576460000804 seconds to run
7604
7605
Grabbing the full link at https://i.postimg.cc/fRgwnrkP/d6.png took 0.3898863019999226 seconds to run

Connecting to https://i.postimg.cc/fRgwnrkP/d6.png ...
Downloading d6.png ...
[==================================================] 100.00%

OCR returns: 17/3/2022
Running OCR on https://i.postimg.cc/fRgwnrkP/d6.png took 24.18621496800006 seconds to run
7605
7606
Grabbing the full link at https://i.postimg.cc/DyQ6Gzg4/2000-ANTPQ-50-Counterfire-radar-destr-29-06-23.jpg took 0.4517047750000529 seconds to run
7606
7607
Grabbing the full link at https://i.postimg.cc/jS8bs2tc/2021-AN-TPQ-50-counter-battery-radar-destr-08-07-23.jpg took 0.3978070100001787 seconds to run
7607
7608
Grabbing the full link at https://i.postimg.cc/rmFTxmSR/2001-AN-TPQ50-destr-26-07-23.jpg took 0.418180773000131 seconds to run
7608
7609
Grabbing the full link at https://i.postimg.cc/dV3Qdbpq/6511.png took 0.4771557080002822 seconds to run

Connecting to https://i.postimg.cc/dV3Qdbpq/6511.png ...
Downloading 6511.png ...
[==================================================] 100.00%

OCR returns: 10/9/2023|KPbINATLE|09/0440|PbInaTLE|000/00
Running OCR on https://i.postimg.cc/dV3Qdbpq/6511.png took 28.392966902999888 seconds to run
7609
7610

Connecting to https://i.postimg.cc/DyKhkJLK/245.png ...
Downloading 245.png ...
[                                                  ] 0.38%

Grabbing the full link at https://i.postimg.cc/DyKhkJLK/245.png took 0.3907202270002017 seconds to run

[==================================================] 100.00%

OCR returns: 17/9/2023|PNNISENEIN|BENE
Running OCR on https://i.postimg.cc/DyKhkJLK/245.png took 17.375931689000026 seconds to run
7610
7611
Grabbing the full link at https://i.postimg.cc/MTcMzZJg/2041-AN-TPQ-50-counter-battery-radar-destr-15-05-24.jpg took 0.40013855600045645 seconds to run
7611
7612
Grabbing the full link at https://i.postimg.cc/k5xGbGpF/2002-AN-TPQ-50-counter-battery-radar-dam-22-07-24.jpg took 0.4416436009996687 seconds to run
7612
7613
Grabbing the full link at https://i.postimg.cc/x1C6QHFP/2002-radar-arthur-destr-21-02-23.jpg took 0.9185291000003417 seconds to run
7613
7614
Grabbing the full link at https://i.postimg.cc/L6JsQYK5/2006-AN-MPQ-53-radar-for-MIM-104-Patriot-dam-10-10-24.jpg took 0.3699989409997215 seconds to run
7614
7615

Connecting to https://i.postimg.cc/SQ2hn9Gm/437.png ...
Downloading 437.png ...
[                                                  ] 0.53%

Grabbing the full link at https://i.postimg.cc/SQ2hn9Gm/437.png took 0.3735778999998729 seconds to run

[==================================================] 100.00%

OCR returns: 16/9/2023
Running OCR on https://i.postimg.cc/SQ2hn9Gm/437.png took 7.7564204860000245 seconds to run
7615
7616
Grabbing the full link at https://i.postimg.cc/g0xymkWN/2017-RADA-ie-MHR-radar-destr-24-02-24.jpg took 0.4371819759999198 seconds to run
7616
7617
Grabbing the full link at https://i.postimg.cc/pLmT5bGd/2006-RADA-ie-MHR-destr-09-07-24.jpg took 0.3886229909994654 seconds to run
7617
7618
Grabbing the full link at https://i.postimg.cc/XJTpdKGv/2004-Unknown-radar-destr-16-05-24.jpg took 0.3811260319998837 seconds to run
7618
7619
Grabbing the full link at https://i.postimg.cc/Y26VFt57/2015-Unknown-radar-destr-26-09-24.jpg took 0.4636992770001598 seconds to run
7619
7620
Grabbing the full link at https://i.postimg.cc/PxMv7FNc/4437.png took 0.40511496200088004 seconds to run

Connecting to https://i.postimg.cc/PxMv7FNc/4437.png ...
Downloading 4437.png ...
[==================================================] 100.00%

OCR returns: 小|eele|04/6/2022 (but captured earlier)|https://t.me/HersonVestnik|https://t.me/HersonVestnik
Running OCR on https://i.postimg.cc/PxMv7FNc/4437.png took 17.75020320800013 seconds to run
7620
7621
Grabbing the full link at https://i.postimg.cc/6QPWKzx5/2008-Bukovel-AD-EW-system-destr-05-05-23.jpg took 0.43315024799994717 seconds to run
7621
7622
Grabbing the full link at https://i.postimg.cc/NGPvP3ND/2049-Bukovel-AD-EW-destr-14-06-23.jpg took 0.4698830730003465 seconds to run
7622
7623
Grabbing the full link at https://i.postimg.cc/B65L5Xf4/2011-Bukovel-AD-EW-system-destr-15-06-23.jpg took 0.49352066700066644 seconds to run
7623
7624
Grabbing the full link at https://i.postimg.cc/Y9m1SL7j/2010-Bukovel-AD-electronic-warfare-system-destr-15-01-25.jpg took 0.457787143999667 seconds to run
7624
7625
Grabbing the full link at https://i.postimg.cc/mrsCVbzg/2005-Bukovel-AD-electronic-warfare-system-destr-13-04-25.jpg took 0.49264414200024476 seconds to run
7625
7626
Grabbing the full link at https://i.postimg.cc/vZVmGWSN/2008-Bukovel-AD-dam-02-12-23.jpg took 0.4720651009993162 seconds to run
7626
7627
Grabbing the full link at https://i.postimg.cc/JnY1xB3s/2015-Plastun-RP3000-MTDFS-destr-03-03-24.jpg took 0.46654606999982207 seconds to run
7627
7628
Grabbing the full link at https://i.postimg.cc/vB3RpDYj/2004-Kolchuga-M-EW-passive-sensor-dam-20-03-24.jpg took 0.4745097340000939 seconds to run
7628
7629
Grabbing the full link at https://i.postimg.cc/XYtgd1XH/g68.png took 0.39164412500031176 seconds to run

Connecting to https://i.postimg.cc/XYtgd1XH/g68.png ...
Downloading g68.png ...
[==================================================] 100.00%

OCR returns: 24/02/2022
Running OCR on https://i.postimg.cc/XYtgd1XH/g68.png took 25.005138134000845 seconds to run
7629
7630
Grabbing the full link at https://i.postimg.cc/fRgL7VPw/2003-mig29-destr-30-09-23.jpg took 0.37824810300026 seconds to run
7630
7631

Connecting to https://i.postimg.cc/bYGXz89F/3f.png ...
Downloading 3f.png ...
[                                                  ] 0.21%

Grabbing the full link at https://i.postimg.cc/bYGXz89F/3f.png took 0.3630577909998465 seconds to run

[==================================================] 100.00%

OCR returns: GNOOICAY|L3|ROHTPOIS CU|AMOTA|PHCBOEHHR|AHHH|KpaiHn|TEPOR|President of Ukraine Volodymyr Zelensky awarded the title of Hero of Ukraine to Lieutenant|Colonel Vyacheslav Yerko (posthumously.|This is reported by Censor.NET.|As stated in Decree No. 338/2022,the award was conferred for personal courage and|heroism shown in the defense of the state sovereignty and territorial integrity of Ukraine.|selfless service to the Ukrainian people.|"Assign the title of Hero of Ukraine with the award of the Order of the Golden Star of YERKO|Vyacheslav Vladimirovich -Lieutenant Colonel (posthumously)." the decree says.|24/02/2022
Running OCR on https://i.postimg.cc/bYGXz89F/3f.png took 62.225722983000196 seconds to run
7631
7632

Connecting to https://i.postimg.cc/tC7ZDK50/532.png ...
Downloading 532.png ...
[                                                  ] 0.42%

Grabbing the full link at https://i.postimg.cc/tC7ZDK50/532.png took 0.43181352600004175 seconds to run

[==================================================] 100.00%

OCR returns: The Military Watch|On24February|2022|a Ukrainian Air Force|Mikoyan-Gurevich MiG-29 fighter aircraft piloted|by podpolkovnik VolodymyrKokhanskyi did not|return to base (most likely was shot down during|air battle in the area of Kyiv). The body of the|pilot was found in late April and buried on 6 May|2022.|COLONE
Running OCR on https://i.postimg.cc/tC7ZDK50/532.png took 32.927844494000055 seconds to run
7632
7633
Grabbing the full link at https://i.postimg.cc/9MhcsqKd/2004-mig29-destr-30-09-23.jpg took 0.39636388800045097 seconds to run
7633
7634

Connecting to https://i.postimg.cc/tJssfG8n/48.png ...
Downloading 48.png ...
[                                                  ] 0.64%

Grabbing the full link at https://i.postimg.cc/tJssfG8n/48.png took 0.41015082100057043 seconds to run

[==================================================] 100.00%

OCR returns: :|LIGA 360|VERDICTUM|中|yxBana Big 24.07.2022 Ne 344/8274/22 lBaHo-ΦpaHkicbKni anenuiinǔ cyA|1) BHKJCBHK CBaTIPO eHOBJHH PKHE MHIBCaO 3BJC HOB PHH,KBHHPBOBOTTPMaHHOCI BPOI| ace ace  ce e eee e |Cπi Cy 3OBaH BiOB ynoOBeHHi cpy pnaHH i Bapo,mo npypopCi He Bee,mo CBHH,HaeHiy acHi peri iεi caTi|A TT|BKpuMiHaJbHOMynpOBaeHHiN 22229002OCOBA_1nOBiOMeHonpo niO3py Bi 01epe3H 2O22 pOKyy ByHeHHi KpnMiHaJbHHXnpaBonOpymeHb,nepeaeHx|q.5 CT. 27,q.3 cr. 110,q.1 cr. 111 KK yKpaiHH (a. C. 73-78),TOTo nOCOHHuTBa y ByHHeHHi yMHCHHx i 3 MeOr 3MiHH Me TepuOpi Ta epKaBHOro KOpOHy YKpaiHH Ha|  e  e  c     |yMHCHo BHeHOMy rOMHHOM pa Hm CypHieOBi,eOpiiiicHOi  HeOOpaHciOHHOCi,paHni aHn,-H|iHOseMHi epaBi,iHOeHiOpraHia ra inpCaBHaM Onor B npoBeHHi nipBHoi ibHOcinpon Ypn.|3Opea,OCOA_1nipοεTC y TOy,mo y nepio 3 22no 25 πooro 222 poKy icyBa 3 onoMoro Oo,BieoMKn CaBnHH onaaHH 24 πoToro 22 poKy|Kpx peaepOpOy BicbOBoacH HOMEP_1 oro HainaBOy25OOro22pOyapopOMy BiCOBoi cH HOMEP_BOxiai|OBipaHx Cnn 3C ypaiHn,ienaiHH 25πooro 22poy Boi i c.KopoiBa a c.Γpyma Tyaboi popiJbHoirpoMa IBaHo-ΦpaHiBCboro paoHy IBaHo|paHiCboioaci niaa Mir-2,a ao nepeaBaB BaaHy iHopairo npeηcaBHnaM Pocicboi Φeepail|3okpema, OCoA_1nio3poeTbC y ToMy,o y nepio 3 2 no 25|In particular, PERSON_1 is suspected of having, between February 22|nOToro 2022 poKy icyBaB 3a onOMoroιo ΦoTo-,Bieo3OMK|and February 25,2022, recorded with the help of photo and video|ocTaBH nonaaHH 24 noToro 222 poKy kpnnaTx paKeT nO|recording the circumstances of the impact of cruise missiles on the|aeponpoMy BiCbKOBoi YaCTH HOMEP_1 Ta oro HacniK, aKT|airfield of military unit NUMBER_1 on February 24, 2022 and its|BHNboTy 25 nIoToro 2022 poKy 3 aepopoMy BiCbKOBoi 4aCTNH|consequences, the fact of the departure on February 25, 2022 from|HOMEP_1 BOx niTaKiB lOBiTpAHX Cun 3C YKpaiHN, Mice naiHH|the airfield of military unit part NUMBER_1 of two planes of the Air|25 noToro 2022 poKy B noni Mi c.KoponiBKa Ta c. pywKa|Force of the Armed Forces of Ukraine, the crash site on February 25,|Tnymabkoi repuopianboi rpoa lBao-ΦpakiBcbkoro paoy|2022,in the field between the village of Korolivka and Hrushka of th|lBaHo-ΦpaHkiBCbKoi onacTi niTaKa Mir-29, a Tao nepeBB|Tlumac Territorial Community of the lvano-Frankivsk District of the|BKa3ay iopaiιo npecaBHkam Pocicbko Φeepaui.|Ivano-Frankivsk Region of the MiG-29 aircraft, and also conveyed the|specified information to the representatives of the Russian|Cyn anenuiHoi iHcaHii 3Bepae yBaryo npemom|Federation.|anenauinHoro ockape|The appellate court draws attention to the subject of the appeal
Running OCR on https://i.postimg.cc/tJssfG8n/48.png took 105.84674308400008 seconds to run
7634
7635

Connecting to https://i.postimg.cc/KcNhcMtc/3114.png ...
Downloading 3114.png ...
[                                                  ] 1.08%

Grabbing the full link at https://i.postimg.cc/KcNhcMtc/3114.png took 1.2242963219996454 seconds to run

[==================================================] 100.00%

OCR returns: OBOZR|08:01April 9 Kyiv Ukraine|The war with the invaders of our native land revealed the incomprehensible heroism of the Ukrainian|people. Many more great names of heroes will become known after the victory.Today is a story about one|ofthem. Pilot Oleksandr Brinzhala courageously defended the capital of Ukraine. It is known that the|major died a brave death in a battle against 12 planes of the invaders.|The pilot of the 40th tactical aviation brigade died on March 2.It is known that on April 2,the President of|Ukraine awarded him the title of Hero of Ukraine, unfortunately-posthumously.|The Ukrainian pilot died as a Hero|Alexander Brynzhal|"The pilot of the 40th tactical aviation brigade, Major Oleksandr Brinjala,courageously defended the|capital and died a brave death in a battle against 12 enemy planes, the Ministry of Defense reported.|They also explained about the tragic day of March 2:|the occupiers attacked Kyiv with fighters from all directions-two Ukrainian MiG-29s went out to|intercept Russian planes;|our pilots gave the occupier a decent repulse, but in that battle, pilot 1st class Oleksandr Brinzhala|died.|Our pilot died at the hands of the occupiers: a video about him|"Since April 2,2022,Major Oleksandr Brynzhala is a Hero of Ukraine (posthumously).Eternal memory and|eternal glory to the Hero!",the ministry concluded.
Running OCR on https://i.postimg.cc/KcNhcMtc/3114.png took 40.747233422000136 seconds to run
7635
7636

Connecting to https://i.postimg.cc/6q91j7pf/1300.jpg ...
Downloading 1300.jpg ...
[                                                  ] 1.39%

Grabbing the full link at https://i.postimg.cc/6q91j7pf/1300.jpg took 0.4743341139992481 seconds to run

[==================================================] 100.00%

OCR returns: Mir-29|Mir-29|SEPEBIBKA|SEPE3IBKA|08.03.2022|08.03.2022|MOTawNH AHApi|Mir-29|08.03.2022|BiuHa naM'ATb repoo!|BEPE3IBKA|Mir-29|08.03.2022
Running OCR on https://i.postimg.cc/6q91j7pf/1300.jpg took 18.000876023000274 seconds to run
7636
7637
Grabbing the full link at https://i.postimg.cc/TYpbCRPG/548.png took 0.47774471400043694 seconds to run

Connecting to https://i.postimg.cc/TYpbCRPG/548.png ...
Downloading 548.png ...
[==================================================] 100.00%

OCR returns: Major Stepan Tarabalka fought for the freedom and independence of our state.He|protected the sky from enemies,informs "Windows".|By Decree of the President of Ukraine N148/2022"On conferring the title of Hero of|Ukraine" for personal courage and heroism shown in defense of state sovereignty and|territorial integrity of Ukraine, loyalty to the military oath,MiG-29 pilot Stepan|Tarabalka was posthumously awarded the title of Hero of Ukraine Star".|(shot down on|13/3/2022)
Running OCR on https://i.postimg.cc/TYpbCRPG/548.png took 22.068523647999427 seconds to run
7637
7638

Connecting to https://i.postimg.cc/k5bY36V0/4f114.png ...
Downloading 4f114.png ...
[                                                  ] 0.80%

Grabbing the full link at https://i.postimg.cc/k5bY36V0/4f114.png took 0.3637843240003349 seconds to run

[==================================================] 100.00%

OCR returns: OSINTtechnical|@Osinttechnical|The|UkranianAirForceconfirmsthedeathofMiG-29|pilot Major|Eugene|Lisenko,|killed "in a air battle near|Zhytomyr"|Engaged2enemy|aircraft, shot down one, but was hit|by antiaircraft fire.|1:48 am· 16 Mar 2022·Twitter Web App
Running OCR on https://i.postimg.cc/k5bY36V0/4f114.png took 16.82632196600025 seconds to run
7638
7639
Grabbing the full link at https://i.postimg.cc/nLCsDSBB/542.png took 0.3659538739993877 seconds to run

Connecting to https://i.postimg.cc/nLCsDSBB/542.png ...
Downloading 542.png ...
[==================================================] 100.00%

OCR returns: 16/3/2022
Running OCR on https://i.postimg.cc/nLCsDSBB/542.png took 18.603544949000025 seconds to run
7639
7640

Connecting to https://i.postimg.cc/nVsqVZzK/4388.png ...
Downloading 4388.png ...
[==================================================] 100.00%

Grabbing the full link at https://i.postimg.cc/nVsqVZzK/4388.png took 0.5209031530002903 seconds to run
OCR returns: It became known about the death of two aviators who served in Lutsk|Olena Parai· March 25,22:28|Lutsk Mayor lhor Polishchuk announced the death of two servicemen of the Sevastopol Brigade of Tactical|Aviation named after Oleksandr Pokryshkin, based in Lutsk.|Both servicemen and their families arrived in the regional center of Volyn in 2018.|Dmitry Chumachenko|Dmytro Chumachenko was the commander of the aviation unit of the Sevastopol Tactical Aviation Brigade. The pilot|was 26 years old.|According to the mayor, Dmytro was born in Russia, but in 1999 he settled in Donetsk region and became a citizen of|Ukraine. The commander was killed on March 23 in an air battle with unequal enemy forces in the village of Tryhirya,|Zhytomyr region.
Running OCR on https://i.postimg.cc/nVsqVZzK/4388.png took 39.78778453999985 seconds to run
7640
7641

Connecting to https://i.postimg.cc/zDgwM9Dm/4439.png ...
Downloading 4439.png ...
[                                                  ] 0.39%

Grabbing the full link at https://i.postimg.cc/zDgwM9Dm/4439.png took 0.38652878500033694 seconds to run

[==================================================] 100.00%

OCR returns: MilitaryLand.net|War Monitor|@Militarylandnet|@WarfareReports|Maj. Taras Redkin was killed during a combat|Deputy squadron commander Taras Redkin was|mission in the area of operations. Exact date and place|also killed in action yesterday, he flew MiG-29.|isn't specified.|#UkraineRussiaWar|Both stories were reported by Ukrainian sources.|9:21 am·3 Oct 2022·Twitter Web App
Running OCR on https://i.postimg.cc/zDgwM9Dm/4439.png took 31.298548030000347 seconds to run
7641
7642
Returning non-postimg link
7642
7643

Connecting to https://i.postimg.cc/bY9szz6f/6651.png ...
Downloading 6651.png ...
[                                                  ] 0.72%

Grabbing the full link at https://i.postimg.cc/bY9szz6f/6651.png took 0.4279889509998611 seconds to run

[==================================================] 100.00%

OCR returns: The Military Watch|7 juli om 18:09|...|S|A Ukrainian|Air|Force|Mikoyan-Gurevich MiG-29|was destroyed|linthe|Russian missile attack on|Voznesensk Air|Base|Mykolaiv Oblast. It is not|clear whether the aircraft was in operational|service or was retired|and used as a|decoy.The|photo was|posted|on|15 June|2022|but in all|likelihood|the event took place considerably|earlier.|07/7/2022
Running OCR on https://i.postimg.cc/bY9szz6f/6651.png took 23.445668544 seconds to run
7643
7644
Returning non-postimg link
7644
7645
Grabbing the full link at https://i.postimg.cc/DzHxJZ9x/2003-mig29-destr-13-02-23.jpg took 0.39579214499917725 seconds to run
7645
7646
Grabbing the full link at https://i.postimg.cc/hG2ggRr7/2008-mig29-destr-24-02-22.jpg took 0.36531081900011486 seconds to run
7646
7647
Grabbing the full link at https://i.postimg.cc/brjCBKhs/2012-mig29-destr-02-06-23.jpg took 0.36294521699983306 seconds to run
7647
7648
Grabbing the full link at https://i.postimg.cc/SRdHJSj6/2007-mig29-destr-24-07-23.png took 0.3701619480007139 seconds to run
7648
7649

Connecting to https://i.postimg.cc/3x7HkxGb/5426.png ...
Downloading 5426.png ...
[                                                  ] 0.95%

Grabbing the full link at https://i.postimg.cc/3x7HkxGb/5426.png took 0.36752906200035795 seconds to run

[==================================================] 100.00%

OCR returns: 25/9/2023
Running OCR on https://i.postimg.cc/3x7HkxGb/5426.png took 10.551959166000415 seconds to run
7649
7650
Grabbing the full link at https://i.postimg.cc/9MSTfJWZ/2001-mig29-destr-22-12-23.jpg took 0.3875466839999717 seconds to run
7650
7651
Grabbing the full link at https://i.postimg.cc/vHJBt8ch/2012-mig29-destr-08-03-24.jpg took 0.38494698900012736 seconds to run
7651
7652
Grabbing the full link at https://i.postimg.cc/t4GzqNGd/2035-mig-29-destr-24-02-22.jpg took 0.42040677500062884 seconds to run
7652
7653
Grabbing the full link at https://i.postimg.cc/mkFRfPqr/2003-mig29-destr-20-04-24.jpg took 0.4580958019996615 seconds to run
7653
7654
Grabbing the full link at https://i.postimg.cc/gJPh0tMs/2009-mig29-destr-22-05-24.jpg took 0.4332732989996657 seconds to run
7654
7655
Grabbing the full link at https://i.postimg.cc/R0sCwDd5/2024-mig29-destr-27-04-24.jpg took 0.3937646300000779 seconds to run
7655
7656
Grabbing the full link at https://i.postimg.cc/mkP4qpTm/2019-Mi-G-29-fighter-aircraft-destr-03-07-24.jpg took 0.393625843999871 seconds to run
7656
7657
Grabbing the full link at https://i.postimg.cc/GhYBmXgs/2033-mig29-destr-12-08-24.jpg took 0.36840167799982737 seconds to run
7657
7658
Grabbing the full link at https://i.postimg.cc/J03BcYGz/2017-Mi-G-29-fighter-aircraft-destr-16-08-24.jpg took 0.43849071800013917 seconds to run
7658
7659
Returning non-postimg link
7659
7660
Grabbing the full link at https://i.postimg.cc/rsVRdPfr/2009-Mi-G-29-fighter-aircraft-dam-18-04-24.jpg took 0.394969754000158 seconds to run
7660
7661
Grabbing the full link at https://i.postimg.cc/L5yDGw6f/2018-Mi-G-29-MU1-fighter-aircraft-dam-30-04-24.jpg took 0.46141848499974003 seconds to run
7661
7662
Grabbing the full link at https://i.postimg.cc/8z4RX6tX/2100-su27-destr-24-02-22.jpg took 0.4466318400000091 seconds to run
7662
7663

Connecting to https://i.postimg.cc/bN1TbkjC/46.png ...
Downloading 46.png ...
[                                                  ] 0.49%

Grabbing the full link at https://i.postimg.cc/bN1TbkjC/46.png took 0.4447577739992994 seconds to run

[==================================================] 100.00%

OCR returns: KOHTPON AAEJEHMSI|BNDIETEPHETHAN|25/02/2022
Running OCR on https://i.postimg.cc/bN1TbkjC/46.png took 15.59815593500025 seconds to run
7663
7664

Connecting to https://i.postimg.cc/dQWVLThg/326.png ...
Downloading 326.png ...
[                                                  ] 0.87%

Grabbing the full link at https://i.postimg.cc/dQWVLThg/326.png took 0.4082887250006024 seconds to run

[==================================================] 100.00%

OCR returns: MiniTapHn|21|@mil_in_ua|NinoT Cy-27 Maop CenaH YoaH, K io|Te  r   rr  eee|Shot|down|KponNBHNUbKM.|on|penet Bonoup|3eneHcbknianncaByka3npo|nPnCBOHH OMy BHH epO YKpaiH OCMTHO!|28/02/2022|BIYHA ∩AM'ATb TEPOIO!|Translated from Ukrainian by|Google|Su-27|pilot Major Stepan Choban, who at the cost of|his own life|distracted|enemy aircraft over|Kropyvnytskyi.|President Volodymyr|Zelensky signed a decree|awarding|him|the|titleofHeroofUkraine|posthumously!|ETERNALMEMORYOFTHEHERO!|12:13 pm· 3 Mar 2022 ·Twitter for Android
Running OCR on https://i.postimg.cc/dQWVLThg/326.png took 42.20165872800044 seconds to run
7664
7665

Connecting to https://i.postimg.cc/fR6S8HY7/4f.png ...
Downloading 4f.png ...
[                                                  ] 0.26%

Grabbing the full link at https://i.postimg.cc/fR6S8HY7/4f.png took 0.41225076699993224 seconds to run

[==================================================] 100.00%

OCR returns: Cnope|38|Cna cHan GPS(|70.90|03811m|23:06|nauath|A|RES&FPS EV|4K30|+0.7
Running OCR on https://i.postimg.cc/fR6S8HY7/4f.png took 24.87768988299922 seconds to run
7665
7666

Connecting to https://i.postimg.cc/g2crXNnW/662.png ...
Downloading 662.png ...
[                                                  ] 0.37%

Grabbing the full link at https://i.postimg.cc/g2crXNnW/662.png took 0.3904789450007229 seconds to run

[==================================================] 100.00%

OCR returns: Heavy loss: a pilot from Zhytomyr crashed while performing a mission|5ABN4|Photo: Oleksandr Lovyniuk's Facebook page|E|August23,202220:13|5|The city was shaken by the sad news: on August 21, 2022, our compatriot Babych Pavlo Petrovych, lieutenant colonel, commander of an|aviation squadron, died while performing a combat mission.|This was reported by Oleksandr Lovyniuk, a deputy of the Novoyguvin settlement council
Running OCR on https://i.postimg.cc/g2crXNnW/662.png took 35.4761462739998 seconds to run
7666
7667

Connecting to https://i.postimg.cc/tgDL4PKN/6523.png ...
Downloading 6523.png ...
[                                                  ] 0.39%

Grabbing the full link at https://i.postimg.cc/tgDL4PKN/6523.png took 0.4379594239999278 seconds to run

[==================================================] 100.00%

OCR returns: On October 10, Povitryany Forces lost a Su-27 from the 39th BrTA,piloted by Colonel Oleg Shupik. Shupyk, already a middle-aged pilot born in|1966, graduated from the Chernihiv Higher Military Aviation School in 1987,rose to the rank of deputy chief navigator and inspector of the navigation|service of the Center Air Command. In 2006, he retired from the Povitryany Forces and worked in the Ministry of Transport and various aviation|structures of Ukraine. With the beginning of the war,the 39th BrTA returned to service for a position in the navigation service of the brigade. It is known|that he died on October 10 near the village of Shishaki, Poltava region, and there are no Russian requests for the destruction of Ukrainian Su-27s on that|day, as well as other types of aircraft.|The funeral of another veteran of the 39th BrTA, Colonel Oleg Shupik, who died in a sortie on October 10, 2022.As|usual, there is no application for the downing of this Su-27 from the RF Ministry of Defense.
Running OCR on https://i.postimg.cc/tgDL4PKN/6523.png took 43.847079493999445 seconds to run
7667
7668

Connecting to https://i.postimg.cc/yYYnJqkd/332o.png ...
Downloading 332o.png ...
[                                                  ] 0.59%

Grabbing the full link at https://i.postimg.cc/yYYnJqkd/332o.png took 0.4230900989996371 seconds to run

[==================================================] 100.00%

OCR returns: 10/3/2022
Running OCR on https://i.postimg.cc/yYYnJqkd/332o.png took 14.639155898000354 seconds to run
7668
7669

Connecting to https://i.postimg.cc/g01tJpzN/3fp.png ...
Downloading 3fp.png ...
[                                                  ] 0.48%

Grabbing the full link at https://i.postimg.cc/g01tJpzN/3fp.png took 0.39044927499980986 seconds to run

[==================================================] 100.00%

OCR returns: 28/3/2023|Pilot:|Denys|Kyrylyuk|31
Running OCR on https://i.postimg.cc/g01tJpzN/3fp.png took 24.46746548200008 seconds to run
7669
7670
Grabbing the full link at https://i.postimg.cc/43f8XSQt/2001-su27-destr-23-07-22.jpg took 0.3841003469997304 seconds to run
7670
7671
Grabbing the full link at https://i.postimg.cc/4xZP1SMM/2002-su27-destr-23-07-22.jpg took 0.4609909089995199 seconds to run
7671
7672
Grabbing the full link at https://i.postimg.cc/Ghnxcfc2/2003-su27-destr-13-03-22.jpg took 0.4151649200002794 seconds to run
7672
7673
Grabbing the full link at https://i.postimg.cc/XYjFGXyJ/2023-su27-destr-22-12-23.jpg took 0.4040150889995857 seconds to run
7673
7674
Grabbing the full link at https://i.postimg.cc/MpNRCpVh/2010-su27-destr-17-05-24.jpg took 0.38077449799948226 seconds to run
7674
7675
Grabbing the full link at https://i.postimg.cc/C5SQsHBn/2007-Su-27-fighter-aircraft-destr-01-07-24.jpg took 0.3784352009997747 seconds to run
7675
7676
Grabbing the full link at https://i.postimg.cc/fyCg2tm2/2006-Su-27-fighter-aircraft-destr-01-07-24.jpg took 0.3790768869994281 seconds to run
7676
7677
Grabbing the full link at https://i.postimg.cc/vHzKXQyL/2000-Su27-destr-02-02-25.jpg took 0.3896308389994374 seconds to run
7677
7678
Grabbing the full link at https://i.postimg.cc/yx7z3rYg/2030-Su27-destr-28-04-25.jpg took 0.4238504489994739 seconds to run
7678
7679

Connecting to https://i.postimg.cc/YC63jp5h/p1.png ...
Downloading p1.png ...
[                                                  ] 0.50%

Grabbing the full link at https://i.postimg.cc/YC63jp5h/p1.png took 0.3694419249995917 seconds to run

[==================================================] 100.00%

OCR returns: 26/02/2022
Running OCR on https://i.postimg.cc/YC63jp5h/p1.png took 9.712741889000426 seconds to run
7679
7680
Grabbing the full link at https://i.postimg.cc/zfqkgsNp/p2.png took 0.5087334030004058 seconds to run

Connecting to https://i.postimg.cc/zfqkgsNp/p2.png ...
Downloading p2.png ...
[==================================================] 100.00%

OCR returns: 26/02/2022|190
Running OCR on https://i.postimg.cc/zfqkgsNp/p2.png took 43.717721082000025 seconds to run
7680
7681

Connecting to https://i.postimg.cc/rmZ7jy9j/3329.png ...
Downloading 3329.png ...
[                                                  ] 0.52%

Grabbing the full link at https://i.postimg.cc/rmZ7jy9j/3329.png took 0.39535429700026725 seconds to run

[==================================================] 100.00%

OCR returns: Every day at 9 a.m. during the Russian-Ukrainian war,|Ukrainians observe a minute of silence in memory of their|fallen compatriots. On April 29, let's remember the 28-year-|old captain of the 299th tactical aviation brigade named|after Lieutenant General Vasyl Nikiforov, the attack pilot|Oleksandr Korpan.|The story of Captain Oleksandr Korpan was told by Army Inform|journalists.|Oleksandr Korpan was born in Sevastopol. While studying at|the Kharkiv National University of the Air Force of Ukraine|Photo:armyinform.com.ua|named after lvan Kozhedub, he obtained the specialty of an|attack pilot and mastered the Su-25 aircraft. After graduation, he was sent to serve in the 299th Tactical Aviation Brigade named after|Lieutenant General Vasyl Nikiforov.|Oleksandr was repeatedly involved in the Operation of the United Forces in the east of Ukraine. With his professionalism and|diligence, he won the title of the best fighter pilot. In 2021, he was awarded departmental honors: the "Mastery, Honor, Courage"|commemorative badge,the "For Achievements in Military Service" honorary badge, and the "10 Years of Faithful Service" medal.|On March 2,Oleksandr Korpan was returning from another combat mission.His plane was suddenly hit by enemy fire.The car caught|fire.|"Captain Korpan performed a real feat by taking the plane engulfed in flames away from the airfield and at the cost of his own life|saved the lives of his brothers and many civilian residents of the city of Starokostyantyniv, where this tragedy occurred,"eyewitnesses|reported.|The stormtrooper pilot was buried in the town of Pidhaytsi, near Ternopil. In addition to his brothers, even strangers came to see him|on his last journey.|"We didn't know him personally, but we came to thank the guy for protecting our homes.Now he will protect us from the sky…"- said|the grateful townspeople.
Running OCR on https://i.postimg.cc/rmZ7jy9j/3329.png took 74.42365599299956 seconds to run
7681
7682

Connecting to https://i.postimg.cc/C5fYn87Q/542f.png ...
Downloading 542f.png ...
[                                                  ] 1.86%

Grabbing the full link at https://i.postimg.cc/C5fYn87Q/542f.png took 0.42990531000032206 seconds to run

[==================================================] 100.00%

OCR returns: 12|10/3/2022
Running OCR on https://i.postimg.cc/C5fYn87Q/542f.png took 16.356133033999868 seconds to run
7682
7683

Connecting to https://i.postimg.cc/Hnv8NnNz/554.png ...
Downloading 554.png ...
[                                                  ] 0.21%

Grabbing the full link at https://i.postimg.cc/Hnv8NnNz/554.png took 0.6257616869997946 seconds to run

[==================================================] 100.00%

OCR returns: Mamyur|Tereriagiu|M|BanisbBur|Rbimiar 1947foky|hapmiiibna|ecrcr paiομ|iBcεnεi b|25/02/2022
Running OCR on https://i.postimg.cc/Hnv8NnNz/554.png took 24.42399354600002 seconds to run
7683
7684

Connecting to https://i.postimg.cc/N09Nt886/669.png ...
Downloading 669.png ...
[                                                  ] 0.74%

Grabbing the full link at https://i.postimg.cc/N09Nt886/669.png took 0.386599323000155 seconds to run

[==================================================] 100.00%

OCR returns: Ukrainian pilot Roman Vasyliuk was released from|captivity|Thanks totheefortsoftheMain DirectorateofIntelligenceof theMinistryof DefenseaUkrainianpilot wasreleased from enemycaptivity.|Lt.Col.RomanVaylyuk,Ukraianu-2pilot,whowashotdownbemardenseoverVolovaka,Dokio|on March 14|while performing a combat mission. He was able to eject, but was wounded and captured by the occupiers.|Passed through numerous interrogations by the Russian special services.Before his release,he was in the regional central clinical hospital|of Donetsk.|On April 24,hereturned to the territory controlled byUkraine.Immediately afterhis release,the Ukrainianpilot met with thehead ofthe|MinistryofIntenalfairandommuicions,illBudao,andOlksiyDaiocrtaroftheC.
Running OCR on https://i.postimg.cc/N09Nt886/669.png took 43.9555442840001 seconds to run
7684
7685

Connecting to https://i.postimg.cc/mD8NFMTY/f5.png ...
Downloading f5.png ...
[                                                  ] 0.74%

Grabbing the full link at https://i.postimg.cc/mD8NFMTY/f5.png took 0.6114821920000395 seconds to run

[==================================================] 100.00%

OCR returns: Tetyana Seredyuk:"No awards will return my|husband and myfathers daughter.Yegor|M|M|deserved the tile ofHero ofUkrainelikeno|other"|mash|mash|mash|mash|ma|15/4/2022
Running OCR on https://i.postimg.cc/mD8NFMTY/f5.png took 21.140629546000127 seconds to run
7685
7686
Returning non-postimg link
7686
7687

Connecting to https://i.postimg.cc/sxysJGKk/58.png ...
Downloading 58.png ...
[                                                  ] 0.38%

Grabbing the full link at https://i.postimg.cc/sxysJGKk/58.png took 0.38504407399977936 seconds to run

[==================================================] 100.00%

OCR returns: On 14 May 2022, the Ukrainian Air Force kapitan Serhiy Parkhomenko was killed during combat|mission near Huliaipole, Zaporizhzhia Oblast. He was a Sukhoi Su-25 pilot from the 299th Tactical|Aviation Brigade.|37|XAPKIB|MNKOnAIB|IH|KEPCOH|棚|MIC
Running OCR on https://i.postimg.cc/sxysJGKk/58.png took 24.829559788999177 seconds to run
7687
7688

Connecting to https://i.postimg.cc/5tmrhZrn/2001.jpg ...
Downloading 2001.jpg ...
[=                                                 ] 3.97%

Grabbing the full link at https://i.postimg.cc/5tmrhZrn/2001.jpg took 0.4142214419998709 seconds to run

[==================================================] 100.00%

OCR returns: Illia Ponomarenko|@IAPonomarenko|MajorOleksandrKukurba,aSukhoiSu-25pilotofthe|299th Tactical Aviation Brigade (Mykolaiv), was killed|in air combat on July 26.|He was previously awarded the Hero of Ukraine title.|He was 28.|6:29PM·Jul27,2022·TwitterforMac
Running OCR on https://i.postimg.cc/5tmrhZrn/2001.jpg took 26.50358596099977 seconds to run
7688
7689

Connecting to https://i.postimg.cc/2ym06SYn/229.png ...
Downloading 229.png ...
[                                                  ] 0.73%

Grabbing the full link at https://i.postimg.cc/2ym06SYn/229.png took 0.4639414509993003 seconds to run

[==================================================] 100.00%

OCR returns: MilitaryAviationlnUa|@Ukraine_AF|Nig yac BKOHaHH|BnaroBiCH nioT wTypoBa Cy-5, ypoeHeub|HiHcbKoro paoHy, 4epHiriBcbKoi onacTi.|y epeHi peHT paiH HapB Ba|07/9/2022|OpaeHOM|boraHa|XmenbHubKoro l cyne.|BiuHa naM'aTb epoo!|Translated from Ukrainian by|Google|Vadym|Blagovisny,|the pilot of the Su-25 attack|aircraft,|anative|of|fNizhynsky|district,Cherni|region,|died while|performing a combatmission.|In March,|the President of Ukraine awarded Vadim with|the|Order of Bohdan Khmelnytskyi,|IIIdegree.|Eternal memory of the Hero!|SAAOSCMOO|BAAA|M08|nh|3A dEY.DO|CAOXRUTE OPEA
Running OCR on https://i.postimg.cc/2ym06SYn/229.png took 37.221990060999815 seconds to run
7689
7690
Returning non-postimg link
7690
7691
Returning non-postimg link
7691
7692

Connecting to https://i.postimg.cc/qBF97szr/62.png ...
Downloading 62.png ...
[                                                  ] 1.16%

Grabbing the full link at https://i.postimg.cc/qBF97szr/62.png took 0.3816439439997339 seconds to run

[==================================================] 100.00%

OCR returns: Vadim Serhiyevich Moroz|Nnatφopma|Ukrainian military serviceman|Vadym Serhiyovych Moroz-captainpilotofthe9thBrTAoftheArmedForceofUkraieaparticipantinthe Russian-Ukraiianwar.|nam'aTi|Biography|Vadim Moroz|Vodum Corhivich More|He was born on November 91995 in the village of Recruiters of Balakli district in Kharkiv|+++|Captain|Memopian|region .|general information|Captain, serviceman of the Armed Forces of Ukraine (unit - not specified). He received his|Birth|November 9.1995 p.|military education at Ivan Kozhedub KhNUPs.|Verbivka,Balakliya|district,Kharkiv|3arn6ni|y|BiǚHi|Poci|npoTn|YκpaH|Died on March 3, 2022,during a flight over Mykolaiv Oblast.|region, Ukraine|Death|March 3, 2022 (26 years old) Mykolaiv|He is buried in the village of Novooleksandrivka, Mykolaiv region, which he defended|region , Ukraine|during his last flight[1|Nationality|Ukrainian|Bam Mopo3|^ Awards|Alma Mater|KhNUPS named after|Ivan Kozhedub|•Order of Bohdan Khmelnytsky Il degree (2022, posthumous)—for personal courage|Military Service|and selflessactionsshown in thedefenseof state sovereigntyand territorial integrityof|Affiliation|Ukraine|299-Ta 6puraa|Ukraine, loyalty to the military oath.|Kind of ZS| Air Force|TaKTnHoi aBiauii| Sources|Formation|299 BrTA|• Decree of the President of Ukraine dated March 22, 2022 No.157/2022 "On State|Wars / battles|Russian-Ukrainian war|Awards of Ukraine"|Awards and honors
Running OCR on https://i.postimg.cc/qBF97szr/62.png took 59.1130336719998 seconds to run
7692
7693
Grabbing the full link at https://i.postimg.cc/9F4PYCXX/2019-su25-destr-27-01-23.jpg took 0.45740890500019304 seconds to run
7693
7694
Returning non-postimg link
7694
7695
Grabbing the full link at https://i.postimg.cc/GtrxsgM2/2017-su25-destr-07-02-24.jpg took 0.5025540189999447 seconds to run
7695
7696
Grabbing the full link at https://i.postimg.cc/CxNKXWr8/2025-su25-destr-10-06-24.jpg took 0.5246298309994017 seconds to run
7696
7697
Grabbing the full link at https://i.postimg.cc/023N4h19/2011-su25-destr-15-03-22.jpg took 0.5339540949998991 seconds to run
7697
7698
Grabbing the full link at https://i.postimg.cc/SxDGQvRn/2030-Su-25-destr-14-12-24.png took 0.5149747630002821 seconds to run
7698
7699
Grabbing the full link at https://i.postimg.cc/ZK57GTsJ/2203-Su-25-M1-K-close-air-support-aircraft-destr-31-10-24.jpg took 0.501928073000272 seconds to run
7699
7700
Grabbing the full link at https://i.postimg.cc/dQBNN7BW/2204-Su-25-M1-K-close-air-support-aircraft-destr-31-10-24.jpg took 0.48957278299985774 seconds to run
7700
7701
Grabbing the full link at https://i.postimg.cc/RZ3JpWC2/2013-su25-dam-06-06-24.jpg took 0.42196667900043394 seconds to run
7701
7702

Connecting to https://i.postimg.cc/L85FXF1d/7999.png ...
Downloading 7999.png ...
[                                                  ] 0.70%

Grabbing the full link at https://i.postimg.cc/L85FXF1d/7999.png took 0.4872902229999454 seconds to run

[==================================================] 100.00%

OCR returns: It became known about the new loss of the Ukrainian|Air Force.A Ukrainian Su-24 bomber was shot down|near Bucha in the Kiev region.|The crew of the plane was also destroyed. The car|belonged to|the|7th tactical|aviationbrigade.|JIbOTYHKH HO|BMHPaIOTb,|BOHH JICTATE|B|CBiA|OCTAHHIK|nonir...|SLAOYC PYCRAH|AOBIAIOKPOMAH|KAnITAN|QAEKCAILIPOHHY|OEKCAHJIPOBHY|77-1041653|S|Cy-24M"Fencer-D"|Iaiccaapa8|pa TA iM.IT.paa|GspOvOcTTus|IC 3C Yxpain|27.02
Running OCR on https://i.postimg.cc/L85FXF1d/7999.png took 22.773599613999977 seconds to run
7702
7703

Connecting to https://i.postimg.cc/wM3HJxdb/3260.png ...
Downloading 3260.png ...
[                                                  ] 0.48%

Grabbing the full link at https://i.postimg.cc/wM3HJxdb/3260.png took 0.3954590220000682 seconds to run

[==================================================] 100.00%

OCR returns: And again, the Ukrainian command modestly kept silent about the fact that on this day, March 2, a Ukrainian Su-24 was shot|down in the Novograd-Volynsky region, the crew of which - pilot Colonel Nikolai Kovalenko and navigator Captain Yevgeny|Kazimirov died.|SH|The crew of the Ukrainian Su-24, who died on March 2, is ex-brigade commander Colonel Nikolai|Kovalenko and captain Yevgeny Kazimirov. Both photos are old, Kazimirov was taken more than 10 years|ago, before his retirement.
Running OCR on https://i.postimg.cc/wM3HJxdb/3260.png took 37.29498565999984 seconds to run
7703
7704
Grabbing the full link at https://i.postimg.cc/RhpmNb6K/531.png took 0.40158951899957174 seconds to run

Connecting to https://i.postimg.cc/RhpmNb6K/531.png ...
Downloading 531.png ...
[==================================================] 100.00%

OCR returns: The Military Watch|1d|On 12 March 2022 a Ukrainian Air Force Sukhoi Su-24 was shot down by the Russian forces in the|area of Kakhovka,|Kherson Oblast. The crew consisting of podpolkovnik Valery Oshkalo and mayor|Roman Chehun did not survive.
Running OCR on https://i.postimg.cc/RhpmNb6K/531.png took 26.666064016000746 seconds to run
7704
7705
Grabbing the full link at https://i.postimg.cc/htJYmC3s/29.png took 0.42785762200037425 seconds to run

Connecting to https://i.postimg.cc/htJYmC3s/29.png ...
Downloading 29.png ...
[==================================================] 100.00%

OCR returns: 01985239|342|ixapee cniourno upo cepn.|935|(onepro|(mTpcorx pcrpaircramy)|xincroro |2303|2020|1.p|Uu KE)|7|Biric8|.fμomoiiut|2.Cran:on.-1.xis.-2(mxpec).|3.laa a:pixs|10|4.ara cuepri: pixsc|CO|05|03|SRC.T0|21|5.ne,xirel noyBisi6iomic|2oo-1,nooc-2(ipec)|6.o|a)Maca (sar)pu apoi|6)3picr ap wapoco|_r,|7.Me:|CM.|Aopans|,pecuyGnika,oacns.|palior|sicro,cr-1,c-2(xpe)|wyn.|8.Micoe cuepti:|Gya|KB.|ame，|paonobciicenenyur|6)csepn.gacana：ycaipi-1,，oa–2amymici-3(niaxpcms)|tinobi Qi|(ANCETW)|Su-24 pilot Major Vyacheslav Khodakovsky and his certificate of death as a result of military operations,|date of death -March 21|On March 21, another pilot from the 7th BrTA was killed - pilot Major Vyacheslav Khodakovsky, who a week earlier, on March 13,|was awarded the Order of Bogdan Khmelnitsky 3rd degree. The plane crashed in the Zaporozhye region, on the territory occupied|by Ukrainian troops.There are currently no media reports of his death from the Ukrainian side, the information was posted bythe|Telegram channel https://t.me/ragulinho, they also provided the author with evidence of the death of the Ukrainian pilot as a result|of hostilities.
Running OCR on https://i.postimg.cc/htJYmC3s/29.png took 59.55289659099981 seconds to run
7705
7706

Connecting to https://i.postimg.cc/hGtH70n0/531.png ...
Downloading 531.png ...
[                                                  ] 0.52%

Grabbing the full link at https://i.postimg.cc/hGtH70n0/531.png took 0.3688405460006834 seconds to run

[==================================================] 100.00%

OCR returns: The Military Watch|23u·|In the early stages of the war (before 26 March 2022) a Ukrainian Air Force Sukhoi Su-24 was shot|down by the Russian forces. The crew consisting of mayor Mykola Savchuk and mayor Dmytro|Kulikov did not survive.|CABYyK
Running OCR on https://i.postimg.cc/hGtH70n0/531.png took 25.490366207999614 seconds to run
7706
7707

Connecting to https://i.postimg.cc/sx4cct9G/531.png ...
Downloading 531.png ...
[                                                  ] 0.47%

Grabbing the full link at https://i.postimg.cc/sx4cct9G/531.png took 0.3726769120003155 seconds to run

[==================================================] 100.00%

OCR returns: The Military Watch|22u|'|On 30 March 2022 a Ukrainian Air Force Sukhoi Su-24 was shot down by the Russian forces|reportedly in the area of Tumen,|RivneOblast.ThecrewconsistingofpolkovnikMaksymSikalenko|and mayorKonstantin Gorodnychev did not survive.
Running OCR on https://i.postimg.cc/sx4cct9G/531.png took 25.13500315100009 seconds to run
7707
7708

Connecting to https://i.postimg.cc/nVQQVmKN/398.png ...
Downloading 398.png ...
[                                                  ] 0.19%

Grabbing the full link at https://i.postimg.cc/nVQQVmKN/398.png took 0.3697726230002445 seconds to run

[==================================================] 100.00%

OCR returns: TikTok|03/4/2022|@romapyrotech
Running OCR on https://i.postimg.cc/nVQQVmKN/398.png took 27.29683498600025 seconds to run
7708
7709

Connecting to https://i.postimg.cc/0jF7pNht/27.png ...
Downloading 27.png ...
[                                                  ] 0.31%

Grabbing the full link at https://i.postimg.cc/0jF7pNht/27.png took 0.38144773399926635 seconds to run

[==================================================] 100.00%

OCR returns: Lme/razved dozor|Winsto|Wisri|Kyp|Kobarerieo|OrerciLe|The risk of Corong)|Heart Disease in|08 woior01981poky|ceaseMlaokomepuibka|Rdauuo|N750|BOCALNDOU sETE|3anOrizonoro raLiOnJ|Oumi|ACI HIA SCIR TESTOPYEPAD|3anorizoct 0δami|Cunaugkotue|sbim20|Documents of Major Aleksey Kovalenko, whose body was found among the wreckage|of a Su-24 shot down on April 10|ine/razveddozo
Running OCR on https://i.postimg.cc/0jF7pNht/27.png took 37.04910339499929 seconds to run
7709
7710

Connecting to https://i.postimg.cc/8k69sX9b/6652.png ...
Downloading 6652.png ...
[                                                  ] 0.28%

Grabbing the full link at https://i.postimg.cc/8k69sX9b/6652.png took 0.41235011400021904 seconds to run

[==================================================] 100.00%

OCR returns: +|Kouargyha floeirpan Cun3Cy/ArForce Command ofUAArmed Forces|XAPRIB|2|BIPCKOBMXAOTHMKIBYBIHHVUINPOBENBOCTAHHNONIT|YEPHIrIB|23202pBn|XMAPY1aMJOp LAOHETAPA|192|OBoo|n|XapioyyepnCelaKya|ropc|wypuaoaiail ecxaapu|toc|oxynantis.|3aco|nXpHo|TepopcxipiBYoYx|apaHaroppOpeH3yllen|-Meyciorropoiayxpa|rpouoeiKouayeanloeirpan|iworo ropsxo6|xCoCHOronotipar|3aneg Bcix np|nepesarwe noei|norptoLiLBo|HMai|M.Choroma|o6ooeinafloipnxCn|Choaare 3MpoM6pamal|Hau fepcaul|f po sa ey cep|Crasa reposul|Estoprussia|EPH|19/5/2022|XMAPA|HETAP
Running OCR on https://i.postimg.cc/8k69sX9b/6652.png took 85.8253044840003 seconds to run
7710
7711
Returning non-postimg link
7711
7712

Connecting to https://i.postimg.cc/wv4ZVYw4/518.png ...
Downloading 518.png ...
[                                                  ] 0.89%

Grabbing the full link at https://i.postimg.cc/wv4ZVYw4/518.png took 0.36821096600033343 seconds to run

[==================================================] 100.00%

OCR returns: The Military Watch|A Ukrainian|Air|Force jet aircraft (most likelya|Sukhoi Su-24M)|was destroyed in the|Russian|missile|attack on|Voznesensk Air|Base,|Mykolaiv|Oblast.|It is|not|clear|whether|the|aircraft was in|operational|service or was retired|and used as a|decoy.|.The|photo was|posted on|15 June 2022|but in|alllikelihood|the|event took place|considerably|earlier.|05/7/2022
Running OCR on https://i.postimg.cc/wv4ZVYw4/518.png took 22.88994861900028 seconds to run
7712
7713
Returning non-postimg link
7713
7714
Returning non-postimg link
7714
7715
Grabbing the full link at https://i.postimg.cc/MKMYsd7k/2000-su24-destr-01-03-23.jpg took 0.3703457760002493 seconds to run
7715
7716
Grabbing the full link at https://i.postimg.cc/hGv9yW0C/2004-su24m-destr-23-07-22.jpg took 0.36776367199945525 seconds to run
7716
7717
Grabbing the full link at https://i.postimg.cc/kgnNStRP/2005-su24m-destr-23-07-22.jpg took 0.3604873349995614 seconds to run
7717
7718
Grabbing the full link at https://i.postimg.cc/02R5mNT4/2027-su24-M-destr-09-03-22.jpg took 0.37352699199982453 seconds to run
7718
7719
Grabbing the full link at https://i.postimg.cc/zDRXVhcW/2028-su24-M-destr-01-03-22.jpg took 0.37307531100032065 seconds to run
7719
7720
Grabbing the full link at https://i.postimg.cc/MHMbd83j/2000-su24-destr-30-06-22.jpg took 0.38022444499983976 seconds to run
7720
7721
Returning non-postimg link
7721
7722
Grabbing the full link at https://i.postimg.cc/7hwsGtjF/2000-f16-destr-26-08-24.jpg took 0.36597502600034204 seconds to run
7722
7723
Grabbing the full link at https://i.postimg.cc/j2YB0YtG/2039-F-16-destr-12-04-25.jpg took 0.3692401600001176 seconds to run
7723
7724
Grabbing the full link at https://i.postimg.cc/4xjKXSkL/2031-F-16-fighter-aircraft-destr-16-05-25.jpg took 0.36905688300066686 seconds to run
7724
7725
Grabbing the full link at https://i.postimg.cc/Sxyxx0HW/2037-F-16-destr-29-06-25.jpg took 0.38005775900001026 seconds to run
7725
7726
Grabbing the full link at https://i.postimg.cc/SRrD43W4/2003-Mirage-2000-5-F-destr-22-07-25.jpg took 0.3745292410003458 seconds to run
7726
7727

Connecting to https://i.postimg.cc/mDYQJgsS/64.png ...
Downloading 64.png ...
[                                                  ] 0.35%

Grabbing the full link at https://i.postimg.cc/mDYQJgsS/64.png took 0.39594600800046464 seconds to run

[==================================================] 100.00%

OCR returns: KoMaHyBaHHa FloBirpRHvx Cnn 3Cy/Air Force Command of UA Armed Forces|8m ·θ|…|REGARDING THE L-39 DISASTER|Zhytomyr region.During acombat mission in theskythecrewsof two L-39 naval sino-fighter|We are saddened to announce that on August 25.2023.a terribleplane crashoccurred in|aircraft collided.|All threepilotswereunfortunatykedAnivesiaion i ongng|Among thedeadis afamous pilotof the4Oth Tactical AviationBrigade on positiveJUiCE|Weexpressourcondolencestothefamiliesof the victims.Thisis apainful andirreparable losstoall|of us.|Wealsoask tocarefullyandunderstand thetermsofreleaseofsensitiveinformationinaccordance|with established orocedures and ethical standards|O-See original -Rate this translation|cycnIbHE|HOBNHN|AEPKABHEBIOPO|PO3CnIOYBAHb
Running OCR on https://i.postimg.cc/mDYQJgsS/64.png took 43.13132236099955 seconds to run
7727
7728

Connecting to https://i.postimg.cc/mDYQJgsS/64.png ...
Downloading 64.png ...
[                                                  ] 0.35%

Grabbing the full link at https://i.postimg.cc/mDYQJgsS/64.png took 0.3760101850002684 seconds to run

[==================================================] 100.00%

OCR returns: KoMaHyBaHHa FloBirpRHvx Cnn 3Cy/Air Force Command of UA Armed Forces|8m ·θ|…|REGARDING THE L-39 DISASTER|Zhytomyr region.During acombat mission in theskythecrewsof two L-39 naval sino-fighter|We are saddened to announce that on August 25.2023.a terribleplane crashoccurred in|aircraft collided.|All threepilotswereunfortunatykedAnivesiaion i ongng|Among thedeadis afamous pilotof the4Oth Tactical AviationBrigade on positiveJUiCE|Weexpressourcondolencestothefamiliesof the victims.Thisis apainful andirreparable losstoall|of us.|Wealsoask tocarefullyandunderstand thetermsofreleaseofsensitiveinformationinaccordance|with established orocedures and ethical standards|O-See original -Rate this translation|cycnIbHE|HOBNHN|AEPKABHEBIOPO|PO3CnIOYBAHb
Running OCR on https://i.postimg.cc/mDYQJgsS/64.png took 40.54400630500004 seconds to run
7728
7729

Connecting to https://i.postimg.cc/zf2nkrpX/3325.png ...
Downloading 3325.png ...
[                                                  ] 0.40%

Grabbing the full link at https://i.postimg.cc/zf2nkrpX/3325.png took 0.36580912600038573 seconds to run

[==================================================] 100.00%

OCR returns: CNAMN3ABAHHA – LE BPATOBAHI|Fighter pilot Dmytro Kolomiets was killed in|an air battle while covering his comrades|KTT PAIB – PE3EHT|10h29202211.54 = 658|3ENEHCbKN|08.08.22|H环T|Mymother'swordsDaddiedforUraineforeverdividedmylifeioahappybeforeandan|unbearablerdUaKomie21thedaugrofteHeroofUane|AlitlemoretanmontgoudeofPoycicwasworriedabouttheupomiso|difficultprjctincomputerecorchShysshedidntevenknowowmeaigess|everything would be later...|father.Donot return anythingHeavilyHowtolivefurther?|-Dadgave hislife tosaveothers.HewasaHero.HeisaHero.But1don'twantaHero,Iwart a lving|MajorDmroKolomisisfgerpilotHewasoneofthefirsttomeettheenemyFromevy|morningofFebrury2wemoUawerellseeingpeefulnddidtusp|largeewrhadunteoffiredtrbteitekemtrycly|avertedthefireofenemyaratTisvedthebrtrHewastdownbyanupiplane.|deliberately died.|Relativessaytht thechiceofprofessionforDmitrywasoviouAmoeveryonein tefmilyserved|DmitryhadmanyhobbiesmuickayakstechnologyButairplaneshavealwayscomefistSo,whnthe|3HaronAH oBiτpRHx cn 3CypeeHT YKpaH BonoMp3eneHcK BpyuB OpeH|MyfatherwasmilitarypiltsomychidoodwspearieldndgarrisonsAndmy|godppltoeCvFligtcotdntuioHestuidvel|ganervedinteatrosrivedmanrdwabrveandd|beauehsfrydhowimporiistoberfsoaliniinmrofmoe|3onOTa 3ipKaBiMCbKOBOCny6OBURMRKMMnPNCBOCHO 3BaHHArepO YKpaHM,i4neHaM POH|moreconfidenttthehlmandquicklybeamerelaeHeevedpilointheZhtoyrregion|sarnnx repoiB,a TaKoiHwi nepaBHi Haropon|eesttougeiinritedysTtckrofhedeedewe|mastered the Su-27, MiG-29, L-39.|grandmotherwhoraisedhergrandsonbeforeschoolage,andtherewerelegendsabouther herosm|-DmytrohasyslovedteskyandatonandonnedttitismuulHewasolyyrs|OpneH nepenaHo  piHM Fepon YKpaTHn Maiopa MTpa|others, - adds Tatiana.|old. It's so litte. But for Dmytro,it turned out to be enough to give himself without hesitation to save|KOnOMiURK 3rHyBBMKOHyH 3BaHHR Ha naKy .in|The order was also handed over to the relatives of the Hero of Ukraine|TheHeroisurvivedbysdaugryanndwifeLyudmilwitwhomhelivedfor24yerTe|4ac BMBeneHHR rpynn 3nin Bopokoro pakeTHoroynapy Ha|Major Dmytro Kolomiyets,who died while performing a mission on|theL-39 aircraft.During the withdrawal of the group from an enemy|wifeworksasaneducaor ata localkindergartenShewll beable to explain tovoungUkrainianswha|aeponpoMicMTOaepHeKnToMpcbKoionacτiAMnτpoKonoMicub|true patriotism and heroism is..|BinBonik Ha ceeBoroHb aBiaunpoTMBHMKa.fponycKaoM 6ooy|missile strike at the airfield of the town of Ozerne,Zhytomyr region,|Forouesrandingpersonafcourageand heroism shown in defending chestotesovereigntyondterritoriol|rpyny, BiH 6yB 3uui niTaKoM Bopora.|Dmytro Kolomiets diverted the enemy's aircraft fire. Passing the|inegrityofUinytytoteMtyOhbteDotePdoUraiofFbruy28,2022|combat group, he was shot down by an enemy plane.|Ne78/2022MojorOmytroKolomietswosowordedthetitleofHeroofUkroinewiththeOrderofGold.|BononnMp 3eneHCbKn TaKO BpyuMB 3axNCHMKaM iHwi ePBHi|田27|日
Running OCR on https://i.postimg.cc/zf2nkrpX/3325.png took 89.74933354500081 seconds to run
7729
7730
Grabbing the full link at https://i.postimg.cc/bY4d8STg/2002-L-39-destr-24-02-22.jpg took 0.37359895999998116 seconds to run
7730
7731
Grabbing the full link at https://i.postimg.cc/850QRW50/2003-L-39-destr-24-02-22.jpg took 0.36135684799955925 seconds to run
7731
7732
Grabbing the full link at https://i.postimg.cc/9f6zgX83/2011-L-39-destr-17-03-23.jpg took 0.3702041279993864 seconds to run
7732
7733
Grabbing the full link at https://i.postimg.cc/NjH0vbQm/2012-l39-destr-04-03-22.jpg took 0.37287096500040207 seconds to run
7733
7734
Grabbing the full link at https://i.postimg.cc/PJkGLCCz/2037-unkn-figher-jet-destr-05-03-22.jpg took 0.37575335600013204 seconds to run
7734
7735
Returning non-postimg link
7735
7736
Returning non-postimg link
7736
7737

Connecting to https://i.postimg.cc/rmdB2PLQ/489.png ...
Downloading 489.png ...
[                                                  ] 0.42%

Grabbing the full link at https://i.postimg.cc/rmdB2PLQ/489.png took 0.3691965029993298 seconds to run

[==================================================] 100.00%

OCR returns: 24/02/2022|0|SHOTON REDMI9|AIQUAD CAMERA
Running OCR on https://i.postimg.cc/rmdB2PLQ/489.png took 26.815592406000178 seconds to run
7737
7738
Grabbing the full link at https://i.postimg.cc/52yq9Qjt/2006-An-26-transport-aircraft-destr-06-03-22.jpg took 0.40543604400045297 seconds to run
7738
7739
Grabbing the full link at https://i.postimg.cc/28kZKSd2/331.png took 0.3620556949999809 seconds to run

Connecting to https://i.postimg.cc/28kZKSd2/331.png ...
Downloading 331.png ...
[==================================================] 100.00%

OCR returns: nOCBIAYEHHA|AOBin3HaKN|MiHicTepCTBa|o6opoHn|VkpaTHn|*222Aug:-2lotatosthumouslyadymravetsisIoncombamisionresumabllgtmissioOBOct1.aratovgradpreRcollapseXertoUkraineaterindependnce.aelo|pilotiiitrnioiiilirttultrrcll|out"456"onit.Afterafewweekstrainingwasre-ualifiedandflewasaMi-2pilot.Flewapproximately3hrsinmonthsofwar.NoevidencethatheflewanyothertypesotherthanMi-2.
Running OCR on https://i.postimg.cc/28kZKSd2/331.png took 59.62577705900003 seconds to run
7739
7740
Grabbing the full link at https://i.postimg.cc/DZXfDW54/2000-mi2-destr-31-01-23.jpg took 0.38122443500014924 seconds to run
7740
7741
Grabbing the full link at https://i.postimg.cc/Y2Y1XB50/2000-mi-2-training-helicopter-destr-01-09-24.jpg took 0.3690182330001335 seconds to run
7741
7742

Connecting to https://i.postimg.cc/htNmVbzn/887.png ...
Downloading 887.png ...
[                                                  ] 0.31%

Grabbing the full link at https://i.postimg.cc/htNmVbzn/887.png took 0.37094495499968616 seconds to run

[==================================================] 100.00%

OCR returns: 0|H|23/5/2022|02/3/2022|RT|me/MSGazdiev|t.me/Murd_Gazdiev
Running OCR on https://i.postimg.cc/htNmVbzn/887.png took 32.734753941000235 seconds to run
7742
7743

Connecting to https://i.postimg.cc/htNmVbzn/887.png ...
Downloading 887.png ...
[                                                  ] 0.31%

Grabbing the full link at https://i.postimg.cc/htNmVbzn/887.png took 0.3763344870003493 seconds to run

[==================================================] 100.00%

OCR returns: 0|H|23/5/2022|02/3/2022|RT|me/MSGazdiev|t.me/Murd_Gazdiev
Running OCR on https://i.postimg.cc/htNmVbzn/887.png took 33.025489122999716 seconds to run
7743
7744

Connecting to https://i.postimg.cc/htNmVbzn/887.png ...
Downloading 887.png ...
[                                                  ] 0.31%

Grabbing the full link at https://i.postimg.cc/htNmVbzn/887.png took 0.3695179410005949 seconds to run

[==================================================] 100.00%

OCR returns: 0|H|23/5/2022|02/3/2022|RT|me/MSGazdiev|t.me/Murd_Gazdiev
Running OCR on https://i.postimg.cc/htNmVbzn/887.png took 33.053019676000076 seconds to run
7744
7745

Connecting to https://i.postimg.cc/nhHc6k3z/34.png ...
Downloading 34.png ...
[                                                  ] 0.41%

Grabbing the full link at https://i.postimg.cc/nhHc6k3z/34.png took 0.37138521799988666 seconds to run

[==================================================] 100.00%

OCR returns: BoeHHb OcBenOMnTenb|BoeHHI OcBenOMNTenb|d BoopyeHHbe cunbtYxpanHbl npn.|U|Ouepena nopepkeHHa|P0AA0B|orenbHo 6purab apmecko|aBnaunn|BepToneT bIn yHMuTOeH paKeTo|28.02.2022 r.B6nn3n nrr. MaKapOB|5vuaHCkoro paoHaKneBcKO|o6nacrn.|KunaK nOrn B nOnHoM CoCTaBE:|- nonKOBHnK TpuropbeB AneKcaHAp|AnekcaHapoBny, 1983 r.p.;|-KannTaHHecrepVKMnTpn|HuKonaeBny, 1997 r.p.;|-CTaPwN neTeHaHT HaTIOK|Bacnnn AHapeeBn4, 1999 r.p.| 209,8K 17:52|63
Running OCR on https://i.postimg.cc/nhHc6k3z/34.png took 26.164119355000366 seconds to run
7745
7746

Connecting to https://i.postimg.cc/FKpXBSV7/79.png ...
Downloading 79.png ...
[                                                  ] 0.34%

Grabbing the full link at https://i.postimg.cc/FKpXBSV7/79.png took 0.3656638450001992 seconds to run

[==================================================] 100.00%

OCR returns: 31/3/2022|:H|:H|3A|6ADY|BEPY!|:H
Running OCR on https://i.postimg.cc/FKpXBSV7/79.png took 22.22269568199954 seconds to run
7746
7747

Connecting to https://i.postimg.cc/wBW5vCQw/3d6.png ...
Downloading 3d6.png ...
[                                                  ] 1.89%

Grabbing the full link at https://i.postimg.cc/wBW5vCQw/3d6.png took 0.40189321799971367 seconds to run

[==================================================] 100.00%

OCR returns: N|ew details are coming to light about incredibly daring resupply missions that were|flown by Ukrainian helicopter crews right into the heart of the fighting in the|THE*WARZONE|occupied seaport city of Mariupol. Flying two at a time and once four at a time, Ukrainian|Mi-8 Hip helicopter crews braved dense Russian air defense and enemv aircraft|Inside Ukraine's Daring Helicopter|concentrated in and around Mariupol to deliver desperately needed supplies and fresh|troops to the defenders of the besieged Azovstal steel plant.|Missions Into Russian-Occupied|Ofthe 16 total helicopters involved,two were destroyed, Ukraine Brig. Gen. Kyrylo Budanov,|Mariupol|the head of Defense Intelligence of Ukraine, told The War Zone in an exclusive series of|interviews. Another helicopter was destroyed coming to the rescue of one of the downed|Hips.|With Ukrainian troops besieged in a massive steel plant and under constant fire from|Russian forces, helicopter crews sprung into action.|Believed to have occured in late March 2022|BY  HOWARD ALTMAN  MAY 25,2022 6:54 PM|THE WAR ZONE
Running OCR on https://i.postimg.cc/wBW5vCQw/3d6.png took 38.08256722400074 seconds to run
7747
7748

Connecting to https://i.postimg.cc/wBW5vCQw/3d6.png ...
Downloading 3d6.png ...
[                                                  ] 1.89%

Grabbing the full link at https://i.postimg.cc/wBW5vCQw/3d6.png took 0.35974022099981084 seconds to run

[==================================================] 100.00%

OCR returns: N|ew details are coming to light about incredibly daring resupply missions that were|flown by Ukrainian helicopter crews right into the heart of the fighting in the|THE*WARZONE|occupied seaport city of Mariupol. Flying two at a time and once four at a time, Ukrainian|Mi-8 Hip helicopter crews braved dense Russian air defense and enemv aircraft|Inside Ukraine's Daring Helicopter|concentrated in and around Mariupol to deliver desperately needed supplies and fresh|troops to the defenders of the besieged Azovstal steel plant.|Missions Into Russian-Occupied|Ofthe 16 total helicopters involved,two were destroyed, Ukraine Brig. Gen. Kyrylo Budanov,|Mariupol|the head of Defense Intelligence of Ukraine, told The War Zone in an exclusive series of|interviews. Another helicopter was destroyed coming to the rescue of one of the downed|Hips.|With Ukrainian troops besieged in a massive steel plant and under constant fire from|Russian forces, helicopter crews sprung into action.|Believed to have occured in late March 2022|BY  HOWARD ALTMAN  MAY 25,2022 6:54 PM|THE WAR ZONE
Running OCR on https://i.postimg.cc/wBW5vCQw/3d6.png took 37.70601088999956 seconds to run
7748
7749
Returning non-postimg link
7749
7750
Returning non-postimg link
7750
Saved at index 7750
7751
Grabbing the full link at https://i.postimg.cc/136TTS48/1887.png took 0.37309299600019585 seconds to run

Connecting to https://i.postimg.cc/136TTS48/1887.png ...
Downloading 1887.png ...
[==================================================] 100.00%

OCR returns: nkOn|YKP|IHKOTIITd|Before April 2022
Running OCR on https://i.postimg.cc/136TTS48/1887.png took 18.73506750500019 seconds to run
7751
7752
Grabbing the full link at https://i.postimg.cc/y8GgrPfR/3270.png took 0.3658638589995462 seconds to run

Connecting to https://i.postimg.cc/y8GgrPfR/3270.png ...
Downloading 3270.png ...
[==================================================] 100.00%

OCR returns: 06/3/2022|ΦEPMEPN|rOTyI0YN|NOnE|AO|NOCIBHOrO|CE30Hy,|3HANWNN|PEYI|CEPrIA|BOHAPEHKA:|IMEHHNN|KETOH,|KΛI04I|BIA|KBAPTNPN|TA|HIK|一|NOAPYHOK|BATbKA.|Rg|15|MICALI|BOHN|WYKANN|PIAHNXI|BPEWTI|BJITKy|2023|POKy|4E|BAAnOCa|3ABAAKN|COLMEPEKAM.
Running OCR on https://i.postimg.cc/y8GgrPfR/3270.png took 42.54793490999964 seconds to run
7752
7753
Returning non-postimg link
7753
7754

Connecting to https://i.postimg.cc/GhZDhNht/4665.png ...
Downloading 4665.png ...
[                                                  ] 0.85%

Grabbing the full link at https://i.postimg.cc/GhZDhNht/4665.png took 0.38168986799973936 seconds to run

[==================================================] 100.00%

OCR returns: In Poltava, they paid their last respects to helicopter|loading..|pilot Serhiy Mehedi and signalman Oleksandr|Nekhayev|Victor Dyachenko18:0218.06.2022714|WAR|KOP.NET.UAPMIRNFORM|Today in Poltava, near the Assumption Cathedral, they said goodbye to two|Ukrainian servicemen who died heroically in the fight against the Rashists.|Armiyalnform tells about it.|Relatives, relatives, residents of the city and the military spent the last journey|of helicopter pilot Serhiy Mehed and signalman Oleksandr Nekhayev.|Archbishop Fedir of Poltava and Kremenchug and clergy of the Diocese of|Poltava sent a memorial service for the dead.|The 40-year-old navigator of the unit, the pilot of the helicopter unit, Captain|Serhiy Meheda, died on June 16 as a result of the shelling and fall of the|Mi-8MT helicopter in the Kramatorsk region. A resident of Kremenchug|repeatedly made combat sorties in hot areas, where he delivered ammunition|to our soldiers under fire and evacuated the wounded to medical facilities on|the way back.In the last flight,Serhiy Meheda remained forever in the sky…|It should be added that in March the pilot was awarded the Order of "Bohdan|Khmelnytskyi" Il degree for personal courage and selfless actions shown in|the defense of state sovereignty and territorial integrity of Ukraine, loyalty to|the Military Oath.
Running OCR on https://i.postimg.cc/GhZDhNht/4665.png took 50.61885284099935 seconds to run
7754
7755
Grabbing the full link at https://i.postimg.cc/Mp1PKvX4/2107-mi8-destr-13-07-22.jpg took 0.3710679630003142 seconds to run
7755
7756
Returning non-postimg link
7756
7757
Grabbing the full link at https://i.postimg.cc/8cxzWk7Z/65g2.png took 0.3714428870007396 seconds to run

Connecting to https://i.postimg.cc/8cxzWk7Z/65g2.png ...
Downloading 65g2.png ...
[==================================================] 100.00%

OCR returns: Mi-8|MapuHa paHCKaa|16 hours ago|B ue nye Bako noBipnTn..ue Tak ongye.ane..|11.11.2022|BHH B|3arnHyBlepo,ninonKoBHK aBiaui oBiτpaHx Cnn|36poHNx Cnn YKpaHN,bOTNK.
Running OCR on https://i.postimg.cc/8cxzWk7Z/65g2.png took 16.703102460999617 seconds to run
7757
7758
Grabbing the full link at https://i.postimg.cc/3Jc5LSKG/2140-Mi-8-transport-helicopter-destr-06-03-22.jpg took 0.3886256770001637 seconds to run
7758
7759
Returning non-postimg link
7759
7760
Grabbing the full link at https://i.postimg.cc/RZ2n6L74/2004-mi8-destr.jpg took 0.36865319900061877 seconds to run

Connecting to https://i.postimg.cc/RZ2n6L74/2004-mi8-destr.jpg ...
Downloading 2004-mi8-destr.jpg ...
[==================================================] 100.00%

OCR returns: /t.me/xykon|t.me/Xykonst|/tme/xykonst|11.12.2022
Running OCR on https://i.postimg.cc/RZ2n6L74/2004-mi8-destr.jpg took 13.711915311999292 seconds to run
7760
7761
Returning non-postimg link
7761
7762
Grabbing the full link at https://i.postimg.cc/0yXDmyzf/2006-mi-8-helicopter-destr-24-12-22.jpg took 0.37390969000080077 seconds to run
7762
7763
Grabbing the full link at https://i.postimg.cc/Njw3ts7f/2011-mi8-destr-01-08-23.jpg took 0.3726840130002529 seconds to run
7763
7764
Grabbing the full link at https://i.postimg.cc/bvB5cyG3/54g5.png took 0.3662392690002889 seconds to run

Connecting to https://i.postimg.cc/bvB5cyG3/54g5.png ...
Downloading 54g5.png ...
[==================================================] 100.00%

OCR returns: HaBiHi 3arHynn wecTepo ninoTiB,ki cnynn y nonTaBCbki bpnrani|apmicbkoi aBiaui|Banepia Pwt6antxa|30 cepnH, 17:56 AA|①OTO:18o6paaiM.1.CiKopcboro.2023|φoro:18 OpAA iM.1. Cixopooro|29 cepnHg Ha axMyTcbKoMy HanpaMKy 3arwHynn wecTepo ninoTiB i318-|OnAugust29sixpilotsfromthe18thseparate armyaviationbrigade|named after Igor Sikorskywere killed in the Bakhmutregion. It|okpeMoi 6pnraan apMicbkoi aBiai imeHi Irop Cikopcbkoro.CTanoca e|BHHREOAOB|The spokesperson of the brigadeYevhen Rakitainformed Suspino|about this.|Npo ye CycninbHoMy noBigoMB peyHk 6pnran εereH Paia.|Thefallen had officer ranks.One of themis from PoltavaOblast,the|rest are from other regions of Ukraine,the spokesperson added|Nonerni ManiepbKi3BaHHA.OH 3 HX–pogom i3onaBuH,ewTa|When they say goodbye to the pilots|i3 iHwnx perioHiB YKpaH, ρoaB peHK.|They have to say goodbve in Poltava.Amemorial service will be held|on September1 at10:00 a.m.near the Assumption Cathedral|eee|Pilots from the Poltava region will be buried at their place of residence|others will be taken to the regionswhere theycame from|13 HnMN MaoTb nonpowaTncg yOaεi.aHaxnAy BnawTVιtk1 BeecH o10:00|Currently,the namesand circumstances of the deaths are notbeing|6ing CBAro-ycneHcbKoro co6opy.|disclosed for security reasons,says Yevhen Rakita.|Ninora i3 onraBcbKoionacri noxoBaloTb 3a MicueM npoMBaHH,iHwX|nOBe3yTbyτi onacTi,3BiKinb BOH poAOM.|HapasiieH Ta ocaBnH 3arneni He po3ronowyoTb yuinax 6enekn,Kae|EBreH PakiTa.
Running OCR on https://i.postimg.cc/bvB5cyG3/54g5.png took 48.805715082999996 seconds to run
7764
7765

Connecting to https://i.postimg.cc/bvB5cyG3/54g5.png ...
Downloading 54g5.png ...
[                                                  ] 1.19%

Grabbing the full link at https://i.postimg.cc/bvB5cyG3/54g5.png took 0.3644905569999537 seconds to run

[==================================================] 100.00%

OCR returns: HaBiHi 3arHynn wecTepo ninoTiB,ki cnynn y nonTaBCbki bpnrani|apmicbkoi aBiaui|Banepia Pwt6antxa|30 cepnH, 17:56 AA|①OTO:18o6paaiM.1.CiKopcboro.2023|φoro:18 OpAA iM.1. Cixopooro|29 cepnHg Ha axMyTcbKoMy HanpaMKy 3arwHynn wecTepo ninoTiB i318-|OnAugust29sixpilotsfromthe18thseparate armyaviationbrigade|named after Igor Sikorskywere killed in the Bakhmutregion. It|okpeMoi 6pnraan apMicbkoi aBiai imeHi Irop Cikopcbkoro.CTanoca e|BHHREOAOB|The spokesperson of the brigadeYevhen Rakitainformed Suspino|about this.|Npo ye CycninbHoMy noBigoMB peyHk 6pnran εereH Paia.|Thefallen had officer ranks.One of themis from PoltavaOblast,the|rest are from other regions of Ukraine,the spokesperson added|Nonerni ManiepbKi3BaHHA.OH 3 HX–pogom i3onaBuH,ewTa|When they say goodbye to the pilots|i3 iHwnx perioHiB YKpaH, ρoaB peHK.|They have to say goodbve in Poltava.Amemorial service will be held|on September1 at10:00 a.m.near the Assumption Cathedral|eee|Pilots from the Poltava region will be buried at their place of residence|others will be taken to the regionswhere theycame from|13 HnMN MaoTb nonpowaTncg yOaεi.aHaxnAy BnawTVιtk1 BeecH o10:00|Currently,the namesand circumstances of the deaths are notbeing|6ing CBAro-ycneHcbKoro co6opy.|disclosed for security reasons,says Yevhen Rakita.|Ninora i3 onraBcbKoionacri noxoBaloTb 3a MicueM npoMBaHH,iHwX|nOBe3yTbyτi onacTi,3BiKinb BOH poAOM.|HapasiieH Ta ocaBnH 3arneni He po3ronowyoTb yuinax 6enekn,Kae|EBreH PakiTa.
Running OCR on https://i.postimg.cc/bvB5cyG3/54g5.png took 45.156429572999514 seconds to run
7765
7766
Grabbing the full link at https://i.postimg.cc/Y0sgFsyW/553.png took 0.36933763199976966 seconds to run

Connecting to https://i.postimg.cc/Y0sgFsyW/553.png ...
Downloading 553.png ...
[==================================================] 100.00%

OCR returns: 2022 or early|y2023
Running OCR on https://i.postimg.cc/Y0sgFsyW/553.png took 8.118653477000407 seconds to run
7766
7767
Grabbing the full link at https://i.postimg.cc/tgVZ0xfM/347.png took 0.374206673000117 seconds to run

Connecting to https://i.postimg.cc/tgVZ0xfM/347.png ...
Downloading 347.png ...
[==================================================] 100.00%

OCR returns: 06/3/2022|6BEPE3H92022POKy|HA|MNKOAiBWNHINIA|YAC|NOBITPAHORO|BOIO|BOPOI|BPA3NB|PAKETAMN|BA|YKPAIHCbKNX|TENIKONTEPN.|BHACMIOK|4boro|3ArNHyNO|WECTEPO|BINCbKOBNX|CEPE|XNH|BYB|CEPrIN|BOHAPEHKO.
Running OCR on https://i.postimg.cc/tgVZ0xfM/347.png took 26.581492650000655 seconds to run
7767
7768
Grabbing the full link at https://i.postimg.cc/mrkGDsFv/2006-mi8-destr-15-03-22.jpg took 0.37724284599971725 seconds to run
7768
7769
Returning non-postimg link
7769
7770
Grabbing the full link at https://i.postimg.cc/wjPsNKPR/2010-Mi-8-destr-31-12-22.jpg took 0.37508198200066545 seconds to run
7770
7771
Returning non-postimg link
7771
7772
Returning non-postimg link
7772
7773
Grabbing the full link at https://i.postimg.cc/261GVDRF/2012-mi8msb-v-dam-19-07-24.jpg took 0.3732031339995956 seconds to run
7773
7774
Grabbing the full link at https://i.postimg.cc/sDhzVSMY/1300-mi14ps-destr-07-05-22.jpg took 0.37601090099997236 seconds to run
7774
7775
Grabbing the full link at https://i.postimg.cc/JhWL5jTW/2042-mi8-destr-09-06-23.jpg took 0.3679747469996073 seconds to run
7775
7776
Grabbing the full link at https://i.postimg.cc/WzK7ZmcF/2015-mi17-destr-13-02-24.png took 0.36207819700030086 seconds to run
7776
7777
Returning non-postimg link
7777
7778
Grabbing the full link at https://i.postimg.cc/13B6dC51/2015-mi-8-17-destr-09-07-24.jpg took 0.3666994440000053 seconds to run
7778
7779
Grabbing the full link at https://i.postimg.cc/3xT0zpGZ/54.png took 0.36651702000017394 seconds to run

Connecting to https://i.postimg.cc/3xT0zpGZ/54.png ...
Downloading 54.png ...
[==================================================] 100.00%

OCR returns: 22/5/2022
Running OCR on https://i.postimg.cc/3xT0zpGZ/54.png took 26.07748971500041 seconds to run
7779
7780
Grabbing the full link at https://i.postimg.cc/s2h82Dr3/332.png took 0.37213081500067346 seconds to run

Connecting to https://i.postimg.cc/s2h82Dr3/332.png ...
Downloading 332.png ...
[==================================================] 100.00%

OCR returns: no later than 09/08/2022|repoiHe BMnpaloTb|CnaBarykpaiHi|TikTok|TiKTok|TikTok|@fop_front|@fop_fropt|@olexandr_uikrop
Running OCR on https://i.postimg.cc/s2h82Dr3/332.png took 22.412329480000153 seconds to run
7780
7781
Grabbing the full link at https://i.postimg.cc/N0fx6ym4/2s.png took 0.377811928000483 seconds to run

Connecting to https://i.postimg.cc/N0fx6ym4/2s.png ...
Downloading 2s.png ...
[==================================================] 100.00%

OCR returns: UkrArmyBlog|@UkrArmyBlog|3 rnK CyMom a CKpOTι nOBiOεo, o 8|6epe3Ha 2022p, np BKOHaHHi nObOTHoro 6oOBOro|aBH 3 Bi poi arpii pcioi|Φeepaui, 3arHyB ekina BepoboTy Mi-24 16-|ereeeee|niAnOKOBHNK MAPNHK O.M;|kaniTaH|BE33yb I.P.|Translated from Ukrainian by|Google|We are deeply|saddened to announce that on March 8,|2022,|the|crew|of|theMi-24helicopterofthe16th|separate|brigade|"Brody" consisting of:|lieutenant colonel MARINYAK|OM;|Captain|BEZZUB|IR|6E33Y5|5:39 pm · 11 Mar 2022· Twitter for Android
Running OCR on https://i.postimg.cc/N0fx6ym4/2s.png took 28.837603334999585 seconds to run
7781
7782
Grabbing the full link at https://i.postimg.cc/SN6k3Jpm/2020-mi24-destr-20-10-23.jpg took 0.3646500479999304 seconds to run
7782
7783
Grabbing the full link at https://i.postimg.cc/6Qwz0LH6/2003-mi24-destr-17-03-24.jpg took 0.366117674000634 seconds to run
7783
7784
Grabbing the full link at https://i.postimg.cc/brSX3JSN/2010-Mi-24-P-attack-helicopter-destr-23-04-22.jpg took 0.362905528999363 seconds to run
7784
7785
Returning non-postimg link
7785
7786
Returning non-postimg link
7786
7787
Grabbing the full link at https://i.postimg.cc/9F0R4khC/2000-mi-24-dam-17-05-23.jpg took 0.3647296899998764 seconds to run
7787
7788
Grabbing the full link at https://i.postimg.cc/PrRgTTq3/2000-mi24-dam-22-10-24.jpg took 0.36743698000009317 seconds to run
7788
7789
Returning non-postimg link
7789
7790
Returning non-postimg link
7790
7791
Grabbing the full link at https://i.postimg.cc/0yTqfP7n/314.png took 0.36875338300069416 seconds to run

Connecting to https://i.postimg.cc/0yTqfP7n/314.png ...
Downloading 314.png ...
[==================================================] 100.00%

OCR returns: 17/3/2022
Running OCR on https://i.postimg.cc/0yTqfP7n/314.png took 14.950509283000429 seconds to run
7791
7792

Connecting to https://i.postimg.cc/0rR38Jw1/241.png ...
Downloading 241.png ...
[                                                  ] 0.62%

Grabbing the full link at https://i.postimg.cc/0rR38Jw1/241.png took 0.36655317199983983 seconds to run

[==================================================] 100.00%

OCR returns: 30/3/2022|t.me/faceofwar
Running OCR on https://i.postimg.cc/0rR38Jw1/241.png took 8.573883680000108 seconds to run
7792
7793
Returning non-postimg link
7793
7794
Grabbing the full link at https://i.postimg.cc/PqzGsG3M/329.png took 0.36403005400006805 seconds to run

Connecting to https://i.postimg.cc/PqzGsG3M/329.png ...
Downloading 329.png ...
[==================================================] 100.00%

OCR returns: S49T|BAYRAKTAR|100|DIOM ONYN ON|25/4/2022
Running OCR on https://i.postimg.cc/PqzGsG3M/329.png took 24.118688443999417 seconds to run
7794
7795
Grabbing the full link at https://i.postimg.cc/kX0F9FCc/b1.png took 0.36599751399990055 seconds to run

Connecting to https://i.postimg.cc/kX0F9FCc/b1.png ...
Downloading b1.png ...
[==================================================] 100.00%

OCR returns: 27/4/2022
Running OCR on https://i.postimg.cc/kX0F9FCc/b1.png took 22.275881988000037 seconds to run
7795
7796
Grabbing the full link at https://i.postimg.cc/rFQWg4Vr/6522.png took 0.37202536099994177 seconds to run

Connecting to https://i.postimg.cc/rFQWg4Vr/6522.png ...
Downloading 6522.png ...
[==================================================] 100.00%

OCR returns: R|RT|RT|27/4/2022
Running OCR on https://i.postimg.cc/rFQWg4Vr/6522.png took 26.716750929999762 seconds to run
7796
7797

Connecting to https://i.postimg.cc/nh1W0Rc3/4.jpg ...
Downloading 4.jpg ...
[                                                  ] 1.69%

Grabbing the full link at https://i.postimg.cc/nh1W0Rc3/4.jpg took 0.3734082880000642 seconds to run

[==================================================] 100.00%

OCR returns: T12|中|01.05.2022|BAYRAKTAR TB2
Running OCR on https://i.postimg.cc/nh1W0Rc3/4.jpg took 16.309682859999157 seconds to run
7797
7798

Connecting to https://i.postimg.cc/nrWysFk5/43118.png ...
Downloading 43118.png ...
[                                                  ] 0.59%

Grabbing the full link at https://i.postimg.cc/nrWysFk5/43118.png took 0.45340195700009644 seconds to run

[==================================================] 100.00%

OCR returns: 23/5/2022|NS|ayraktar|gǎsita|la|Sulina|traordinar,|sustinut|de|Orchestra|Operei|Na
Running OCR on https://i.postimg.cc/nrWysFk5/43118.png took 16.20778367100047 seconds to run
7798
7799
Returning non-postimg link
7799
7800
Grabbing the full link at https://i.postimg.cc/XNKtRCXz/2000.jpg took 0.4045077750006385 seconds to run

Connecting to https://i.postimg.cc/XNKtRCXz/2000.jpg ...
Downloading 2000.jpg ...
[==================================================] 100.00%

OCR returns: 23.07.2022|ANNATAA|EEEEA|1662 N0 1|BANs|A|BNs|ZININIST|ianr|AAE|KAFILE NO: 005-|SAGNEAN|SOAENOT|3000|1311215|NLAEEE|EAAE|18|AAAE
Running OCR on https://i.postimg.cc/XNKtRCXz/2000.jpg took 24.28067001799991 seconds to run
7800
7801
Returning non-postimg link
7801
7802
Grabbing the full link at https://i.postimg.cc/BnChYS2q/2003.jpg took 0.4393048380006803 seconds to run

Connecting to https://i.postimg.cc/BnChYS2q/2003.jpg ...
Downloading 2003.jpg ...
[==================================================] 100.00%

OCR returns: 26.07.2022|PATRIOT|U139|BAYRAKTAR TB2|BoeHHbIN OcBeoMNTenb|t.me/milinfolive
Running OCR on https://i.postimg.cc/BnChYS2q/2003.jpg took 15.93384743200022 seconds to run
7802
7803
Returning non-postimg link
7803
7804
Returning non-postimg link
7804
7805
Grabbing the full link at https://i.postimg.cc/Rh9hRy7t/2004-tb2-destr-22-01-23.jpg took 0.4408269819996349 seconds to run
7805
7806
Grabbing the full link at https://i.postimg.cc/mkWZGb6X/2003-TB2-destr-18-02-23.jpg took 0.3793881679994229 seconds to run
7806
7807
Returning non-postimg link
7807
7808
Returning non-postimg link
7808
7809
Grabbing the full link at https://i.postimg.cc/PxnVJZvn/2042-Bayraktar-TB2-UCAV-destr-09-05-23.jpg took 0.39270136899995123 seconds to run
7809
7810
Grabbing the full link at https://i.postimg.cc/SQVxQ1gY/2000-4x-tb2-ucav-and-2-ground-stations-destr-24-02-22.png took 0.3726591679997 seconds to run
7810
7811
Grabbing the full link at https://i.postimg.cc/SQVxQ1gY/2000-4x-tb2-ucav-and-2-ground-stations-destr-24-02-22.png took 0.38249687799998355 seconds to run
7811
7812
Grabbing the full link at https://i.postimg.cc/SQVxQ1gY/2000-4x-tb2-ucav-and-2-ground-stations-destr-24-02-22.png took 0.40446808299930126 seconds to run
7812
7813
Grabbing the full link at https://i.postimg.cc/SQVxQ1gY/2000-4x-tb2-ucav-and-2-ground-stations-destr-24-02-22.png took 0.38316857700010587 seconds to run
7813
7814
Returning non-postimg link
7814
7815
Grabbing the full link at https://i.postimg.cc/mgQSydGF/2008-Bayraktar-TB2-UCAV-destr-20-03-22.jpg took 0.3765952659996401 seconds to run
7815
7816
Grabbing the full link at https://i.postimg.cc/tTdXQtgV/2031-Bayraktar-TB2-UCAV-destr-08-03-22.jpg took 0.4511118290001832 seconds to run
7816
7817

Connecting to https://i.postimg.cc/TYfbDmSq/2.png ...
Downloading 2.png ...
[                                                  ] 0.20%

Grabbing the full link at https://i.postimg.cc/TYfbDmSq/2.png took 0.37805262500023673 seconds to run

[==================================================] 100.00%

OCR returns: 16/6/2023
Running OCR on https://i.postimg.cc/TYfbDmSq/2.png took 22.321665745000246 seconds to run
7817
7818
Grabbing the full link at https://i.postimg.cc/BbYynqNn/2017-Punisher-attack-UAV-destr-10-11-23.jpg took 0.384076203999939 seconds to run
7818
7819
Grabbing the full link at https://i.postimg.cc/VNDcKLCh/2009-Punisher-attack-UAV-capt-25-02-24.jpg took 0.3710284019998653 seconds to run
7819
7820
Grabbing the full link at https://i.postimg.cc/hGnpzJdF/4f0.png took 0.35866114100008417 seconds to run

Connecting to https://i.postimg.cc/hGnpzJdF/4f0.png ...
Downloading 4f0.png ...
[==================================================] 100.00%

OCR returns: 20/3/2022|11 views|0:03/ 1:13|2
Running OCR on https://i.postimg.cc/hGnpzJdF/4f0.png took 27.694697209999504 seconds to run
7820
7821
Grabbing the full link at https://i.postimg.cc/KvBkj4zY/554.png took 0.3751328789994659 seconds to run

Connecting to https://i.postimg.cc/KvBkj4zY/554.png ...
Downloading 554.png ...
[==================================================] 100.00%

OCR returns: RVvoenkor|RVvoenkor|32S08O|320|29/3/2022|RusVesna Su|RusVesnaSu
Running OCR on https://i.postimg.cc/KvBkj4zY/554.png took 17.71405902799961 seconds to run
7821
7822
Grabbing the full link at https://i.postimg.cc/c4gpDpFx/488.png took 0.3718563800002812 seconds to run

Connecting to https://i.postimg.cc/c4gpDpFx/488.png ...
Downloading 488.png ...
[==================================================] 100.00%

OCR returns: SS0|17/5/2022|REDMINOTE7|AIDUAL CAMERA
Running OCR on https://i.postimg.cc/c4gpDpFx/488.png took 14.389397435999854 seconds to run
7822
7823
Returning non-postimg link
7823
7824
Returning non-postimg link
7824
7825
Grabbing the full link at https://i.postimg.cc/sX2HnM4D/2022-A1-SM-Fury-destr-14-05-22.jpg took 0.4142894050000905 seconds to run
7825
7826
Grabbing the full link at https://i.postimg.cc/MHMPSgLC/2023-A1-SM-Fury-reconnaissance-UAV-destr-13-05-22.jpg took 0.39793960099996184 seconds to run
7826
7827
Grabbing the full link at https://i.postimg.cc/nrydc0bC/2024-A1-SM-Fury-reconnaissance-UAV-destr-13-04-22.jpg took 0.3960528150000755 seconds to run
7827
7828
Grabbing the full link at https://i.postimg.cc/ncnddN4g/2004-A1-SM-Fury-UAV-destr-18-02-23.jpg took 0.3721215099994879 seconds to run
7828
7829
Grabbing the full link at https://i.postimg.cc/Gtv4qMm8/2007-A1-SM-Fury-UAV-destr-08-07-22.jpg took 0.3664342359998045 seconds to run
7829
7830
Grabbing the full link at https://i.postimg.cc/y821ZBtc/2003-fury-uav-destr-06-03-23.jpg took 0.3729822490004153 seconds to run
7830
7831
Grabbing the full link at https://i.postimg.cc/bN4DFKJL/2008-fury-uav-destr-21-04-23.jpg took 0.37359315999947285 seconds to run
7831
7832
Grabbing the full link at https://i.postimg.cc/3wST3MrV/2000-A1-SM-Fury-destr-06-05-23.jpg took 0.37722814900007506 seconds to run
7832
7833
Grabbing the full link at https://i.postimg.cc/mkTwKZJL/2003-A1-SM-Fury-reconnaissance-UAV-destr-29-04-23.jpg took 0.3719869389997257 seconds to run
7833
7834
Grabbing the full link at https://i.postimg.cc/j5kTBZk4/2041-A1-SM-Fury-reconnaissance-UAV-destr-11-05-23.jpg took 0.3713660389994402 seconds to run
7834
7835
Grabbing the full link at https://i.postimg.cc/cHp9FQ2y/2000-A1-SM-destr-27-05-23.jpg took 0.35951411000041844 seconds to run
7835
7836
Grabbing the full link at https://i.postimg.cc/02DQ48V7/2036-A1-SM-UAV-destr-01-06-23.jpg took 0.39583506000053603 seconds to run
7836
7837
Grabbing the full link at https://i.postimg.cc/BQz872W2/2005-A1-SM-Fury-destr-30-06-23.jpg took 0.37114504700002726 seconds to run
7837
7838
Grabbing the full link at https://i.postimg.cc/fbrw409W/2009-A1-SM-Fury-reconnaissance-UAV-destr-12-08-23.jpg took 0.36458055000002787 seconds to run
7838
7839
Grabbing the full link at https://i.postimg.cc/VLtXXCd7/2002-A1-SM-Fury-reconnaissance-UAV-destr-29-07-23.jpg took 0.36699976099953346 seconds to run
7839
7840
Grabbing the full link at https://i.postimg.cc/4d6XG4Rg/2002-A1-SM-Furia-destr-22-08-23.jpg took 0.36528897899916046 seconds to run
7840
7841
Grabbing the full link at https://i.postimg.cc/9M3s9QTs/2005-A1-SM-Furia-destr-20-08-23.jpg took 0.36454992499966465 seconds to run
7841
7842
Grabbing the full link at https://i.postimg.cc/7PcV58MS/332d.png took 0.36550328900011664 seconds to run

Connecting to https://i.postimg.cc/7PcV58MS/332d.png ...
Downloading 332d.png ...
[==================================================] 100.00%

OCR returns: @HersonEnot|26/8/2023
Running OCR on https://i.postimg.cc/7PcV58MS/332d.png took 14.152845401999912 seconds to run
7842
7843
Grabbing the full link at https://i.postimg.cc/6q2R2wg0/430.png took 0.42770610900061 seconds to run

Connecting to https://i.postimg.cc/6q2R2wg0/430.png ...
Downloading 430.png ...
[==================================================] 100.00%

OCR returns: A|38E30A|RF30A|3日E3日|☆|☆|☆|☆|@ZVEZDANEWS|28/8/2023|☆|☆|@ZVEZDANEWS|☆|☆|A|国|☆|A|☆|☆|文|38E30A|3BE3DA|☆|3BE3AA|3BE3AA|A|☆|38E30A|A|A|☆|☆|A|☆|☆|3日|☆|38E30A|☆|国|☆☆
Running OCR on https://i.postimg.cc/6q2R2wg0/430.png took 25.711710777000008 seconds to run
7843
7844
Grabbing the full link at https://i.postimg.cc/GppV8C2d/438.png took 0.368346814000688 seconds to run

Connecting to https://i.postimg.cc/GppV8C2d/438.png ...
Downloading 438.png ...
[==================================================] 100.00%

OCR returns: 00012535|t.me/razved dozor|me/razvendozor-tme/razvedozore|ael|dozO|11/9/2023
Running OCR on https://i.postimg.cc/GppV8C2d/438.png took 54.45198859800075 seconds to run
7844
7845
Grabbing the full link at https://i.postimg.cc/PxN0hFhw/2001-A1-SM-Fury-destr-06-09-23.jpg took 0.3710632960001021 seconds to run
7845
7846
Grabbing the full link at https://i.postimg.cc/SRM5Y2nQ/2002-fury-uav-destr-19-09-23.jpg took 0.36463490899950557 seconds to run
7846
7847
Grabbing the full link at https://i.postimg.cc/ZK62TNkV/2011-fury-uav-destr-28-09-23.jpg took 0.3625489109999762 seconds to run
7847
7848
Grabbing the full link at https://i.postimg.cc/7PGjWcKv/2020-fury-uav-destr-12-03-23.jpg took 0.37120052600039344 seconds to run
7848
7849
Grabbing the full link at https://i.postimg.cc/PxW1VmVS/2009-fury-uav-destr-13-10-23.jpg took 0.3748488389992417 seconds to run
7849
7850
Grabbing the full link at https://i.postimg.cc/rwBpBLfc/2014-fury-uav-destr-30-08-23.jpg took 0.42112249999991036 seconds to run
7850
7851
Grabbing the full link at https://i.postimg.cc/ZRfXhBC8/2007-FURY-uav-destr-19-12-23.jpg took 0.36263964800036774 seconds to run
7851
7852
Grabbing the full link at https://i.postimg.cc/KY4TcBWf/2002-fury-uav-destr-14-12-23.jpg took 0.36553258599997207 seconds to run
7852
7853
Grabbing the full link at https://i.postimg.cc/Zq0dHgHz/2003-fury-uav-destr-06-06-23.jpg took 0.3667351920003057 seconds to run
7853
7854
Grabbing the full link at https://i.postimg.cc/W3m5B61y/2009-fury-uav-destr-30-11-22.jpg took 0.3703089529999488 seconds to run
7854
7855
Grabbing the full link at https://i.postimg.cc/fb0x7xRC/1020-fury-uav-25-11-23.jpg took 0.37010018700038927 seconds to run
7855
7856
Grabbing the full link at https://i.postimg.cc/HxWFK4sW/2006-FURY-uav-destr-19-12-23.jpg took 0.36639366799954587 seconds to run
7856
7857
Grabbing the full link at https://i.postimg.cc/P5qK4cdv/2011-A1-SM-Fury-reconnaissance-UAV-destr-05-02-24.jpg took 0.37531764499999554 seconds to run
7857
7858
Grabbing the full link at https://i.postimg.cc/tgX0mfGR/2011-fury-uav-destr-16-02-24.jpg took 0.3737287550002293 seconds to run
7858
7859
Grabbing the full link at https://i.postimg.cc/xjM2qfdp/2015-A1-SM-Fury-destr-28-12-23.jpg took 0.35946089400022174 seconds to run
7859
7860
Grabbing the full link at https://i.postimg.cc/Vv56DdqG/2003-fury-uav-destr-05-06-22.jpg took 0.37650932900032785 seconds to run
7860
7861
Grabbing the full link at https://i.postimg.cc/Kj1R9kVz/2002-fury-uav-destr-17-03-24.jpg took 0.3817571939998743 seconds to run
7861
7862
Grabbing the full link at https://i.postimg.cc/C59d9MT4/2020-fury-uav-destr-13-03-24.jpg took 0.3612963139994463 seconds to run
7862
7863
Grabbing the full link at https://i.postimg.cc/PqwW4n2z/2029-A1-SM-Furiia-reconnaissance-UAV-destr-02-04-24.jpg took 0.36359950799942453 seconds to run
7863
7864
Grabbing the full link at https://i.postimg.cc/6qpfyr3s/2001-A1-SM-Furiia-reconnaissance-UAV-destr-08-04-24.jpg took 0.37155162899944116 seconds to run
7864
7865
Grabbing the full link at https://i.postimg.cc/yNSK4L3g/2002-fury-uav-destr-25-04-24.jpg took 0.37397602000055485 seconds to run
7865
7866
Grabbing the full link at https://i.postimg.cc/ZKMBVZWc/2010-fury-uav-destr-22-05-24.jpg took 0.39139591500043025 seconds to run
7866
7867
Grabbing the full link at https://i.postimg.cc/sgDF7pXp/2016-fury-uav-destr-08-06-24.jpg took 0.4040267459995448 seconds to run
7867
7868
Grabbing the full link at https://i.postimg.cc/q76wQyjV/2028-A1-SM-Furiia-reconnaissance-UAV-destr-10-06-24.jpg took 0.35981922799965105 seconds to run
7868
7869
Grabbing the full link at https://i.postimg.cc/k5X59NXs/2020-A1-SM-Furiia-reconnaissance-UAV-destr-18-07-24.jpg took 0.3773251180000443 seconds to run
7869
7870
Grabbing the full link at https://i.postimg.cc/0QhckqJc/2026-A1-SM-Furiia-reconnaissance-UAV-destr-25-08-24.jpg took 0.36122624600011477 seconds to run
7870
7871
Grabbing the full link at https://i.postimg.cc/7LwsbDRR/2003-A1-SM-Furiia-reconnaissance-UAV-destr-07-09-24.jpg took 0.3752528639997763 seconds to run
7871
7872
Grabbing the full link at https://i.postimg.cc/L4GK0yg9/2007-A1-SM-Furiia-reconnaissance-UAV-destr-12-09-24.jpg took 0.37278901300032885 seconds to run
7872
7873
Grabbing the full link at https://i.postimg.cc/1z95nfXH/2119-A1-SM-Furiia-reconnaissance-UAV-destr-20-10-24.jpg took 0.36996743500003504 seconds to run
7873
7874
Grabbing the full link at https://i.postimg.cc/KvLWxJvN/2004-A1-SM-Furiia-reconnaissance-UAV-destr-20-10-24.jpg took 0.36779945899979793 seconds to run
7874
7875
Grabbing the full link at https://i.postimg.cc/6pf1GqZ4/2005-A1-SM-Furiia-reconnaissance-UAV-destr-26-10-24.jpg took 0.36797811900032684 seconds to run
7875
7876
Grabbing the full link at https://i.postimg.cc/8zS05M7V/2012-A1-SM-Furiia-reconnaissance-UAV-destr-11-05-24.jpg took 0.36630540500027564 seconds to run
7876
7877
Grabbing the full link at https://i.postimg.cc/QNFKsZ9y/2018-A1-SM-Furiia-reconnaissance-UAV-destr-15-11-24.jpg took 0.36460518700005196 seconds to run
7877
7878
Grabbing the full link at https://i.postimg.cc/tCKV28J2/2008-A1-SM-Furiia-reconnaissance-UAV-destr-21-11-24.jpg took 0.36601842799973383 seconds to run
7878
7879
Grabbing the full link at https://i.postimg.cc/7Z2qhmXK/2005-A1-SM-Furiia-reconnaissance-UAV-destr-03-01-25.jpg took 0.37048802099980094 seconds to run
7879
7880
Grabbing the full link at https://i.postimg.cc/ZnHJyfLC/2031-A1-SM-Furiia-reconnaissance-UAV-destr-18-06-24.jpg took 0.36374322099982237 seconds to run
7880
7881
Grabbing the full link at https://i.postimg.cc/htTjGhtx/2033-A1-SM-Furiia-reconnaissance-UAV-destr-05-12-24.jpg took 0.37307024799974897 seconds to run
7881
7882
Grabbing the full link at https://i.postimg.cc/gkfjd3mm/2024-A1-SM-Furiia-reconnaissance-UAV-destr-20-08-22.jpg took 0.36733624399948894 seconds to run
7882
7883
Grabbing the full link at https://i.postimg.cc/htg51VQ9/2032-A1-SM-Furiia-reconnaissance-UAV-destr-15-02-25.jpg took 0.3646482329995706 seconds to run
7883
7884
Grabbing the full link at https://i.postimg.cc/JzwXbxkS/2135-A1-SM-Furiia-reconnaissance-UAV-destr-13-03-25.jpg took 0.36490442299964343 seconds to run
7884
7885

Connecting to https://i.postimg.cc/wj96QDhY/317.png ...
Downloading 317.png ...
[                                                  ] 0.28%

Grabbing the full link at https://i.postimg.cc/wj96QDhY/317.png took 0.3650111080005445 seconds to run

[==================================================] 100.00%

OCR returns: RVvoenkor|02/5/2022|RusVesna Su|RVvoenkor|ACM135001|hux|ACM135001|RusVesna SU
Running OCR on https://i.postimg.cc/wj96QDhY/317.png took 21.632961584999975 seconds to run
7885
7886
Grabbing the full link at https://i.postimg.cc/NFtSQZQN/3d5.png took 0.5141595929999312 seconds to run

Connecting to https://i.postimg.cc/NFtSQZQN/3d5.png ...
Downloading 3d5.png ...
[==================================================] 100.00%

OCR returns: ACM135801|ACM135801|30/5/2022|LMEARDURNAL
Running OCR on https://i.postimg.cc/NFtSQZQN/3d5.png took 18.37697971200032 seconds to run
7886
7887
Grabbing the full link at https://i.postimg.cc/zXLjKRdV/2001-A1-SM-Fury.jpg took 0.36880635600027745 seconds to run

Connecting to https://i.postimg.cc/zXLjKRdV/2001-A1-SM-Fury.jpg ...
Downloading 2001-A1-SM-Fury.jpg ...
[==================================================] 100.00%

OCR returns: ACM136903|ACM136903
Running OCR on https://i.postimg.cc/zXLjKRdV/2001-A1-SM-Fury.jpg took 17.11765603799995 seconds to run
7887
7888
Grabbing the full link at https://i.postimg.cc/Kc9zf0HQ/4376.png took 0.38818811800047115 seconds to run

Connecting to https://i.postimg.cc/Kc9zf0HQ/4376.png ...
Downloading 4376.png ...
[==================================================] 100.00%

OCR returns: CS|27/10/2022|ACM1387
Running OCR on https://i.postimg.cc/Kc9zf0HQ/4376.png took 23.473565639999833 seconds to run
7888
7889
Grabbing the full link at https://i.postimg.cc/QdQQwy4B/2001-A1-SM-Fury-UAV-capt.jpg took 0.37887160500031314 seconds to run

Connecting to https://i.postimg.cc/QdQQwy4B/2001-A1-SM-Fury-UAV-capt.jpg ...
Downloading 2001-A1-SM-Fury-UAV-capt.jpg ...
[==================================================] 100.00%

OCR returns: RusVesna SU|27.11.2022
Running OCR on https://i.postimg.cc/QdQQwy4B/2001-A1-SM-Fury-UAV-capt.jpg took 29.11080379899977 seconds to run
7889
7890
Grabbing the full link at https://i.postimg.cc/TY7bG6hy/2001-A1-SM-Fury-capt.jpg took 0.4473747709998861 seconds to run

Connecting to https://i.postimg.cc/TY7bG6hy/2001-A1-SM-Fury-capt.jpg ...
Downloading 2001-A1-SM-Fury-capt.jpg ...
[==================================================] 100.00%

OCR returns: ACM226260|ACM226260|12.12.2022
Running OCR on https://i.postimg.cc/TY7bG6hy/2001-A1-SM-Fury-capt.jpg took 23.223402364999856 seconds to run
7890
7891
Grabbing the full link at https://i.postimg.cc/Ss0Jw2np/2001-fury-uav-capt-05-01-23.jpg took 0.37827289100005146 seconds to run
7891
7892
Grabbing the full link at https://i.postimg.cc/vTZ3nBwT/1002-Furia-capt-12-01-2023.png took 0.42223591600031796 seconds to run
7892
7893
Grabbing the full link at https://i.postimg.cc/XqNxtDsK/2006-A1-SM-Fury-capt-31-01-23.jpg took 0.3782647329999236 seconds to run
7893
7894
Grabbing the full link at https://i.postimg.cc/9X1LyCfL/2011-A1-SM-Fury-capt-30-01-23.jpg took 0.40969587699964904 seconds to run
7894
7895
Grabbing the full link at https://i.postimg.cc/Nf4sWv8D/2002-A1-SM-Fury-UAV-capt-18-02-23.jpg took 0.4839720390000366 seconds to run
7895
7896
Grabbing the full link at https://i.postimg.cc/GtSbKKxW/4.png took 0.4594250239997564 seconds to run

Connecting to https://i.postimg.cc/GtSbKKxW/4.png ...
Downloading 4.png ...
[==================================================] 100.00%

OCR returns: 31/7/2022
Running OCR on https://i.postimg.cc/GtSbKKxW/4.png took 12.989727811999728 seconds to run
7896
7897

Connecting to https://i.postimg.cc/yNbhhd96/33d.png ...
Downloading 33d.png ...
[                                                  ] 0.49%

Grabbing the full link at https://i.postimg.cc/yNbhhd96/33d.png took 0.4602306460001273 seconds to run

[==================================================] 100.00%

OCR returns: bl|SS|16/6/2023
Running OCR on https://i.postimg.cc/yNbhhd96/33d.png took 13.463117581000006 seconds to run
7897
7898
Grabbing the full link at https://i.postimg.cc/tCBbhqJg/2026-A1-SM-Furia-capt-29-06-23.jpg took 0.3809703750002882 seconds to run
7898
7899
Grabbing the full link at https://i.postimg.cc/ydS4F4mS/79.png took 0.36775141899943264 seconds to run

Connecting to https://i.postimg.cc/ydS4F4mS/79.png ...
Downloading 79.png ...
[==================================================] 100.00%

OCR returns: 30/6/2023|httpswtamo/tovroheskllkaZochok
Running OCR on https://i.postimg.cc/ydS4F4mS/79.png took 5.902280921999591 seconds to run
7899
7900
Grabbing the full link at https://i.postimg.cc/Bn5LWyXw/478.png took 0.418074369000351 seconds to run

Connecting to https://i.postimg.cc/Bn5LWyXw/478.png ...
Downloading 478.png ...
[==================================================] 100.00%

OCR returns: 08/7/2023|YHNYTOKEHHbINBNnA"YPNA"BCy
Running OCR on https://i.postimg.cc/Bn5LWyXw/478.png took 9.747228584999903 seconds to run
7900
7901
Grabbing the full link at https://i.postimg.cc/YqHtw7hF/2014-A1-SM-Fury-capt-14-08-23.jpg took 0.37446623199957685 seconds to run
7901
7902
Grabbing the full link at https://i.postimg.cc/V6yCBPZm/54.png took 0.3658655170002021 seconds to run

Connecting to https://i.postimg.cc/V6yCBPZm/54.png ...
Downloading 54.png ...
[==================================================] 100.00%

OCR returns: 24/8/2023|ACM131202|ACM131202|12100300|2300000
Running OCR on https://i.postimg.cc/V6yCBPZm/54.png took 27.95202737299951 seconds to run
7902
7903
Grabbing the full link at https://i.postimg.cc/mZMJ8dK2/3770.png took 0.3774238449996119 seconds to run

Connecting to https://i.postimg.cc/mZMJ8dK2/3770.png ...
Downloading 3770.png ...
[==================================================] 100.00%

OCR returns: 09/8/2023|PNA HOBOCTN|PNA HOBOCTN|PNAHOBOCTN|PNAHOBOCTN
Running OCR on https://i.postimg.cc/mZMJ8dK2/3770.png took 27.92622322599982 seconds to run
7903
7904
Grabbing the full link at https://i.postimg.cc/HxWKZgjB/27.png took 0.36050677099956374 seconds to run

Connecting to https://i.postimg.cc/HxWKZgjB/27.png ...
Downloading 27.png ...
[==================================================] 100.00%

OCR returns: 08/9/2023|RB|OBTR80
Running OCR on https://i.postimg.cc/HxWKZgjB/27.png took 10.326717197999642 seconds to run
7904
7905
Grabbing the full link at https://i.postimg.cc/LsZtLdtK/2007-fury-uav-capt-06-10-23.jpg took 0.38153843300005974 seconds to run
7905
7906
Grabbing the full link at https://i.postimg.cc/25ZcwfRr/2012-fury-uav-capt-30-09-23.jpg took 0.3652536350000446 seconds to run
7906
7907
Grabbing the full link at https://i.postimg.cc/Y9BXDyMg/2015-fury-uav-capt-23-06-22.jpg took 0.38314138100031414 seconds to run
7907
7908
Grabbing the full link at https://i.postimg.cc/VNrNKYyX/2011-fury-uav-capr-02-11-23.jpg took 0.41665324099994905 seconds to run
7908
7909
Grabbing the full link at https://i.postimg.cc/8ktxHHDg/2020-fury-uav-capt-16-11-23.jpg took 0.3735636519995751 seconds to run
7909
7910
Grabbing the full link at https://i.postimg.cc/Z5CfjxQw/2020-A1-SM-Fury-capt-17-11-23.jpg took 0.3729636460002439 seconds to run
7910
7911
Grabbing the full link at https://i.postimg.cc/fLmhfb5F/2025-fury-uav-capt-07-12-23.jpg took 0.36548397299975477 seconds to run
7911
7912
Grabbing the full link at https://i.postimg.cc/yN5ZDW4H/2007-fury-uav-capt-14-12-23.jpg took 0.36443699699975696 seconds to run
7912
7913
Grabbing the full link at https://i.postimg.cc/bJPsJWn7/2003-A1-SM-Furia-uav-capt-08-01-24.jpg took 0.37713032600004226 seconds to run
7913
7914
Grabbing the full link at https://i.postimg.cc/g2BsBD0S/2012-A1-SM-Fury-reconnaissance-UAV-capt-23-01-24.jpg took 0.36244998599977407 seconds to run
7914
7915
Grabbing the full link at https://i.postimg.cc/rpNCGL4g/2000-A1-SM-Fury-UAV-capt-06-02-24.jpg took 0.3733589370003756 seconds to run
7915
7916
Grabbing the full link at https://i.postimg.cc/9F2j76Rm/2007-A1-SM-Fury-capt-23-02-24.jpg took 0.3678240780000124 seconds to run
7916
7917
Grabbing the full link at https://i.postimg.cc/sDJC9T7p/2012-A1-SM-Fury-capt-16-02-24.jpg took 0.36633720100053324 seconds to run
7917
7918
Grabbing the full link at https://i.postimg.cc/x1TDsL3B/2013-A1-SM-Fury-capt-20-02-24.jpg took 0.3672241189997294 seconds to run
7918
7919
Grabbing the full link at https://i.postimg.cc/269rS8jW/2025-A1-SM-Furiia-reconnaissance-UAV-capt-30-09-23.jpg took 0.36379886000031547 seconds to run
7919
7920
Grabbing the full link at https://i.postimg.cc/rFrMqkBd/2026-A1-SM-Furiia-reconnaissance-UAV-capt-13-10-23.jpg took 0.4039980560000913 seconds to run
7920
7921
Grabbing the full link at https://i.postimg.cc/x1GQbPTn/2027-A1-SM-Furiia-reconnaissance-UAV-capt-14-07-23.jpg took 0.3721407940001882 seconds to run
7921
7922
Grabbing the full link at https://i.postimg.cc/qvWzf37p/2010-A1-SM-Furiia-reconnaissance-UAV-capt-22-09-23.jpg took 0.38184288699994795 seconds to run
7922
7923
Grabbing the full link at https://i.postimg.cc/Z5RfNB79/2020-fury-uav-capt-07-08-23.jpg took 0.37624619799953507 seconds to run
7923
7924
Grabbing the full link at https://i.postimg.cc/yYFYsfBD/2000-fury-auv-capt-27-02-24.jpg took 0.36385707699992054 seconds to run
7924
7925
Grabbing the full link at https://i.postimg.cc/ncLQpNj8/2017-A1-SM-Furiia-reconnaissance-UAV-capt-12-04-24.jpg took 0.3716009829995528 seconds to run
7925
7926
Grabbing the full link at https://i.postimg.cc/nztDxz7T/2015-A1-SM-Furiia-reconnaissance-UAV-capt-16-04-24.jpg took 0.3682694690005519 seconds to run
7926
7927
Grabbing the full link at https://i.postimg.cc/G2Y9J9Cp/2013-fury-uav-capt-24-04-24.jpg took 0.36872778399992967 seconds to run
7927
7928
Grabbing the full link at https://i.postimg.cc/sgPjCXg6/2026-A1-SM-Furiia-UAV-capt-17-07-23.jpg took 0.37513984499946673 seconds to run
7928
7929
Grabbing the full link at https://i.postimg.cc/jSRYsTxy/2008-fury-uav-capt-10-01-24.jpg took 0.36610465200010367 seconds to run
7929
7930
Grabbing the full link at https://i.postimg.cc/9XPrW9HG/2030-fury-uav-capt-05-03-24.jpg took 0.3709151479997672 seconds to run
7930
7931
Grabbing the full link at https://i.postimg.cc/Dzt6kGZg/2004-A1-SM-Furiia-reconnaissance-UAV-capt-31-05-24.jpg took 0.3810107050003353 seconds to run
7931
7932
Grabbing the full link at https://i.postimg.cc/cH8xKkN4/2001-A1-SM-Furiia-reconnaissance-UAV-capt-16-06-24.jpg took 0.3650939600001948 seconds to run
7932
7933
Grabbing the full link at https://i.postimg.cc/5yhJM9RG/2005-A1-SM-Furiia-reconnaissance-UAV-capt-26-06-24.jpg took 0.3676388650001172 seconds to run
7933
7934
Grabbing the full link at https://i.postimg.cc/zG6ChMdg/2005-A1-SM-Furiia-reconnaissance-UAV-capt-03-07-24.jpg took 0.3672799389996726 seconds to run
7934
7935
Grabbing the full link at https://i.postimg.cc/9fHQmTfS/2010-A1-SM-Furiia-reconnaissance-UAV-capt-10-07-24.jpg took 0.3791726829995241 seconds to run
7935
7936
Grabbing the full link at https://i.postimg.cc/1RWt6LJT/2006-A1-SM-Furiia-reconnaissance-UAV-capt-22-07-24.jpg took 0.37928261999968527 seconds to run
7936
7937
Grabbing the full link at https://i.postimg.cc/65GWhTds/2016-A1-SM-Furiia-reconnaissance-UAV-capt-05-08-24.jpg took 0.36864807899928564 seconds to run
7937
7938
Grabbing the full link at https://i.postimg.cc/26GkZpkQ/2023-A1-SM-Furiia-reconnaissance-UAV-capt-14-09-24.jpg took 0.3831008090000978 seconds to run
7938
7939
Grabbing the full link at https://i.postimg.cc/sxv6Ncw4/2019-A1-SM-Furiia-reconnaissance-UAV-capt-20-09-24.jpg took 0.37121568499969726 seconds to run
7939
7940
Grabbing the full link at https://i.postimg.cc/NFWNRJrR/2025-A1-SM-Furiia-reconnaissance-UAV-capr-04-10-24.jpg took 0.3786563940002452 seconds to run
7940
7941
Grabbing the full link at https://i.postimg.cc/dVcH1fFY/2027-A1-SM-Furiia-reconnaissance-UAV-capt-02-10-24.jpg took 0.3661536999998134 seconds to run
7941
7942
Grabbing the full link at https://i.postimg.cc/tRKFV6mc/2021-A1-SM-Furiia-reconnaissance-UAV-capt-24-09-24.jpg took 0.3627808430001096 seconds to run
7942
7943
Grabbing the full link at https://i.postimg.cc/jjv4DCGK/2031-A1-SM-Furiia-reconnaissance-UAV-capt-08-11-24.jpg took 0.3699501410001176 seconds to run
7943
7944
Grabbing the full link at https://i.postimg.cc/hGYdTL5y/2011-A1-SM-Furiia-reconnaissance-UAV-capt-23-06-24.jpg took 0.37665303900030267 seconds to run
7944
7945
Grabbing the full link at https://i.postimg.cc/4y67DrNq/2012-A1-SM-Furiia-reconnaissance-UAV-capt-12-11-24.jpg took 0.4156116939993808 seconds to run
7945
7946
Grabbing the full link at https://i.postimg.cc/4xYZx73W/2006-A1-SM-Furiia-reconnaissance-UAV-capt-13-12-24.jpg took 0.3803267799994501 seconds to run
7946
7947
Grabbing the full link at https://i.postimg.cc/Rh4MhrKk/2029-A1-SM-Furiia-reconnaissance-UAV-capt-07-01-25.jpg took 0.36185234599997784 seconds to run
7947
7948
Grabbing the full link at https://i.postimg.cc/mZn3stKt/2036-A1-SM-Furiia-reconnaissance-UAV-capt-03-02-25.jpg took 0.36149303300044267 seconds to run
7948
7949
Grabbing the full link at https://i.postimg.cc/s2Jgp8Sg/2044-A1-SM-Furiia-reconnaissance-UAV-capt-27-12-24.jpg took 0.3690101299998787 seconds to run
7949
7950
Grabbing the full link at https://i.postimg.cc/fy3wxS17/2000-A1-SM-Furiia-reconnaissance-UAV-capt-21-09-24.jpg took 0.3629118280005059 seconds to run
7950
7951
Grabbing the full link at https://i.postimg.cc/4yg7qkYn/2006-A1-SM-Furiia-reconnaissance-UAV-capt-20-02-25.jpg took 0.4132504549997975 seconds to run
7951
7952
Grabbing the full link at https://i.postimg.cc/VL0Mrpdj/2015-A1-SM-Furiia-reconnaissance-UAV-capt-06-12-24.jpg took 0.3661469090002356 seconds to run
7952
7953
Grabbing the full link at https://i.postimg.cc/bJFGX8Jb/2015-A1-SM-Furiia-reconnaissance-UAV-capt-13-02-25.jpg took 0.3779344670001592 seconds to run
7953
7954
Grabbing the full link at https://i.postimg.cc/mZ3FCfkk/2012-A1-SM-Furiia-reconnaissance-UAV-capt-28-04-25.jpg took 0.3941847649994088 seconds to run
7954
7955
Grabbing the full link at https://i.postimg.cc/XJNPDQfD/2017-A1-SM-Furiia-reconnaissance-UAV-capt-24-03-25.jpg took 0.39740538699970784 seconds to run
7955
7956
Grabbing the full link at https://i.postimg.cc/TwXrr6sz/2001-A1-SM-Furiia-reconnaissance-UAV-capt-07-06-25.jpg took 0.38938748799955647 seconds to run
7956
7957
Grabbing the full link at https://i.postimg.cc/MTb15L2v/2002-A1-SM-Furiia-reconnaissance-UAV-capt-12-04-25.jpg took 0.37456527999984246 seconds to run
7957
7958
Grabbing the full link at https://i.postimg.cc/rFTrr8SR/2026-A1-SM-Furiia-reconnaissance-UAV-capt-11-05-25.jpg took 0.38666202500007785 seconds to run
7958
7959
Grabbing the full link at https://i.postimg.cc/VNC6NC8n/314.png took 0.3701327079998009 seconds to run

Connecting to https://i.postimg.cc/VNC6NC8n/314.png ...
Downloading 314.png ...
[==================================================] 100.00%

OCR returns: 11/10/2022|VR46|MotoGP
Running OCR on https://i.postimg.cc/VNC6NC8n/314.png took 22.674067115999605 seconds to run
7959
7960
Grabbing the full link at https://i.postimg.cc/NfW8bL7S/2002-ASU-1-Valkyrja-UAV-destr-25-08-22.jpg took 0.3701450729995486 seconds to run
7960
7961
Grabbing the full link at https://i.postimg.cc/PJWwRdmw/2006-ASU-1-Valkyrja-destr-20-01-23.jpg took 0.39040248399942357 seconds to run
7961
7962
Grabbing the full link at https://i.postimg.cc/3NtpZnqm/2013-ASU-1-Valkyria-UAV-destr-16-02-23.jpg took 0.36750978300005954 seconds to run
7962
7963
Grabbing the full link at https://i.postimg.cc/qqHRh8xk/2000-ASU-1-Valkirya-destr-23-02-2023.jpg took 0.3799218340000152 seconds to run
7963
7964
Returning non-postimg link
7964
7965
Grabbing the full link at https://i.postimg.cc/QdwcwNGc/2018-ASU-1-Valkyrja-destr-12-03-23.jpg took 0.3670636819997526 seconds to run
7965
7966
Grabbing the full link at https://i.postimg.cc/PJ4zs7cg/2002-ASU-1-valkyria-destr-21-03-23.jpg took 0.3656243949999407 seconds to run
7966
7967
Grabbing the full link at https://i.postimg.cc/3Jk01KKd/2006-valkyria-uav-destr-26-04-23.jpg took 0.36891003900018404 seconds to run
7967
7968
Grabbing the full link at https://i.postimg.cc/k5VjRLFk/2019-ASU-1-Valkyria-destr-09-05-23.jpg took 0.36341129199990974 seconds to run
7968
7969
Grabbing the full link at https://i.postimg.cc/XvJXHRQR/2041-ASU-1-Valkyria-destr-15-05-23.jpg took 0.36503795699991315 seconds to run
7969
7970
Grabbing the full link at https://i.postimg.cc/1zh1NNDK/2016-ASU-1-Valkyriya-destr-23-05-23.jpg took 0.3707370920001267 seconds to run
7970
7971
Grabbing the full link at https://i.postimg.cc/P5rZTfhG/2005-ASU-1-Valkyrja-reconnaissance-UAV-destr-14-05-23.jpg took 0.359518840000419 seconds to run
7971
7972
Grabbing the full link at https://i.postimg.cc/yNXzQW53/2044-asu1-destr-14-06-23.jpg took 0.3610731520002446 seconds to run
7972
7973
Grabbing the full link at https://i.postimg.cc/wjNb6RjC/2010-ASU-1-Valkyrja-destr-22-06-23.jpg took 0.3806838729997253 seconds to run
7973
7974
Grabbing the full link at https://i.postimg.cc/SQXdD2Qr/28.png took 0.36813317799988 seconds to run

Connecting to https://i.postimg.cc/SQXdD2Qr/28.png ...
Downloading 28.png ...
[==================================================] 100.00%

OCR returns: 27/6/2023
Running OCR on https://i.postimg.cc/SQXdD2Qr/28.png took 14.388971155000036 seconds to run
7974
7975
Grabbing the full link at https://i.postimg.cc/qvqnS120/2010-asu-1-valkyra-destr-06-08-23.jpg took 0.3772087739998824 seconds to run
7975
7976
Grabbing the full link at https://i.postimg.cc/MpKBh2jJ/2009-ASU-1-Valkiria-destr-10-08-23.jpg took 0.3824237910002921 seconds to run
7976
7977
Grabbing the full link at https://i.postimg.cc/d0gTkhNJ/2012-ASU-1-Valkiria-destr-09-08-23.jpg took 0.3667845790005231 seconds to run
7977
7978
Grabbing the full link at https://i.postimg.cc/15h356Yf/2001-ASU-1-Valkiria-reconnaissance-UAV-destr-11-08-23.jpg took 0.3653264480008147 seconds to run
7978
7979
Grabbing the full link at https://i.postimg.cc/J7BhLKxf/2006-ASU-1-Valkiria-reconnaissance-UAV-destr-31-07-23.jpg took 0.3809877960002268 seconds to run
7979
7980
Grabbing the full link at https://i.postimg.cc/zD6nLjXb/2004-ASU-1-Valkiria-reconnaissance-UAV-destr-25-07-23.jpg took 0.3678480819999095 seconds to run
7980
7981
Grabbing the full link at https://i.postimg.cc/BnYp5G9k/3277.png took 0.39441992199954257 seconds to run

Connecting to https://i.postimg.cc/BnYp5G9k/3277.png ...
Downloading 3277.png ...
[==================================================] 100.00%

OCR returns: 16/9/2023|000
Running OCR on https://i.postimg.cc/BnYp5G9k/3277.png took 25.47305524500007 seconds to run
7981
7982
Grabbing the full link at https://i.postimg.cc/DyThk9w5/3280.png took 0.37481524299982993 seconds to run

Connecting to https://i.postimg.cc/DyThk9w5/3280.png ...
Downloading 3280.png ...
[==================================================] 100.00%

OCR returns: BOV|Za CBONX|Za CBONX 34|LaCBONX 34|c6op|Za CBONX 34 (c6op)|Za CBONX 34 (c60p)|23/5/2023|CBONX34|Za|Za.CBONX 34(c6op)|c6op）|c6op)|NX34（C6
Running OCR on https://i.postimg.cc/DyThk9w5/3280.png took 30.21081396000045 seconds to run
7982
7983
Grabbing the full link at https://i.postimg.cc/SRLBcm80/2038-ASU-1-Valkyrie-UAV-destr-05-10-23.jpg took 0.3992249559996708 seconds to run
7983
7984
Grabbing the full link at https://i.postimg.cc/CL5X6qLB/2006-asu-1-valkyria-destr-13-11-23.jpg took 0.383424130000094 seconds to run
7984
7985
Grabbing the full link at https://i.postimg.cc/MGB9JKqR/2003-ASU-1-Valkiria-destr-06-07-23.jpg took 0.3943414759996813 seconds to run
7985
7986
Grabbing the full link at https://i.postimg.cc/RVPscDg3/2007-ASU-1-Valkiria-18-10-23.jpg took 0.4078159410000808 seconds to run
7986
7987
Grabbing the full link at https://i.postimg.cc/0QJRY0nZ/2012-ASU-1-Valkiria-destr-12-03-23.jpg took 0.39378257200041844 seconds to run
7987
7988
Grabbing the full link at https://i.postimg.cc/R0XyzzH8/2006-ASU-1-Valkiria-UAV-destr-25-01-24.jpg took 0.38079701399965415 seconds to run
7988
7989
Grabbing the full link at https://i.postimg.cc/6Qyj9PSx/2005-ASU-1-Valkiria-reconnaissance-UAV-destr-29-01-24.jpg took 0.3733949890001895 seconds to run
7989
7990
Grabbing the full link at https://i.postimg.cc/sxqpffFf/2001-ASU-1-Valkiria-UAV-destr-28-02-23.jpg took 0.39186804099972505 seconds to run
7990
7991
Grabbing the full link at https://i.postimg.cc/L8bx39wx/2022-Valkiria-UAV-destr-01-03-24.jpg took 1.401985142999365 seconds to run
7991
7992
Grabbing the full link at https://i.postimg.cc/fTDKKtmB/2003-ASU-1-Valkiria-UAV-destr-23-02-24.jpg took 0.37317893100043875 seconds to run
7992
7993
Grabbing the full link at https://i.postimg.cc/zXxnFdJG/2016-Valkiria-UAV-destr-09-03-24.jpg took 0.4487447470000916 seconds to run
7993
7994
Grabbing the full link at https://i.postimg.cc/gc7wxsX6/2021-Valkiria-uav-destr-11-03-24.jpg took 0.45390549099920463 seconds to run
7994
7995
Grabbing the full link at https://i.postimg.cc/Gp87HgFc/2001-ASU-1-Valkiria-destr-24-03-24.jpg took 0.4210148990005109 seconds to run
7995
7996
Grabbing the full link at https://i.postimg.cc/13mwyPhm/2001-ASU-1-Valkiria-destr-29-03-24.jpg took 0.4554735460005759 seconds to run
7996
7997
Grabbing the full link at https://i.postimg.cc/BbmL2Bzw/2007-ASU-1-Valkiria-destr-15-04-24.jpg took 0.4124774059991978 seconds to run
7997
7998
Grabbing the full link at https://i.postimg.cc/DyXf55kK/2003-Valkiria-UAV-destr-05-05-24.jpg took 0.388297674999194 seconds to run
7998
7999
Grabbing the full link at https://i.postimg.cc/1R2sFM3H/2010-ASU-1-Valkiria-reconnaissance-UAV-destr-30-06-24.jpg took 0.37627400099972874 seconds to run
7999
8000
Grabbing the full link at https://i.postimg.cc/NjwtJMT2/2011-ASU-1-Valkiria-reconnaissance-UAV-destr-15-06-24.jpg took 0.4973667509993902 seconds to run
8000
Saved at index 8000
8001
Grabbing the full link at https://i.postimg.cc/SspcT9bQ/2013-ASU-1-Valkiria-reconnaissance-UAV-destr-06-07-24.jpg took 0.38609984399954556 seconds to run
8001
8002
Grabbing the full link at https://i.postimg.cc/qMz506bX/2001-ASU-1-Valkiria-reconnaissance-UAV-destr-04-01-24.jpg took 0.4484434370006056 seconds to run
8002
8003
Grabbing the full link at https://i.postimg.cc/jSf3n0rD/2007-ASU-1-Valkiria-reconnaissance-UAV-destr-23-07-24.jpg took 0.45017734599969117 seconds to run
8003
8004
Grabbing the full link at https://i.postimg.cc/CLX6KM9y/2008-ASU-1-Valkiria-reconnaissance-UAV-destr-23-07-24.jpg took 0.4052024349994099 seconds to run
8004
8005
Grabbing the full link at https://i.postimg.cc/TYmM8rnr/2006-ASU-1-Valkiria-reconnaissance-UAV-destr-12-09-24.jpg took 0.4565598260005572 seconds to run
8005
8006
Grabbing the full link at https://i.postimg.cc/DzhrkDNc/2000-ASU-1-Valkyrja-UAV-capt-22-08-22.jpg took 0.5519643580000775 seconds to run
8006
8007
Grabbing the full link at https://i.postimg.cc/HWX759J4/9l.png took 0.4566416139996363 seconds to run

Connecting to https://i.postimg.cc/HWX759J4/9l.png ...
Downloading 9l.png ...
[==================================================] 100.00%

OCR returns: 10/4/2023
Running OCR on https://i.postimg.cc/HWX759J4/9l.png took 26.329699109000103 seconds to run
8007
8008
Grabbing the full link at https://i.postimg.cc/QtTrTCZ0/2f.png took 0.38982657700034906 seconds to run

Connecting to https://i.postimg.cc/QtTrTCZ0/2f.png ...
Downloading 2f.png ...
[==================================================] 100.00%

OCR returns: 09/9/2023|ZA
Running OCR on https://i.postimg.cc/QtTrTCZ0/2f.png took 32.47072746499998 seconds to run
8008
8009

Connecting to https://i.postimg.cc/1zZ3Cgz4/327.png ...
Downloading 327.png ...
[                                                  ] 0.23%

Grabbing the full link at https://i.postimg.cc/1zZ3Cgz4/327.png took 0.3691830840007242 seconds to run

[==================================================] 100.00%

OCR returns: 13/9/2023
Running OCR on https://i.postimg.cc/1zZ3Cgz4/327.png took 23.017123861000073 seconds to run
8009
8010
Grabbing the full link at https://i.postimg.cc/8kFczgDS/4311.png took 0.3843877799999973 seconds to run

Connecting to https://i.postimg.cc/8kFczgDS/4311.png ...
Downloading 4311.png ...
[==================================================] 100.00%

OCR returns: 25/9/2023|Sitha
Running OCR on https://i.postimg.cc/8kFczgDS/4311.png took 22.54133418099991 seconds to run
8010
8011
Grabbing the full link at https://i.postimg.cc/hGhm7rtN/2005-ASU-1-Valkiria-capt-27-03-24.jpg took 0.3662360170001193 seconds to run
8011
8012
Grabbing the full link at https://i.postimg.cc/NF4M06gY/2004-ASU-1-Valkiria-reconnaissance-UAV-capt-10-06-24.jpg took 0.3769053999994867 seconds to run
8012
8013
Grabbing the full link at https://i.postimg.cc/mkrb3dk0/2022-ASU-1-Valkiria-reconnaissance-UAV-capt-14-09-24.jpg took 0.383204291999391 seconds to run
8013
8014
Grabbing the full link at https://i.postimg.cc/4dbNf3bs/42.jpg took 0.4124720910003816 seconds to run

Connecting to https://i.postimg.cc/4dbNf3bs/42.jpg ...
Downloading 42.jpg ...
[==================================================] 100.00%

OCR returns: 12.04.2022|RSY E
Running OCR on https://i.postimg.cc/4dbNf3bs/42.jpg took 13.120661754999674 seconds to run
8014
8015
Grabbing the full link at https://i.postimg.cc/ZKx3TB2d/33221.png took 0.41630843199982337 seconds to run

Connecting to https://i.postimg.cc/ZKx3TB2d/33221.png ...
Downloading 33221.png ...
[==================================================] 100.00%

OCR returns: HDONTSTOPWAR|30/9/2022
Running OCR on https://i.postimg.cc/ZKx3TB2d/33221.png took 13.378508986999805 seconds to run
8015
8016
Grabbing the full link at https://i.postimg.cc/B6RVYNGC/29.png took 0.37128654299976915 seconds to run

Connecting to https://i.postimg.cc/B6RVYNGC/29.png ...
Downloading 29.png ...
[==================================================] 100.00%

OCR returns: 30/8/2022|NOBEPHVTbIE|HA BONHE|:48
Running OCR on https://i.postimg.cc/B6RVYNGC/29.png took 26.750922807999814 seconds to run
8016
8017
Grabbing the full link at https://i.postimg.cc/0QfVrS3h/1001-Leleka-100-destr-12-01-23.png took 0.3656553310001982 seconds to run
8017
8018
Returning non-postimg link
8018
8019
Grabbing the full link at https://i.postimg.cc/3wnprvXC/2009-Leleka-100-destr-01-07-22.jpg took 0.3588001380003334 seconds to run
8019
8020
Returning non-postimg link
8020
8021
Grabbing the full link at https://i.postimg.cc/WbPHkRJz/651.png took 0.36269400200035307 seconds to run

Connecting to https://i.postimg.cc/WbPHkRJz/651.png ...
Downloading 651.png ...
[==================================================] 100.00%

OCR returns: 25/3/2023|896|896|968
Running OCR on https://i.postimg.cc/WbPHkRJz/651.png took 23.25340568700085 seconds to run
8021
8022
Grabbing the full link at https://i.postimg.cc/htDV64nK/665.png took 0.374714161999691 seconds to run

Connecting to https://i.postimg.cc/htDV64nK/665.png ...
Downloading 665.png ...
[==================================================] 100.00%

OCR returns: 04/4/2023
Running OCR on https://i.postimg.cc/htDV64nK/665.png took 44.834289417000036 seconds to run
8022
8023
Grabbing the full link at https://i.postimg.cc/ydLNgRP9/2000-Leleka-100-destr-28-04-23.png took 0.3760703649995776 seconds to run
8023
8024
Grabbing the full link at https://i.postimg.cc/76GpDfWJ/2001-Leleka-100-destr-07-05-23.png took 0.3676204499997766 seconds to run
8024
8025
Grabbing the full link at https://i.postimg.cc/W38rFGYV/2011-leleka100-destr-12-05-23.jpg took 0.36696331099938106 seconds to run
8025
8026
Grabbing the full link at https://i.postimg.cc/85CDyqwC/2006-Leleka-100-reconnaissance-UAV-destr-18-05-23.jpg took 0.36154576700027974 seconds to run
8026
8027
Grabbing the full link at https://i.postimg.cc/Xv4n5ZCd/2013-Leleka-100-reconnaissance-UAV-destr-13-05-23.jpg took 0.3788532890002898 seconds to run
8027
8028
Grabbing the full link at https://i.postimg.cc/02ZMWgSV/2002-Leleka-100-reconnaissance-UAV-destr-24-05-23.jpg took 0.361162453000361 seconds to run
8028
8029
Grabbing the full link at https://i.postimg.cc/L4P0nbgH/2001-Leleka-100-destr.jpg took 0.36171199599994 seconds to run

Connecting to https://i.postimg.cc/L4P0nbgH/2001-Leleka-100-destr.jpg ...
Downloading 2001-Leleka-100-destr.jpg ...
[==================================================] 100.00%

OCR returns:  E|SE3 AHTEHM|27.05.2023
Running OCR on https://i.postimg.cc/L4P0nbgH/2001-Leleka-100-destr.jpg took 13.176417433999632 seconds to run
8029
8030
Grabbing the full link at https://i.postimg.cc/CxMtYTf8/2013-leleka100-destr-06-06-23.jpg took 0.3673786380004458 seconds to run
8030
8031
Grabbing the full link at https://i.postimg.cc/DZ3PvLYN/2034-leleka100-capt-01-06-23.png took 0.3709181679996618 seconds to run
8031
8032
Grabbing the full link at https://i.postimg.cc/xdr0pw1h/2008-leleka100-destr-08-06-23.jpg took 0.3674524300004123 seconds to run
8032
8033
Grabbing the full link at https://i.postimg.cc/3JRJkjqS/2011-leleka100-destr-07-06-23.jpg took 0.3698750140001721 seconds to run
8033
8034
Grabbing the full link at https://i.postimg.cc/y6gTcZSP/2009-leleka100-destr-20-07-23.jpg took 0.38394453699947917 seconds to run
8034
8035
Grabbing the full link at https://i.postimg.cc/MZBQsk8f/2007-Leleka-100-destr-31-07-23.jpg took 0.3814032709997264 seconds to run
8035
8036
Grabbing the full link at https://i.postimg.cc/rwVRFKR5/2011-Leleka-100-destr-30-07-23.jpg took 0.3682967770000687 seconds to run
8036
8037
Grabbing the full link at https://i.postimg.cc/G2kVxnxt/2006-Leleka-100-destr-20-08-23.jpg took 0.3746282349993635 seconds to run
8037
8038
Grabbing the full link at https://i.postimg.cc/HLH7JvXS/433.png took 0.37969237900051667 seconds to run

Connecting to https://i.postimg.cc/HLH7JvXS/433.png ...
Downloading 433.png ...
[==================================================] 100.00%

OCR returns: 21/9/2023|21cer.2023r.13:42
Running OCR on https://i.postimg.cc/HLH7JvXS/433.png took 26.7017993620002 seconds to run
8038
8039
Grabbing the full link at https://i.postimg.cc/Kzt8yJ8z/2013-Leleka-100-destr-01-11-23.jpg took 0.36952589099928446 seconds to run
8039
8040
Grabbing the full link at https://i.postimg.cc/52C1tqWm/2003-Leleka-100-destr-15-11-23.jpg took 0.3604046930004188 seconds to run
8040
8041
Grabbing the full link at https://i.postimg.cc/c4MWQKpw/2003-Leleka-100-UAV-destr-27-10-23.jpg took 0.36496888199962996 seconds to run
8041
8042
Grabbing the full link at https://i.postimg.cc/pTxrGpC1/2004-leleka100-destr-03-12-23.jpg took 0.3620668260000457 seconds to run
8042
8043
Grabbing the full link at https://i.postimg.cc/KYd2TT7B/2023-leleka100-destr-25-10-23.jpg took 0.37515138600065256 seconds to run
8043
8044
Grabbing the full link at https://i.postimg.cc/4dm72TZK/2008-Leleka100-destr-22-12-23.jpg took 0.36486884000078135 seconds to run
8044
8045
Grabbing the full link at https://i.postimg.cc/yNGC3bmk/2013-Leleka-100-destr-31-12-23.jpg took 0.3702707009997539 seconds to run
8045
8046
Grabbing the full link at https://i.postimg.cc/kgMYHGv4/2003-Leleka-100-destr-19-01-24.jpg took 0.36334617099964817 seconds to run
8046
8047
Grabbing the full link at https://i.postimg.cc/KjRPykHs/2003-Leleka-100-UAV-destr-19-09-22.jpg took 0.3600022809996517 seconds to run
8047
8048
Grabbing the full link at https://i.postimg.cc/JhPwwqRN/2006-Leleka-100-reconnaissance-UAV-destr-14-02-24.jpg took 0.3612107590006417 seconds to run
8048
8049
Grabbing the full link at https://i.postimg.cc/mrScKTB5/2012-leleka100-destr-16-02-24.jpg took 0.3686527469999419 seconds to run
8049
8050
Grabbing the full link at https://i.postimg.cc/TP2zSNtW/2030-leleka100-destr-21-02-24.jpg took 0.36444811500041396 seconds to run
8050
8051
Grabbing the full link at https://i.postimg.cc/Kzq1rr0w/2016-lelka100-destr-04-03-24.jpg took 0.36242178500015143 seconds to run
8051
8052
Grabbing the full link at https://i.postimg.cc/FH1gYLS6/2011-leleka100-destr-02-04-24.jpg took 0.36405574299988075 seconds to run
8052
8053
Grabbing the full link at https://i.postimg.cc/VLKWsRJM/2031-Leleka-100-UAV-destr-18-02-24.jpg took 0.3579033280002477 seconds to run
8053
8054
Grabbing the full link at https://i.postimg.cc/VkJxQ22T/2004-leleka100-destr-04-04-24.jpg took 0.3826049929994042 seconds to run
8054
8055
Grabbing the full link at https://i.postimg.cc/TY38QK0T/2012-leleka100-destr-05-04-24.jpg took 0.3662548060001427 seconds to run
8055
8056
Grabbing the full link at https://i.postimg.cc/mgRzmRfm/2003-leleka100-destr-07-04-24.jpg took 0.3647440060003646 seconds to run
8056
8057
Grabbing the full link at https://i.postimg.cc/cHwhPJRW/2007-leleka100-destr-10-04-24.jpg took 0.36599743500028126 seconds to run
8057
8058
Grabbing the full link at https://i.postimg.cc/028nHPbg/2014-Leleka-100-reconnaissance-UAV-destr-13-04-24.jpg took 0.36216167000020505 seconds to run
8058
8059
Grabbing the full link at https://i.postimg.cc/2yYGYfGZ/2015-Leleka-100-reconnaissance-UAV-destr-15-04-24.jpg took 0.36161308999999164 seconds to run
8059
8060
Grabbing the full link at https://i.postimg.cc/mZjHxTrN/2002-Leleka-100-destr-13-04-24.jpg took 0.3632743930002107 seconds to run
8060
8061
Grabbing the full link at https://i.postimg.cc/B6jtbQyr/2002-leleka100-destr-15-04-24.jpg took 0.35808464100045967 seconds to run
8061
8062
Grabbing the full link at https://i.postimg.cc/6qf3gSTJ/2002-Leleka-100-reconnaissance-UAV-destr-22-04-24.jpg took 0.3662301000003936 seconds to run
8062
8063
Grabbing the full link at https://i.postimg.cc/LsGn1LG7/2014-leleka100-destr-09-03-24.jpg took 0.37535714200021175 seconds to run
8063
8064
Grabbing the full link at https://i.postimg.cc/MpL0CnxZ/2031-leleka100-destr-30-03-24.jpg took 0.3679982800003927 seconds to run
8064
8065
Grabbing the full link at https://i.postimg.cc/VvSfxWJn/2004-Leleka-100-UAV-destr-04-05-24.jpg took 0.3627341820001675 seconds to run
8065
8066
Grabbing the full link at https://i.postimg.cc/59GNwTr3/2005-Leleka-100-UAV-destr-02-05-24.jpg took 0.3840027819996976 seconds to run
8066
8067
Grabbing the full link at https://i.postimg.cc/qMd9LrCW/2020-leleka100-destr-12-05-24.jpg took 0.3757527600000685 seconds to run
8067
8068
Grabbing the full link at https://i.postimg.cc/ydNztq22/2026-Leleka-100-reconnaissance-UAV-destr-11-05-24.jpg took 0.36639381400073034 seconds to run
8068
8069
Grabbing the full link at https://i.postimg.cc/Ghc99pb6/2007-leleka100-destr-13-05-24.jpg took 0.3821312879999823 seconds to run
8069
8070
Grabbing the full link at https://i.postimg.cc/63Lv4VgX/2002-leleka100-destr-13-04-24.jpg took 0.37024742500034336 seconds to run
8070
8071
Grabbing the full link at https://i.postimg.cc/NfKvYF5v/2015-Leleka-100-reconnaissance-UAV-destr-01-06-24.jpg took 0.3674526619997778 seconds to run
8071
8072
Grabbing the full link at https://i.postimg.cc/9MCsP9Pr/2017-Leleka-100-reconnaissance-UAV-destr-05-06-24.jpg took 0.3633640239995657 seconds to run
8072
8073
Grabbing the full link at https://i.postimg.cc/dVWbBLkg/2017-leleka100-destr-08-06-24.jpg took 0.3782531500000914 seconds to run
8073
8074
Grabbing the full link at https://i.postimg.cc/PqPBFT1J/2018-leleka100-destr-08-06-24.jpg took 0.3706778639998447 seconds to run
8074
8075
Grabbing the full link at https://i.postimg.cc/8CYkzQ90/2014-leleka100-destr-17-06-24.jpg took 0.3671923769998102 seconds to run
8075
8076
Grabbing the full link at https://i.postimg.cc/htnNVpsc/2000-Leleka-100-reconnaissance-UAV-destr-11-06-24.jpg took 0.363625822999893 seconds to run
8076
8077
Grabbing the full link at https://i.postimg.cc/vBcrBFKF/2016-Leleka-100-reconnaissance-UAV-destr-05-02-24.jpg took 0.36595622999993793 seconds to run
8077
8078
Grabbing the full link at https://i.postimg.cc/hGqy9ySp/2012-Leleka-100-reconnaissance-UAV-destr-23-07-24.jpg took 0.3695230339999398 seconds to run
8078
8079
Grabbing the full link at https://i.postimg.cc/ZqFfj8nZ/2013-Leleka-100-reconnaissance-UAV-destr-23-07-24.jpg took 0.38057857300009346 seconds to run
8079
8080
Grabbing the full link at https://i.postimg.cc/PxXS7CvD/2014-Leleka-100-reconnaissance-UAV-destr-23-07-24.jpg took 0.37540265700044984 seconds to run
8080
8081
Grabbing the full link at https://i.postimg.cc/3RktQwWk/2004-Leleka-100-reconnaissance-UAV-destr-23-08-24.jpg took 0.3790360940001847 seconds to run
8081
8082
Grabbing the full link at https://i.postimg.cc/8c4yhBSj/2002-Leleka-100-reconnaissance-UAV-destr-10-07-24.jpg took 0.368505704999734 seconds to run
8082
8083
Grabbing the full link at https://i.postimg.cc/hGsCd6Wt/2022-Leleka-100-reconnaissance-UAV-destr-09-09-24.jpg took 0.3639325269996334 seconds to run
8083
8084
Grabbing the full link at https://i.postimg.cc/C53NHn10/2013-Leleka-100-reconnaissance-UAV-destr-21-04-24.jpg took 0.3837204159999601 seconds to run
8084
8085
Grabbing the full link at https://i.postimg.cc/xjMwB3KM/2033-Leleka-100-reconnaissance-UAV-destr-30-09-24.jpg took 0.367425121999986 seconds to run
8085
8086
Grabbing the full link at https://i.postimg.cc/76ZQ4TkJ/2022-Leleka-100-reconnaissance-UAV-destr-01-12-23.jpg took 0.37809282800026267 seconds to run
8086
8087
Grabbing the full link at https://i.postimg.cc/Hk0kkQYn/2118-Leleka-100-reconnaissance-UAV-destr-20-10-24.jpg took 0.36906214699956763 seconds to run
8087
8088
Grabbing the full link at https://i.postimg.cc/9fJ0byLh/2023-Leleka-100-reconnaissance-UAV-destr-12-11-24.jpg took 0.3649656950001372 seconds to run
8088
8089
Grabbing the full link at https://i.postimg.cc/hvQBYrG2/2004-Leleka-100-reconnaissance-UAV-destr-13-11-24.jpg took 0.3671591800002716 seconds to run
8089
8090
Grabbing the full link at https://i.postimg.cc/52B3MsgX/2020-Leleka-100-reconnaissance-UAV-destr-03-12-24.jpg took 0.3748544989994116 seconds to run
8090
8091
Grabbing the full link at https://i.postimg.cc/rwyfvyND/2008-Leleka-100-reconnaissance-UAV-destr-25-11-24.jpg took 0.36929359900022973 seconds to run
8091
8092
Grabbing the full link at https://i.postimg.cc/255TXw0X/2008-Leleka-100-reconnaissance-UAV-destr-03-12-24.jpg took 0.3695298680004271 seconds to run
8092
8093
Grabbing the full link at https://i.postimg.cc/k46s753Q/2009-Leleka-100-reconnaissance-UAV-destr-10-12-24.jpg took 0.36435514599997987 seconds to run
8093
8094
Grabbing the full link at https://i.postimg.cc/MGrtkQ4Z/2010-Leleka-100-reconnaissance-UAV-destr-07-03-24.jpg took 0.38482497699988016 seconds to run
8094
8095
Grabbing the full link at https://i.postimg.cc/Rh3gcRQB/2006-Leleka-100-reconnaissance-UAV-destr-06-11-24.jpg took 0.38167195500045636 seconds to run
8095
8096
Grabbing the full link at https://i.postimg.cc/pXc0qmyR/2023-Leleka-100-reconnaissance-UAV-destr-15-12-24.jpg took 0.37643928199941 seconds to run
8096
8097
Grabbing the full link at https://i.postimg.cc/W1Q5cxMy/2024-Leleka-100-reconnaissance-UAV-destr-26-12-24.jpg took 0.40175072099918907 seconds to run
8097
8098
Grabbing the full link at https://i.postimg.cc/hGt9CQbm/2054-Leleka-100-reconnaissance-UAV-destr-21-03-25.jpg took 0.3713261209995835 seconds to run
8098
8099
Grabbing the full link at https://i.postimg.cc/rpN49bKT/2031-Leleka-100-reconnaissance-UAV-destr-18-04-24.jpg took 0.38187191099950724 seconds to run
8099
8100
Grabbing the full link at https://i.postimg.cc/3wPBw7nk/2020-Leleka-100-reconnaissance-UAV-destr-19-11-24.jpg took 0.3734237779999603 seconds to run
8100
8101
Grabbing the full link at https://i.postimg.cc/GtWxDzxP/2000-Leleka-100-reconnaissance-UAV-destr-19-02-25.jpg took 0.36455697899964434 seconds to run
8101
8102
Grabbing the full link at https://i.postimg.cc/MTsLkVtZ/2014-Leleka-100-reconnaissance-UAV-destr-26-03-25.jpg took 0.36289969100016606 seconds to run
8102
8103
Grabbing the full link at https://i.postimg.cc/7h3qqXVs/2031-Leleka-100-reconnaissance-UAV-destr-18-06-25.jpg took 0.3657194839997828 seconds to run
8103
8104
Grabbing the full link at https://i.postimg.cc/KYNx5MMQ/2001-Leleka-100-reconnaissance-UAV-destr-20-04-25.jpg took 0.3651469079995877 seconds to run
8104
8105
Grabbing the full link at https://i.postimg.cc/GmqtDQjp/2014-Leleka-100-reconnaissance-UAV-destr-13-04-25.jpg took 0.3761539300003278 seconds to run
8105
8106
Grabbing the full link at https://i.postimg.cc/Nj2txW1y/d4.png took 0.3705177519996141 seconds to run

Connecting to https://i.postimg.cc/Nj2txW1y/d4.png ...
Downloading d4.png ...
[==================================================] 100.00%

OCR returns: 258|EnAK"Neneka-100"|KoAKoMnnekTy:|3aBOACbKMA N 058/20/258/259/260|5nJA"enexa-100" Ne258|AaTa BMFOTOBAEHH9:O1.1O.2020|07/3/2022
Running OCR on https://i.postimg.cc/Nj2txW1y/d4.png took 24.26591835199997 seconds to run
8106
8107
Grabbing the full link at https://i.postimg.cc/J7NmcVwY/6653.jpg took 0.36608518000048207 seconds to run

Connecting to https://i.postimg.cc/J7NmcVwY/6653.jpg ...
Downloading 6653.jpg ...
[==================================================] 100.00%

OCR returns: 09.03.2022|11
Running OCR on https://i.postimg.cc/J7NmcVwY/6653.jpg took 27.74167358900013 seconds to run
8107
8108
Grabbing the full link at https://i.postimg.cc/zXvjPkVf/3333.png took 0.3730234790000395 seconds to run

Connecting to https://i.postimg.cc/zXvjPkVf/3333.png ...
Downloading 3333.png ...
[==================================================] 100.00%

OCR returns: 25/9/2022|SaHOOpea
Running OCR on https://i.postimg.cc/zXvjPkVf/3333.png took 14.465434046000155 seconds to run
8108
8109
Grabbing the full link at https://i.postimg.cc/90K79qWy/4436.png took 0.36344611200001964 seconds to run

Connecting to https://i.postimg.cc/90K79qWy/4436.png ...
Downloading 4436.png ...
[==================================================] 100.00%

OCR returns: 10/9/2022
Running OCR on https://i.postimg.cc/90K79qWy/4436.png took 13.609613229000388 seconds to run
8109
8110
Grabbing the full link at https://i.postimg.cc/SNqzgSD3/2000-Leleka-uav-dam-capt.jpg took 0.37323614599972643 seconds to run

Connecting to https://i.postimg.cc/SNqzgSD3/2000-Leleka-uav-dam-capt.jpg ...
Downloading 2000-Leleka-uav-dam-capt.jpg ...
[==================================================] 100.00%

OCR returns: 23.11.2022
Running OCR on https://i.postimg.cc/SNqzgSD3/2000-Leleka-uav-dam-capt.jpg took 14.651879166999606 seconds to run
8110
8111
Grabbing the full link at https://i.postimg.cc/FRVDWQVs/2002-Leleka-100-capt-31-01-23.jpg took 0.3727488700005779 seconds to run
8111
8112
Grabbing the full link at https://i.postimg.cc/cJ6LRknm/2010-Leleka-100-reconnaissance-UAV-capt-27-09-22.jpg took 0.36675640100020246 seconds to run
8112
8113
Grabbing the full link at https://i.postimg.cc/fLHQR4t7/g7.png took 0.3617622269994172 seconds to run

Connecting to https://i.postimg.cc/fLHQR4t7/g7.png ...
Downloading g7.png ...
[==================================================] 100.00%

OCR returns: 01/4/2023
Running OCR on https://i.postimg.cc/fLHQR4t7/g7.png took 16.317805973999384 seconds to run
8113
8114
Grabbing the full link at https://i.postimg.cc/Kzdtp6Db/446.png took 0.3759409499998583 seconds to run

Connecting to https://i.postimg.cc/Kzdtp6Db/446.png ...
Downloading 446.png ...
[==================================================] 100.00%

OCR returns: 07/4/2023|M|M|mash|mash
Running OCR on https://i.postimg.cc/Kzdtp6Db/446.png took 20.317581520000203 seconds to run
8114
8115
Grabbing the full link at https://i.postimg.cc/qRtfThq9/2013-leleka100-capt-31-05-23.jpg took 0.36553086299954884 seconds to run
8115
8116
Grabbing the full link at https://i.postimg.cc/KvxprSfW/2024-leleka100-capt-04-06-23.jpg took 0.3681938950003314 seconds to run
8116
8117
Grabbing the full link at https://i.postimg.cc/BQ9Jm2kh/2005-leleka-100-uav-05-07-22.jpg took 0.3761796859998867 seconds to run
8117
8118
Grabbing the full link at https://i.postimg.cc/xCxQ5VSb/2006-leleka100-capt-16-01-23.jpg took 0.3730133669996576 seconds to run
8118
8119
Grabbing the full link at https://i.postimg.cc/J0B2JD2V/2009-Leleka-100-UAV-capt-29-01-24.jpg took 0.3621428019996529 seconds to run
8119
8120
Grabbing the full link at https://i.postimg.cc/NfHwymxt/2002-leleka100-capt-11-02-24.jpg took 0.3719849460003388 seconds to run
8120
8121
Grabbing the full link at https://i.postimg.cc/mD50kgzh/2007-leleka100-capt-12-02-24.jpg took 0.3746957390003445 seconds to run
8121
8122
Grabbing the full link at https://i.postimg.cc/QCRDc4Tx/2024-Leleka-100-reconnaissance-UAV-capt-23-02-24.jpg took 0.3782251760003419 seconds to run
8122
8123
Grabbing the full link at https://i.postimg.cc/pd2HQnp8/2010-Leleka-100-reconnaissance-UAV-capt-25-02-24.jpg took 0.3863637700005711 seconds to run
8123
8124
Grabbing the full link at https://i.postimg.cc/X7xHXc8S/2005-leleka100-capt-24-02-24.jpg took 0.3760292639999534 seconds to run
8124
8125
Grabbing the full link at https://i.postimg.cc/mr18XxGB/2021-leleka100-capt-02-03-24.jpg took 0.38220919800005504 seconds to run
8125
8126
Grabbing the full link at https://i.postimg.cc/fTzXnfmy/2006-leleka100-capt-16-03-24.jpg took 0.38071170300008816 seconds to run
8126
8127
Grabbing the full link at https://i.postimg.cc/kX10H7YK/2011-leleka100-capt-05-04-24.jpg took 0.4014132600004814 seconds to run
8127
8128
Grabbing the full link at https://i.postimg.cc/CL9TK0qB/2012-Leleka-100-reconnaissance-UAV-capt-31-05-24.jpg took 0.3923259170005622 seconds to run
8128
8129
Grabbing the full link at https://i.postimg.cc/nhKkfzYg/2005-leleka100-capt-21-06-24.jpg took 0.4256779040006222 seconds to run
8129
8130
Grabbing the full link at https://i.postimg.cc/d13mC9Pc/2007-leleka100-capt-21-06-24.jpg took 0.3761471289999463 seconds to run
8130
8131
Grabbing the full link at https://i.postimg.cc/yxgK53vc/2006-Leleka-100-reconnaissance-UAV-capt-26-06-24.jpg took 0.3636854169999424 seconds to run
8131
8132
Grabbing the full link at https://i.postimg.cc/NGNzWk4j/2006-Leleka-100-reconnaissance-UAV-capt-24-07-24.jpg took 0.3653545919996759 seconds to run
8132
8133
Grabbing the full link at https://i.postimg.cc/sxfK6sys/2028-Leleka-100-reconnaissance-UAV-capt-06-09-24.jpg took 0.37726063300033275 seconds to run
8133
8134
Grabbing the full link at https://i.postimg.cc/d1wQ3QYQ/2021-Leleka-100-reconnaissance-UAV-capt-14-09-24.jpg took 0.39409519199944043 seconds to run
8134
8135
Grabbing the full link at https://i.postimg.cc/WzDWFLt2/2004-Leleka-100-reconnaissance-UAV-capt-29-09-24.jpg took 0.36828654700002517 seconds to run
8135
8136
Grabbing the full link at https://i.postimg.cc/k5nTNtDY/2096-Leleka-100-reconnaissance-UAV-capt-18-10-24.jpg took 0.37477606999982527 seconds to run
8136
8137
Grabbing the full link at https://i.postimg.cc/s20QXKTy/2125-Leleka-100-reconnaissance-UAV-capt-21-10-24.jpg took 0.37523727900043014 seconds to run
8137
8138
Grabbing the full link at https://i.postimg.cc/tg9zRFv2/2035-Leleka-100-reconnaissance-UAV-capt-01-12-24.jpg took 0.40442306000022654 seconds to run
8138
8139
Grabbing the full link at https://i.postimg.cc/3RRCmYTG/2036-Leleka-100-reconnaissance-UAV-capt-01-12-24.jpg took 0.45682185599980585 seconds to run
8139
8140
Grabbing the full link at https://i.postimg.cc/MTjjDckW/2010-Leleka-100-reconnaissance-UAV-capt-22-11-24.jpg took 0.5182957679999163 seconds to run
8140
8141
Grabbing the full link at https://i.postimg.cc/g0RW3C8R/2001-Leleka-100-reconnaissance-UAV-capt-01-01-25.jpg took 0.5200457729997652 seconds to run
8141
8142
Grabbing the full link at https://i.postimg.cc/8PKNGBTF/2020-Leleka-100-reconnaissance-UAV-capt-30-12-24.jpg took 1.4728730870001527 seconds to run
8142
8143
Grabbing the full link at https://i.postimg.cc/PxFkk3jJ/2003-Leleka-100-reconnaissance-UAV-capt-17-01-25.jpg took 0.39707856199947855 seconds to run
8143
8144
Grabbing the full link at https://i.postimg.cc/YCQ9zbtX/2027-Leleka-100-reconnaissance-UAV-capt-16-01-25.jpg took 0.3668477889996211 seconds to run
8144
8145
Grabbing the full link at https://i.postimg.cc/J4y09pwp/2034-Leleka-100-reconnaissance-UAV-capt-06-02-25.jpg took 0.3609322010006508 seconds to run
8145
8146
Grabbing the full link at https://i.postimg.cc/NG3VL3gC/2023-Leleka-100-reconnaissance-UAV-capt-12-11-24.jpg took 0.37677681599961943 seconds to run
8146
8147
Grabbing the full link at https://i.postimg.cc/L8qx7mZf/2017-Leleka-100-reconnaissance-UAV-capt-13-01-25.jpg took 0.36395344199991086 seconds to run
8147
8148
Grabbing the full link at https://i.postimg.cc/6qcTb68h/2015-Leleka-100-reconnaissance-UAV-capt-25-03-25.jpg took 0.38234100899990153 seconds to run
8148
8149
Grabbing the full link at https://i.postimg.cc/1Rq7TyZC/2000-Leleka-100-reconnaissance-UAV-capt-30-06-24.jpg took 0.4532214760001807 seconds to run
8149
8150
Grabbing the full link at https://i.postimg.cc/6qnHGf0J/2020-Leleka-100-reconnaissance-UAV-capt-12-09-24.jpg took 0.36770752699976583 seconds to run
8150
8151
Grabbing the full link at https://i.postimg.cc/7ZFW314r/2001-Leleka-100-reconnaissance-UAV-capt-04-03-25.jpg took 0.3729902579998452 seconds to run
8151
8152
Grabbing the full link at https://i.postimg.cc/s250wBfQ/2011-Leleka-100-reconnaissance-UAV-capt-12-03-25.jpg took 0.3692793160007568 seconds to run
8152
8153
Grabbing the full link at https://i.postimg.cc/KjSZXCn3/2030-Leleka-100-reconnaissance-UAV-capt-25-06-25.jpg took 0.41093426999941585 seconds to run
8153
8154
Grabbing the full link at https://i.postimg.cc/7LDq7Vff/2005-Leleka-100-reconnaissance-UAV-capt-04-07-25.jpg took 0.37300799900003767 seconds to run
8154
8155
Grabbing the full link at https://i.postimg.cc/JnBz9WCy/2000-Leleka-100-reconnaissance-UAV-capt-15-05-25.jpg took 0.3680924079999386 seconds to run
8155
8156
Grabbing the full link at https://i.postimg.cc/J0gGF0Fp/2002-Leleka-100-reconnaissance-UAV-capt-02-07-25.jpg took 0.36845586500021454 seconds to run
8156
8157
Grabbing the full link at https://i.postimg.cc/DzjqqfnM/2019-Leleka-LR-UAV-destr-15-07-23.jpg took 0.3801055100002486 seconds to run
8157
8158
Grabbing the full link at https://i.postimg.cc/zf1snkpq/2011-Leleka-LR-reconnaissance-UAV-destr-31-05-24.jpg took 0.3626252439999007 seconds to run
8158
8159
Grabbing the full link at https://i.postimg.cc/qMw35Ft5/2049-Leleka-LR-reconnaissance-UAV-destr-13-11-24.jpg took 0.375040762000026 seconds to run
8159
8160
Grabbing the full link at https://i.postimg.cc/LXYBLRWz/2026-Leleka-LR-reconnaissance-UAV-destr-02-06-25.jpg took 0.3821687560002829 seconds to run
8160
8161
Grabbing the full link at https://i.postimg.cc/wvZjm9Gm/2029-Spaitech-Sparrow-reconnaissance-UAV-destr-13-07-23.jpg took 0.3688879249993988 seconds to run
8161
8162
Grabbing the full link at https://i.postimg.cc/D090Ds6d/d138.jpg took 0.3636311019999994 seconds to run

Connecting to https://i.postimg.cc/D090Ds6d/d138.jpg ...
Downloading d138.jpg ...
[==================================================] 100.00%

OCR returns: T.ME/VOENACHER|06.05.2022
Running OCR on https://i.postimg.cc/D090Ds6d/d138.jpg took 10.001428999999916 seconds to run
8162
8163
Grabbing the full link at https://i.postimg.cc/qBDxh1tk/2001-Spaitech-Sparrow-UAV-capt-28-10-22.jpg took 0.3849763240004904 seconds to run
8163
8164
Grabbing the full link at https://i.postimg.cc/3rvkZSxF/2012-Spaitech-Sparrow-UAV-capt-19-06-23.jpg took 0.4194667430001573 seconds to run
8164
8165
Grabbing the full link at https://i.postimg.cc/dQG4GwTW/2001-Spectator-M1.jpg took 0.4087978369998382 seconds to run

Connecting to https://i.postimg.cc/dQG4GwTW/2001-Spectator-M1.jpg ...
Downloading 2001-Spectator-M1.jpg ...
[==================================================] 100.00%

OCR returns: 01.08.2022
Running OCR on https://i.postimg.cc/dQG4GwTW/2001-Spectator-M1.jpg took 13.555946588000552 seconds to run
8165
8166
Grabbing the full link at https://i.postimg.cc/qvn7k9zZ/5546.png took 0.3835914809997121 seconds to run

Connecting to https://i.postimg.cc/qvn7k9zZ/5546.png ...
Downloading 5546.png ...
[==================================================] 100.00%

OCR returns: 45OKPEMAAPTNNEPICbKABPNTAAA|3SPOHICUNNYKPAIHN|05/6/2022|酒
Running OCR on https://i.postimg.cc/qvn7k9zZ/5546.png took 29.160878914000023 seconds to run
8166
8167
Grabbing the full link at https://i.postimg.cc/2yMzL2QS/2005-Spectator-M1-reconnaissance-UAV-destr-17-05-23.jpg took 0.368343296000603 seconds to run
8167
8168
Grabbing the full link at https://i.postimg.cc/MGsfYGk2/2000-Spectator-M1-uav-destr-29-12-23.jpg took 0.4018558550005764 seconds to run
8168
8169
Grabbing the full link at https://i.postimg.cc/TwfHPPLT/55.png took 0.39291489199968055 seconds to run

Connecting to https://i.postimg.cc/TwfHPPLT/55.png ...
Downloading 55.png ...
[==================================================] 100.00%

OCR returns: 20|12/6/2022|t:me/razved_dozor
Running OCR on https://i.postimg.cc/TwfHPPLT/55.png took 27.156139606999204 seconds to run
8169
8170
Grabbing the full link at https://i.postimg.cc/mk5GB7Ff/5.png took 0.3764048069997443 seconds to run

Connecting to https://i.postimg.cc/mk5GB7Ff/5.png ...
Downloading 5.png ...
[==================================================] 100.00%

OCR returns: 18/6/2023
Running OCR on https://i.postimg.cc/mk5GB7Ff/5.png took 13.258631892999801 seconds to run
8170
8171
Grabbing the full link at https://i.postimg.cc/nhffqrdD/2004-PD-1-multipurpose-UAV-destr-14-02-24.jpg took 0.9255305779997798 seconds to run
8171
8172
Returning non-postimg link
8172
8173
Grabbing the full link at https://i.postimg.cc/P5bsyHcF/2005-PD-1-multipurpose-UAV-destr-14-02-24.jpg took 0.4419406400002117 seconds to run
8173
8174
Grabbing the full link at https://i.postimg.cc/vZj7fZLZ/2013-PD-2-UAV-destr-29-03-24.jpg took 0.44376600500072527 seconds to run
8174
8175
Grabbing the full link at https://i.postimg.cc/59D7MfKX/3351.png took 0.38754144699942117 seconds to run

Connecting to https://i.postimg.cc/59D7MfKX/3351.png ...
Downloading 3351.png ...
[==================================================] 100.00%

OCR returns: 24/3/2022|UJ-22 AIRBORNE|RusVesna SU|RVvoenkor|ullan|SSRC-S00C.1
Running OCR on https://i.postimg.cc/59D7MfKX/3351.png took 20.90668714700041 seconds to run
8175
8176
Returning non-postimg link
8176
8177
Grabbing the full link at https://i.postimg.cc/yxh11wMV/2004-ITEC-Skif-YAV-destr-18-02-23.jpg took 0.4177250669999921 seconds to run
8177
8178
Grabbing the full link at https://i.postimg.cc/VkYLWdF1/2014-ITEC-Skif-UAV-destr-03-05-23.jpg took 0.37823579399992013 seconds to run
8178
8179
Grabbing the full link at https://i.postimg.cc/QtTW1shW/2014-Skif-uav-destr-26-12-23.jpg took 0.3973282320002909 seconds to run
8179
8180
Returning non-postimg link
8180
8181
Grabbing the full link at https://i.postimg.cc/7h8JQxDS/2013-Mini-Shark-reconnaissance-UAV-destr-20-11-24.jpg took 0.394147650999912 seconds to run
8181
8182
Grabbing the full link at https://i.postimg.cc/GmkyzDPt/2016-Shark-M-reconnaissance-UAV-destr-10-03-25.jpg took 0.40300819399999455 seconds to run
8182
8183
Returning non-postimg link
8183
8184
Returning non-postimg link
8184
8185
Grabbing the full link at https://i.postimg.cc/Qd0CMvfh/2023-UAV-Shark-destr-27-06-23.jpg took 0.37068842699954985 seconds to run
8185
8186
Grabbing the full link at https://i.postimg.cc/vmxpDV1W/2003-Shark-destr-26-08-23.jpg took 0.3920052850007778 seconds to run
8186
8187
Grabbing the full link at https://i.postimg.cc/xdw17WYh/2008-Shark-uav-destr-31-10-23.jpg took 0.3668680540004061 seconds to run
8187
8188
Grabbing the full link at https://i.postimg.cc/XJG3FsWY/2002-shark-uav-destr-26-11-23.jpg took 0.3730355210000198 seconds to run
8188
8189
Grabbing the full link at https://i.postimg.cc/ZR291DKw/2012-Shark-UAV-destr-24-12-23.jpg took 0.37693659600063256 seconds to run
8189
8190
Grabbing the full link at https://i.postimg.cc/6QZRtxhT/2003-shark-uav-destr-21-05-24.jpg took 0.36108176699963224 seconds to run
8190
8191
Grabbing the full link at https://i.postimg.cc/FsvXstXC/2015-Shark-reconnaissance-UAV-destr-08-06-24.jpg took 0.37789101199996367 seconds to run
8191
8192
Grabbing the full link at https://i.postimg.cc/1zFprHTY/2006-Shark-reconnaissance-UAV-destr-04-07-24.jpg took 0.3809219579998171 seconds to run
8192
8193
Grabbing the full link at https://i.postimg.cc/MZQVt0QM/2001-Shark-reconnaissance-UAV-destr-17-05-24.jpg took 0.3970703670001967 seconds to run
8193
8194
Grabbing the full link at https://i.postimg.cc/Y9xQn3FZ/2014-Shark-reconnaissance-UAV-destr-19-07-24.jpg took 0.39408720699975675 seconds to run
8194
8195
Grabbing the full link at https://i.postimg.cc/Dz9dz5wZ/2000-Shark-reconnaissance-UAV-destr-23-07-24.jpg took 0.3759501360000286 seconds to run
8195
8196
Grabbing the full link at https://i.postimg.cc/QM2DdqQp/2008-Shark-reconnaissance-UAV-destr-27-07-24.jpg took 0.37355516200022976 seconds to run
8196
8197
Grabbing the full link at https://i.postimg.cc/506q8vTx/2000-Shark-reconnaissance-UAV-destr-07-08-24.jpg took 0.9878339389997564 seconds to run
8197
8198
Grabbing the full link at https://i.postimg.cc/0NWV4S5g/2010-Shark-reconnaissance-UAV-destr-12-08-24.jpg took 0.36611641099989356 seconds to run
8198
8199
Grabbing the full link at https://i.postimg.cc/bJQVvfV0/2001-Shark-reconnaissance-UAV-destr-28-08-24.jpg took 0.36216177300048 seconds to run
8199
8200
Grabbing the full link at https://i.postimg.cc/MZnJ5kT3/2008-Shark-reconnaissance-UAV-destr-12-09-24.jpg took 0.3584222170002249 seconds to run
8200
8201
Grabbing the full link at https://i.postimg.cc/bvPvS8Z5/2043-Shark-D-reconnaissance-UAV-destr-23-09-24.jpg took 0.3771710270002586 seconds to run
8201
8202
Grabbing the full link at https://i.postimg.cc/wM0Zfyyf/2011-Shark-D-reconnaissance-UAV-destr-21-03-25.jpg took 0.37720469499981846 seconds to run
8202
8203
Grabbing the full link at https://i.postimg.cc/KjZCDrz3/2025-Shark-D-reconnaissance-UAV-destr-25-03-25.jpg took 0.37529633100075444 seconds to run
8203
8204
Grabbing the full link at https://i.postimg.cc/7hH0WNwX/2003-Shark-D-reconnaissance-UAV-destr-12-04-25.jpg took 0.36787912199997663 seconds to run
8204
8205
Grabbing the full link at https://i.postimg.cc/7Ymf7sbT/2000-Shark-D-reconnaissance-UAV-destr-16-03-25.jpg took 0.36634171799960313 seconds to run
8205
8206
Grabbing the full link at https://i.postimg.cc/nVd8VWCg/35.png took 0.36245284599954175 seconds to run

Connecting to https://i.postimg.cc/nVd8VWCg/35.png ...
Downloading 35.png ...
[==================================================] 100.00%

OCR returns: 05/1/2023
Running OCR on https://i.postimg.cc/nVd8VWCg/35.png took 24.968095449999964 seconds to run
8206
8207
Grabbing the full link at https://i.postimg.cc/QMx6Sm3k/2033-Shark-reconnaissance-UAV-capt-24-08-24.jpg took 0.5063103889997365 seconds to run
8207
8208
Grabbing the full link at https://i.postimg.cc/pXXfBf4W/2012-Shark-D-reconnaissance-UAV-capt-21-01-25.jpg took 0.43854749599995557 seconds to run
8208
8209
Grabbing the full link at https://i.postimg.cc/MZVBHcj8/2027-Shark-D-reconnaissance-UAV-capt-06-05-25.jpg took 0.3798125910007002 seconds to run
8209
8210
Grabbing the full link at https://i.postimg.cc/dt14Bpkw/2028-Mara-2-M-capt-03-02-23.jpg took 0.3952512839996416 seconds to run
8210
8211
Grabbing the full link at https://i.postimg.cc/bwndCsyc/2005-Mara-M2-reconnaissance-UAV-destr-01-05-23.jpg took 0.3818183359999239 seconds to run
8211
8212
Grabbing the full link at https://i.postimg.cc/mhf6SLvc/2007-Mara-2-M-UAV-destr-25-01-24.jpg took 0.3783960999999181 seconds to run
8212
8213
Grabbing the full link at https://i.postimg.cc/66MhFmjB/2002-Mara-2-M-reconnaissance-UAV-destr-09-04-24.jpg took 0.42444259600051737 seconds to run
8213
8214
Grabbing the full link at https://i.postimg.cc/sfPKcvf9/2017-Mara-2-M-reconnaissance-UAV-destr-15-04-24.jpg took 0.40675574700071593 seconds to run
8214
8215
Grabbing the full link at https://i.postimg.cc/76d19hrS/2009-Mara-2-M-reconnaissance-UAV-destr-27-04-24.jpg took 0.4612687230001029 seconds to run
8215
8216
Grabbing the full link at https://i.postimg.cc/Dz9q2t3S/t43.png took 0.9669153559998449 seconds to run

Connecting to https://i.postimg.cc/Dz9q2t3S/t43.png ...
Downloading t43.png ...
[==================================================] 100.00%

OCR returns: 10/6/2023|工
Running OCR on https://i.postimg.cc/Dz9q2t3S/t43.png took 15.101679876000162 seconds to run
8216
8217
Grabbing the full link at https://i.postimg.cc/kg7qmqnK/2009-Mara-2-M-UAV-capt-06-10-23.jpg took 0.36691713799973513 seconds to run
8217
8218
Grabbing the full link at https://i.postimg.cc/FHXmR6vT/2022-Mara-2-M-UAV-capt-24-02-24.jpg took 0.3974646169999687 seconds to run
8218
8219
Grabbing the full link at https://i.postimg.cc/PrDhQZLk/2013-Mara-2-M-reconnaissance-UAV-capt-02-07-24.jpg took 0.5164015950003886 seconds to run
8219
8220
Grabbing the full link at https://i.postimg.cc/Z5mRt1Q2/2001-Chaklun-reconnaissance-UAV-destr-26-05-23.jpg took 0.4155226689999836 seconds to run
8220
8221
Grabbing the full link at https://i.postimg.cc/TYZCvCmf/438.png took 0.48683768499995494 seconds to run

Connecting to https://i.postimg.cc/TYZCvCmf/438.png ...
Downloading 438.png ...
[==================================================] 100.00%

OCR returns: 07/8/2023
Running OCR on https://i.postimg.cc/TYZCvCmf/438.png took 12.114327135000167 seconds to run
8221
8222
Grabbing the full link at https://i.postimg.cc/pL4sSnbR/2029-Elf-uav-destr-03-12-23.jpg took 0.3694381229997816 seconds to run
8222
8223
Grabbing the full link at https://i.postimg.cc/pL4sSnbR/2029-Elf-uav-destr-03-12-23.jpg took 0.3659686689998125 seconds to run
8223
8224
Grabbing the full link at https://i.postimg.cc/QNPjLtyG/2008-Raybird-3-ACS-3-destr-21-02-24.jpg took 0.3671185989996957 seconds to run
8224
8225
Grabbing the full link at https://i.postimg.cc/9XttWd5m/2009-Raybird-3-ACS-3-reconnaissance-UAV-destr-27-07-24.jpg took 0.3589401640001597 seconds to run
8225
8226
Grabbing the full link at https://i.postimg.cc/BnvK9CHQ/2019-Raybird-3-ACS-3-reconnaissance-UAV-destr-20-10-24.jpg took 0.3663108500004455 seconds to run
8226
8227
Grabbing the full link at https://i.postimg.cc/CLzB46Jh/2000-Ares-UAV-destr-31-01-24.jpg took 0.3659493739996833 seconds to run
8227
8228
Grabbing the full link at https://i.postimg.cc/QMWghjxQ/2009-Hor-UAV-destr-26-04-24.jpg took 0.3744112340000356 seconds to run
8228
8229
Grabbing the full link at https://i.postimg.cc/P5b68Mf8/2092-Hor-reconnaissance-UAV-destr-08-10-24.jpg took 0.41889372500008903 seconds to run
8229
8230
Grabbing the full link at https://i.postimg.cc/KYxgWYQN/2148-Hor-reconnaissance-UAV-capt-13-03-25.jpg took 0.3827555220004797 seconds to run
8230
8231
Grabbing the full link at https://i.postimg.cc/pybm6VjP/2066-Hor-reconnaissance-UAV-capt-02-04-25.jpg took 0.3717876319997231 seconds to run
8231
8232
Returning non-postimg link
8232
8233
Grabbing the full link at https://i.postimg.cc/wBLx24Rt/3.png took 0.3654181289994085 seconds to run

Connecting to https://i.postimg.cc/wBLx24Rt/3.png ...
Downloading 3.png ...
[==================================================] 100.00%

OCR returns: 18/6/2023
Running OCR on https://i.postimg.cc/wBLx24Rt/3.png took 23.43336960800025 seconds to run
8233
8234
Grabbing the full link at https://i.postimg.cc/RCTvb0T1/2000-Primoco-One-150-UAV-destr-21-08-23.jpg took 0.3850979909993839 seconds to run
8234
8235
Grabbing the full link at https://i.postimg.cc/NMR82TKx/2008-Primoco-ONE-150-reconnaissance-UAV-destr-27-07-24.jpg took 0.3680408910004189 seconds to run
8235
8236
Grabbing the full link at https://i.postimg.cc/x8mv4Q9h/2010-Primoco-ONE-150-reconnaissance-UAV-destr-06-08-24.jpg took 0.3593101989999923 seconds to run
8236
8237
Grabbing the full link at https://i.postimg.cc/R008sKJv/6599.png took 0.3792485289995966 seconds to run

Connecting to https://i.postimg.cc/R008sKJv/6599.png ...
Downloading 6599.png ...
[==================================================] 100.00%

OCR returns: 07/6/2022|7|POCTBRPAHR|10.4K views|0:07/0:53
Running OCR on https://i.postimg.cc/R008sKJv/6599.png took 28.048251193000397 seconds to run
8237
8238
Grabbing the full link at https://i.postimg.cc/nrJ9rVL3/588.png took 0.3710581360001015 seconds to run

Connecting to https://i.postimg.cc/nrJ9rVL3/588.png ...
Downloading 588.png ...
[==================================================] 100.00%

OCR returns: 22/6/2022
Running OCR on https://i.postimg.cc/nrJ9rVL3/588.png took 16.804924175999986 seconds to run
8238
8239
Grabbing the full link at https://i.postimg.cc/8CQ5sDsg/76jj.png took 0.36585323700001027 seconds to run

Connecting to https://i.postimg.cc/8CQ5sDsg/76jj.png ...
Downloading 76jj.png ...
[==================================================] 100.00%

OCR returns: 2023-06-0614：29：42|TIB|05-13
Running OCR on https://i.postimg.cc/8CQ5sDsg/76jj.png took 15.402212019000217 seconds to run
8239
8240
Grabbing the full link at https://i.postimg.cc/SQWKFZ60/2017-flyeye-UAV-destr-30-09-23.jpg took 0.3646364119995269 seconds to run
8240
8241
Grabbing the full link at https://i.postimg.cc/D0v0xdBX/2000-Fly-Eye-UAV-destr-25-10-23.jpg took 0.36906090899992705 seconds to run
8241
8242
Grabbing the full link at https://i.postimg.cc/ZnPTTX0r/2000-Fly-Eye-UAV-destr-06-11-23.jpg took 0.3632211929998448 seconds to run
8242
8243
Grabbing the full link at https://i.postimg.cc/7hYd4C3R/2014-Fly-Eye-UAV-destr-30-10-23.jpg took 0.36504396599957545 seconds to run
8243
8244
Grabbing the full link at https://i.postimg.cc/fTzvhFRD/2030-Fly-Eye-reconnaissance-UAV-destr-18-02-24.jpg took 0.36268838300020434 seconds to run
8244
8245
Grabbing the full link at https://i.postimg.cc/3JnFZLcv/2022-Fly-Eye-UAV-destr-02-05-24.jpg took 0.36410225800045737 seconds to run
8245
8246
Grabbing the full link at https://i.postimg.cc/C5WhSn8t/2008-Fly-Eye-reconnaissance-UAV-destr-08-05-24.jpg took 0.36365361499974824 seconds to run
8246
8247
Grabbing the full link at https://i.postimg.cc/25zzkDqz/2019-Fly-Eye-UAV-destr-09-05-24.jpg took 0.369236713000646 seconds to run
8247
8248
Grabbing the full link at https://i.postimg.cc/g0cyC6q0/2011-Fly-Eye-reconnaissance-UAV-destr-14-07-24.jpg took 0.3648406190004607 seconds to run
8248
8249
Grabbing the full link at https://i.postimg.cc/0NLXrjGx/2006-Fly-Eye-reconnaissance-UAV-destr-31-01-25.jpg took 0.3658938010003112 seconds to run
8249
8250
Grabbing the full link at https://i.postimg.cc/nhqHC5Vy/2000-Fly-Eye-reconnaissance-UAV-destr-20-04-25.jpg took 0.3746515740003815 seconds to run
8250
Saved at index 8250
8251
Grabbing the full link at https://i.postimg.cc/PJVKQjd4/1000-Flyeye-capt-09-01-2023.png took 0.36730291100047907 seconds to run
8251
8252
Grabbing the full link at https://i.postimg.cc/4yKZ7knS/2021-Fly-Eye-reconnaissance-UAV-capt-24-02-24.jpg took 0.37375517199961905 seconds to run
8252
8253
Grabbing the full link at https://i.postimg.cc/k522GfYK/2016-Fly-Eye-UAV-capt-04-04-24.jpg took 0.3716857190001974 seconds to run
8253
8254
Grabbing the full link at https://i.postimg.cc/mDfsb77d/2004-Fly-Eye-reconnaissance-UAV-capt-26-04-24.jpg took 0.37433328299994173 seconds to run
8254
8255
Grabbing the full link at https://i.postimg.cc/x14Jbjtm/2005-Fly-Eye-reconnaissance-UAV-capt-14-01-25.jpg took 0.3649801080000543 seconds to run
8255
8256
Grabbing the full link at https://i.postimg.cc/X73QYYDM/2002-Fly-Eye-reconnaissance-UAV-capt-10-04-25.jpg took 0.358588365000287 seconds to run
8256
8257
Grabbing the full link at https://i.postimg.cc/KcBG7v2P/2032-Fly-Eye-reconnaissance-UAV-capt-11-04-25.jpg took 0.36567476599975635 seconds to run
8257
8258
Grabbing the full link at https://i.postimg.cc/KYjzDM9D/2001-Fly-Eye-reconnaissance-UAV-capt-15-05-25.jpg took 0.36213288299950364 seconds to run
8258
8259
Grabbing the full link at https://i.postimg.cc/TPsP73FM/2002-Fly-Eye-reconnaissance-UAV-capt-15-05-25.jpg took 0.3759970640003303 seconds to run
8259
8260
Grabbing the full link at https://i.postimg.cc/kGycXhYh/2013-Penguin-C-reconnaissance-UAV-destr-12-04-24.jpg took 0.3666778169999816 seconds to run
8260
8261
Grabbing the full link at https://i.postimg.cc/0NdLZJHD/2016-Penguin-C-reconnaissance-UAV-destr-01-06-24.jpg took 0.3675084060005247 seconds to run
8261
8262
Grabbing the full link at https://i.postimg.cc/7h3vM90N/2009-Penguin-C-reconnaissance-UAV-destr-06-06-24.jpg took 0.3654552400003013 seconds to run
8262
8263
Grabbing the full link at https://i.postimg.cc/vmzSCtpd/2011-Penguin-C-reconnaissance-UAV-destr-09-10-24.jpg took 0.36271932999989076 seconds to run
8263
8264
Grabbing the full link at https://i.postimg.cc/ZKCQ6BwT/355.png took 0.36745078200056014 seconds to run

Connecting to https://i.postimg.cc/ZKCQ6BwT/355.png ...
Downloading 355.png ...
[==================================================] 100.00%

OCR returns: KITAM|SPA|BAYRAKTARTB2|403
Running OCR on https://i.postimg.cc/ZKCQ6BwT/355.png took 27.087675538999974 seconds to run
8264
8265
Grabbing the full link at https://i.postimg.cc/7LfWG39Y/2025-penguin-c-capt-03-06-23.jpg took 0.4036970269999074 seconds to run
8265
8266
Grabbing the full link at https://i.postimg.cc/jdh0D8sx/2000-Penguin-C-reconnaissance-UAV-capt-28-05-24.jpg took 0.39119137699981366 seconds to run
8266
8267
Grabbing the full link at https://i.postimg.cc/j2kRMzJC/2024-Penguin-C-reconnaissance-UAV-capt-14-09-24.jpg took 0.3915423449998343 seconds to run
8267
8268
Grabbing the full link at https://i.postimg.cc/CLnL0W1S/6658.png took 0.3706562870002017 seconds to run

Connecting to https://i.postimg.cc/CLnL0W1S/6658.png ...
Downloading 6658.png ...
[==================================================] 100.00%

OCR returns: 06/4/2023
Running OCR on https://i.postimg.cc/CLnL0W1S/6658.png took 21.948839028000293 seconds to run
8268
8269
Grabbing the full link at https://i.postimg.cc/L6WKdnSb/2003-Poseidon-H10-reconnaissance-UAV-destr03-06-24.jpg took 0.38790200499988714 seconds to run

Connecting to https://i.postimg.cc/L6WKdnSb/2003-Poseidon-H10-reconnaissance-UAV-destr03-06-24.jpg ...
Downloading 2003-Poseidon-H10-reconnaissance-UAV-destr03-06-24.jpg ...
[==================================================] 100.00%

Running OCR on https://i.postimg.cc/L6WKdnSb/2003-Poseidon-H10-reconnaissance-UAV-destr03-06-24.jpg took 13.548909492999883 seconds to run
8269
8270
Grabbing the full link at https://i.postimg.cc/cLQs67rd/2035-EOS-C-VTOL-reconnaissance-UAV-destr-14-05-23.jpg took 0.3800000850005745 seconds to run
8270
8271
Grabbing the full link at https://i.postimg.cc/mrMbdxLM/2007-EOS-C-VTOL-destr-18-11-23.jpg took 0.36874592200001644 seconds to run
8271
8272
Grabbing the full link at https://i.postimg.cc/MZnkyTYX/2002-EOS-C-VTOL-reconnaissance-UAV-capt-21-11-24.jpg took 0.382323685999836 seconds to run
8272
8273
Returning non-postimg link
8273
8274
Grabbing the full link at https://i.postimg.cc/gjM4pq7C/2005-Bayraktar-Mini-capt-31-01-23.jpg took 0.3704356899997947 seconds to run
8274
8275
Grabbing the full link at https://i.postimg.cc/Kcq4y5gV/2004-RQ-20-puma-destr-19-05-23.jpg took 0.37351773099999264 seconds to run
8275
8276
Grabbing the full link at https://i.postimg.cc/fRFvP67D/2040-RQ-20-PUMA-UAV-capt-08-06-23.jpg took 0.404136410999854 seconds to run
8276
8277
Grabbing the full link at https://i.postimg.cc/9f14Kzp2/2008-rq20-puma3ae-destr-11-07-23.jpg took 0.3677415430001929 seconds to run
8277
8278
Grabbing the full link at https://i.postimg.cc/3NjDtPyV/2005-RQ-20-Puma-AE-destr-20-11-23.jpg took 0.3638182870008677 seconds to run
8278
8279
Grabbing the full link at https://i.postimg.cc/fTkLC9Yg/2001-RQ-20-destr-10-12-23.jpg took 0.43272395500025596 seconds to run
8279
8280
Grabbing the full link at https://i.postimg.cc/MHKWW4sr/2000-rq20-uav-destr-16-12-23.jpg took 0.39775481800006673 seconds to run
8280
8281
Grabbing the full link at https://i.postimg.cc/Y07BnwsS/2010-rq20-puma-destr-17-12-23.jpg took 0.3648290569999517 seconds to run
8281
8282
Grabbing the full link at https://i.postimg.cc/4xFsz4HC/2000-rq20-destr-28-01-24.jpg took 0.37788717500006896 seconds to run
8282
8283
Grabbing the full link at https://i.postimg.cc/rsZCWD0D/2003-Aero-Vironment-RQ-20-Puma-reconnaissance-UAV-destr-09-04-24.jpg took 0.3787455970004885 seconds to run
8283
8284
Grabbing the full link at https://i.postimg.cc/CLmN3XqR/2018-Aero-Vironment-RQ-20-Puma-reconnaissance-UAV-destr-14-04-24.jpg took 0.36590464700020675 seconds to run
8284
8285
Grabbing the full link at https://i.postimg.cc/13p794v6/2004-Aero-Vironment-RQ-20-Puma-reconnaissance-UAV-destr-07-09-24.jpg took 0.3604810670003644 seconds to run
8285
8286
Grabbing the full link at https://i.postimg.cc/DfCffKYF/2033-Aero-Vironment-RQ-20-Puma-reconnaissance-UAV-destr-03-08-24.jpg took 0.3676116599999659 seconds to run
8286
8287
Grabbing the full link at https://i.postimg.cc/N0rwRyB6/2013-Aero-Vironment-RQ-20-Puma-reconnaissance-UAV-destr-14-05-24.jpg took 0.3627883400004066 seconds to run
8287
8288
Grabbing the full link at https://i.postimg.cc/V6qQH3S5/2029-Aero-Vironment-RQ-20-Puma-reconnaissance-UAV-destr-28-10-24.jpg took 0.3838637210001252 seconds to run
8288
8289
Grabbing the full link at https://i.postimg.cc/L4LjPVMw/2007-rq20-dam-08-08-23.jpg took 0.37180181599978823 seconds to run
8289
8290
Grabbing the full link at https://i.postimg.cc/J4PQnTF6/2002-RQ-20-Puma-capt.jpg took 0.36847872999987885 seconds to run

Connecting to https://i.postimg.cc/J4PQnTF6/2002-RQ-20-Puma-capt.jpg ...
Downloading 2002-RQ-20-Puma-capt.jpg ...
[==================================================] 100.00%

OCR returns: 14.12.2022|RQ-20 PUMA|HTTPS://T.ME/EVGENIY_LISITSYN|TELEGRAM-BOEHKOPJINCNLbIH
Running OCR on https://i.postimg.cc/J4PQnTF6/2002-RQ-20-Puma-capt.jpg took 27.0626160540005 seconds to run
8290
8291
Returning non-postimg link
8291
8292
Grabbing the full link at https://i.postimg.cc/5tRpYK4b/2014-RQ-20-Puma-LE-capt-08-07-23.jpg took 0.4024235670003691 seconds to run
8292
8293

Connecting to https://i.postimg.cc/y8GDZ84s/554g0.png ...
Downloading 554g0.png ...
[                                                  ] 0.39%

Grabbing the full link at https://i.postimg.cc/y8GDZ84s/554g0.png took 0.387746502000482 seconds to run

[==================================================] 100.00%

OCR returns: (Before August 2023|RQ-20PUMA|CWA|CWA|RQ-20PUMA
Running OCR on https://i.postimg.cc/y8GDZ84s/554g0.png took 36.75966941200022 seconds to run
8293
8294
Grabbing the full link at https://i.postimg.cc/bYWBw9Bx/659.png took 0.3773199070001283 seconds to run

Connecting to https://i.postimg.cc/bYWBw9Bx/659.png ...
Downloading 659.png ...
[==================================================] 100.00%

OCR returns: 21/7/2023
Running OCR on https://i.postimg.cc/bYWBw9Bx/659.png took 13.462959323999712 seconds to run
8294
8295
Grabbing the full link at https://i.postimg.cc/N0cX0sfP/5489.png took 0.47873877300025924 seconds to run

Connecting to https://i.postimg.cc/N0cX0sfP/5489.png ...
Downloading 5489.png ...
[==================================================] 100.00%

OCR returns: 04/9/2023
Running OCR on https://i.postimg.cc/N0cX0sfP/5489.png took 10.391767199999776 seconds to run
8295
8296
Grabbing the full link at https://i.postimg.cc/8zB5thNt/65.png took 0.3646759719995316 seconds to run

Connecting to https://i.postimg.cc/8zB5thNt/65.png ...
Downloading 65.png ...
[==================================================] 100.00%

OCR returns: AO5PO|08/9/2023
Running OCR on https://i.postimg.cc/8zB5thNt/65.png took 14.212911677000193 seconds to run
8296
8297
Grabbing the full link at https://i.postimg.cc/RhpkjYQX/38.png took 0.3780527409999195 seconds to run

Connecting to https://i.postimg.cc/RhpkjYQX/38.png ...
Downloading 38.png ...
[==================================================] 100.00%

OCR returns: AO5POVA BON|MECTb|业|茶|HE|HE PABOT|14/9/2023
Running OCR on https://i.postimg.cc/RhpkjYQX/38.png took 16.473880535999342 seconds to run
8297
8298
Grabbing the full link at https://i.postimg.cc/7hN8jQFn/2024-rq20-puma-capt-04-09-23.jpg took 0.38795339500029513 seconds to run
8298
8299
Grabbing the full link at https://i.postimg.cc/B6Kf73kh/2006-rq20-puma-uav-capt-10-01-24.jpg took 0.36383697299970663 seconds to run
8299
8300
Grabbing the full link at https://i.postimg.cc/zGtLq97q/2015-RQ-20-Puma-capt-04-04-24.jpg took 0.36529839700051525 seconds to run
8300
8301
Grabbing the full link at https://i.postimg.cc/3w7wSmR3/2062-Aero-Vironment-RQ-20-Puma-reconnaissance-UAV-capt-12-04-24.jpg took 0.3667819789998248 seconds to run
8301
8302
Grabbing the full link at https://i.postimg.cc/nrBc0m5V/2007-Quantix-Recons-UAV-capt-29-04-23.jpg took 0.37014563100001396 seconds to run
8302
8303
Grabbing the full link at https://i.postimg.cc/3w9xwX1j/2004-Scan-Eagle-2-destr-15-07-23.jpg took 0.37239290199977404 seconds to run
8303
8304
Grabbing the full link at https://i.postimg.cc/52PMP9rb/2035-Scan-Eagle2-UAV-destr-05-10-23.jpg took 0.3659192750001239 seconds to run
8304
8305
Grabbing the full link at https://i.postimg.cc/zBrvvYWM/2007-Scan-Eagle-2-destr-26-02-24.jpg took 0.3684922419997747 seconds to run
8305
8306
Grabbing the full link at https://i.postimg.cc/m2Q7YZvD/2016-Scan-Eagle-2-reconnaisance-UAV-destr-30-04-24.jpg took 0.3800140099992859 seconds to run
8306
8307
Grabbing the full link at https://i.postimg.cc/Xv82Xjxr/5g44.png took 0.3695341949996873 seconds to run

Connecting to https://i.postimg.cc/Xv82Xjxr/5g44.png ...
Downloading 5g44.png ...
[==================================================] 100.00%

OCR returns: 10/6/2023|MECTb|业|HE
Running OCR on https://i.postimg.cc/Xv82Xjxr/5g44.png took 15.536116623000453 seconds to run
8307
8308
Grabbing the full link at https://i.postimg.cc/XNsn1Yg9/2004-Quantum-Vector-destr-17-11-23.jpg took 0.37819227399995725 seconds to run
8308
8309
Grabbing the full link at https://i.postimg.cc/c1bwJ04x/2063-Quantum-Vector-reconnaissance-UAV-destr-09-02-25.jpg took 0.3615982060000533 seconds to run
8309
8310
Grabbing the full link at https://i.postimg.cc/5yYmjDLN/2001-Quantum-Vector-reconnaissance-UAV-capt-02-03-25.jpg took 0.4057358119998753 seconds to run
8310
8311
Grabbing the full link at https://i.postimg.cc/RCghLj43/2002-RQ-35-Heidrun-destr-04-12-23.jpg took 0.3743855029997576 seconds to run
8311
8312
Grabbing the full link at https://i.postimg.cc/QtZpYYzL/2028-RQ-35-Heidrun-reconnaissance-UAV-destr-02-04-24.jpg took 0.366944312000669 seconds to run
8312
8313
Grabbing the full link at https://i.postimg.cc/g21pXzXm/2019-RQ-35-Heidrun-reconnaissance-UAV-capt-29-12-24.jpg took 0.37002890599978855 seconds to run
8313
8314
Grabbing the full link at https://i.postimg.cc/Sj0hbM2k/2001-Malloy-Aeronautics-T150-cargo-UAV-destr-17-11-24.jpg took 0.36769457799982774 seconds to run
8314
8315

Connecting to https://i.postimg.cc/ZnR7mS1s/5428.png ...
Downloading 5428.png ...
[                                                  ] 0.55%

Grabbing the full link at https://i.postimg.cc/ZnR7mS1s/5428.png took 0.3667175939999652 seconds to run

[==================================================] 100.00%

OCR returns: KADYROV95|12/10/2022|0:12/0:25|4
Running OCR on https://i.postimg.cc/ZnR7mS1s/5428.png took 29.55973088399969 seconds to run
8315
8316
Grabbing the full link at https://i.postimg.cc/zGkfJxZB/2033-Malloy-Aeronautics-capt-31-05-23.jpg took 0.37803367100059404 seconds to run
8316
8317
Grabbing the full link at https://i.postimg.cc/rynQDw0S/38.png took 0.3667544629988697 seconds to run

Connecting to https://i.postimg.cc/rynQDw0S/38.png ...
Downloading 38.png ...
[==================================================] 100.00%

OCR returns: 08|25/8/2023
Running OCR on https://i.postimg.cc/rynQDw0S/38.png took 15.271195790999627 seconds to run
8317
8318
Grabbing the full link at https://i.postimg.cc/L8mXfVwB/2012-FLIRT-Cetus-reconnisaince-UAV-destr-06-04-24.jpg took 0.36501694500111626 seconds to run
8318
8319
Grabbing the full link at https://i.postimg.cc/MTmdmXC9/2016-FLIRT-Cetus-reconnisaince-UAV-destr-24-06-24.jpg took 0.3658237849995203 seconds to run
8319
8320
Grabbing the full link at https://i.postimg.cc/bwLSVXvW/2022-FLIRT-Cetus-reconnisaince-UAV-capt-10-11-24.jpg took 0.4214907420009695 seconds to run
8320
8321
Grabbing the full link at https://i.postimg.cc/3wn3Wcp2/2027-Tekever-AR3-UAV-destr-02-05-24.jpg took 0.3654919590007921 seconds to run
8321
8322
Grabbing the full link at https://i.postimg.cc/Y90MFzfZ/2028-Tekever-AR3-UAV-capt-09-04-24.jpg took 0.4073768210000708 seconds to run
8322
8323
Grabbing the full link at https://i.postimg.cc/vZ3T3wgk/2016-Tekever-AR3-multipurpose-UAV-destr-27-05-24.jpg took 0.36989099200036435 seconds to run
8323
8324
Grabbing the full link at https://i.postimg.cc/RFcRxmkg/2025-Tekever-AR3-multipurpose-UAV-destr-01-06-24.jpg took 0.366493626999727 seconds to run
8324
8325
Grabbing the full link at https://i.postimg.cc/QxNzBmZR/2000-Tekever-AR3-multipurpose-UAV-destr-29-06-24.jpg took 0.37190535199988517 seconds to run
8325
8326
Grabbing the full link at https://i.postimg.cc/2SvpbtQH/2014-Tekever-AR3-multipurpose-UAV-capt-01-06-24.jpg took 0.3750202730007004 seconds to run
8326
8327
Grabbing the full link at https://i.postimg.cc/prmp978f/2006-Tekever-AR3-multipurpose-UAV-capt-30-07-24.jpg took 0.37616611999874294 seconds to run
8327
8328
Grabbing the full link at https://i.postimg.cc/MT8HCWwV/2003-UAS-HAWK-capt-09-03-24.jpg took 0.3653516109989141 seconds to run
8328
8329
Grabbing the full link at https://i.postimg.cc/DzTH128h/2004-DH-1-Domakha-reconnaissance-UAV-destr-30-05-25.jpg took 0.3897045869998692 seconds to run
8329
8330
Grabbing the full link at https://i.postimg.cc/hG1wrHdd/2006-DH-1-Domakha-reconnaissance-UAV-destr-30-09-24.jpg took 0.5843181269992783 seconds to run
8330
8331
Grabbing the full link at https://i.postimg.cc/kg8LVVMw/2005-DH-1-Domakha-reconnaissance-UAV-capt-11-11-23.jpg took 0.5268575320005766 seconds to run
8331
8332
Grabbing the full link at https://i.postimg.cc/zX49XwNV/2007-DH-1-Domakha-reconnaissance-UAV-capt-30-05-24.jpg took 0.5263990680014103 seconds to run
8332
8333
Grabbing the full link at https://i.postimg.cc/SQt2R1Kc/2001-DH-1-Domakha-reconnaissance-UAV-capt-25-07-25.jpg took 0.5332171040008689 seconds to run
8333
8334
Grabbing the full link at https://i.postimg.cc/bw9YW99f/658.png took 1.5257597580002766 seconds to run

Connecting to https://i.postimg.cc/bw9YW99f/658.png ...
Downloading 658.png ...
[==================================================] 100.00%

OCR returns: 21/6/2023|@BLACKPIRATEZ125|HE SPATICR.
Running OCR on https://i.postimg.cc/bw9YW99f/658.png took 16.528146237998953 seconds to run
8334
8335
Grabbing the full link at https://i.postimg.cc/V6BFMv9d/354.png took 0.4104776080002921 seconds to run

Connecting to https://i.postimg.cc/V6BFMv9d/354.png ...
Downloading 354.png ...
[==================================================] 100.00%

OCR returns: 27/8/2023
Running OCR on https://i.postimg.cc/V6BFMv9d/354.png took 28.297224533998815 seconds to run
8335
8336
Grabbing the full link at https://i.postimg.cc/7Y1LJdj8/2007-Unknown-UAV-destr-27-01-24.jpg took 0.3692635549996339 seconds to run
8336
8337

Connecting to https://i.postimg.cc/Kzj3f087/5546.png ...
Downloading 5546.png ...
[                                                  ] 0.42%

Grabbing the full link at https://i.postimg.cc/Kzj3f087/5546.png took 0.365589238001121 seconds to run

[==================================================] 100.00%

OCR returns: 23/10/2022|ZBOEV LIST Z
Running OCR on https://i.postimg.cc/Kzj3f087/5546.png took 13.322589576999235 seconds to run
8337
8338

Connecting to https://i.postimg.cc/yxy8CH6r/469.png ...
Downloading 469.png ...
[                                                  ] 0.21%

Grabbing the full link at https://i.postimg.cc/yxy8CH6r/469.png took 0.3704049080006371 seconds to run

[==================================================] 100.00%

OCR returns: 27/3/2022
Running OCR on https://i.postimg.cc/yxy8CH6r/469.png took 24.973440408999522 seconds to run
8338
8339
Grabbing the full link at https://i.postimg.cc/tCcm2Y7L/47.png took 0.3681564279995655 seconds to run

Connecting to https://i.postimg.cc/tCcm2Y7L/47.png ...
Downloading 47.png ...
[==================================================] 100.00%

OCR returns: 15/5/2022|(sunk|earlier|during|the|battle for|Mariupol)
Running OCR on https://i.postimg.cc/tCcm2Y7L/47.png took 24.624440743000378 seconds to run
8339
8340

Connecting to https://i.postimg.cc/tCcm2Y7L/47.png ...
Downloading 47.png ...
[                                                  ] 0.25%

Grabbing the full link at https://i.postimg.cc/tCcm2Y7L/47.png took 0.3648780289986462 seconds to run

[==================================================] 100.00%

OCR returns: 15/5/2022|(sunk|earlier|during|the|battle for|Mariupol)
Running OCR on https://i.postimg.cc/tCcm2Y7L/47.png took 20.637896215999717 seconds to run
8340
8341
Returning non-postimg link
8341
8342

Connecting to https://i.postimg.cc/hjqgGwmt/f55.jpg ...
Downloading f55.jpg ...
[=                                                 ] 3.13%

Grabbing the full link at https://i.postimg.cc/hjqgGwmt/f55.jpg took 0.39091313000062655 seconds to run

[==================================================] 100.00%

OCR returns: 14/03/2022|AKKEPMAN|@MSGazdiev|@MSGazdiev|PRESS|RT.com|RT.com
Running OCR on https://i.postimg.cc/hjqgGwmt/f55.jpg took 16.045002175000263 seconds to run
8342
8343
Grabbing the full link at https://i.postimg.cc/hjqgGwmt/f55.jpg took 0.4067578220001451 seconds to run

Connecting to https://i.postimg.cc/hjqgGwmt/f55.jpg ...
Downloading f55.jpg ...
[==================================================] 100.00%

OCR returns: 14/03/2022|AKKEPMAN|@MSGazdiev|@MSGazdiev|PRESS|RT.com|RT.com
Running OCR on https://i.postimg.cc/hjqgGwmt/f55.jpg took 16.108013798000684 seconds to run
8343
8344
Grabbing the full link at https://i.postimg.cc/Xv5443pP/f6.jpg took 0.37487959300051443 seconds to run

Connecting to https://i.postimg.cc/Xv5443pP/f6.jpg ...
Downloading f6.jpg ...
[==================================================] 100.00%

OCR returns: 14/03/2022|BMWrOPOA|MSGazdiev|@MSGazdiev|RT.com|com
Running OCR on https://i.postimg.cc/Xv5443pP/f6.jpg took 17.98112311099976 seconds to run
8344
8345

Connecting to https://i.postimg.cc/Xv5443pP/f6.jpg ...
Downloading f6.jpg ...
[=                                                 ] 3.11%

Grabbing the full link at https://i.postimg.cc/Xv5443pP/f6.jpg took 0.3783720409992384 seconds to run

[==================================================] 100.00%

OCR returns: 14/03/2022|BMWrOPOA|MSGazdiev|@MSGazdiev|RT.com|com
Running OCR on https://i.postimg.cc/Xv5443pP/f6.jpg took 17.71643117399981 seconds to run
8345
8346
Grabbing the full link at https://i.postimg.cc/wjr3y0Lx/28.png took 0.4553349870002421 seconds to run

Connecting to https://i.postimg.cc/wjr3y0Lx/28.png ...
Downloading 28.png ...
[==================================================] 100.00%

OCR returns: 15/4/2022|AC-12|AC9|KPEMEH4YK
Running OCR on https://i.postimg.cc/wjr3y0Lx/28.png took 18.727935603999867 seconds to run
8346
8347

Connecting to https://i.postimg.cc/wjr3y0Lx/28.png ...
Downloading 28.png ...
[                                                  ] 0.35%

Grabbing the full link at https://i.postimg.cc/wjr3y0Lx/28.png took 0.36903956800051674 seconds to run

[==================================================] 100.00%

OCR returns: 15/4/2022|AC-12|AC9|KPEMEH4YK
Running OCR on https://i.postimg.cc/wjr3y0Lx/28.png took 17.026960389999658 seconds to run
8347
8348
Returning non-postimg link
8348
8349
Returning non-postimg link
8349
8350
Grabbing the full link at https://i.postimg.cc/Hn5sJRPW/2043-Island-class-patrol-boat-dam-18-03-24.jpg took 0.3658331750011712 seconds to run
8350
8351
Grabbing the full link at https://i.postimg.cc/8zG990c2/36.png took 0.3654935939994175 seconds to run

Connecting to https://i.postimg.cc/8zG990c2/36.png ...
Downloading 36.png ...
[==================================================] 100.00%

OCR returns: 19/4/2022|NETPFAΛAKTMOHO
Running OCR on https://i.postimg.cc/8zG990c2/36.png took 15.387788647998605 seconds to run
8351
8352

Connecting to https://i.postimg.cc/8zG990c2/36.png ...
Downloading 36.png ...
[                                                  ] 0.51%

Grabbing the full link at https://i.postimg.cc/8zG990c2/36.png took 0.5451505239998369 seconds to run

[==================================================] 100.00%

OCR returns: 19/4/2022|NETPFAΛAKTMOHO
Running OCR on https://i.postimg.cc/8zG990c2/36.png took 14.705705128999398 seconds to run
8352
8353
Grabbing the full link at https://i.postimg.cc/661SR8Mj/2011-Project-205-P-Tarantul-class-border-patrol-ship-dam-20-03-24.jpg took 0.3825627700007317 seconds to run
8353
8354
Grabbing the full link at https://i.postimg.cc/Dys0zfpT/2020-BG-105-Zhuk-class-destr-15-03-22.jpg took 0.3956641929999023 seconds to run
8354
8355
Grabbing the full link at https://i.postimg.cc/Dys0zfpT/2020-BG-105-Zhuk-class-destr-15-03-22.jpg took 0.3634947270002158 seconds to run
8355
8356
Grabbing the full link at https://i.postimg.cc/q7JvJQmV/2001.jpg took 0.37784970499888004 seconds to run

Connecting to https://i.postimg.cc/q7JvJQmV/2001.jpg ...
Downloading 2001.jpg ...
[==================================================] 100.00%

OCR returns: 07.07.2022|3G108|ne/istorijaoruzijaz
Running OCR on https://i.postimg.cc/q7JvJQmV/2001.jpg took 22.770013585000925 seconds to run
8356
8357

Connecting to https://i.postimg.cc/q7JvJQmV/2001.jpg ...
Downloading 2001.jpg ...
[=                                                 ] 3.65%

Grabbing the full link at https://i.postimg.cc/q7JvJQmV/2001.jpg took 0.39360176799891633 seconds to run

[==================================================] 100.00%

OCR returns: 07.07.2022|3G108|ne/istorijaoruzijaz
Running OCR on https://i.postimg.cc/q7JvJQmV/2001.jpg took 22.532254498999464 seconds to run
8357
8358
Grabbing the full link at https://i.postimg.cc/05zrL0pr/2021-BG-110-Zhuk-class-destr-15-03-22.jpg took 0.4982551639986923 seconds to run
8358
8359
Grabbing the full link at https://i.postimg.cc/05zrL0pr/2021-BG-110-Zhuk-class-destr-15-03-22.jpg took 0.49994449599944346 seconds to run
8359
8360
Grabbing the full link at https://i.postimg.cc/13JMyjN5/2019-Zhuk-Class-Patrol-Boat-dam-14-11-23.jpg took 0.5155576350007323 seconds to run
8360
8361
Grabbing the full link at https://i.postimg.cc/L5nyF4sY/g77.jpg took 0.46202958100002434 seconds to run

Connecting to https://i.postimg.cc/L5nyF4sY/g77.jpg ...
Downloading g77.jpg ...
[==================================================] 100.00%

OCR returns: BEPAHCK,YKPANHA|14/03/2022|118|HOBOCTNAHA|NEPEROBOPbIPOYKPANHbI3ANAHNPOBAHbIHA∩OHEAEbHNK-ECKOB|☆|38E3AA|☆|☆|☆3BE3AA|大|☆|☆|3BE3AA|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|3BE3AA|☆|38E3AA|☆|☆|☆|☆|☆|☆|★|☆☆|☆|3BE32A|享|早|☆|3日E3A|☆☆|38E30A|大|GA18|☆|☆
Running OCR on https://i.postimg.cc/L5nyF4sY/g77.jpg took 38.16255690499929 seconds to run
8361
8362
Grabbing the full link at https://i.postimg.cc/L5nyF4sY/g77.jpg took 0.38967804499952763 seconds to run

Connecting to https://i.postimg.cc/L5nyF4sY/g77.jpg ...
Downloading g77.jpg ...
[==================================================] 100.00%

OCR returns: BEPAHCK,YKPANHA|14/03/2022|118|HOBOCTNAHA|NEPEROBOPbIPOYKPANHbI3ANAHNPOBAHbIHA∩OHEAEbHNK-ECKOB|☆|38E3AA|☆|☆|☆3BE3AA|大|☆|☆|3BE3AA|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|3BE3AA|☆|38E3AA|☆|☆|☆|☆|☆|☆|★|☆☆|☆|3BE32A|享|早|☆|3日E3A|☆☆|38E30A|大|GA18|☆|☆
Running OCR on https://i.postimg.cc/L5nyF4sY/g77.jpg took 37.936615729999176 seconds to run
8362
8363
Grabbing the full link at https://i.postimg.cc/654HHQSF/g78.jpg took 0.40776163000009547 seconds to run

Connecting to https://i.postimg.cc/654HHQSF/g78.jpg ...
Downloading g78.jpg ...
[==================================================] 100.00%

OCR returns: 38E3AA|3BE3AA|38E3AA|☆|☆|☆|☆|14/03/2022|*|☆|☆|☆|☆|☆|☆|☆|☆|☆|38E3AA|38E3AA|☆|茶|☆|☆|☆|☆|☆|☆|*|☆|福|★|*|￥|3日E32A|H9GE30A|☆|38E30A|?|☆☆|BBE3AA|GA18|☆|文|江
Running OCR on https://i.postimg.cc/654HHQSF/g78.jpg took 38.79968795199966 seconds to run
8363
8364
Grabbing the full link at https://i.postimg.cc/654HHQSF/g78.jpg took 0.37574851700082945 seconds to run

Connecting to https://i.postimg.cc/654HHQSF/g78.jpg ...
Downloading g78.jpg ...
[==================================================] 100.00%

OCR returns: 38E3AA|3BE3AA|38E3AA|☆|☆|☆|☆|14/03/2022|*|☆|☆|☆|☆|☆|☆|☆|☆|☆|38E3AA|38E3AA|☆|茶|☆|☆|☆|☆|☆|☆|*|☆|福|★|*|￥|3日E32A|H9GE30A|☆|38E30A|?|☆☆|BBE3AA|GA18|☆|文|江
Running OCR on https://i.postimg.cc/654HHQSF/g78.jpg took 61.5734137670006 seconds to run
8364
8365
Grabbing the full link at https://i.postimg.cc/rw5PwbFs/64.jpg took 0.36608795699976326 seconds to run

Connecting to https://i.postimg.cc/rw5PwbFs/64.jpg ...
Downloading 64.jpg ...
[==================================================] 100.00%

OCR returns: 14/03/2022|M387CT681E3|1387#|M3BECTHAL2|M3BECTH31E3|M3BECTHRD2|M3BECTHR|运|H3BECTHAIE3|3BE30A|☆|真|☆☆|本|38E30A|☆|☆|☆|*|文|A|文|A|*|A|☆|A|☆|+|*|3DE30A|*|☆|☆|3BE3DA|☆|.|☆|冷|*|☆|★|×|☆|☆|☆|文|☆|4|A|3BE3A|☆|3830|*|☆|☆|☆|☆|☆|☆|☆|BE30A|☆|☆|方|3BE3AA|3BE30A|☆|☆|A|☆|3BE3A|Y|☆|A|M6|分享|A|☆|☆|A|☆|3BE30A|A-830|A|☆|文|BE3AA|文|3BE3|文|文|3BE3A|☆|文|☆|A|☆☆|☆|☆|A|☆☆|☆|A|x|A|3日E3A|☆|☆3BE3A|☆|A|☆|☆
Running OCR on https://i.postimg.cc/rw5PwbFs/64.jpg took 49.814567896999506 seconds to run
8365
8366
Grabbing the full link at https://i.postimg.cc/rw5PwbFs/64.jpg took 0.4395209159993101 seconds to run

Connecting to https://i.postimg.cc/rw5PwbFs/64.jpg ...
Downloading 64.jpg ...
[==================================================] 100.00%

OCR returns: 14/03/2022|M387CT681E3|1387#|M3BECTHAL2|M3BECTH31E3|M3BECTHRD2|M3BECTHR|运|H3BECTHAIE3|3BE30A|☆|真|☆☆|本|38E30A|☆|☆|☆|*|文|A|文|A|*|A|☆|A|☆|+|*|3DE30A|*|☆|☆|3BE3DA|☆|.|☆|冷|*|☆|★|×|☆|☆|☆|文|☆|4|A|3BE3A|☆|3830|*|☆|☆|☆|☆|☆|☆|☆|BE30A|☆|☆|方|3BE3AA|3BE30A|☆|☆|A|☆|3BE3A|Y|☆|A|M6|分享|A|☆|☆|A|☆|3BE30A|A-830|A|☆|文|BE3AA|文|3BE3|文|文|3BE3A|☆|文|☆|A|☆☆|☆|☆|A|☆☆|☆|A|x|A|3日E3A|☆|☆3BE3A|☆|A|☆|☆
Running OCR on https://i.postimg.cc/rw5PwbFs/64.jpg took 46.15580896699976 seconds to run
8366
8367

Connecting to https://i.postimg.cc/rw5PwbFs/64.jpg ...
Downloading 64.jpg ...
[=                                                 ] 2.84%

Grabbing the full link at https://i.postimg.cc/rw5PwbFs/64.jpg took 0.379717914000139 seconds to run

[==================================================] 100.00%

OCR returns: 14/03/2022|M387CT681E3|1387#|M3BECTHAL2|M3BECTH31E3|M3BECTHRD2|M3BECTHR|运|H3BECTHAIE3|3BE30A|☆|真|☆☆|本|38E30A|☆|☆|☆|*|文|A|文|A|*|A|☆|A|☆|+|*|3DE30A|*|☆|☆|3BE3DA|☆|.|☆|冷|*|☆|★|×|☆|☆|☆|文|☆|4|A|3BE3A|☆|3830|*|☆|☆|☆|☆|☆|☆|☆|BE30A|☆|☆|方|3BE3AA|3BE30A|☆|☆|A|☆|3BE3A|Y|☆|A|M6|分享|A|☆|☆|A|☆|3BE30A|A-830|A|☆|文|BE3AA|文|3BE3|文|文|3BE3A|☆|文|☆|A|☆☆|☆|☆|A|☆☆|☆|A|x|A|3日E3A|☆|☆3BE3A|☆|A|☆|☆
Running OCR on https://i.postimg.cc/rw5PwbFs/64.jpg took 45.797848322999926 seconds to run
8367
8368
Returning non-postimg link
8368
8369
Returning non-postimg link
8369
8370
Grabbing the full link at https://i.postimg.cc/Kj96m8Tg/2006-Strizh-class-boat-dam-30-04-22.jpg took 0.40278928100087796 seconds to run
8370
8371
Grabbing the full link at https://i.postimg.cc/Kj96m8Tg/2006-Strizh-class-boat-dam-30-04-22.jpg took 0.3599771419994795 seconds to run
8371
8372
Grabbing the full link at https://i.postimg.cc/0j2ggwzs/2004-tug-boat-project-T-63-M-Kostromich-class-destroyed-30-04-22.jpg took 0.3655290650003735 seconds to run
8372
8373
Grabbing the full link at https://i.postimg.cc/HxS8Hm41/28.png took 0.42975630999899295 seconds to run

Connecting to https://i.postimg.cc/HxS8Hm41/28.png ...
Downloading 28.png ...
[==================================================] 100.00%

OCR returns: 06/4/2022|15/4/2022
Running OCR on https://i.postimg.cc/HxS8Hm41/28.png took 26.876520150000943 seconds to run
8373
8374

Connecting to https://i.postimg.cc/HxS8Hm41/28.png ...
Downloading 28.png ...
[                                                  ] 0.35%

Grabbing the full link at https://i.postimg.cc/HxS8Hm41/28.png took 0.3865195809994475 seconds to run

[==================================================] 100.00%

OCR returns: 06/4/2022|15/4/2022
Running OCR on https://i.postimg.cc/HxS8Hm41/28.png took 23.12743096200029 seconds to run
8374
8375
Grabbing the full link at https://i.postimg.cc/9FkkFm77/54.png took 0.39815672599979735 seconds to run

Connecting to https://i.postimg.cc/9FkkFm77/54.png ...
Downloading 54.png ...
[==================================================] 100.00%

OCR returns: The boat "Stanislav"|sank in May|On May 7,the amphibious assaultboat|"Stanislav"ofthe"Centaur" type took|part in the recapture of Zmiiny Island.|As aresultof a direct hit,he drowned,|and the fate of fi ve crew members is|still unknown.The commanderof the|boat,Serhii Tukmachov, was among|the missing.
Running OCR on https://i.postimg.cc/9FkkFm77/54.png took 23.525332327000797 seconds to run
8375
8376

Connecting to https://i.postimg.cc/9FkkFm77/54.png ...
Downloading 54.png ...
[=                                                 ] 2.63%

Grabbing the full link at https://i.postimg.cc/9FkkFm77/54.png took 0.41905345199847943 seconds to run

[==================================================] 100.00%

OCR returns: The boat "Stanislav"|sank in May|On May 7,the amphibious assaultboat|"Stanislav"ofthe"Centaur" type took|part in the recapture of Zmiiny Island.|As aresultof a direct hit,he drowned,|and the fate of fi ve crew members is|still unknown.The commanderof the|boat,Serhii Tukmachov, was among|the missing.
Running OCR on https://i.postimg.cc/9FkkFm77/54.png took 24.081586464000793 seconds to run
8376
8377
Grabbing the full link at https://i.postimg.cc/zvNg5LQJ/2011-UMS-600-patrol-boat-capt-04-05-22.jpg took 0.4008409649995883 seconds to run
8377
8378
Grabbing the full link at https://i.postimg.cc/zvNg5LQJ/2011-UMS-600-patrol-boat-capt-04-05-22.jpg took 0.36984991899953457 seconds to run
8378
8379
Grabbing the full link at https://i.postimg.cc/CMmTGm2L/2005-UMS-1000-patrol-boat-destr-30-04-22.jpg took 0.3619403609991423 seconds to run
8379
8380

Connecting to https://i.postimg.cc/sfhswL6V/2500-bg22-capt.jpg ...
Downloading 2500-bg22-capt.jpg ...
[                                                  ] 1.73%

Grabbing the full link at https://i.postimg.cc/sfhswL6V/2500-bg22-capt.jpg took 0.3631067419992178 seconds to run

[==================================================] 100.00%

OCR returns: PNAHOBOCTN|Anekce aHM4eB#8494876|19.04.2022
Running OCR on https://i.postimg.cc/sfhswL6V/2500-bg22-capt.jpg took 25.428703505000158 seconds to run
8380
8381
Grabbing the full link at https://i.postimg.cc/sfhswL6V/2500-bg22-capt.jpg took 0.3688749929988262 seconds to run

Connecting to https://i.postimg.cc/sfhswL6V/2500-bg22-capt.jpg ...
Downloading 2500-bg22-capt.jpg ...
[==================================================] 100.00%

OCR returns: PNAHOBOCTN|Anekce aHM4eB#8494876|19.04.2022
Running OCR on https://i.postimg.cc/sfhswL6V/2500-bg22-capt.jpg took 26.220186361999367 seconds to run
8381
8382

Connecting to https://i.postimg.cc/kMQZ9Gw8/d9.jpg ...
Downloading d9.jpg ...
[=                                                 ] 2.66%

Grabbing the full link at https://i.postimg.cc/kMQZ9Gw8/d9.jpg took 0.38174716899993655 seconds to run

[==================================================] 100.00%

OCR returns: 38E3A|38E3AA|☆|38E3AA|☆|六|14/03/2022|*|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|38E30|☆|38E30A|☆|☆|外|38E3|X|38E3A|☆|38E3A|大|☆|★|BG14|@MSGazdiev|RT.com
Running OCR on https://i.postimg.cc/kMQZ9Gw8/d9.jpg took 28.623482772998614 seconds to run
8382
8383
Grabbing the full link at https://i.postimg.cc/kMQZ9Gw8/d9.jpg took 0.37164546699932544 seconds to run

Connecting to https://i.postimg.cc/kMQZ9Gw8/d9.jpg ...
Downloading d9.jpg ...
[==================================================] 100.00%

OCR returns: 38E3A|38E3AA|☆|38E3AA|☆|六|14/03/2022|*|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|38E30|☆|38E30A|☆|☆|外|38E3|X|38E3A|☆|38E3A|大|☆|★|BG14|@MSGazdiev|RT.com
Running OCR on https://i.postimg.cc/kMQZ9Gw8/d9.jpg took 28.985951955999553 seconds to run
8383
8384

Connecting to https://i.postimg.cc/HxQSpv0H/d2.jpg ...
Downloading d2.jpg ...
[=                                                 ] 2.95%

Grabbing the full link at https://i.postimg.cc/HxQSpv0H/d2.jpg took 0.6751101549998566 seconds to run

[==================================================] 100.00%

OCR returns: 14/03/2022|BG24|@MSGazdiev|RT.com
Running OCR on https://i.postimg.cc/HxQSpv0H/d2.jpg took 24.391138864000823 seconds to run
8384
8385
Grabbing the full link at https://i.postimg.cc/HxQSpv0H/d2.jpg took 0.3856678970005305 seconds to run

Connecting to https://i.postimg.cc/HxQSpv0H/d2.jpg ...
Downloading d2.jpg ...
[==================================================] 100.00%

OCR returns: 14/03/2022|BG24|@MSGazdiev|RT.com
Running OCR on https://i.postimg.cc/HxQSpv0H/d2.jpg took 24.60144907099857 seconds to run
8385
8386
Grabbing the full link at https://i.postimg.cc/xdWmxpyN/2002-Sea-Guard-BG23-capt-14-03-22.jpg took 0.5134576049986208 seconds to run
8386
8387
Grabbing the full link at https://i.postimg.cc/xdWmxpyN/2002-Sea-Guard-BG23-capt-14-03-22.jpg took 0.5270387659984408 seconds to run
8387
8388
Grabbing the full link at https://i.postimg.cc/4djNchf2/2003-UMS-1000-patrol-boat-BG-25-capt-19-04-22.jpg took 1.5875754889984819 seconds to run
8388
8389
Grabbing the full link at https://i.postimg.cc/4djNchf2/2003-UMS-1000-patrol-boat-BG-25-capt-19-04-22.jpg took 0.5230679769993003 seconds to run
8389
8390
Grabbing the full link at https://i.postimg.cc/4xgdHCjh/2000-2x-Project-50030-Kalkan-class-patrol-boat-BG303-and-304-capt-14-03-22.jpg took 1.1542512830001215 seconds to run
8390
8391
Grabbing the full link at https://i.postimg.cc/4xgdHCjh/2000-2x-Project-50030-Kalkan-class-patrol-boat-BG303-and-304-capt-14-03-22.jpg took 0.5431863410012738 seconds to run
8391
8392
Grabbing the full link at https://i.postimg.cc/4xgdHCjh/2000-2x-Project-50030-Kalkan-class-patrol-boat-BG303-and-304-capt-14-03-22.jpg took 0.6103662310015352 seconds to run
8392
8393
Grabbing the full link at https://i.postimg.cc/4xgdHCjh/2000-2x-Project-50030-Kalkan-class-patrol-boat-BG303-and-304-capt-14-03-22.jpg took 0.5254109919987968 seconds to run
8393
8394
Grabbing the full link at https://i.postimg.cc/15KK7NBC/v7.jpg took 0.6579987570003141 seconds to run

Connecting to https://i.postimg.cc/15KK7NBC/v7.jpg ...
Downloading v7.jpg ...
[==================================================] 100.00%

OCR returns: ☆|38E30A|3BE3AA|☆|38E3AA|☆|☆|14/03/2022|☆|☆|☆|☆|☆|☆|A|☆|☆|☆|☆|☆|☆|38E30A|3日E30A|☆|☆|4|☆|*|☆|G9E|鑫|☆|38E3A|★☆|BBE30A|☆|☆|京|@MSGazdiev|RT.com
Running OCR on https://i.postimg.cc/15KK7NBC/v7.jpg took 28.379630695999367 seconds to run
8394
8395
Grabbing the full link at https://i.postimg.cc/15KK7NBC/v7.jpg took 0.4487048099999811 seconds to run

Connecting to https://i.postimg.cc/15KK7NBC/v7.jpg ...
Downloading v7.jpg ...
[==================================================] 100.00%

OCR returns: ☆|38E30A|3BE3AA|☆|38E3AA|☆|☆|14/03/2022|☆|☆|☆|☆|☆|☆|A|☆|☆|☆|☆|☆|☆|38E30A|3日E30A|☆|☆|4|☆|*|☆|G9E|鑫|☆|38E3A|★☆|BBE30A|☆|☆|京|@MSGazdiev|RT.com
Running OCR on https://i.postimg.cc/15KK7NBC/v7.jpg took 28.324972675000026 seconds to run
8395
8396
Grabbing the full link at https://i.postimg.cc/fRS41cLr/2141-Small-sea-guard-patrol-boats-capt-01-05-22.jpg took 0.3853578159996687 seconds to run
8396
8397
Grabbing the full link at https://i.postimg.cc/fRS41cLr/2141-Small-sea-guard-patrol-boats-capt-01-05-22.jpg took 0.36727549799979897 seconds to run
8397
8398
Grabbing the full link at https://i.postimg.cc/9QK1yHJC/dg.jpg took 0.3628562639987649 seconds to run

Connecting to https://i.postimg.cc/9QK1yHJC/dg.jpg ...
Downloading dg.jpg ...
[==================================================] 100.00%

OCR returns: 14/03/2022|BG310|@MSGazdiev|RT.com
Running OCR on https://i.postimg.cc/9QK1yHJC/dg.jpg took 24.354879243999676 seconds to run
8398
8399
Grabbing the full link at https://i.postimg.cc/9QK1yHJC/dg.jpg took 0.3669280020003498 seconds to run

Connecting to https://i.postimg.cc/9QK1yHJC/dg.jpg ...
Downloading dg.jpg ...
[==================================================] 100.00%

OCR returns: 14/03/2022|BG310|@MSGazdiev|RT.com
Running OCR on https://i.postimg.cc/9QK1yHJC/dg.jpg took 24.517430066000088 seconds to run
8399
8400

Connecting to https://i.postimg.cc/J4hymDmd/c0.jpg ...
Downloading c0.jpg ...
[=                                                 ] 2.58%

Grabbing the full link at https://i.postimg.cc/J4hymDmd/c0.jpg took 0.4528905279985338 seconds to run

[==================================================] 100.00%

OCR returns: ￥|38E3AA|3BE3AA|W|☆|38E3AA|A|14/03/2022|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|38E30A|☆|3BE3AA|☆|*|☆|☆|公|☆|☆|☆|☆|☆|工|39E3|38E3A|☆|☆|BBEA|GA18|☆|@MSGazdiev
Running OCR on https://i.postimg.cc/J4hymDmd/c0.jpg took 29.214677903000847 seconds to run
8400
8401
Grabbing the full link at https://i.postimg.cc/J4hymDmd/c0.jpg took 0.42279792499903124 seconds to run

Connecting to https://i.postimg.cc/J4hymDmd/c0.jpg ...
Downloading c0.jpg ...
[==================================================] 100.00%

OCR returns: ￥|38E3AA|3BE3AA|W|☆|38E3AA|A|14/03/2022|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|☆|38E30A|☆|3BE3AA|☆|*|☆|☆|公|☆|☆|☆|☆|☆|工|39E3|38E3A|☆|☆|BBEA|GA18|☆|@MSGazdiev
Running OCR on https://i.postimg.cc/J4hymDmd/c0.jpg took 30.487499033999484 seconds to run
8401
8402
Grabbing the full link at https://i.postimg.cc/cHFGjZfF/2006-40-Defiant-patrol-boat-dam-09-03-24.jpg took 0.45222756499970274 seconds to run
8402
8403
Returning non-postimg link
8403
8404
Grabbing the full link at https://i.postimg.cc/m2znSTqb/2009-landing-ship-Project-773-Yuriy-Olefirenko-destr-14-09-23.jpg took 0.43115725999996357 seconds to run
8404
8405
Grabbing the full link at https://i.postimg.cc/vTJJjs57/2022-Dmytro-Chubar-project-1462-capt-15-03-22.jpg took 0.395055091001268 seconds to run
8405
8406
Grabbing the full link at https://i.postimg.cc/15N05wkg/2014-unkn-boat-dam-23-12-23.jpg took 0.38446961999943596 seconds to run
8406
8407
Grabbing the full link at https://i.postimg.cc/qqmmt6Nz/1002.jpg took 0.39803098599986697 seconds to run

Connecting to https://i.postimg.cc/qqmmt6Nz/1002.jpg ...
Downloading 1002.jpg ...
[==================================================] 100.00%

OCR returns: 25.02.2022
Running OCR on https://i.postimg.cc/qqmmt6Nz/1002.jpg took 52.90884794399972 seconds to run
8407
8408
Grabbing the full link at https://i.postimg.cc/fTM2FsNZ/327.png took 0.4011286589993688 seconds to run

Connecting to https://i.postimg.cc/fTM2FsNZ/327.png ...
Downloading 327.png ...
[==================================================] 100.00%

OCR returns: 股|17/8/2023
Running OCR on https://i.postimg.cc/fTM2FsNZ/327.png took 15.214612399000544 seconds to run
8408
8409
Grabbing the full link at https://i.postimg.cc/SxxWfdC2/769.png took 0.3778565360007633 seconds to run

Connecting to https://i.postimg.cc/SxxWfdC2/769.png ...
Downloading 769.png ...
[==================================================] 100.00%

OCR returns: 18|17r|W|TMCT|APXAHFEn CNELIHA3A
Running OCR on https://i.postimg.cc/SxxWfdC2/769.png took 30.545401048999338 seconds to run
8409
8410
Grabbing the full link at https://i.postimg.cc/dVbmXF10/2022-11-13-UA-Kr-AZ-255-B-destroyed.jpg took 0.3775020430002769 seconds to run

Connecting to https://i.postimg.cc/dVbmXF10/2022-11-13-UA-Kr-AZ-255-B-destroyed.jpg ...
Downloading 2022-11-13-UA-Kr-AZ-255-B-destroyed.jpg ...
[==================================================] 100.00%

OCR returns: WMBload|13/11/2022|https://t.me/winaa22|Kherson Airport
Running OCR on https://i.postimg.cc/dVbmXF10/2022-11-13-UA-Kr-AZ-255-B-destroyed.jpg took 27.74069493999923 seconds to run
8410
8411
Grabbing the full link at https://i.postimg.cc/VvkjML7K/2022-11-13-UA-Kr-AZ-255-B-destroyed-2.jpg took 0.47825354899941885 seconds to run

Connecting to https://i.postimg.cc/VvkjML7K/2022-11-13-UA-Kr-AZ-255-B-destroyed-2.jpg ...
Downloading 2022-11-13-UA-Kr-AZ-255-B-destroyed-2.jpg ...
[==================================================] 100.00%

OCR returns: WMBlood|13/11/2022|https://t.me/winua22|Kherson Airport
Running OCR on https://i.postimg.cc/VvkjML7K/2022-11-13-UA-Kr-AZ-255-B-destroyed-2.jpg took 28.672314469000412 seconds to run
8411
8412

Connecting to https://i.postimg.cc/C1hHMGmc/2022-04-24-UA-Kr-AZ-6322.jpg ...
Downloading 2022-04-24-UA-Kr-AZ-6322.jpg ...
[=                                                 ] 2.85%

Grabbing the full link at https://i.postimg.cc/C1hHMGmc/2022-04-24-UA-Kr-AZ-6322.jpg took 0.38337366199993994 seconds to run

[==================================================] 100.00%

OCR returns: 24/04/2022|Kherson Oblast
Running OCR on https://i.postimg.cc/C1hHMGmc/2022-04-24-UA-Kr-AZ-6322.jpg took 13.149188003000745 seconds to run
8412
8413
Grabbing the full link at https://i.postimg.cc/FHstn6gy/2003-Kr-AZ-255-B-truck-destr-01-05-23.jpg took 0.40703199099880294 seconds to run
8413
8414
Grabbing the full link at https://i.postimg.cc/cCrr5wrm/2014-Kr-AZ-255-B-destr-12-11-22.jpg took 0.4075212290008494 seconds to run
8414
8415
Grabbing the full link at https://i.postimg.cc/qRBty9rW/2015-Kr-AZ-255-B-destr-12-11-22.jpg took 0.4329870839992509 seconds to run
8415
8416
Grabbing the full link at https://i.postimg.cc/rwSzb8Fv/2016-Kr-AZ-255-B-destr-12-11-22.jpg took 0.44559829300123965 seconds to run
8416
8417
Grabbing the full link at https://i.postimg.cc/FKHfghYY/2005-Kr-AZ-255-B-destr-24-09-22.jpg took 0.39641485799984366 seconds to run
8417
8418
Grabbing the full link at https://i.postimg.cc/KzFCBBHm/2017-Kr-AZ-255-B-destr-09-09-24.jpg took 0.37323052499959886 seconds to run
8418
8419
Grabbing the full link at https://i.postimg.cc/wjjD0jPm/2017-Kr-AZ-255-B-destr-09-09-24.jpg took 0.4257578269989608 seconds to run
8419
8420
Grabbing the full link at https://i.postimg.cc/XvTgNNG8/2016-Kr-AZ-255-B-destr-31-10-24.jpg took 0.3987390130005224 seconds to run
8420
8421
Grabbing the full link at https://i.postimg.cc/xj5Q54Kd/2011-Kr-AZ-255-B-destr-03-01-25.jpg took 0.3833829489994969 seconds to run
8421
8422
Grabbing the full link at https://i.postimg.cc/zfSx8kdJ/2002-kraz255b-dam-05-12-23.jpg took 0.38510066799972265 seconds to run
8422
8423
Grabbing the full link at https://i.postimg.cc/G2jDGvM1/Screenshot-9319.png took 0.3957270390001213 seconds to run

Connecting to https://i.postimg.cc/G2jDGvM1/Screenshot-9319.png ...
Downloading Screenshot-9319.png ...
[==================================================] 100.00%

OCR returns: 17/3/2022|AHCK|24|IVCAHCI|SAHCK|格|14.2Kviews|0:09/ 0:31|2
Running OCR on https://i.postimg.cc/G2jDGvM1/Screenshot-9319.png took 29.69877462000113 seconds to run
8423
8424

Connecting to https://i.postimg.cc/g2gTpp0b/415.png ...
Downloading 415.png ...
[                                                  ] 0.54%

Grabbing the full link at https://i.postimg.cc/g2gTpp0b/415.png took 0.4236693759994523 seconds to run

[==================================================] 100.00%

OCR returns: imeafront line.RussiaUkraineWar20220225|imeafrontline.Russia UkraineWar20220225|Onewkn|XepcoH.|OnewKn,|XepcoH.|25.02.22|25.02.22|c|TikTok|TikTok|@andriiboiko93kh|@andriiboiko93kh
Running OCR on https://i.postimg.cc/g2gTpp0b/415.png took 27.336248121999233 seconds to run
8424
8425
Grabbing the full link at https://i.postimg.cc/5tf3zRcG/225.png took 0.36856169900056557 seconds to run

Connecting to https://i.postimg.cc/5tf3zRcG/225.png ...
Downloading 225.png ...
[==================================================] 100.00%

OCR returns: March 2022|DAMMHMPOBAH|https://t.me/istorijaoruzija|4270H
Running OCR on https://i.postimg.cc/5tf3zRcG/225.png took 24.68512749399997 seconds to run
8425
8426
Grabbing the full link at https://i.postimg.cc/9fkwYzXY/2007-Kr-AZ-255-B-tanker-destr-08-04-24.jpg took 0.3729049600005965 seconds to run
8426
8427
Grabbing the full link at https://i.postimg.cc/N0N1FB1N/2002-Kr-AZ-260-destr-31-11-22.jpg took 0.3777110709997942 seconds to run
8427
8428
Grabbing the full link at https://i.postimg.cc/C5r6DZvN/776.png took 0.4304149440013134 seconds to run

Connecting to https://i.postimg.cc/C5r6DZvN/776.png ...
Downloading 776.png ...
[==================================================] 100.00%

OCR returns: 04/3/2022|ZIL-131ARS-14|KraZ-260(ATZ-9.3-260),|KraZ-5233|ZIL-131,ZIL-131（ZU-23）,|ZIL-131ARS-14|GAZ-66,GAZ-3307|GAZ-66|ZIL-131|2BMP-1P|URAL-375,UAZ-469,|GAZ-66
Running OCR on https://i.postimg.cc/C5r6DZvN/776.png took 30.790886750000936 seconds to run
8428
8429
Grabbing the full link at https://i.postimg.cc/NjFSSs6g/43i.jpg took 0.37678921699989587 seconds to run

Connecting to https://i.postimg.cc/NjFSSs6g/43i.jpg ...
Downloading 43i.jpg ...
[==================================================] 100.00%

OCR returns: 30/03/2022|国
Running OCR on https://i.postimg.cc/NjFSSs6g/43i.jpg took 24.755338566999853 seconds to run
8429
8430
Grabbing the full link at https://i.postimg.cc/4xzqNWbC/4668.png took 0.5456245690002106 seconds to run

Connecting to https://i.postimg.cc/4xzqNWbC/4668.png ...
Downloading 4668.png ...
[==================================================] 100.00%

OCR returns: H:|09/4/2022
Running OCR on https://i.postimg.cc/4xzqNWbC/4668.png took 27.503697961999933 seconds to run
8430
8431
Grabbing the full link at https://i.postimg.cc/jSJW85jm/64.jpg took 0.38458424099917465 seconds to run

Connecting to https://i.postimg.cc/jSJW85jm/64.jpg ...
Downloading 64.jpg ...
[==================================================] 100.00%

OCR returns: 24.04.2022
Running OCR on https://i.postimg.cc/jSJW85jm/64.jpg took 22.80782415700014 seconds to run
8431
8432
Grabbing the full link at https://i.postimg.cc/3JQbBs2Q/287.png took 0.4114073759992607 seconds to run

Connecting to https://i.postimg.cc/3JQbBs2Q/287.png ...
Downloading 287.png ...
[==================================================] 100.00%

OCR returns: RVvoenkor|30/4/2022|RusVesna Su|RVvoenkor|RusVesna Su
Running OCR on https://i.postimg.cc/3JQbBs2Q/287.png took 22.334394477000387 seconds to run
8432
8433

Connecting to https://i.postimg.cc/3JQbBs2Q/287.png ...
Downloading 287.png ...
[                                                  ] 0.31%

Grabbing the full link at https://i.postimg.cc/3JQbBs2Q/287.png took 0.47796916699917347 seconds to run

[==================================================] 100.00%

OCR returns: RVvoenkor|30/4/2022|RusVesna Su|RVvoenkor|RusVesna Su
Running OCR on https://i.postimg.cc/3JQbBs2Q/287.png took 20.92179095499887 seconds to run
8433
8434

Connecting to https://i.postimg.cc/3JQbBs2Q/287.png ...
Downloading 287.png ...
[                                                  ] 0.31%

Grabbing the full link at https://i.postimg.cc/3JQbBs2Q/287.png took 0.3803218630000629 seconds to run

[==================================================] 100.00%

OCR returns: RVvoenkor|30/4/2022|RusVesna Su|RVvoenkor|RusVesna Su
Running OCR on https://i.postimg.cc/3JQbBs2Q/287.png took 20.832163232998937 seconds to run
8434
8435
Grabbing the full link at https://i.postimg.cc/CxnhNhSb/2004-Kr-AZ-5233-destr-30-04-22.jpg took 0.37434830100028194 seconds to run
8435
8436
Grabbing the full link at https://i.postimg.cc/hPHsycCC/2701.jpg took 0.37362399399899004 seconds to run

Connecting to https://i.postimg.cc/hPHsycCC/2701.jpg ...
Downloading 2701.jpg ...
[==================================================] 100.00%

OCR returns: Bogdan-63172|KrAZ-5233|03/07/2022
Running OCR on https://i.postimg.cc/hPHsycCC/2701.jpg took 23.431489693000913 seconds to run
8436
8437
Grabbing the full link at https://i.postimg.cc/T2sNcP8r/2030-Kr-AZ-5233-destr-29-08-22.jpg took 0.3825361729996075 seconds to run
8437
8438
Grabbing the full link at https://i.postimg.cc/7Pg2YVww/2016-Kr-AZ-5233-destr-30-04-22.jpg took 0.3962176470013219 seconds to run
8438
8439
Grabbing the full link at https://i.postimg.cc/sfh1MQ1x/2009-Kr-AZ-5233-destr-12-01-23.jpg took 0.38185331000022416 seconds to run
8439
8440
Grabbing the full link at https://i.postimg.cc/FR3F4Y5w/2008-Kr-AZ-5322-destr-26-02-23.jpg took 0.369480499999554 seconds to run
8440
8441
Grabbing the full link at https://i.postimg.cc/k52sy9Vh/4f221.png took 0.37245226400045794 seconds to run

Connecting to https://i.postimg.cc/k52sy9Vh/4f221.png ...
Downloading 4f221.png ...
[==================================================] 100.00%

OCR returns: 16/4/2022
Running OCR on https://i.postimg.cc/k52sy9Vh/4f221.png took 12.168153333999726 seconds to run
8441
8442
Grabbing the full link at https://i.postimg.cc/hvv6sQ7j/2022-kraz6322-destr-15-04-22.jpg took 0.3695367719992646 seconds to run
8442
8443
Grabbing the full link at https://i.postimg.cc/4Ny50z39/2022-04-10-Kr-AZ-5233-destroyed-2.jpg took 0.36145812399990973 seconds to run

Connecting to https://i.postimg.cc/4Ny50z39/2022-04-10-Kr-AZ-5233-destroyed-2.jpg ...
Downloading 2022-04-10-Kr-AZ-5233-destroyed-2.jpg ...
[==================================================] 100.00%

OCR returns: 10/04/2022|Varivske, KyivOblast
Running OCR on https://i.postimg.cc/4Ny50z39/2022-04-10-Kr-AZ-5233-destroyed-2.jpg took 23.84179505299835 seconds to run
8443
8444
Grabbing the full link at https://i.postimg.cc/HsN21VJP/2022-04-10-UA-Kr-AZ-5233-destroyed.jpg took 0.5307669769990753 seconds to run

Connecting to https://i.postimg.cc/HsN21VJP/2022-04-10-UA-Kr-AZ-5233-destroyed.jpg ...
Downloading 2022-04-10-UA-Kr-AZ-5233-destroyed.jpg ...
[==================================================] 100.00%

OCR returns: 10/04/2022|Varivske, Kyiv Oblast
Running OCR on https://i.postimg.cc/HsN21VJP/2022-04-10-UA-Kr-AZ-5233-destroyed.jpg took 23.508704668000064 seconds to run
8444
8445

Connecting to https://i.postimg.cc/BQGGrBnJ/427.png ...
Downloading 427.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/BQGGrBnJ/427.png took 0.3962908690009499 seconds to run

[==================================================] 100.00%

OCR returns: 19/9/2023
Running OCR on https://i.postimg.cc/BQGGrBnJ/427.png took 21.83751485600078 seconds to run
8445
8446
Grabbing the full link at https://i.postimg.cc/T1K6HNRN/2002-Kr-AZ-5233-destr-25-02-22.jpg took 0.43276202699962596 seconds to run
8446
8447
Grabbing the full link at https://i.postimg.cc/zGsVCvny/2008-Kr-AZ-5233-destr-25-07-23.jpg took 0.39980478699908417 seconds to run
8447
8448
Grabbing the full link at https://i.postimg.cc/43BYrW07/2008-Kr-AZ-5233-destr-12-03-22.jpg took 0.3962078200001997 seconds to run
8448
8449
Grabbing the full link at https://i.postimg.cc/PrTh0bMK/2013-Kr-AZ-5233-destr-01-11-22.jpg took 0.3734511959992233 seconds to run
8449
8450
Grabbing the full link at https://i.postimg.cc/Dy883wnh/2034-Kr-AZ-5233-destr-07-04-24.jpg took 0.4169128199991974 seconds to run
8450
8451
Grabbing the full link at https://i.postimg.cc/zXHjGp5s/2008-Kr-AZ-5233-destr-21-06-24.jpg took 0.40638771900012216 seconds to run
8451
8452
Grabbing the full link at https://i.postimg.cc/wM9M11ZK/2002-Kr-AZ-5233-destr-09-07-24.jpg took 0.4625009460014553 seconds to run
8452
8453
Grabbing the full link at https://i.postimg.cc/L8pcv6Hd/2006-Kr-AZ-5233-destr-07-08-24.jpg took 0.38018227000065963 seconds to run
8453
8454
Grabbing the full link at https://i.postimg.cc/nL8Pf08B/2041-Kr-AZ-5233-destr-17-09-24.jpg took 0.4201424639995821 seconds to run
8454
8455
Grabbing the full link at https://i.postimg.cc/PJ3hzRzj/2007-Kr-AZ-5233-destr-26-12-24.jpg took 0.39411778500107175 seconds to run
8455
8456
Grabbing the full link at https://i.postimg.cc/15zQjrHr/2014-Kr-AZ-5233-destr-16-12-24.jpg took 0.406253855999239 seconds to run
8456
8457
Grabbing the full link at https://i.postimg.cc/PfWm2PmL/2006-Kr-AZ-5233-destr-31-08-24.jpg took 0.45357432099990547 seconds to run
8457
8458
Grabbing the full link at https://i.postimg.cc/hPKVwcr2/2007-Kr-AZ-5233-destr-31-08-24.jpg took 0.4395929549991706 seconds to run
8458
8459
Grabbing the full link at https://i.postimg.cc/bvcCRHVY/2009-Kr-AZ-5233-destr-13-02-25.jpg took 0.41428519200053415 seconds to run
8459
8460
Grabbing the full link at https://i.postimg.cc/76VQgYxg/5g9.png took 0.41246419299932313 seconds to run

Connecting to https://i.postimg.cc/76VQgYxg/5g9.png ...
Downloading 5g9.png ...
[==================================================] 100.00%

OCR returns: 14/4/2023
Running OCR on https://i.postimg.cc/76VQgYxg/5g9.png took 13.645490967001024 seconds to run
8460
8461
Grabbing the full link at https://i.postimg.cc/SQXzX1yB/2022-Kr-AZ-5233-aband-26-04-25.jpg took 0.4526044030008052 seconds to run
8461
8462
Grabbing the full link at https://i.postimg.cc/fR5HJv28/dd11.png took 0.494310318999851 seconds to run

Connecting to https://i.postimg.cc/fR5HJv28/dd11.png ...
Downloading dd11.png ...
[==================================================] 100.00%

OCR returns: @smotri_media|@smotri_media|2|3|07/3/2022
Running OCR on https://i.postimg.cc/fR5HJv28/dd11.png took 14.428764448000948 seconds to run
8462
8463

Connecting to https://i.postimg.cc/fR5HJv28/dd11.png ...
Downloading dd11.png ...
[                                                  ] 0.38%

Grabbing the full link at https://i.postimg.cc/fR5HJv28/dd11.png took 0.4560147469983349 seconds to run

[==================================================] 100.00%

OCR returns: @smotri_media|@smotri_media|2|3|07/3/2022
Running OCR on https://i.postimg.cc/fR5HJv28/dd11.png took 13.258429355999397 seconds to run
8463
8464

Connecting to https://i.postimg.cc/fR5HJv28/dd11.png ...
Downloading dd11.png ...
[                                                  ] 0.38%

Grabbing the full link at https://i.postimg.cc/fR5HJv28/dd11.png took 0.3942525170004956 seconds to run

[==================================================] 100.00%

OCR returns: @smotri_media|@smotri_media|2|3|07/3/2022
Running OCR on https://i.postimg.cc/fR5HJv28/dd11.png took 13.311582991998876 seconds to run
8464
8465
Grabbing the full link at https://i.postimg.cc/sfJzxw3j/776.png took 0.8038443739987997 seconds to run

Connecting to https://i.postimg.cc/sfJzxw3j/776.png ...
Downloading 776.png ...
[==================================================] 100.00%

OCR returns: 04/3/2022|ARS-14|KraZ-260（ATZ-9.3-260），|aZ-5233|ZIL-131,ZIL-131(ZU-23)，|ZIL-131ARS-14|GAZ-66,GAZ-3307|GAZ-66|ZIL-131|2BMP-1P|URAL-375,UAZ-469,|GAZ-66
Running OCR on https://i.postimg.cc/sfJzxw3j/776.png took 28.813482211999144 seconds to run
8465
8466
Grabbing the full link at https://i.postimg.cc/vmpRN9VB/480.png took 0.37344023600053333 seconds to run

Connecting to https://i.postimg.cc/vmpRN9VB/480.png ...
Downloading 480.png ...
[==================================================] 100.00%

OCR returns: 23/3/2022
Running OCR on https://i.postimg.cc/vmpRN9VB/480.png took 53.240525698000056 seconds to run
8466
8467
Grabbing the full link at https://i.postimg.cc/jq49zBZC/480.png took 0.43695148000006157 seconds to run

Connecting to https://i.postimg.cc/jq49zBZC/480.png ...
Downloading 480.png ...
[==================================================] 100.00%

OCR returns: 23/3/2022
Running OCR on https://i.postimg.cc/jq49zBZC/480.png took 30.624284827999873 seconds to run
8467
8468
Grabbing the full link at https://i.postimg.cc/265Nhxbz/393.png took 0.989780559000792 seconds to run

Connecting to https://i.postimg.cc/265Nhxbz/393.png ...
Downloading 393.png ...
[==================================================] 100.00%

OCR returns: 16/4/2022
Running OCR on https://i.postimg.cc/265Nhxbz/393.png took 22.960870212998998 seconds to run
8468
8469
Grabbing the full link at https://i.postimg.cc/265Nhxbz/393.png took 1.107387063000715 seconds to run

Connecting to https://i.postimg.cc/265Nhxbz/393.png ...
Downloading 393.png ...
[==================================================] 100.00%

OCR returns: 16/4/2022
Running OCR on https://i.postimg.cc/265Nhxbz/393.png took 23.276290443000107 seconds to run
8469
8470
Grabbing the full link at https://i.postimg.cc/kgbQvfh1/d16.png took 0.4424265979996562 seconds to run

Connecting to https://i.postimg.cc/kgbQvfh1/d16.png ...
Downloading d16.png ...
[==================================================] 100.00%

OCR returns: BHNMAHNE!|HA TEPPHTOPHN KOMEHHATA|BEnETCR|BHIEOHAEJIIONEHNE|@zhganovrt|25/5/2022
Running OCR on https://i.postimg.cc/kgbQvfh1/d16.png took 26.859022029999323 seconds to run
8470
8471
Returning non-postimg link
8471
8472
Grabbing the full link at https://i.postimg.cc/Gh9ZQSm1/a335.png took 0.40704185299910023 seconds to run

Connecting to https://i.postimg.cc/Gh9ZQSm1/a335.png ...
Downloading a335.png ...
[==================================================] 100.00%

OCR returns: 05/9/2022|GGAL
Running OCR on https://i.postimg.cc/Gh9ZQSm1/a335.png took 26.79170511099983 seconds to run
8472
8473
Grabbing the full link at https://i.postimg.cc/2ymcx5p5/2018-Kr-AZ-5233-capt-04-06-22.jpg took 0.3871859980008594 seconds to run
8473
8474
Grabbing the full link at https://i.postimg.cc/mkZZN7gr/2003-Kr-AZ-5233-capt-20-06-22.jpg took 0.3731329040001583 seconds to run
8474
8475
Grabbing the full link at https://i.postimg.cc/50CwqJ19/5444.png took 0.36791604600148275 seconds to run

Connecting to https://i.postimg.cc/50CwqJ19/5444.png ...
Downloading 5444.png ...
[==================================================] 100.00%

OCR returns: 28/3/2022|1614E6
Running OCR on https://i.postimg.cc/50CwqJ19/5444.png took 24.86832836999929 seconds to run
8475
8476
Grabbing the full link at https://i.postimg.cc/MT0QM4sL/33311.png took 0.8796442620005109 seconds to run

Connecting to https://i.postimg.cc/MT0QM4sL/33311.png ...
Downloading 33311.png ...
[==================================================] 100.00%

OCR returns: 13/3/2022|5353
Running OCR on https://i.postimg.cc/MT0QM4sL/33311.png took 12.893269788999532 seconds to run
8476
8477
Grabbing the full link at https://i.postimg.cc/CK34jkkQ/2004-Kr-AZ-5233-capt-28-02-22.jpg took 1.6196939120000025 seconds to run
8477
8478
Grabbing the full link at https://i.postimg.cc/L5yR6Mjq/2009-kraz5322-capt-01-03-22.jpg took 0.541919166000298 seconds to run
8478
8479

Connecting to https://i.postimg.cc/fWxRgjt0/555g.png ...
Downloading 555g.png ...
[                                                  ] 0.20%

Grabbing the full link at https://i.postimg.cc/fWxRgjt0/555g.png took 0.5048800980002852 seconds to run

[==================================================] 100.00%

OCR returns: 12/6/2022
Running OCR on https://i.postimg.cc/fWxRgjt0/555g.png took 26.62675554099951 seconds to run
8479
8480
Grabbing the full link at https://i.postimg.cc/Z5ys3DcD/2005-Kr-AZ-5233-capt-13-03-22.jpg took 0.37776793699958944 seconds to run
8480
8481
Grabbing the full link at https://i.postimg.cc/0QMkBhwk/Screenshot-8021.png took 0.3914828959987062 seconds to run

Connecting to https://i.postimg.cc/0QMkBhwk/Screenshot-8021.png ...
Downloading Screenshot-8021.png ...
[==================================================] 100.00%

OCR returns: 24/02/2022|602 views|0:16/0:23|1|0
Running OCR on https://i.postimg.cc/0QMkBhwk/Screenshot-8021.png took 28.498822559000473 seconds to run
8481
8482
Grabbing the full link at https://i.postimg.cc/rpSkR4S2/2000-Kr-AZ-6322-destr-03-03-23.jpg took 0.4969490000003134 seconds to run
8482
8483
Grabbing the full link at https://i.postimg.cc/yxSqxF6N/2005-Kr-AZ-6322-destr-28-02-23.jpg took 1.026765125001475 seconds to run
8483
8484
Grabbing the full link at https://i.postimg.cc/vBdfY7td/Screenshot-8019.png took 0.5223460939996585 seconds to run

Connecting to https://i.postimg.cc/vBdfY7td/Screenshot-8019.png ...
Downloading Screenshot-8019.png ...
[==================================================] 100.00%

OCR returns: 24/02/2022|602 views|0:09/0:23|2|0
Running OCR on https://i.postimg.cc/vBdfY7td/Screenshot-8019.png took 27.98091120800018 seconds to run
8484
8485
Grabbing the full link at https://i.postimg.cc/BZjGgMFV/1004-t72b3.jpg took 0.4550828210012696 seconds to run

Connecting to https://i.postimg.cc/BZjGgMFV/1004-t72b3.jpg ...
Downloading 1004-t72b3.jpg ...
[==================================================] 100.00%

Running OCR on https://i.postimg.cc/BZjGgMFV/1004-t72b3.jpg took 27.091703582000264 seconds to run
8485
8486
Grabbing the full link at https://i.postimg.cc/sfWCv4wL/s3.png took 0.4023906589991384 seconds to run

Connecting to https://i.postimg.cc/sfWCv4wL/s3.png ...
Downloading s3.png ...
[==================================================] 100.00%

OCR returns: 08/04/2022|Hostomel|Airport|↓
Running OCR on https://i.postimg.cc/sfWCv4wL/s3.png took 27.655304366000564 seconds to run
8486
8487
Grabbing the full link at https://i.postimg.cc/L5k9q4Vc/2217.png took 0.37308673999905295 seconds to run

Connecting to https://i.postimg.cc/L5k9q4Vc/2217.png ...
Downloading 2217.png ...
[==================================================] 100.00%

OCR returns: 04/10/2022|REDMINOTE8PRO|LQUADCAMERA
Running OCR on https://i.postimg.cc/L5k9q4Vc/2217.png took 14.775343928000439 seconds to run
8487
8488
Grabbing the full link at https://i.postimg.cc/QC4vXLRx/2001-Kraz-6322-destr-23-01-23.jpg took 0.504269982000551 seconds to run
8488
8489
Grabbing the full link at https://i.postimg.cc/FzYYNfCX/2022-11-13-UA-Kr-AZ-6322-destroyed.jpg took 0.4755069930015452 seconds to run

Connecting to https://i.postimg.cc/FzYYNfCX/2022-11-13-UA-Kr-AZ-6322-destroyed.jpg ...
Downloading 2022-11-13-UA-Kr-AZ-6322-destroyed.jpg ...
[==================================================] 100.00%

OCR returns: 13/11/2022|Kherson Airport|WM Blood|hualtmefwinnc
Running OCR on https://i.postimg.cc/FzYYNfCX/2022-11-13-UA-Kr-AZ-6322-destroyed.jpg took 28.070947379001154 seconds to run
8489
8490
Grabbing the full link at https://i.postimg.cc/C1FDTxVw/2022-11-13-UA-Kr-AZ-6322-destroyed-2.jpg took 0.5504237980003381 seconds to run

Connecting to https://i.postimg.cc/C1FDTxVw/2022-11-13-UA-Kr-AZ-6322-destroyed-2.jpg ...
Downloading 2022-11-13-UA-Kr-AZ-6322-destroyed-2.jpg ...
[==================================================] 100.00%

OCR returns: WM Blood|13/11/2022|https://t.me/winua22|Kherson Airport
Running OCR on https://i.postimg.cc/C1FDTxVw/2022-11-13-UA-Kr-AZ-6322-destroyed-2.jpg took 31.73680987700027 seconds to run
8490
8491
Grabbing the full link at https://i.postimg.cc/G2QFHsjB/2022-11-13-UA-Kr-AZ-6322-destroyed-3.jpg took 0.3952274139992369 seconds to run

Connecting to https://i.postimg.cc/G2QFHsjB/2022-11-13-UA-Kr-AZ-6322-destroyed-3.jpg ...
Downloading 2022-11-13-UA-Kr-AZ-6322-destroyed-3.jpg ...
[==================================================] 100.00%

OCR returns: WMBlood|13/11/2022|https://t.me/winua22|Kherson Airport
Running OCR on https://i.postimg.cc/G2QFHsjB/2022-11-13-UA-Kr-AZ-6322-destroyed-3.jpg took 28.111376945998927 seconds to run
8491
8492

Connecting to https://i.postimg.cc/yNDh5XND/2022-04-07-Kr-AZ-6322-destroyed.jpg ...
Downloading 2022-04-07-Kr-AZ-6322-destroyed.jpg ...
[=                                                 ] 3.02%

Grabbing the full link at https://i.postimg.cc/yNDh5XND/2022-04-07-Kr-AZ-6322-destroyed.jpg took 0.41867656799877295 seconds to run

[==================================================] 100.00%

OCR returns: 07/04/2022
Running OCR on https://i.postimg.cc/yNDh5XND/2022-04-07-Kr-AZ-6322-destroyed.jpg took 12.966470477998882 seconds to run
8492
8493
Grabbing the full link at https://i.postimg.cc/TwmPMLRt/2002-Kraz-pontoon-bridge-truck.jpg took 0.4208114510001906 seconds to run

Connecting to https://i.postimg.cc/TwmPMLRt/2002-Kraz-pontoon-bridge-truck.jpg ...
Downloading 2002-Kraz-pontoon-bridge-truck.jpg ...
[==================================================] 100.00%

OCR returns: 27.07.22|Play|□|0:48/4:08
Running OCR on https://i.postimg.cc/TwmPMLRt/2002-Kraz-pontoon-bridge-truck.jpg took 30.31268415299928 seconds to run
8493
8494
Grabbing the full link at https://i.postimg.cc/Qd9Tqh7G/2010-Kr-AZ-6322-destr-06-04-22.jpg took 0.39845969899943157 seconds to run
8494
8495
Grabbing the full link at https://i.postimg.cc/GtQMg1rx/2008-Kr-AZ-6322-destr-15-07-22.jpg took 0.4205849260015384 seconds to run
8495
8496

Connecting to https://i.postimg.cc/sXvZJTzw/54k.png ...
Downloading 54k.png ...
[                                                  ] 0.19%

Grabbing the full link at https://i.postimg.cc/sXvZJTzw/54k.png took 0.37386570099988603 seconds to run

[==================================================] 100.00%

OCR returns: 30/11/2022
Running OCR on https://i.postimg.cc/sXvZJTzw/54k.png took 23.13747910999882 seconds to run
8496
8497
Grabbing the full link at https://i.postimg.cc/ZYdDY9T4/2010-Kra-AZ-6322-destr-07-05-23.jpg took 0.38511346300037985 seconds to run
8497
8498
Grabbing the full link at https://i.postimg.cc/YCngX9Lh/2026-1x-Kr-AZ-6322-2x-gaz66-destr-04-06-23.jpg took 0.36928398499912873 seconds to run
8498
8499
Grabbing the full link at https://i.postimg.cc/NGrCTt2V/2011-Kr-AZ-6322-destr-02-07-23.jpg took 0.3868219070009218 seconds to run
8499
8500
Grabbing the full link at https://i.postimg.cc/MH2R4n19/2004-Kraz-6322-Soldat-destr-31-07-23.jpg took 0.3863354029999755 seconds to run
8500
Saved at index 8500
8501
Grabbing the full link at https://i.postimg.cc/q7HGTHXG/3320.png took 0.44398783199903846 seconds to run

Connecting to https://i.postimg.cc/q7HGTHXG/3320.png ...
Downloading 3320.png ...
[==================================================] 100.00%

OCR returns: 31/5/2022
Running OCR on https://i.postimg.cc/q7HGTHXG/3320.png took 17.656220431001202 seconds to run
8501
8502
Grabbing the full link at https://i.postimg.cc/Nj3djHYm/4460.png took 0.3949974210008804 seconds to run

Connecting to https://i.postimg.cc/Nj3djHYm/4460.png ...
Downloading 4460.png ...
[==================================================] 100.00%

OCR returns: 31/5/2022
Running OCR on https://i.postimg.cc/Nj3djHYm/4460.png took 22.93581170899961 seconds to run
8502
8503
Grabbing the full link at https://i.postimg.cc/tJRzFpvz/43f4.png took 0.5500674229988363 seconds to run

Connecting to https://i.postimg.cc/tJRzFpvz/43f4.png ...
Downloading 43f4.png ...
[==================================================] 100.00%

OCR returns: 29/3/2023
Running OCR on https://i.postimg.cc/tJRzFpvz/43f4.png took 26.38756421799917 seconds to run
8503
8504
Grabbing the full link at https://i.postimg.cc/CKyVWVjq/75.png took 0.465591514001062 seconds to run

Connecting to https://i.postimg.cc/CKyVWVjq/75.png ...
Downloading 75.png ...
[==================================================] 100.00%

OCR returns: 25/8/2023|t.me/Ukr_G_M|t.me/Ukr_G_M|t.me/Ukr_G_M
Running OCR on https://i.postimg.cc/CKyVWVjq/75.png took 44.42462106600033 seconds to run
8504
8505
Grabbing the full link at https://i.postimg.cc/ZqjwVxBf/329.png took 0.5335023890002049 seconds to run

Connecting to https://i.postimg.cc/ZqjwVxBf/329.png ...
Downloading 329.png ...
[==================================================] 100.00%

OCR returns: 05/9/2023
Running OCR on https://i.postimg.cc/ZqjwVxBf/329.png took 24.09712105899962 seconds to run
8505
8506

Connecting to https://i.postimg.cc/ZqjwVxBf/329.png ...
Downloading 329.png ...
[                                                  ] 0.58%

Grabbing the full link at https://i.postimg.cc/ZqjwVxBf/329.png took 0.5393154689991206 seconds to run

[==================================================] 100.00%

OCR returns: 05/9/2023
Running OCR on https://i.postimg.cc/ZqjwVxBf/329.png took 13.735770555000272 seconds to run
8506
8507
Grabbing the full link at https://i.postimg.cc/cCpzggzn/335.png took 0.37772977399981755 seconds to run

Connecting to https://i.postimg.cc/cCpzggzn/335.png ...
Downloading 335.png ...
[==================================================] 100.00%

OCR returns: 4|17/8/2023
Running OCR on https://i.postimg.cc/cCpzggzn/335.png took 12.524189343999751 seconds to run
8507
8508
Grabbing the full link at https://i.postimg.cc/nzRJ8yr5/2480.png took 0.43960574099946825 seconds to run

Connecting to https://i.postimg.cc/nzRJ8yr5/2480.png ...
Downloading 2480.png ...
[==================================================] 100.00%

OCR returns: 19/9/2023
Running OCR on https://i.postimg.cc/nzRJ8yr5/2480.png took 24.272399718000088 seconds to run
8508
8509
Grabbing the full link at https://i.postimg.cc/T11TpRBf/257.png took 0.37117764399954467 seconds to run

Connecting to https://i.postimg.cc/T11TpRBf/257.png ...
Downloading 257.png ...
[==================================================] 100.00%

OCR returns: 19/9/2023|Shot on BV9600Pro|Powered byBlackview
Running OCR on https://i.postimg.cc/T11TpRBf/257.png took 24.997574815999542 seconds to run
8509
8510
Grabbing the full link at https://i.postimg.cc/NLh3H5Lk/2006-2x-Kr-AZ-6322-destr-28-02-23.jpg took 0.8452324570007477 seconds to run
8510
8511
Grabbing the full link at https://i.postimg.cc/NLh3H5Lk/2006-2x-Kr-AZ-6322-destr-28-02-23.jpg took 0.5251641279992327 seconds to run
8511
8512
Grabbing the full link at https://i.postimg.cc/YS4M4vh2/2013-Kr-AZ-6322-destr-31-10-23.jpg took 0.5189453910006705 seconds to run
8512
8513
Grabbing the full link at https://i.postimg.cc/j52CvPB5/2030-Kr-AZ-6322-destr-30-11-23.jpg took 0.9501873070003057 seconds to run
8513
8514
Grabbing the full link at https://i.postimg.cc/ZRbLF7g2/2007-Kr-AZ-6322-destr-31-03-22.jpg took 0.5274232730007498 seconds to run
8514
8515
Grabbing the full link at https://i.postimg.cc/rwJF1G7c/2020-Kr-AZ-6322-destr-08-11-23.jpg took 0.5310641430005489 seconds to run
8515
8516
Grabbing the full link at https://i.postimg.cc/pd58FRHj/uukt2.jpg took 2.298263874999975 seconds to run

Connecting to https://i.postimg.cc/pd58FRHj/uukt2.jpg ...
Downloading uukt2.jpg ...
[==================================================] 100.00%

OCR returns: 06.04.2022|MyskckouKnyonacca
Running OCR on https://i.postimg.cc/pd58FRHj/uukt2.jpg took 23.297872602999632 seconds to run
8516
8517
Grabbing the full link at https://i.postimg.cc/MTsxFBBc/2009-Kr-AZ-6322-destr-21-03-24.jpg took 0.3948972189991764 seconds to run
8517
8518
Grabbing the full link at https://i.postimg.cc/PJqb2jXr/2014-Kr-AZ-6322-destr-10-08-22.jpg took 0.4526210789990728 seconds to run
8518
8519
Grabbing the full link at https://i.postimg.cc/NMMy4681/2003-Kr-AZ-6322-destr-13-07-24.jpg took 0.4637580689995957 seconds to run
8519
8520
Grabbing the full link at https://i.postimg.cc/1zyyPHbP/2011-Kr-AZ-6322-destr-10-08-24.jpg took 0.46066203500049596 seconds to run
8520
8521
Grabbing the full link at https://i.postimg.cc/c4DGQXPZ/2013-Kr-AZ-6322-destr-31-07-24.jpg took 0.829835851000098 seconds to run
8521
8522
Grabbing the full link at https://i.postimg.cc/j20ysM7R/2008-Kr-AZ-6322-destr-03-07-24.jpg took 0.49712285900022835 seconds to run
8522
8523
Grabbing the full link at https://i.postimg.cc/DyXvMh8y/2029-Kr-AZ-6322-destr-30-09-24.jpg took 0.4038581910008361 seconds to run
8523
8524
Grabbing the full link at https://i.postimg.cc/P5btdMWg/2032-Kr-AZ-6322-destr-28-09-24.jpg took 0.5077681700004177 seconds to run
8524
8525
Grabbing the full link at https://i.postimg.cc/5tsgjzjL/2000-Kr-AZ-6322-destr-01-10-22.jpg took 0.5372453880008834 seconds to run
8525
8526
Grabbing the full link at https://i.postimg.cc/50k7xfwB/2027-Kr-AZ-6322-destr-02-01-25.jpg took 0.5302374799994141 seconds to run
8526
8527
Grabbing the full link at https://i.postimg.cc/cHqLvVHJ/2017-Kr-AZ-6322-destr-20-03-25.jpg took 0.5406504460006545 seconds to run
8527
8528
Grabbing the full link at https://i.postimg.cc/FzN9Nrvd/2009-Kr-AZ-6322-destr-10-01-24.jpg took 0.5173098750001373 seconds to run
8528
8529
Grabbing the full link at https://i.postimg.cc/XqLnvRN2/2010-Kr-AZ-6322-destr-10-04-24.jpg took 0.5128802920007729 seconds to run
8529
8530
Grabbing the full link at https://i.postimg.cc/1RMf8t1N/2017-Kr-AZ-6322-destr-04-05-25.jpg took 0.42414208000082 seconds to run
8530
8531
Grabbing the full link at https://i.postimg.cc/7L7Qr3Hv/2000-Kr-AZ-6322-destr-05-05-25.jpg took 0.47944447100053367 seconds to run
8531
8532
Grabbing the full link at https://i.postimg.cc/76ktH5h5/2002-Kr-AZ-6322-destr-01-05-25.jpg took 0.4705290429992601 seconds to run
8532
8533
Grabbing the full link at https://i.postimg.cc/FHSn1hYM/2002-Kr-AZ-6322-destr-21-07-25.jpg took 1.8320348219986045 seconds to run
8533
8534
Grabbing the full link at https://i.postimg.cc/vZddS15B/2002-Kr-AZ-6322-dam-30-01-24.jpg took 1.3890358600001491 seconds to run
8534
8535
Grabbing the full link at https://i.postimg.cc/nrmS7T64/2007-Kr-AZ-6322-dam-21-06-24.jpg took 0.5522271980007645 seconds to run
8535
8536
Grabbing the full link at https://i.postimg.cc/YSCTXgWM/Screenshot-8024.png took 0.5195287949991325 seconds to run

Connecting to https://i.postimg.cc/YSCTXgWM/Screenshot-8024.png ...
Downloading Screenshot-8024.png ...
[==================================================] 100.00%

OCR returns: 24/02/2022|602 views|0:18/0:23|1|☆
Running OCR on https://i.postimg.cc/YSCTXgWM/Screenshot-8024.png took 27.06301505400006 seconds to run
8536
8537
Grabbing the full link at https://i.postimg.cc/8c7GjB1r/31.png took 0.5443477539993182 seconds to run

Connecting to https://i.postimg.cc/8c7GjB1r/31.png ...
Downloading 31.png ...
[==================================================] 100.00%

OCR returns: 08/5/2022|6152P5
Running OCR on https://i.postimg.cc/8c7GjB1r/31.png took 26.770065527000042 seconds to run
8537
8538
Grabbing the full link at https://i.postimg.cc/ZKYPvctb/Screenshot-8017.png took 0.4389975220001361 seconds to run

Connecting to https://i.postimg.cc/ZKYPvctb/Screenshot-8017.png ...
Downloading Screenshot-8017.png ...
[==================================================] 100.00%

OCR returns: 24/02/2022|602views|0:08/0:23|1|0
Running OCR on https://i.postimg.cc/ZKYPvctb/Screenshot-8017.png took 27.44893138900079 seconds to run
8538
8539
Grabbing the full link at https://i.postimg.cc/m2sVjnKd/44311.png took 0.5176619819994812 seconds to run

Connecting to https://i.postimg.cc/m2sVjnKd/44311.png ...
Downloading 44311.png ...
[==================================================] 100.00%

OCR returns: @smotri_media|@smotri_media|2|1
Running OCR on https://i.postimg.cc/m2sVjnKd/44311.png took 13.971106727000006 seconds to run
8539
8540

Connecting to https://i.postimg.cc/m2sVjnKd/44311.png ...
Downloading 44311.png ...
[                                                  ] 0.35%

Grabbing the full link at https://i.postimg.cc/m2sVjnKd/44311.png took 0.3847827829995367 seconds to run

[==================================================] 100.00%

OCR returns: @smotri_media|@smotri_media|2|1
Running OCR on https://i.postimg.cc/m2sVjnKd/44311.png took 12.878554672999599 seconds to run
8540
8541

Connecting to https://i.postimg.cc/hvdD2hLs/479.png ...
Downloading 479.png ...
[                                                  ] 0.30%

Grabbing the full link at https://i.postimg.cc/hvdD2hLs/479.png took 0.37129647599977034 seconds to run

[==================================================] 100.00%

OCR returns: 19/4/2022|0:22/ 2:10
Running OCR on https://i.postimg.cc/hvdD2hLs/479.png took 25.933253719000277 seconds to run
8541
8542
Grabbing the full link at https://i.postimg.cc/5NWBD7d7/1007.png took 0.5597048479994555 seconds to run

Connecting to https://i.postimg.cc/5NWBD7d7/1007.png ...
Downloading 1007.png ...
[==================================================] 100.00%

OCR returns: 01.03.2022|amic
Running OCR on https://i.postimg.cc/5NWBD7d7/1007.png took 6.199417600000743 seconds to run
8542
8543
Grabbing the full link at https://i.postimg.cc/fTv9pMvy/1008.png took 0.9688340029988467 seconds to run

Connecting to https://i.postimg.cc/fTv9pMvy/1008.png ...
Downloading 1008.png ...
[==================================================] 100.00%

OCR returns: OPUNO!|01.03.2022
Running OCR on https://i.postimg.cc/fTv9pMvy/1008.png took 5.265910740001345 seconds to run
8543
8544
Grabbing the full link at https://i.postimg.cc/VkR3B45K/Screenshot-8023.png took 0.5183370830000058 seconds to run

Connecting to https://i.postimg.cc/VkR3B45K/Screenshot-8023.png ...
Downloading Screenshot-8023.png ...
[==================================================] 100.00%

OCR returns: 24/02/2022|602 views|0:17/0:23|1|0
Running OCR on https://i.postimg.cc/VkR3B45K/Screenshot-8023.png took 27.466683353999542 seconds to run
8544
8545
Grabbing the full link at https://i.postimg.cc/02gR8bL0/Screenshot-8022.png took 0.41355155800010834 seconds to run

Connecting to https://i.postimg.cc/02gR8bL0/Screenshot-8022.png ...
Downloading Screenshot-8022.png ...
[==================================================] 100.00%

OCR returns: 24/02/2022|602views|0:16/0:23|1|0
Running OCR on https://i.postimg.cc/02gR8bL0/Screenshot-8022.png took 27.463135770000008 seconds to run
8545
8546
Grabbing the full link at https://i.postimg.cc/BvCS3ctn/2003-Kr-AZ6322-capt-04-03-22.jpg took 0.5377371699996729 seconds to run
8546
8547
Grabbing the full link at https://i.postimg.cc/CxJcYL9Z/2002-Kr-AZ-6322-capt-11-06-22.jpg took 0.6578162210007577 seconds to run
8547
8548
Grabbing the full link at https://i.postimg.cc/285nK3Pj/2000-Bogdan-63172-Kozak-destr.jpg took 0.4590756039997359 seconds to run

Connecting to https://i.postimg.cc/285nK3Pj/2000-Bogdan-63172-Kozak-destr.jpg ...
Downloading 2000-Bogdan-63172-Kozak-destr.jpg ...
[==================================================] 100.00%

OCR returns: 29.11.2022|p|TAOT|@visorechanne
Running OCR on https://i.postimg.cc/285nK3Pj/2000-Bogdan-63172-Kozak-destr.jpg took 11.043267839999316 seconds to run
8548
8549
Grabbing the full link at https://i.postimg.cc/MpFCLnDH/f6.png took 0.43887260900010006 seconds to run

Connecting to https://i.postimg.cc/MpFCLnDH/f6.png ...
Downloading f6.png ...
[==================================================] 100.00%

OCR returns: BOEHLAR|KPOHNKA|03/8/2022|AH338G|二共热|GMILCHRONICLES
Running OCR on https://i.postimg.cc/MpFCLnDH/f6.png took 12.560570757999812 seconds to run
8549
8550
Grabbing the full link at https://i.postimg.cc/vHMb7xqd/44377.png took 0.42056072799823596 seconds to run

Connecting to https://i.postimg.cc/vHMb7xqd/44377.png ...
Downloading 44377.png ...
[==================================================] 100.00%

OCR returns: 03/8/2022
Running OCR on https://i.postimg.cc/vHMb7xqd/44377.png took 10.219277692000105 seconds to run
8550
8551

Connecting to https://i.postimg.cc/pVFKmp2r/2007-UA-Kr-AZ-6322-capt.jpg ...
Downloading 2007-UA-Kr-AZ-6322-capt.jpg ...
[=                                                 ] 3.72%

Grabbing the full link at https://i.postimg.cc/pVFKmp2r/2007-UA-Kr-AZ-6322-capt.jpg took 0.39088936900043336 seconds to run

[==================================================] 100.00%

OCR returns: 15.10.2022
Running OCR on https://i.postimg.cc/pVFKmp2r/2007-UA-Kr-AZ-6322-capt.jpg took 20.445248705998893 seconds to run
8551
8552

Connecting to https://i.postimg.cc/rwnCQYq6/2022-03-01-UA-Kr-AZ-6322-captured-1.jpg ...
Downloading 2022-03-01-UA-Kr-AZ-6322-captured-1.jpg ...
[                                                  ] 1.51%

Grabbing the full link at https://i.postimg.cc/rwnCQYq6/2022-03-01-UA-Kr-AZ-6322-captured-1.jpg took 0.38505055399946286 seconds to run

[==================================================] 100.00%

OCR returns: Z|01/03/2022
Running OCR on https://i.postimg.cc/rwnCQYq6/2022-03-01-UA-Kr-AZ-6322-captured-1.jpg took 24.456533949000004 seconds to run
8552
8553
Grabbing the full link at https://i.postimg.cc/QtPKnKS6/2011-Kr-AZ-6322-capt-26-02-22.jpg took 0.37455801400028577 seconds to run
8553
8554
Grabbing the full link at https://i.postimg.cc/L50Dsqg1/2012-Kr-AZ-6446-capt-17-06-22.jpg took 0.3601767590007512 seconds to run
8554
8555
Grabbing the full link at https://i.postimg.cc/5yPVR40G/2006-Kr-AZ-6446-destr-03-10-23.jpg took 0.36161052899842616 seconds to run
8555
8556
Grabbing the full link at https://i.postimg.cc/Z59Fb6kv/2006-Kr-AZ-6446-destr-06-07-24.jpg took 0.3725990959992487 seconds to run
8556
8557
Grabbing the full link at https://i.postimg.cc/9QdGyVFC/2019-Kr-AZ-65055-destr-29-07-23.jpg took 0.3737070160004805 seconds to run
8557
8558
Grabbing the full link at https://i.postimg.cc/4xw80f2B/2016-Kr-AZ-65055-Prorab-capt-25-05-23.jpg took 0.3757184679998318 seconds to run
8558
8559
Grabbing the full link at https://i.postimg.cc/yNJmp5dK/truck2.jpg took 0.3704121819991997 seconds to run

Connecting to https://i.postimg.cc/yNJmp5dK/truck2.jpg ...
Downloading truck2.jpg ...
[==================================================] 100.00%

OCR returns: 10.04.2022|ikTok
Running OCR on https://i.postimg.cc/yNJmp5dK/truck2.jpg took 25.768156124999223 seconds to run
8559
8560
Grabbing the full link at https://i.postimg.cc/CKw9gRPm/76400.png took 0.4504722169986053 seconds to run

Connecting to https://i.postimg.cc/CKw9gRPm/76400.png ...
Downloading 76400.png ...
[==================================================] 100.00%

OCR returns: 23/11/2022
Running OCR on https://i.postimg.cc/CKw9gRPm/76400.png took 9.878344610000568 seconds to run
8560
8561
Grabbing the full link at https://i.postimg.cc/3RjX9jjM/2014-Bogdan-2351-ambulance-pickup-truck-destr-06-07-22.jpg took 0.5148632340005861 seconds to run
8561
8562
Grabbing the full link at https://i.postimg.cc/KY61mKW1/2010-Bogdan-2351-ambulance-destr-01-04-22.jpg took 0.643740085999525 seconds to run
8562
8563
Grabbing the full link at https://i.postimg.cc/RFwNhSrX/2022-Bogdan-2351-ambulance-pickup-truck-destr-15-04-22.jpg took 0.5126555480001116 seconds to run
8563
8564
Grabbing the full link at https://i.postimg.cc/Kc6K01RR/2000-Bogdan-2351-ambulance-pickup-truck-destr-18-05-22.jpg took 0.47441994799919485 seconds to run
8564
8565
Grabbing the full link at https://i.postimg.cc/rm29YyLz/2003-Bogdan-2251-ambulance-destr-17-08-22.jpg took 0.476833049000561 seconds to run
8565
8566
Grabbing the full link at https://i.postimg.cc/FFCLV8WL/4476.png took 0.44256340699939756 seconds to run

Connecting to https://i.postimg.cc/FFCLV8WL/4476.png ...
Downloading 4476.png ...
[==================================================] 100.00%

OCR returns: 18/4/2023
Running OCR on https://i.postimg.cc/FFCLV8WL/4476.png took 13.117578731000322 seconds to run
8566
8567
Grabbing the full link at https://i.postimg.cc/zBq5YXKN/2000-Bogdan-2251-Ambulance-destr-31-05-23.jpg took 0.3857888210004603 seconds to run
8567
8568
Grabbing the full link at https://i.postimg.cc/FF3y9N8B/2000-Bogdan-2251-ambulance-destr-07-11-22.jpg took 0.40899257399905764 seconds to run
8568
8569
Grabbing the full link at https://i.postimg.cc/VLwjv2cL/2010-Bogdan-2251-ambulance-destr-31-08-22.jpg took 0.36584540599869797 seconds to run
8569
8570
Grabbing the full link at https://i.postimg.cc/jjJBF2bN/2001-Bogdan-2251-ambulance-destr-09-06-23.jpg took 0.4001464950015361 seconds to run
8570
8571
Grabbing the full link at https://i.postimg.cc/26chSTjn/870.png took 0.4042884779992164 seconds to run

Connecting to https://i.postimg.cc/26chSTjn/870.png ...
Downloading 870.png ...
[==================================================] 100.00%

OCR returns: 10/4/2022
Running OCR on https://i.postimg.cc/26chSTjn/870.png took 21.915297188001205 seconds to run
8571
8572
Grabbing the full link at https://i.postimg.cc/qq9V5Q11/2008-Bogdan-2251-ambulance-destr-13-06-24.jpg took 0.5148711080000794 seconds to run
8572
8573
Grabbing the full link at https://i.postimg.cc/7ZcKKC5p/2029-Bogdan-2251-ambulance-destr-30-10-24.jpg took 0.4104573929998878 seconds to run
8573
8574
Grabbing the full link at https://i.postimg.cc/RCpzK7Vk/2009-Bogdan-2251-ambulance-destr-05-10-24.jpg took 0.6081787330003863 seconds to run
8574
8575
Grabbing the full link at https://i.postimg.cc/g0341H34/2011-Bogdan-2251-ambulance-destr-25-01-25.jpg took 0.46918794799967145 seconds to run
8575
8576
Grabbing the full link at https://i.postimg.cc/C14rKkJY/2001-Bogdan-2251-ambulance-destr-06-06-25.jpg took 0.3868424339998455 seconds to run
8576
8577
Grabbing the full link at https://i.postimg.cc/q77QXTL1/2018-Bogdan-2251-ambulance-dam-29-08-24.jpg took 0.37729533499987156 seconds to run
8577
8578
Grabbing the full link at https://i.postimg.cc/8zhmj3DM/54t.png took 0.438329471000543 seconds to run

Connecting to https://i.postimg.cc/8zhmj3DM/54t.png ...
Downloading 54t.png ...
[==================================================] 100.00%

OCR returns: 17/10/2022
Running OCR on https://i.postimg.cc/8zhmj3DM/54t.png took 16.804996480999762 seconds to run
8578
8579
Grabbing the full link at https://i.postimg.cc/c4dR9LXB/2006-Bogdan-2251-Ambulance-capt-xx-07-22.jpg took 0.4221948270005669 seconds to run

Connecting to https://i.postimg.cc/c4dR9LXB/2006-Bogdan-2251-Ambulance-capt-xx-07-22.jpg ...
Downloading 2006-Bogdan-2251-Ambulance-capt-xx-07-22.jpg ...
[==================================================] 100.00%

OCR returns: B
Running OCR on https://i.postimg.cc/c4dR9LXB/2006-Bogdan-2251-Ambulance-capt-xx-07-22.jpg took 11.041805426999417 seconds to run
8579
8580
Grabbing the full link at https://i.postimg.cc/W4dhqjpn/2007-bogdan-2251-ambulance-capt-13-04-22.jpg took 0.37838453900076274 seconds to run
8580
8581
Grabbing the full link at https://i.postimg.cc/QxvdHbF1/334f.png took 0.38541723799971805 seconds to run

Connecting to https://i.postimg.cc/QxvdHbF1/334f.png ...
Downloading 334f.png ...
[==================================================] 100.00%

OCR returns: RIAFAN|07/5/2022|RIAFAN.RU|RIAFAN_EVERYWHERE
Running OCR on https://i.postimg.cc/QxvdHbF1/334f.png took 14.117855692000376 seconds to run
8581
8582
Grabbing the full link at https://i.postimg.cc/5yqmRDH5/2016-Bogdan-2251-ambulance-capt-13-09-24.jpg took 0.3701922399995965 seconds to run

Connecting to https://i.postimg.cc/5yqmRDH5/2016-Bogdan-2251-ambulance-capt-13-09-24.jpg ...
Downloading 2016-Bogdan-2251-ambulance-capt-13-09-24.jpg ...
[==================================================] 100.00%

Running OCR on https://i.postimg.cc/5yqmRDH5/2016-Bogdan-2251-ambulance-capt-13-09-24.jpg took 17.15600681899923 seconds to run
8582
8583
Grabbing the full link at https://i.postimg.cc/6pr9sdqZ/Screenshot-8019.png took 0.5446247170002607 seconds to run

Connecting to https://i.postimg.cc/6pr9sdqZ/Screenshot-8019.png ...
Downloading Screenshot-8019.png ...
[==================================================] 100.00%

OCR returns: 24/02/2022|602 views|0:09/0:23|T|0
Running OCR on https://i.postimg.cc/6pr9sdqZ/Screenshot-8019.png took 27.036819388000367 seconds to run
8583
8584
Grabbing the full link at https://i.postimg.cc/52g8DrqH/n1.png took 0.4971016460003739 seconds to run

Connecting to https://i.postimg.cc/52g8DrqH/n1.png ...
Downloading n1.png ...
[==================================================] 100.00%

OCR returns: 28/02/2022
Running OCR on https://i.postimg.cc/52g8DrqH/n1.png took 47.828376375000516 seconds to run
8584
8585

Connecting to https://i.postimg.cc/L6dvbgC5/v48.png ...
Downloading v48.png ...
[                                                  ] 0.48%

Grabbing the full link at https://i.postimg.cc/L6dvbgC5/v48.png took 0.48291353300010087 seconds to run

[==================================================] 100.00%

OCR returns: 03/3/2022|KADYAOV_S5|1|II|00:30|-00:44
Running OCR on https://i.postimg.cc/L6dvbgC5/v48.png took 34.671403845000896 seconds to run
8585
8586
Grabbing the full link at https://i.postimg.cc/mrXBssWx/416.png took 0.3811656249999942 seconds to run

Connecting to https://i.postimg.cc/mrXBssWx/416.png ...
Downloading 416.png ...
[==================================================] 100.00%

OCR returns: 15/3/2022|58.6Kviews|0:02 / 0:44|2
Running OCR on https://i.postimg.cc/mrXBssWx/416.png took 28.597862868999073 seconds to run
8586
8587
Grabbing the full link at https://i.postimg.cc/s24TZ1bb/4ff.png took 0.36511048700049287 seconds to run

Connecting to https://i.postimg.cc/s24TZ1bb/4ff.png ...
Downloading 4ff.png ...
[==================================================] 100.00%

OCR returns: 28/03/2022|Hostomel Airport|个个
Running OCR on https://i.postimg.cc/s24TZ1bb/4ff.png took 23.504077189998497 seconds to run
8587
8588

Connecting to https://i.postimg.cc/s24TZ1bb/4ff.png ...
Downloading 4ff.png ...
[                                                  ] 0.23%

Grabbing the full link at https://i.postimg.cc/s24TZ1bb/4ff.png took 0.3736369990001549 seconds to run

[==================================================] 100.00%

OCR returns: 28/03/2022|Hostomel Airport|个个
Running OCR on https://i.postimg.cc/s24TZ1bb/4ff.png took 22.523089428001185 seconds to run
8588
8589

Connecting to https://i.postimg.cc/cC2ZgbyT/16.png ...
Downloading 16.png ...
[                                                  ] 0.19%

Grabbing the full link at https://i.postimg.cc/cC2ZgbyT/16.png took 0.481644616000267 seconds to run

[==================================================] 100.00%

OCR returns: 17/1/2023
Running OCR on https://i.postimg.cc/cC2ZgbyT/16.png took 25.77512124399982 seconds to run
8589
8590
Grabbing the full link at https://i.postimg.cc/hG1KV6P1/2002-Bogdan-5316-destr-16-02-24.jpg took 0.4043973570005619 seconds to run
8590
8591
Grabbing the full link at https://i.postimg.cc/Jh0m1VFQ/2035-Bogdan-5316-destr-31-05-22.jpg took 0.38058168000134174 seconds to run
8591
8592
Grabbing the full link at https://i.postimg.cc/L6ZKgBD7/4ff.png took 0.43091574299978674 seconds to run

Connecting to https://i.postimg.cc/L6ZKgBD7/4ff.png ...
Downloading 4ff.png ...
[==================================================] 100.00%

OCR returns: FOCTOMEnb|KNIBCbKAO6n.|09/04/2022|Hostomel, Kyiv Oblast
Running OCR on https://i.postimg.cc/L6ZKgBD7/4ff.png took 25.921005785001398 seconds to run
8592
8593
Grabbing the full link at https://i.postimg.cc/yNzLMGyQ/2006-Bohdan-5316-63172-dam-aband-30-05-22.jpg took 0.5338789849993191 seconds to run
8593
8594
Grabbing the full link at https://i.postimg.cc/ZRPRy9pM/2025-Bogdan-5316-17-07-22.jpg took 0.4656930500004819 seconds to run
8594
8595

Connecting to https://i.postimg.cc/nL8S357x/6h.png ...
Downloading 6h.png ...
[                                                  ] 0.42%

Grabbing the full link at https://i.postimg.cc/nL8S357x/6h.png took 0.4426871100004064 seconds to run

[==================================================] 100.00%

OCR returns: 25/02/2022|7618E9
Running OCR on https://i.postimg.cc/nL8S357x/6h.png took 13.13262253800167 seconds to run
8595
8596
Grabbing the full link at https://i.postimg.cc/26dvvmgq/t12.png took 0.405408520000492 seconds to run

Connecting to https://i.postimg.cc/26dvvmgq/t12.png ...
Downloading t12.png ...
[==================================================] 100.00%

OCR returns: 26/02/2022|AFP|Sergei SUPINSKY/AFP|000_323Y8UL
Running OCR on https://i.postimg.cc/26dvvmgq/t12.png took 11.205707948000054 seconds to run
8596
8597

Connecting to https://i.postimg.cc/g25vbgv0/t11.png ...
Downloading t11.png ...
[                                                  ] 0.53%

Grabbing the full link at https://i.postimg.cc/g25vbgv0/t11.png took 0.546360899001229 seconds to run

[==================================================] 100.00%

OCR returns: 26/02/2022|AFP|Daniel LEAL/AFP|000323Y8VZ
Running OCR on https://i.postimg.cc/g25vbgv0/t11.png took 13.092966676998913 seconds to run
8597
8598
Grabbing the full link at https://i.postimg.cc/6q6QVVMf/2009-Bogdan-63172-destr-23-10-22.jpg took 0.40475002199855226 seconds to run
8598
8599
Grabbing the full link at https://i.postimg.cc/DfttyLxg/4r.png took 0.39837470400016173 seconds to run

Connecting to https://i.postimg.cc/DfttyLxg/4r.png ...
Downloading 4r.png ...
[==================================================] 100.00%

OCR returns: 01/3/2022|2,048 views|0:00/0:07|0
Running OCR on https://i.postimg.cc/DfttyLxg/4r.png took 28.19799124199926 seconds to run
8599
8600
Grabbing the full link at https://i.postimg.cc/TPmQqZVc/d2.png took 0.3794068610004615 seconds to run

Connecting to https://i.postimg.cc/TPmQqZVc/d2.png ...
Downloading d2.png ...
[==================================================] 100.00%

OCR returns: 28/3/2022
Running OCR on https://i.postimg.cc/TPmQqZVc/d2.png took 13.0901765790004 seconds to run
8600
8601
Grabbing the full link at https://i.postimg.cc/CM77xFvk/5542.png took 0.37762365600065095 seconds to run

Connecting to https://i.postimg.cc/CM77xFvk/5542.png ...
Downloading 5542.png ...
[==================================================] 100.00%

OCR returns: 28/3/2022
Running OCR on https://i.postimg.cc/CM77xFvk/5542.png took 22.725683517001016 seconds to run
8601
8602

Connecting to https://i.postimg.cc/qqmmt6Nz/1002.jpg ...
Downloading 1002.jpg ...
[                                                  ] 1.99%

Grabbing the full link at https://i.postimg.cc/qqmmt6Nz/1002.jpg took 0.39194606300043233 seconds to run

[==================================================] 100.00%

OCR returns: 25.02.2022
Running OCR on https://i.postimg.cc/qqmmt6Nz/1002.jpg took 25.908802387000833 seconds to run
8602
8603
Grabbing the full link at https://i.postimg.cc/sDfHVsCc/3.png took 1.26630108900099 seconds to run

Connecting to https://i.postimg.cc/sDfHVsCc/3.png ...
Downloading 3.png ...
[==================================================] 100.00%

OCR returns: 31.5.2022 Ivanivka,Chernihivregion|gettyimages|AlexeyFurman|1241022863
Running OCR on https://i.postimg.cc/sDfHVsCc/3.png took 28.27091609099989 seconds to run
8603
8604
Grabbing the full link at https://i.postimg.cc/Rh2qWKBD/2022-03-16-UA-Bogdan-63172-destroyed.jpg took 0.384250910999981 seconds to run

Connecting to https://i.postimg.cc/Rh2qWKBD/2022-03-16-UA-Bogdan-63172-destroyed.jpg ...
Downloading 2022-03-16-UA-Bogdan-63172-destroyed.jpg ...
[==================================================] 100.00%

OCR returns: 16/03/2022
Running OCR on https://i.postimg.cc/Rh2qWKBD/2022-03-16-UA-Bogdan-63172-destroyed.jpg took 22.45570255200073 seconds to run
8604
8605
Grabbing the full link at https://i.postimg.cc/4NktmXr4/2022-06-03-UA-Bogdan-63172-destroyed-1.jpg took 0.503946287000872 seconds to run

Connecting to https://i.postimg.cc/4NktmXr4/2022-06-03-UA-Bogdan-63172-destroyed-1.jpg ...
Downloading 2022-06-03-UA-Bogdan-63172-destroyed-1.jpg ...
[==================================================] 100.00%

OCR returns: TikTok|@korzhvlad23|03/06/2022|Kyiv Oblast
Running OCR on https://i.postimg.cc/4NktmXr4/2022-06-03-UA-Bogdan-63172-destroyed-1.jpg took 10.612174572001095 seconds to run
8605
8606
Grabbing the full link at https://i.postimg.cc/QC5T0zWr/2022-06-03-UA-Bogdan-63172-destroyed-2.jpg took 0.42018722200009506 seconds to run

Connecting to https://i.postimg.cc/QC5T0zWr/2022-06-03-UA-Bogdan-63172-destroyed-2.jpg ...
Downloading 2022-06-03-UA-Bogdan-63172-destroyed-2.jpg ...
[==================================================] 100.00%

OCR returns: 03/06/2022|Kyiv Oblast|S|TikTok|@korzhvlad23
Running OCR on https://i.postimg.cc/QC5T0zWr/2022-06-03-UA-Bogdan-63172-destroyed-2.jpg took 11.162374475001343 seconds to run
8606
8607
Grabbing the full link at //postimgs.org/apple-touch-icon.png took 0.3724675349985773 seconds to run
OCR failed for some reason (probably a timeout); returning link and unscanned link keyword
8607
8608

[ WARN:0@10860.956] global loadsave.cpp:241 findDecoder imread_('//postimgs.org/apple-touch-icon.png'): can't open/read file: check file path/integrity

Grabbing the full link at https://i.postimg.cc/ZKDN3CCx/2008-Bogdan-63172-destr-24-02-22.jpg took 0.36628789200040046 seconds to run
8608
8609
Grabbing the full link at https://i.postimg.cc/6qtvmMLp/2005-Bogdan-63172-destr-26-02-22.jpg took 0.4229622169987124 seconds to run
8609
8610
Returning non-postimg link
8610
8611
Grabbing the full link at https://i.postimg.cc/T3MkZH31/2001-Bogdan-63172-destr-03-07-22.jpg took 0.3937595909992524 seconds to run
8611
8612
Grabbing the full link at https://i.postimg.cc/0jht5VGt/2034-Bogdan-63172-destr-24-10-22.jpg took 0.3793049529995187 seconds to run
8612
8613
Grabbing the full link at https://i.postimg.cc/BnThscjg/2038-Bogdan-63172-destr-29-03-22.jpg took 0.38556797000092047 seconds to run
8613
8614

Connecting to https://i.postimg.cc/hPHsycCC/2701.jpg ...
Downloading 2701.jpg ...
[                                                  ] 0.85%

Grabbing the full link at https://i.postimg.cc/hPHsycCC/2701.jpg took 0.46908988900031545 seconds to run

[==================================================] 100.00%

OCR returns: Bogdan-63172|KrAZ-5233|03/07/2022
Running OCR on https://i.postimg.cc/hPHsycCC/2701.jpg took 22.68766034699911 seconds to run
8614
8615

Connecting to https://i.postimg.cc/vZnP5dV0/h.png ...
Downloading h.png ...
[                                                  ] 0.19%

Grabbing the full link at https://i.postimg.cc/vZnP5dV0/h.png took 0.41804198600038944 seconds to run

[==================================================] 100.00%

OCR returns: SRLOVS|09/6/2023
Running OCR on https://i.postimg.cc/vZnP5dV0/h.png took 23.184161887998926 seconds to run
8615
8616

Connecting to https://i.postimg.cc/vZnP5dV0/h.png ...
Downloading h.png ...
[                                                  ] 0.19%

Grabbing the full link at https://i.postimg.cc/vZnP5dV0/h.png took 0.49612452700057474 seconds to run

[==================================================] 100.00%

OCR returns: SRLOVS|09/6/2023
Running OCR on https://i.postimg.cc/vZnP5dV0/h.png took 23.008536343999367 seconds to run
8616
8617
Grabbing the full link at https://i.postimg.cc/FzKjjs1h/2012-Bogdan-63172-destr-30-04-22.jpg took 0.42239340000014636 seconds to run
8617
8618
Grabbing the full link at https://i.postimg.cc/FKYKcY5g/2007-Bogdan-63172-destr-14-09-22.jpg took 0.43122215299990785 seconds to run
8618
8619
Grabbing the full link at https://i.postimg.cc/RhsMf38q/2007-Bogdan-63172-destr-25-10-23.jpg took 0.3824543399987306 seconds to run
8619
8620
Grabbing the full link at https://i.postimg.cc/bw8wSVC3/2021-Bogdan-63172-destr-28-10-23.jpg took 0.41477076099909027 seconds to run
8620
8621
Grabbing the full link at https://i.postimg.cc/sgD9H40F/2006-Bogdan-63172-destr-23-02-24.jpg took 0.4251908470014314 seconds to run
8621
8622
Grabbing the full link at https://i.postimg.cc/3wctKLTG/2014-3x-Bogdan-63172-destr-16-04-22.jpg took 0.41275155100083794 seconds to run
8622
8623
Grabbing the full link at https://i.postimg.cc/3wctKLTG/2014-3x-Bogdan-63172-destr-16-04-22.jpg took 0.5025302459998784 seconds to run
8623
8624
Grabbing the full link at https://i.postimg.cc/3wctKLTG/2014-3x-Bogdan-63172-destr-16-04-22.jpg took 0.44525677300043753 seconds to run
8624
8625
Grabbing the full link at https://i.postimg.cc/W4zJZ0V4/2008-Bogdan-63172-destr-07-06-24.jpg took 0.397948895000809 seconds to run
8625
8626
Grabbing the full link at https://i.postimg.cc/mkpjKCpr/2026-Bogdan-63172-destr-18-05-22.jpg took 0.4032497539992619 seconds to run
8626
8627
Grabbing the full link at https://i.postimg.cc/9fRbHBdp/f3.png took 0.40246973099965544 seconds to run

Connecting to https://i.postimg.cc/9fRbHBdp/f3.png ...
Downloading f3.png ...
[==================================================] 100.00%

OCR returns: 25/02/2022
Running OCR on https://i.postimg.cc/9fRbHBdp/f3.png took 13.10659334200136 seconds to run
8627
8628
Grabbing the full link at https://i.postimg.cc/HLT6Lc5C/2020-Bogdan-63172-dam-10-03-22.jpg took 0.48679756199999247 seconds to run
8628
8629
Grabbing the full link at https://i.postimg.cc/5NTj4W2C/2035-Bogdan-63172-dam-08-05-24.jpg took 0.5144532459999027 seconds to run
8629
8630
Grabbing the full link at https://i.postimg.cc/fbhLd7XW/2036-Bogdan-63172-dam-08-05-24.jpg took 0.479799548000301 seconds to run
8630
8631
Grabbing the full link at https://i.postimg.cc/ZRVpWfKB/Screenshot-8260.png took 0.5248254660000384 seconds to run

Connecting to https://i.postimg.cc/ZRVpWfKB/Screenshot-8260.png ...
Downloading Screenshot-8260.png ...
[==================================================] 100.00%

OCR returns: xapbKOB BoeHHbIe eCTBN. 3 eHb.TexHNKa|26/02/2022|D|2:54/ 4:15|E|HD
Running OCR on https://i.postimg.cc/ZRVpWfKB/Screenshot-8260.png took 31.812930226999015 seconds to run
8631
8632
Grabbing the full link at https://i.postimg.cc/hP4hp8v6/d46.png took 0.41657953499998257 seconds to run

Connecting to https://i.postimg.cc/hP4hp8v6/d46.png ...
Downloading d46.png ...
[==================================================] 100.00%

OCR returns: 10/3/2022|Life|0:02 / 0:15|4
Running OCR on https://i.postimg.cc/hP4hp8v6/d46.png took 27.43644343699998 seconds to run
8632
8633
Grabbing the full link at https://i.postimg.cc/7LSW8dKp/35.png took 0.3773877909989096 seconds to run

Connecting to https://i.postimg.cc/7LSW8dKp/35.png ...
Downloading 35.png ...
[==================================================] 100.00%

OCR returns: 04/3/2022|enNMBCeBO3MOKHyIOTeXHNKY,
Running OCR on https://i.postimg.cc/7LSW8dKp/35.png took 27.742617645999417 seconds to run
8633
8634
Returning non-postimg link
8634
8635
Grabbing the full link at https://i.postimg.cc/mg80yFh0/442.png took 0.36572198000067146 seconds to run

Connecting to https://i.postimg.cc/mg80yFh0/442.png ...
Downloading 442.png ...
[==================================================] 100.00%

OCR returns: Z|27/7/2023
Running OCR on https://i.postimg.cc/mg80yFh0/442.png took 27.20019763199889 seconds to run
8635
8636
Grabbing the full link at https://i.postimg.cc/1t1Xt0nF/2023-MAZ-6317-capt-10-07-22.jpg took 0.9521571000004769 seconds to run
8636
8637
Grabbing the full link at https://i.postimg.cc/g20xqXnG/1003.png took 0.533353865999743 seconds to run

Connecting to https://i.postimg.cc/g20xqXnG/1003.png ...
Downloading 1003.png ...
[==================================================] 100.00%

OCR returns: Borodyanka Ukraine|15.04.2022
Running OCR on https://i.postimg.cc/g20xqXnG/1003.png took 31.9815417660011 seconds to run
8637
8638
Grabbing the full link at https://i.postimg.cc/bwMsxYp7/2022-07-08-UA-Bogdan-63172-Kozak-destroyed.jpg took 0.5240235069995833 seconds to run

Connecting to https://i.postimg.cc/bwMsxYp7/2022-07-08-UA-Bogdan-63172-Kozak-destroyed.jpg ...
Downloading 2022-07-08-UA-Bogdan-63172-Kozak-destroyed.jpg ...
[==================================================] 100.00%

OCR returns: 08/07/2022|Kyiv Oblast
Running OCR on https://i.postimg.cc/bwMsxYp7/2022-07-08-UA-Bogdan-63172-Kozak-destroyed.jpg took 38.508667652999065 seconds to run
8638
8639
Grabbing the full link at https://i.postimg.cc/x8sypSG9/5g2.png took 0.4011931779987208 seconds to run

Connecting to https://i.postimg.cc/x8sypSG9/5g2.png ...
Downloading 5g2.png ...
[==================================================] 100.00%

OCR returns: 19/5/2022
Running OCR on https://i.postimg.cc/x8sypSG9/5g2.png took 16.26072679400022 seconds to run
8639
8640
Grabbing the full link at https://i.postimg.cc/3JNY4mLP/Screenshot-8124.png took 0.41238807500121766 seconds to run

Connecting to https://i.postimg.cc/3JNY4mLP/Screenshot-8124.png ...
Downloading Screenshot-8124.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|Y|Onewkn,|XepcoH.|25.02.22|TikTok|1|1:13/ 13:25|V|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/3JNY4mLP/Screenshot-8124.png took 39.34983201999967 seconds to run
8640
8641
Grabbing the full link at https://i.postimg.cc/D0nQ5hY6/2001-osa-transloader-destr.jpg took 1.0573816070009343 seconds to run

Connecting to https://i.postimg.cc/D0nQ5hY6/2001-osa-transloader-destr.jpg ...
Downloading 2001-osa-transloader-destr.jpg ...
[==================================================] 100.00%

OCR returns: 11.12.2022
Running OCR on https://i.postimg.cc/D0nQ5hY6/2001-osa-transloader-destr.jpg took 24.11911316899932 seconds to run
8641
8642
Grabbing the full link at https://i.postimg.cc/5NhHyxWy/2019-9-T217-transloader-for-9-K33-M3-OSA-AKM-destr-16-11-22.jpg took 0.47017506299926026 seconds to run
8642
8643
Grabbing the full link at https://i.postimg.cc/3xYx7Xgm/2007-GAZ-53-destr-30-03-24.jpg took 0.40599066200047673 seconds to run
8643
8644
Grabbing the full link at https://i.postimg.cc/rs16vXPJ/2018-GAZ-53-capt-27-02-22.jpg took 0.3996809239997674 seconds to run
8644
8645
Grabbing the full link at https://i.postimg.cc/J7ZWyZzk/2019-GAZ-53-capt-27-02-22.jpg took 0.392914608000865 seconds to run
8645
8646

Connecting to https://i.postimg.cc/vZ7sdvHn/f4.png ...
Downloading f4.png ...
[                                                  ] 1.56%

Grabbing the full link at https://i.postimg.cc/vZ7sdvHn/f4.png took 0.4001386640011333 seconds to run

[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|Y|Onewkn,|XepcOH.|25.02.22|TikTok|▶|1|0:11/13:25|@andriiboiko93kh|0|E|*|非
Running OCR on https://i.postimg.cc/vZ7sdvHn/f4.png took 33.80484488000002 seconds to run
8646
8647
Grabbing the full link at https://i.postimg.cc/13QPtzYw/Screenshot-8051.png took 0.46938000900081533 seconds to run

Connecting to https://i.postimg.cc/13QPtzYw/Screenshot-8051.png ...
Downloading Screenshot-8051.png ...
[==================================================] 100.00%

OCR returns: 24/02/2022|180|874 views|手|0:01 / 0:29|0
Running OCR on https://i.postimg.cc/13QPtzYw/Screenshot-8051.png took 28.13712417699935 seconds to run
8647
8648

Connecting to https://i.postimg.cc/13QPtzYw/Screenshot-8051.png ...
Downloading Screenshot-8051.png ...
[                                                  ] 0.74%

Grabbing the full link at https://i.postimg.cc/13QPtzYw/Screenshot-8051.png took 0.3661615420005546 seconds to run

[==================================================] 100.00%

OCR returns: 24/02/2022|180|874 views|手|0:01 / 0:29|0
Running OCR on https://i.postimg.cc/13QPtzYw/Screenshot-8051.png took 27.43481923299987 seconds to run
8648
8649
Grabbing the full link at https://i.postimg.cc/13QPtzYw/Screenshot-8051.png took 0.5138339460008865 seconds to run

Connecting to https://i.postimg.cc/13QPtzYw/Screenshot-8051.png ...
Downloading Screenshot-8051.png ...
[==================================================] 100.00%

OCR returns: 24/02/2022|180|874 views|手|0:01 / 0:29|0
Running OCR on https://i.postimg.cc/13QPtzYw/Screenshot-8051.png took 28.352923854001347 seconds to run
8649
8650

Connecting to https://i.postimg.cc/13QPtzYw/Screenshot-8051.png ...
Downloading Screenshot-8051.png ...
[                                                  ] 0.74%

Grabbing the full link at https://i.postimg.cc/13QPtzYw/Screenshot-8051.png took 0.43968258099994273 seconds to run

[==================================================] 100.00%

OCR returns: 24/02/2022|180|874 views|手|0:01 / 0:29|0
Running OCR on https://i.postimg.cc/13QPtzYw/Screenshot-8051.png took 31.158729062999555 seconds to run
8650
8651
Grabbing the full link at https://i.postimg.cc/hjdXLc6L/4f.png took 0.4980570400002762 seconds to run

Connecting to https://i.postimg.cc/hjdXLc6L/4f.png ...
Downloading 4f.png ...
[==================================================] 100.00%

OCR returns: 25/02/2022|72.3K views|0:33 / 0:45|2|0
Running OCR on https://i.postimg.cc/hjdXLc6L/4f.png took 28.884653286000685 seconds to run
8651
8652
Grabbing the full link at https://i.postimg.cc/8PzD9FYh/f23.png took 0.3858213760013314 seconds to run

Connecting to https://i.postimg.cc/8PzD9FYh/f23.png ...
Downloading f23.png ...
[==================================================] 100.00%

OCR returns: 06/3/2022
Running OCR on https://i.postimg.cc/8PzD9FYh/f23.png took 14.44231418399977 seconds to run
8652
8653
Grabbing the full link at https://i.postimg.cc/4xrgYWx5/f235.png took 0.3775032140001713 seconds to run

Connecting to https://i.postimg.cc/4xrgYWx5/f235.png ...
Downloading f235.png ...
[==================================================] 100.00%

OCR returns: 06/3/2022
Running OCR on https://i.postimg.cc/4xrgYWx5/f235.png took 20.69874915100081 seconds to run
8653
8654
Grabbing the full link at https://i.postimg.cc/SQ1Xb993/r3.png took 0.8312827019999531 seconds to run

Connecting to https://i.postimg.cc/SQ1Xb993/r3.png ...
Downloading r3.png ...
[==================================================] 100.00%

OCR returns: 13/3/2022|TOA|CEMECHRA|CENTS|MBC|1KM|5353|AC
Running OCR on https://i.postimg.cc/SQ1Xb993/r3.png took 28.791076232000705 seconds to run
8654
8655
Grabbing the full link at https://i.postimg.cc/PqdfwfZ1/r3.png took 0.4856612019993918 seconds to run

Connecting to https://i.postimg.cc/PqdfwfZ1/r3.png ...
Downloading r3.png ...
[==================================================] 100.00%

OCR returns: 13/3/2022|1116
Running OCR on https://i.postimg.cc/PqdfwfZ1/r3.png took 28.12904117400103 seconds to run
8655
8656
Grabbing the full link at https://i.postimg.cc/43VV4DVy/Screenshot-9318.png took 0.44092031800028053 seconds to run

Connecting to https://i.postimg.cc/43VV4DVy/Screenshot-9318.png ...
Downloading Screenshot-9318.png ...
[==================================================] 100.00%

OCR returns: 17/3/2022|NyFAHCK|24|ACK|UnyrAtICK|MCK|HIYFAHCK|AHCK24|SCK124|24|nyTAHC|yrAHCK|14.2Kviews|0:08/0:31
Running OCR on https://i.postimg.cc/43VV4DVy/Screenshot-9318.png took 29.841734882998935 seconds to run
8656
8657
Grabbing the full link at https://i.postimg.cc/0QHyTC2v/sa.png took 0.3797972819993447 seconds to run

Connecting to https://i.postimg.cc/0QHyTC2v/sa.png ...
Downloading sa.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|Y|Onewkn,|XepcoH.|25.02.22|TikTok|▶|1|1:23/13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/0QHyTC2v/sa.png took 34.06863223399887 seconds to run
8657
8658
Grabbing the full link at https://i.postimg.cc/Lsnxj6d4/g8.png took 0.5179400119995989 seconds to run

Connecting to https://i.postimg.cc/Lsnxj6d4/g8.png ...
Downloading g8.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction-15 km long.Crimea front line. Russia Ukraine War 2022 0225|0|Y|Onewkn,|XepcoH.|25.02.22|TikTok|3:06/ 13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/Lsnxj6d4/g8.png took 32.9860777269987 seconds to run
8658
8659
Grabbing the full link at https://i.postimg.cc/0QFPwLNj/33180.png took 0.4705535979992419 seconds to run

Connecting to https://i.postimg.cc/0QFPwLNj/33180.png ...
Downloading 33180.png ...
[==================================================] 100.00%

OCR returns: RVvoenkor|RVvoenkor|23/3/2022
Running OCR on https://i.postimg.cc/0QFPwLNj/33180.png took 18.391169405000255 seconds to run
8659
8660

Connecting to https://i.postimg.cc/0QFPwLNj/33180.png ...
Downloading 33180.png ...
[                                                  ] 0.29%

Grabbing the full link at https://i.postimg.cc/0QFPwLNj/33180.png took 0.5149609449999843 seconds to run

[==================================================] 100.00%

OCR returns: RVvoenkor|RVvoenkor|23/3/2022
Running OCR on https://i.postimg.cc/0QFPwLNj/33180.png took 17.535938610999438 seconds to run
8660
8661
Grabbing the full link at https://i.postimg.cc/qqgqjtjy/16.png took 0.40447369499997876 seconds to run

Connecting to https://i.postimg.cc/qqgqjtjy/16.png ...
Downloading 16.png ...
[==================================================] 100.00%

OCR returns: 30/3/2022
Running OCR on https://i.postimg.cc/qqgqjtjy/16.png took 16.207146810998893 seconds to run
8661
8662
Grabbing the full link at https://i.postimg.cc/s20y2R1W/542.png took 0.41064834099961445 seconds to run

Connecting to https://i.postimg.cc/s20y2R1W/542.png ...
Downloading 542.png ...
[==================================================] 100.00%

OCR returns: 6061|06/4/2022
Running OCR on https://i.postimg.cc/s20y2R1W/542.png took 17.898358075000942 seconds to run
8662
8663

Connecting to https://i.postimg.cc/s20y2R1W/542.png ...
Downloading 542.png ...
[                                                  ] 0.31%

Grabbing the full link at https://i.postimg.cc/s20y2R1W/542.png took 0.47913031200005207 seconds to run

[==================================================] 100.00%

OCR returns: 6061|06/4/2022
Running OCR on https://i.postimg.cc/s20y2R1W/542.png took 16.759899557000608 seconds to run
8663
8664
Grabbing the full link at https://i.postimg.cc/28rLyFdN/798.jpg took 0.3642613480005821 seconds to run

Connecting to https://i.postimg.cc/28rLyFdN/798.jpg ...
Downloading 798.jpg ...
[==================================================] 100.00%

OCR returns: 07.04.2022|https://t.me/chub_detection|https://t.me/chub detection
Running OCR on https://i.postimg.cc/28rLyFdN/798.jpg took 17.78178812099941 seconds to run
8664
8665
Grabbing the full link at https://i.postimg.cc/MHYc7Wm7/588.png took 0.3695318200007023 seconds to run

Connecting to https://i.postimg.cc/MHYc7Wm7/588.png ...
Downloading 588.png ...
[==================================================] 100.00%

OCR returns: 11/4/2022|ane azued
Running OCR on https://i.postimg.cc/MHYc7Wm7/588.png took 22.766202497999984 seconds to run
8665
8666
Returning non-postimg link
8666
8667
Grabbing the full link at https://i.postimg.cc/SN5W7BYL/d46.png took 0.4430234079991351 seconds to run

Connecting to https://i.postimg.cc/SN5W7BYL/d46.png ...
Downloading d46.png ...
[==================================================] 100.00%

OCR returns: iz|PRESS|19/4/2022|0:11/1:29
Running OCR on https://i.postimg.cc/SN5W7BYL/d46.png took 52.33937911999965 seconds to run
8667
8668

Connecting to https://i.postimg.cc/SN5W7BYL/d46.png ...
Downloading d46.png ...
[                                                  ] 0.23%

Grabbing the full link at https://i.postimg.cc/SN5W7BYL/d46.png took 0.4060403130006307 seconds to run

[==================================================] 100.00%

OCR returns: iz|PRESS|19/4/2022|0:11/1:29
Running OCR on https://i.postimg.cc/SN5W7BYL/d46.png took 29.449314005001725 seconds to run
8668
8669
Grabbing the full link at https://i.postimg.cc/tTFdQZ3L/1004.png took 0.45135004599978856 seconds to run

Connecting to https://i.postimg.cc/tTFdQZ3L/1004.png ...
Downloading 1004.png ...
[==================================================] 100.00%

OCR returns: 06.03.2022
Running OCR on https://i.postimg.cc/tTFdQZ3L/1004.png took 26.0300641599988 seconds to run
8669
8670
Grabbing the full link at https://i.postimg.cc/MT13RQF4/2014-gaz66-destr-30-01-23.jpg took 0.3768106780007656 seconds to run
8670
8671
Grabbing the full link at https://i.postimg.cc/gj9TG17c/Screenshot-8228.png took 0.372901726001146 seconds to run

Connecting to https://i.postimg.cc/gj9TG17c/Screenshot-8228.png ...
Downloading Screenshot-8228.png ...
[==================================================] 100.00%

OCR returns: 24/02/2022|Kherson, Ukraine|CN
Running OCR on https://i.postimg.cc/gj9TG17c/Screenshot-8228.png took 26.6847977489997 seconds to run
8671
8672
Grabbing the full link at https://i.postimg.cc/jScSwHTb/Screenshot-8020.png took 0.3793162519996258 seconds to run

Connecting to https://i.postimg.cc/jScSwHTb/Screenshot-8020.png ...
Downloading Screenshot-8020.png ...
[==================================================] 100.00%

OCR returns: 24/02/2022|602 views|0:15/0:23|X|0
Running OCR on https://i.postimg.cc/jScSwHTb/Screenshot-8020.png took 26.901848079000047 seconds to run
8672
8673
Returning non-postimg link
8673
8674
Grabbing the full link at https://i.postimg.cc/MGNbFHBs/Gaz-66-destroyed.png took 0.36389067900017835 seconds to run

Connecting to https://i.postimg.cc/MGNbFHBs/Gaz-66-destroyed.png ...
Downloading Gaz-66-destroyed.png ...
[==================================================] 100.00%

OCR returns: 10.10.2022|but|earlier, in|the|vicinity ofdestroyed 2S3|ykpaiHg
Running OCR on https://i.postimg.cc/MGNbFHBs/Gaz-66-destroyed.png took 25.58468187299877 seconds to run
8674
8675
Grabbing the full link at https://i.postimg.cc/J459PP5s/65.png took 0.5280231610013288 seconds to run

Connecting to https://i.postimg.cc/J459PP5s/65.png ...
Downloading 65.png ...
[==================================================] 100.00%

OCR returns: 19/4/2022|Lme/razved dozor
Running OCR on https://i.postimg.cc/J459PP5s/65.png took 15.576941735000219 seconds to run
8675
8676
Grabbing the full link at https://i.postimg.cc/hjsbLjq5/2003-GAZ-66-destr-25-03-24.jpg took 0.5177211940008419 seconds to run
8676
8677
Grabbing the full link at https://i.postimg.cc/N0nx31kj/UA-GAZ-66-Zil-130-Ural-4320-destroyed.png took 0.4633330080014275 seconds to run

Connecting to https://i.postimg.cc/N0nx31kj/UA-GAZ-66-Zil-130-Ural-4320-destroyed.png ...
Downloading UA-GAZ-66-Zil-130-Ural-4320-destroyed.png ...
[==================================================] 100.00%

OCR returns: 13.11.2022|CHIRYPIBKA,MWKONAIBCbKAO5A
Running OCR on https://i.postimg.cc/N0nx31kj/UA-GAZ-66-Zil-130-Ural-4320-destroyed.png took 15.690766654000981 seconds to run
8677
8678
Grabbing the full link at https://i.postimg.cc/76SBXK09/5770.png took 0.407475775000421 seconds to run

Connecting to https://i.postimg.cc/76SBXK09/5770.png ...
Downloading 5770.png ...
[==================================================] 100.00%

OCR returns: 中|133/号|56|2|3217|30|28|-10|咖咖酒|15/3/2022|市牛2面|131|60.|30|30|20|20|10|日|0.5|一5|-10|-20|-30|-45|mp
Running OCR on https://i.postimg.cc/76SBXK09/5770.png took 21.985133072999815 seconds to run
8678
8679
Grabbing the full link at https://i.postimg.cc/tRkWqrbf/2009-gaz66-destr-24-02-22.jpg took 0.43022718599968357 seconds to run
8679
8680
Grabbing the full link at https://i.postimg.cc/htKMLg22/279.png took 0.4601336290015752 seconds to run

Connecting to https://i.postimg.cc/htKMLg22/279.png ...
Downloading 279.png ...
[==================================================] 100.00%

OCR returns: Akocb TaK...|Akocb Tak...|Bineo we3BepecHa|Bineowe3 BepecHas|September 2022|B Hac He Bce ie rako (|B|Hac He Bceine rnako|(((
Running OCR on https://i.postimg.cc/htKMLg22/279.png took 24.690014339999834 seconds to run
8680
8681
Grabbing the full link at https://i.postimg.cc/65Q1z5b3/2009-GAZ-66-destr-01-09-24.jpg took 0.41353148899906955 seconds to run
8681
8682
Grabbing the full link at https://i.postimg.cc/SK2X0Lg0/2014-gaz66-destr-16-04-22.jpg took 0.4142207420009072 seconds to run
8682
8683
Grabbing the full link at https://i.postimg.cc/MZ3M5zjv/2009-GAZ66-destr-27-11-22.jpg took 0.45559620699896186 seconds to run
8683
8684
Grabbing the full link at https://i.postimg.cc/zXfWVnXf/2005-GAZ-66-destr-16-11-22.jpg took 0.4673233089997666 seconds to run
8684
8685
Grabbing the full link at https://i.postimg.cc/ydX9SjZD/2006-GAZ-66-destr-14-11-22.jpg took 0.4066523480014439 seconds to run
8685
8686
Grabbing the full link at https://i.postimg.cc/8PJRkw5q/2001-gaz66-destr-22-11-22.jpg took 0.3884368870003527 seconds to run
8686
8687
Grabbing the full link at https://i.postimg.cc/nrtpCBQK/2020-gaz66-destr-16-07-22.jpg took 0.45798051599922474 seconds to run
8687
8688
Grabbing the full link at https://i.postimg.cc/6QPKqbJx/2064-GAZ-66-destr-28-03-25.jpg took 0.3887587630015332 seconds to run
8688
8689
Grabbing the full link at https://i.postimg.cc/65bVLMRH/tr1.png took 0.38600507599949196 seconds to run

Connecting to https://i.postimg.cc/65bVLMRH/tr1.png ...
Downloading tr1.png ...
[==================================================] 100.00%

OCR returns: 02/4/2023|5,165 views|0:09 / 0:13|d
Running OCR on https://i.postimg.cc/65bVLMRH/tr1.png took 27.127370281001276 seconds to run
8689
8690
Grabbing the full link at https://i.postimg.cc/xdtH83Cv/g7.png took 0.40891680700042343 seconds to run

Connecting to https://i.postimg.cc/xdtH83Cv/g7.png ...
Downloading g7.png ...
[==================================================] 100.00%

OCR returns: 07/4/2023|PeanbHnǔ Kon.|@Realniy.Kop.ua.
Running OCR on https://i.postimg.cc/xdtH83Cv/g7.png took 26.40261393400033 seconds to run
8690
8691
Grabbing the full link at https://i.postimg.cc/L8RWbHFR/2023-gaz66-destr-24-02-22.jpg took 0.4582447820012021 seconds to run
8691
8692
Grabbing the full link at https://i.postimg.cc/KY8HmJYH/2027-gaz66-destr-01-10-22.jpg took 0.49539958300010767 seconds to run
8692
8693
Grabbing the full link at https://i.postimg.cc/J46gfsKt/16.png took 0.4021530589998292 seconds to run

Connecting to https://i.postimg.cc/J46gfsKt/16.png ...
Downloading 16.png ...
[==================================================] 100.00%

OCR returns: 30/3/2022
Running OCR on https://i.postimg.cc/J46gfsKt/16.png took 15.791041880000193 seconds to run
8693
8694
Grabbing the full link at https://i.postimg.cc/ZnW46GHW/2017-gaz66-destr-10-05-23.jpg took 0.3862157230014418 seconds to run
8694
8695
Grabbing the full link at https://i.postimg.cc/Jn1Gym7g/2017-gaz66-destr-10-05-23.jpg took 0.41062028700071096 seconds to run
8695
8696
Grabbing the full link at https://i.postimg.cc/j5gdL7Fw/2027-GAZ-66-destr-09-08-22.jpg took 0.3781795320010133 seconds to run
8696
8697
Grabbing the full link at https://i.postimg.cc/vmymjMnB/2028-GAZ-66-destr-29-12-22.jpg took 0.41436445799990906 seconds to run
8697
8698
Grabbing the full link at https://i.postimg.cc/gkfjV3k3/2031-GAZ-66-destr-29-08-22.jpg took 0.3829566300009901 seconds to run
8698
8699
Grabbing the full link at https://i.postimg.cc/25x5NJdx/2032-GAZ-66-destr-30-08-22.jpg took 0.4515650650009775 seconds to run
8699
8700
Grabbing the full link at https://i.postimg.cc/3RJx8BnQ/2033-GAZ-66-destr-22-04-22.jpg took 0.5397124090013676 seconds to run
8700
8701
Grabbing the full link at https://i.postimg.cc/6qqq00vf/2035-GAZ-66-destr-03-03-22.jpg took 0.3855573580003693 seconds to run
8701
8702
Grabbing the full link at https://i.postimg.cc/YCchb4k6/2010-GAZ-66-destr-12-11-22.jpg took 0.36502701899917156 seconds to run
8702
8703
Grabbing the full link at https://i.postimg.cc/tCns3d0R/2011-GAZ-66-destr-25-03-23.jpg took 0.4080577960012306 seconds to run
8703
8704
Grabbing the full link at https://i.postimg.cc/YCngX9Lh/2026-1x-Kr-AZ-6322-2x-gaz66-destr-04-06-23.jpg took 0.4676578270009486 seconds to run
8704
8705
Grabbing the full link at https://i.postimg.cc/YCngX9Lh/2026-1x-Kr-AZ-6322-2x-gaz66-destr-04-06-23.jpg took 0.4777363070006686 seconds to run
8705
8706
Grabbing the full link at https://i.postimg.cc/g0jydRbV/2011-GAZ-66-dam-19-05-23.jpg took 0.47026674800144974 seconds to run
8706
8707
Grabbing the full link at https://i.postimg.cc/1tm1LshC/2046-GAZ-66-destr-14-06-23.jpg took 0.3889545330002875 seconds to run
8707
8708
Grabbing the full link at https://i.postimg.cc/W3QhvrXZ/2008-GAZ-66-destr-16-06-23.jpg took 0.3821635549993516 seconds to run
8708
8709
Grabbing the full link at https://i.postimg.cc/3JjWskpy/2014-GAZ-66-destr-20-01-23.jpg took 0.37597720099984144 seconds to run
8709
8710
Grabbing the full link at https://i.postimg.cc/BbDhKhLJ/2001-gaz66-destr-17-07-23.jpg took 0.36859630800063314 seconds to run
8710
8711
Grabbing the full link at https://i.postimg.cc/D0XdT9KD/2002-gaz66-destr-18-12-22.jpg took 0.39037403499969514 seconds to run
8711
8712
Grabbing the full link at https://i.postimg.cc/g2H6SNmw/2013-GAZ-66-destr-23-06-24.jpg took 0.43297689499922853 seconds to run
8712
8713
Grabbing the full link at https://i.postimg.cc/Qtvs40s9/2026-GAZ-66-destr-07-05-22.jpg took 0.42590209300033166 seconds to run
8713
8714
Grabbing the full link at https://i.postimg.cc/WzFZDdp1/2013-GAZ-66-destr-07-07-23.jpg took 0.4679053740001109 seconds to run
8714
8715
Grabbing the full link at https://i.postimg.cc/fLjcFH3q/2024-GAZ-66-destr-09-08-23.jpg took 0.4711435129993333 seconds to run
8715
8716
Grabbing the full link at https://i.postimg.cc/Vvfqcjnf/2025-GAZ-66-destr-12-08-23.jpg took 0.4153282030001719 seconds to run
8716
8717
Grabbing the full link at https://i.postimg.cc/vm7g13cr/44f3.png took 0.3967834089999087 seconds to run

Connecting to https://i.postimg.cc/vm7g13cr/44f3.png ...
Downloading 44f3.png ...
[==================================================] 100.00%

OCR returns: November 2022|X'epoam"Xumom|X'epoam"Kumom|upcbkOro|upcokoro|Komna Haradyro-|komna maradyro-|Mu nobepHemoca!|Mu nobepHemaca!
Running OCR on https://i.postimg.cc/vm7g13cr/44f3.png took 21.339378545000727 seconds to run
8717
8718
Grabbing the full link at https://i.postimg.cc/T1gG3YdC/3315.png took 0.40736213699892687 seconds to run

Connecting to https://i.postimg.cc/T1gG3YdC/3315.png ...
Downloading 3315.png ...
[==================================================] 100.00%

OCR returns: 13/7/2023
Running OCR on https://i.postimg.cc/T1gG3YdC/3315.png took 18.67457155199918 seconds to run
8718
8719
Grabbing the full link at https://i.postimg.cc/SKj1B46K/6530.png took 0.45517018100144924 seconds to run

Connecting to https://i.postimg.cc/SKj1B46K/6530.png ...
Downloading 6530.png ...
[==================================================] 100.00%

OCR returns: 14/7/2023
Running OCR on https://i.postimg.cc/SKj1B46K/6530.png took 20.85594859000048 seconds to run
8719
8720
Grabbing the full link at https://i.postimg.cc/1tt7ZQDt/438.png took 0.38025458099946263 seconds to run

Connecting to https://i.postimg.cc/1tt7ZQDt/438.png ...
Downloading 438.png ...
[==================================================] 100.00%

OCR returns: 25/8/2023
Running OCR on https://i.postimg.cc/1tt7ZQDt/438.png took 29.615943869999683 seconds to run
8720
8721
Grabbing the full link at https://i.postimg.cc/4dRGk0dW/515.png took 0.37247890700018615 seconds to run

Connecting to https://i.postimg.cc/4dRGk0dW/515.png ...
Downloading 515.png ...
[==================================================] 100.00%

OCR returns: 03/9/2023|paHOKNOyaBCAHe3KaBN|paHOKnoyaBCAHe3KaBN|paHoKnoYaBCAHe3KaBN|PaHOKNOYaBCAHe3KaBN|73
Running OCR on https://i.postimg.cc/4dRGk0dW/515.png took 24.204325861999678 seconds to run
8721
8722
Grabbing the full link at https://i.postimg.cc/V6cdCct4/2006-GAZ-66-destr-16-05-23.jpg took 0.36919133399896964 seconds to run
8722
8723
Grabbing the full link at https://i.postimg.cc/Kv54yXDL/2008-GAZ-66-destr-30-12-23.jpg took 0.36462073900111136 seconds to run
8723
8724
Grabbing the full link at https://i.postimg.cc/x1T8fs6Z/2006-GAZ-66-destr-23-05-23.jpg took 0.36462592800126004 seconds to run
8724
8725
Grabbing the full link at https://i.postimg.cc/g2PygmW3/2004-gaz66-destr-31-12-23.jpg took 0.37248663299942564 seconds to run
8725
8726
Grabbing the full link at https://i.postimg.cc/wvRWvJGj/2003-GAZ-66-destr-29-10-23.jpg took 0.3788812080001662 seconds to run
8726
8727
Grabbing the full link at https://i.postimg.cc/90GJP2V3/2004-GAZ-66-destr-27-10-23.jpg took 0.37414272600108234 seconds to run
8727
8728
Grabbing the full link at https://i.postimg.cc/wTQw790L/2007-GAZ-66-destr-31-08-23.jpg took 0.3689682249987527 seconds to run
8728
8729
Grabbing the full link at https://i.postimg.cc/RZPGLXr0/2022-GAZ-66-destr-01-04-22.jpg took 0.36445196000022406 seconds to run
8729
8730
Grabbing the full link at https://i.postimg.cc/6QL0ZJHC/2009-2x-gaz66-destr-15-03-22.jpg took 0.3680628729998716 seconds to run
8730
8731
Grabbing the full link at https://i.postimg.cc/6QL0ZJHC/2009-2x-gaz66-destr-15-03-22.jpg took 0.41275309499906143 seconds to run
8731
8732
Grabbing the full link at https://i.postimg.cc/tJzNxmzS/2007-GAZ-66-destr-13-06-24.jpg took 0.37748390100023244 seconds to run
8732
8733
Grabbing the full link at https://i.postimg.cc/4ytxYXk2/2001-GAZ-66-destr-18-07-23.jpg took 0.3733490079994226 seconds to run
8733
8734
Grabbing the full link at https://i.postimg.cc/qvmDHr1G/2004-GAZ-66-destr-29-04-23.jpg took 0.3659321089999139 seconds to run
8734
8735
Grabbing the full link at https://i.postimg.cc/LXhdZjFy/2003-GAZ-66-destr-20-07-23.jpg took 0.36998015499921166 seconds to run
8735
8736
Grabbing the full link at https://i.postimg.cc/MTSZ2rW3/2012-gaz66-destr-31-05-22.jpg took 0.42194864399971266 seconds to run
8736
8737
Grabbing the full link at https://i.postimg.cc/d18bHthq/2001-GAZ-66-destr-18-02-24.jpg took 0.408673224001177 seconds to run
8737
8738
Grabbing the full link at https://i.postimg.cc/hPyXrwWz/2006-GAZ-66-destr-24-02-24.jpg took 0.39317061600013403 seconds to run
8738
8739
Grabbing the full link at https://i.postimg.cc/7Yywsg7w/2015-gaz66-destr-05-03-24.jpg took 0.43776899200020125 seconds to run
8739
8740
Grabbing the full link at https://i.postimg.cc/rp0CmS2F/2011-gaz66-destr-17-10-23.jpg took 0.44589417499992123 seconds to run
8740
8741
Grabbing the full link at https://i.postimg.cc/859B3qdG/2008-GAZ-66-destr-15-02-24.jpg took 0.43284835899976315 seconds to run
8741
8742
Grabbing the full link at https://i.postimg.cc/HWf9ZLXG/2014-GAZ-66-destr-29-02-24.jpg took 0.8246000470007857 seconds to run
8742
8743
Grabbing the full link at https://i.postimg.cc/3rgqXqPN/2006-GAZ-66-destr-28-07-22.jpg took 0.4362994269995397 seconds to run
8743
8744
Grabbing the full link at https://i.postimg.cc/vTfTv2PR/2001-GAZ-66-destr-31-03-24.jpg took 0.4271226860000752 seconds to run
8744
8745
Grabbing the full link at https://i.postimg.cc/SKzDKZ3w/2012-GAZ-66-destr-21-02-24.jpg took 0.48014401599903067 seconds to run
8745
8746
Grabbing the full link at https://i.postimg.cc/nzbT94tM/2013-GAZ-66-destr-21-02-24.jpg took 0.4420577359996969 seconds to run
8746
8747
Grabbing the full link at https://i.postimg.cc/C1qzqkKV/2021-GAZ-66-destr-11-04-24.jpg took 0.8230495560001145 seconds to run
8747
8748
Grabbing the full link at https://i.postimg.cc/8zXsXRhg/2022-GAZ-66-destr-27-03-24.jpg took 0.47194099700027436 seconds to run
8748
8749
Grabbing the full link at https://i.postimg.cc/vm1TJ4zg/2021-GAZ-66-destr-18-04-24.jpg took 0.4114656420006213 seconds to run
8749
8750
Grabbing the full link at https://i.postimg.cc/SQzJpRc8/2014-GAZ-66-destr-31-03-22.jpg took 0.41644386799998756 seconds to run
8750
Saved at index 8750
8751
Grabbing the full link at https://i.postimg.cc/8P4DGFKG/2017-GAZ-66-destr-31-03-24.jpg took 0.38830751400018926 seconds to run
8751
8752
Grabbing the full link at https://i.postimg.cc/fTngtg0j/2024-GAZ-66-destr-07-03-24.jpg took 0.4850620990000607 seconds to run
8752
8753
Grabbing the full link at https://i.postimg.cc/qBC57dgv/2038-GAZ-66-destr-16-10-23.jpg took 0.47570765300042694 seconds to run
8753
8754
Grabbing the full link at https://i.postimg.cc/CLf3tHCC/2021-GAZ-66-destr-07-05-24.jpg took 0.5185711699996318 seconds to run
8754
8755
Grabbing the full link at https://i.postimg.cc/mkdzxW8T/2000-GAZ-66-destr-29-09-23.jpg took 0.48472633299934387 seconds to run
8755
8756
Grabbing the full link at https://i.postimg.cc/rFsXY5B4/2001-GAZ-66-destr-31-03-24.jpg took 0.4717127280000568 seconds to run
8756
8757
Grabbing the full link at https://i.postimg.cc/sxDdzW1t/2002-GAZ-66-destr-30-11-23.jpg took 0.48198051400140685 seconds to run
8757
8758
Grabbing the full link at https://i.postimg.cc/5N2CvPh4/2010-GAZ-66-destr-06-06-24.jpg took 0.5214097289990605 seconds to run
8758
8759
Grabbing the full link at https://i.postimg.cc/W36VTsnJ/2006-GAZ-66-destr-24-02-22.jpg took 0.5202192719989398 seconds to run
8759
8760
Grabbing the full link at https://i.postimg.cc/hv2qQMND/2007-GAZ-66-destr-26-02-24.jpg took 0.41352314399955503 seconds to run
8760
8761
Grabbing the full link at https://i.postimg.cc/rm3YK7Yy/2005-GAZ-66-destr-14-07-24.jpg took 0.9675782549984433 seconds to run
8761
8762
Grabbing the full link at https://i.postimg.cc/t4y38ZW3/2054-GAZ-66-destr-08-10-24.jpg took 0.4440944190009759 seconds to run
8762
8763
Grabbing the full link at https://i.postimg.cc/rmK5t3jq/2019-GAZ-66-destr-25-10-24.jpg took 0.7128456560003542 seconds to run
8763
8764
Grabbing the full link at https://i.postimg.cc/DZLPSV1K/2017-GAZ-66-destr-29-02-24.jpg took 0.5727565229990432 seconds to run
8764
8765
Grabbing the full link at https://i.postimg.cc/tJXgdXzC/2029-GAZ-66-destr-22-05-23.jpg took 0.4940383250013838 seconds to run
8765
8766
Grabbing the full link at https://i.postimg.cc/0ydcRFst/2011-GAZ-66-destr-11-11-24.jpg took 0.504234562999045 seconds to run
8766
8767
Grabbing the full link at https://i.postimg.cc/wMdVF9BT/2003-GAZ-66-destr-11-10-24.jpg took 2.5936600169989106 seconds to run
8767
8768
Grabbing the full link at https://i.postimg.cc/j2w82BXG/2011-GAZ-66-destr-31-12-23.jpg took 0.997422672000539 seconds to run
8768
8769
Grabbing the full link at https://i.postimg.cc/grFpwbLG/2036-GAZ-66-destr-21-01-25.jpg took 1.6172397609989275 seconds to run
8769
8770
Grabbing the full link at https://i.postimg.cc/TP1tKGWT/2194-GAZ-66-destr15-04-22.jpg took 0.48942102900036843 seconds to run

Connecting to https://i.postimg.cc/TP1tKGWT/2194-GAZ-66-destr15-04-22.jpg ...
Downloading 2194-GAZ-66-destr15-04-22.jpg ...
[==================================================] 100.00%

OCR returns: @ZVEZDANEWS|AnekcaHap enopuak|HOppecnOHAeHT
Running OCR on https://i.postimg.cc/TP1tKGWT/2194-GAZ-66-destr15-04-22.jpg took 26.684122639000634 seconds to run
8770
8771
Grabbing the full link at https://i.postimg.cc/8ztNQPZ5/2034-GAZ-66-destr-19-03-25.jpg took 0.41370782800004235 seconds to run
8771
8772
Grabbing the full link at https://i.postimg.cc/1txm70YK/2008-GAZ-66-destr-10-04-25.jpg took 0.45975504200032447 seconds to run
8772
8773
Grabbing the full link at https://i.postimg.cc/RCQJYqw3/2018-GAZ-66-destr-12-04-25.jpg took 0.4266197140004806 seconds to run
8773
8774
Grabbing the full link at https://i.postimg.cc/J4xJstnw/2012-GAZ-66-destr-14-04-25.jpg took 0.44175752899900544 seconds to run
8774
8775
Grabbing the full link at https://i.postimg.cc/zvdB6dFk/2027-GAZ-66-destr-12-10-23.jpg took 0.42446528499931446 seconds to run
8775
8776
Grabbing the full link at https://i.postimg.cc/1zDy38pz/2003-GAZ-66-destr-19-05-25.jpg took 0.4304997990002448 seconds to run
8776
8777
Grabbing the full link at https://i.postimg.cc/9fXJtLkS/2016-GAZ-66-destr-14-05-25.jpg took 0.38606288300070446 seconds to run
8777
8778
Grabbing the full link at https://i.postimg.cc/13bYdCZc/2003-GAZ-66-destr-27-04-25.jpg took 0.4547803469995415 seconds to run
8778
8779
Grabbing the full link at https://i.postimg.cc/Z51MsTCk/2015-GAZ-66-destr-28-05-25.jpg took 0.41614332100107276 seconds to run
8779
8780
Grabbing the full link at https://i.postimg.cc/SNdYcxnP/2021-GAZ66-dam-27-02-22.jpg took 0.5186089470007573 seconds to run
8780
8781
Grabbing the full link at https://i.postimg.cc/gj9TG17c/Screenshot-8228.png took 0.4670101830015483 seconds to run

Connecting to https://i.postimg.cc/gj9TG17c/Screenshot-8228.png ...
Downloading Screenshot-8228.png ...
[==================================================] 100.00%

OCR returns: 24/02/2022|Kherson, Ukraine|CN
Running OCR on https://i.postimg.cc/gj9TG17c/Screenshot-8228.png took 27.41569595100009 seconds to run
8781
8782

Connecting to https://i.postimg.cc/qvyKsBvd/Screenshot-8260.png ...
Downloading Screenshot-8260.png ...
[                                                  ] 0.40%

Grabbing the full link at https://i.postimg.cc/qvyKsBvd/Screenshot-8260.png took 0.4119244889989204 seconds to run

[==================================================] 100.00%

OCR returns: xapbKOB BoeHHbIe eCTBN. 3 eHb.TexHNKa|26/02/2022|D|2:54/ 4:15|E|HD
Running OCR on https://i.postimg.cc/qvyKsBvd/Screenshot-8260.png took 30.941803670999434 seconds to run
8782
8783
Grabbing the full link at https://i.postimg.cc/wj9wSs48/2015-GAZ-66-dam-aband-09-07-23.jpg took 0.37703340699954424 seconds to run
8783
8784
Grabbing the full link at https://i.postimg.cc/prPjVJt8/688.jpg took 0.36283723899941833 seconds to run

Connecting to https://i.postimg.cc/prPjVJt8/688.jpg ...
Downloading 688.jpg ...
[==================================================] 100.00%

OCR returns: 12.05.2022|L.me/razved_dozor
Running OCR on https://i.postimg.cc/prPjVJt8/688.jpg took 25.414712406000035 seconds to run
8784
8785
Grabbing the full link at https://i.postimg.cc/65xFtXnZ/2004.jpg took 0.8351537739999912 seconds to run

Connecting to https://i.postimg.cc/65xFtXnZ/2004.jpg ...
Downloading 2004.jpg ...
[==================================================] 100.00%

OCR returns: 28/6/2022|20.07.2022
Running OCR on https://i.postimg.cc/65xFtXnZ/2004.jpg took 17.3846728059998 seconds to run
8785
8786
Grabbing the full link at https://i.postimg.cc/VLr5Xr51/542f.png took 0.41647862199897645 seconds to run

Connecting to https://i.postimg.cc/VLr5Xr51/542f.png ...
Downloading 542f.png ...
[==================================================] 100.00%

OCR returns: 10/3/2022
Running OCR on https://i.postimg.cc/VLr5Xr51/542f.png took 55.736432354999124 seconds to run
8786
8787

Connecting to https://i.postimg.cc/VLr5Xr51/542f.png ...
Downloading 542f.png ...
[                                                  ] 0.39%

Grabbing the full link at https://i.postimg.cc/VLr5Xr51/542f.png took 0.5146237019998807 seconds to run

[==================================================] 100.00%

OCR returns: 10/3/2022
Running OCR on https://i.postimg.cc/VLr5Xr51/542f.png took 30.77700102700146 seconds to run
8787
8788
Grabbing the full link at https://i.postimg.cc/Z507F6Jx/659.png took 0.37668286400003126 seconds to run

Connecting to https://i.postimg.cc/Z507F6Jx/659.png ...
Downloading 659.png ...
[==================================================] 100.00%

OCR returns: 14/3/2022
Running OCR on https://i.postimg.cc/Z507F6Jx/659.png took 19.33745261200056 seconds to run
8788
8789
Grabbing the full link at https://i.postimg.cc/gkG63gXS/g2.png took 0.412214486999801 seconds to run

Connecting to https://i.postimg.cc/gkG63gXS/g2.png ...
Downloading g2.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|Y|Onewkn,|XepcoH.|25.02.22|TikTok|1|▶|1|3:22 / 13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/gkG63gXS/g2.png took 35.247420125000644 seconds to run
8789
8790
Grabbing the full link at https://i.postimg.cc/Y0MjfS9G/43.png took 0.3681910519990197 seconds to run

Connecting to https://i.postimg.cc/Y0MjfS9G/43.png ...
Downloading 43.png ...
[==================================================] 100.00%

OCR returns: Onewkn,|XepcoH.|25.02.22|TikTok|@andriiboiko93kh
Running OCR on https://i.postimg.cc/Y0MjfS9G/43.png took 27.333047995000015 seconds to run
8790
8791

Connecting to https://i.postimg.cc/h40ThkyZ/4370.png ...
Downloading 4370.png ...
[                                                  ] 1.53%

Grabbing the full link at https://i.postimg.cc/h40ThkyZ/4370.png took 0.5081109519996971 seconds to run

[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|Y|Onewkn,|XepcoH.|25.02.22|TikTok|▶|1|3:14/ 13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/h40ThkyZ/4370.png took 33.33805192 seconds to run
8791
8792
Grabbing the full link at https://i.postimg.cc/xdmGTg40/386.png took 0.4918375970009947 seconds to run

Connecting to https://i.postimg.cc/xdmGTg40/386.png ...
Downloading 386.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|Y|Onewkn|XepcoH.|25.02.22|TikTok|1|2:48 / 13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/xdmGTg40/386.png took 32.01910320999923 seconds to run
8792
8793
Grabbing the full link at https://i.postimg.cc/jSPZqkrv/776.png took 0.3863537739998719 seconds to run

Connecting to https://i.postimg.cc/jSPZqkrv/776.png ...
Downloading 776.png ...
[==================================================] 100.00%

OCR returns: 04/3/2022|ZIL-131ARS-14|KraZ-260(ATZ-9.3-260）|KraZ-5233|ZIL-131,ZIL-131（ZU-23),|ZIL-131ARS-14|-66,GAZ-3307|GAZ-66|ZIL-131|2BMP-1P|URAL-375,UAZ-469,|GAZ-66
Running OCR on https://i.postimg.cc/jSPZqkrv/776.png took 27.288692289999744 seconds to run
8793
8794

Connecting to https://i.postimg.cc/jSPZqkrv/776.png ...
Downloading 776.png ...
[                                                  ] 0.29%

Grabbing the full link at https://i.postimg.cc/jSPZqkrv/776.png took 0.36755961000017123 seconds to run

[==================================================] 100.00%

OCR returns: 04/3/2022|ZIL-131ARS-14|KraZ-260(ATZ-9.3-260）|KraZ-5233|ZIL-131,ZIL-131（ZU-23),|ZIL-131ARS-14|-66,GAZ-3307|GAZ-66|ZIL-131|2BMP-1P|URAL-375,UAZ-469,|GAZ-66
Running OCR on https://i.postimg.cc/jSPZqkrv/776.png took 27.123642460001065 seconds to run
8794
8795
Grabbing the full link at https://i.postimg.cc/9MGPZgQM/Screenshot-8017.png took 0.3781698239999969 seconds to run

Connecting to https://i.postimg.cc/9MGPZgQM/Screenshot-8017.png ...
Downloading Screenshot-8017.png ...
[==================================================] 100.00%

OCR returns: 24/02/2022|602views|0:08/0:23|1|☆
Running OCR on https://i.postimg.cc/9MGPZgQM/Screenshot-8017.png took 27.33057265700154 seconds to run
8795
8796
Grabbing the full link at https://i.postimg.cc/pddP8SJY/Screenshot-8138.png took 0.3805877170016174 seconds to run

Connecting to https://i.postimg.cc/pddP8SJY/Screenshot-8138.png ...
Downloading Screenshot-8138.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long. Crimea front line. Russia Ukraine War 2022 02 25|0|Y|OnewKn,|XepcOH.|25.02.22|TikTok|1|1:48/ 13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/pddP8SJY/Screenshot-8138.png took 31.54764194800009 seconds to run
8796
8797
Grabbing the full link at https://i.postimg.cc/MT3cJ0K8/2013-GAZ-66-capt-13-06-22.jpg took 0.39544440799909353 seconds to run
8797
8798
Grabbing the full link at https://i.postimg.cc/s21R1h3T/Screenshot-8160.png took 0.39443350300098245 seconds to run

Connecting to https://i.postimg.cc/s21R1h3T/Screenshot-8160.png ...
Downloading Screenshot-8160.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction-15km long.Crimeafront line.Russia Ukraine War2022 0225|0|?|AloporaHaXepcoH|yepe3AHTOHOBCKN|MOCT.OnewKN|25.02.22|TikTok|1|5:59/13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/s21R1h3T/Screenshot-8160.png took 34.5928150689997 seconds to run
8798
8799
Grabbing the full link at https://i.postimg.cc/6QKvXBw6/Screenshot-8148.png took 0.48580381300052977 seconds to run

Connecting to https://i.postimg.cc/6QKvXBw6/Screenshot-8148.png ...
Downloading Screenshot-8148.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 0225|0|?|Onewkn,|XepcOH.|25.02.22|TikTok|1|3:06/ 13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/6QKvXBw6/Screenshot-8148.png took 33.69044405400018 seconds to run
8799
8800
Grabbing the full link at https://i.postimg.cc/6QCMtvY4/3d.jpg took 0.3646595120007987 seconds to run

Connecting to https://i.postimg.cc/6QCMtvY4/3d.jpg ...
Downloading 3d.jpg ...
[==================================================] 100.00%

OCR returns: 04.04.2022|1778|E6
Running OCR on https://i.postimg.cc/6QCMtvY4/3d.jpg took 26.172121872999924 seconds to run
8800
8801
Grabbing the full link at https://i.postimg.cc/Bbst1r4s/2025-GAZ66-capt-19-04-22.jpg took 0.5028046240004187 seconds to run
8801
8802
Grabbing the full link at https://i.postimg.cc/Cxj4pQ45/87.png took 0.9627937209988886 seconds to run

Connecting to https://i.postimg.cc/Cxj4pQ45/87.png ...
Downloading 87.png ...
[==================================================] 100.00%

OCR returns: 14/3/2022|47.9K views|0:00/1:28|4
Running OCR on https://i.postimg.cc/Cxj4pQ45/87.png took 27.101118947999566 seconds to run
8802
8803

Connecting to https://i.postimg.cc/rFZ5bm4k/588.png ...
Downloading 588.png ...
[                                                  ] 0.17%

Grabbing the full link at https://i.postimg.cc/rFZ5bm4k/588.png took 0.527106895999168 seconds to run

[==================================================] 100.00%

OCR returns: 24/4/2022
Running OCR on https://i.postimg.cc/rFZ5bm4k/588.png took 27.958004613999947 seconds to run
8803
8804
Grabbing the full link at https://i.postimg.cc/NGCNSPrF/4433.png took 0.4786101339996094 seconds to run

Connecting to https://i.postimg.cc/NGCNSPrF/4433.png ...
Downloading 4433.png ...
[==================================================] 100.00%

OCR returns: iZ|i2|0|19/4/2022|PR2SS|PRESS|0M/120|015/129
Running OCR on https://i.postimg.cc/NGCNSPrF/4433.png took 14.505085335998956 seconds to run
8804
8805
Grabbing the full link at https://i.postimg.cc/NGCNSPrF/4433.png took 0.4535877170001186 seconds to run

Connecting to https://i.postimg.cc/NGCNSPrF/4433.png ...
Downloading 4433.png ...
[==================================================] 100.00%

OCR returns: iZ|i2|0|19/4/2022|PR2SS|PRESS|0M/120|015/129
Running OCR on https://i.postimg.cc/NGCNSPrF/4433.png took 14.41518091099897 seconds to run
8805
8806
Grabbing the full link at https://i.postimg.cc/nzXbQ1rM/2024-GAZ-66-capt-05-06-24.jpg took 0.4240288330001931 seconds to run
8806
8807
Grabbing the full link at https://i.postimg.cc/wBSHD9mX/2012-GAZ-66-capt-29-07-22.jpg took 0.3779469569999492 seconds to run
8807
8808
Grabbing the full link at https://i.postimg.cc/pLQFR0zy/2113.jpg took 0.36410201499893446 seconds to run

Connecting to https://i.postimg.cc/pLQFR0zy/2113.jpg ...
Downloading 2113.jpg ...
[==================================================] 100.00%

OCR returns: 20.06.2022
Running OCR on https://i.postimg.cc/pLQFR0zy/2113.jpg took 21.208023400000457 seconds to run
8808
8809
Grabbing the full link at https://i.postimg.cc/yNymWq1g/2114.jpg took 0.364856978001626 seconds to run

Connecting to https://i.postimg.cc/yNymWq1g/2114.jpg ...
Downloading 2114.jpg ...
[==================================================] 100.00%

OCR returns: 25.06.2022|115TPO|t.me/Ugolok|Sitha
Running OCR on https://i.postimg.cc/yNymWq1g/2114.jpg took 26.41417720499885 seconds to run
8809
8810
Grabbing the full link at https://i.postimg.cc/qR4Nyztq/113.png took 0.3637893039995106 seconds to run

Connecting to https://i.postimg.cc/qR4Nyztq/113.png ...
Downloading 113.png ...
[==================================================] 100.00%

OCR returns: 03/3/2022|7887K5
Running OCR on https://i.postimg.cc/qR4Nyztq/113.png took 15.97619086099985 seconds to run
8810
8811
Grabbing the full link at https://i.postimg.cc/P5ksMxmY/33r56.png took 0.38473154599887494 seconds to run

Connecting to https://i.postimg.cc/P5ksMxmY/33r56.png ...
Downloading 33r56.png ...
[==================================================] 100.00%

OCR returns: 13/4/2022
Running OCR on https://i.postimg.cc/P5ksMxmY/33r56.png took 30.05477906700071 seconds to run
8811
8812
Grabbing the full link at https://i.postimg.cc/ZR7JBb8k/2016-gaz66-capt-04-03-22.jpg took 0.5298868730005779 seconds to run
8812
8813
Grabbing the full link at https://i.postimg.cc/Y98f1yCk/2029-GAZ-66-capt-28-07-22.jpg took 0.5106293469998491 seconds to run
8813
8814
Grabbing the full link at https://i.postimg.cc/LsnQxzpz/2022-GAZ-66-capt-01-05-24.jpg took 0.5086727130001236 seconds to run
8814
8815
Grabbing the full link at https://i.postimg.cc/QdPHLZj0/2024-GAZ-66-capt-17-07-22.jpg took 0.50717259799967 seconds to run
8815
8816
Grabbing the full link at https://i.postimg.cc/HnWxVk1G/2046-GAZ-66-capt-06-04-22.jpg took 0.9530386019996513 seconds to run
8816
8817
Grabbing the full link at https://i.postimg.cc/vTPm9wG4/2048-GAZ-66-capt-02-03-22.jpg took 2.5388143510008376 seconds to run
8817
8818
Grabbing the full link at https://i.postimg.cc/V6NZQJbs/2019-GAZ-66-capt-02-03-22.jpg took 0.5137310849986534 seconds to run
8818
8819
Grabbing the full link at https://i.postimg.cc/sxxPF5y5/2001-GAZ-66-capt-30-03-22.jpg took 0.5822955130006449 seconds to run
8819
8820
Grabbing the full link at https://i.postimg.cc/W1hSScGX/2030-GAZ-66-capt-12-05-22.jpg took 0.45309638300022925 seconds to run
8820
8821
Grabbing the full link at https://i.postimg.cc/qqLt6Zpc/2026-GAZ-66-capt-28-06-22.jpg took 0.41940215599970543 seconds to run
8821
8822
Grabbing the full link at https://i.postimg.cc/J4rHCmQp/2027-GAZ-66-capt-16-06-22.jpg took 0.45937471099932736 seconds to run
8822
8823
Grabbing the full link at https://i.postimg.cc/MG9wC3jh/4ff.png took 0.4656692190001195 seconds to run

Connecting to https://i.postimg.cc/MG9wC3jh/4ff.png ...
Downloading 4ff.png ...
[==================================================] 100.00%

OCR returns: 15/4/2022|military_politik
Running OCR on https://i.postimg.cc/MG9wC3jh/4ff.png took 55.29698165500122 seconds to run
8823
8824
Grabbing the full link at https://i.postimg.cc/FFMRNHjt/2019-GAZ-3307-destr-31-05-22.jpg took 0.47864609799944446 seconds to run
8824
8825
Grabbing the full link at https://i.postimg.cc/HswvQ4wG/2008-GAZ-3307-destr-01-05-24.jpg took 0.43686478299969167 seconds to run
8825
8826
Grabbing the full link at https://i.postimg.cc/wBqkRyBq/2017-GAZ-3307-destr-05-10-24.jpg took 0.4326125030002004 seconds to run
8826
8827
Grabbing the full link at https://i.postimg.cc/YSx4dv6v/2022-09-23-UA-GAZ-3308.jpg took 0.4526751859993965 seconds to run

Connecting to https://i.postimg.cc/YSx4dv6v/2022-09-23-UA-GAZ-3308.jpg ...
Downloading 2022-09-23-UA-GAZ-3308.jpg ...
[==================================================] 100.00%

OCR returns: 23/09/2022
Running OCR on https://i.postimg.cc/YSx4dv6v/2022-09-23-UA-GAZ-3308.jpg took 29.062022332000197 seconds to run
8827
8828
Grabbing the full link at https://i.postimg.cc/cCyy94XC/2017-GAZ-3308-capt-27-02-22.jpg took 0.40059245500015095 seconds to run
8828
8829
Grabbing the full link at https://i.postimg.cc/3wP6j42F/363.png took 0.3704275399995822 seconds to run

Connecting to https://i.postimg.cc/3wP6j42F/363.png ...
Downloading 363.png ...
[==================================================] 100.00%

OCR returns: 30/7/2023
Running OCR on https://i.postimg.cc/3wP6j42F/363.png took 19.01732694400016 seconds to run
8829
8830
Grabbing the full link at https://i.postimg.cc/SxLW3hgy/59.png took 0.3660389489996305 seconds to run

Connecting to https://i.postimg.cc/SxLW3hgy/59.png ...
Downloading 59.png ...
[==================================================] 100.00%

OCR returns: 17/3/2022
Running OCR on https://i.postimg.cc/SxLW3hgy/59.png took 22.95314306200089 seconds to run
8830
8831

Connecting to https://i.postimg.cc/N0nx31kj/UA-GAZ-66-Zil-130-Ural-4320-destroyed.png ...
Downloading UA-GAZ-66-Zil-130-Ural-4320-destroyed.png ...
[                                                  ] 0.41%

Grabbing the full link at https://i.postimg.cc/N0nx31kj/UA-GAZ-66-Zil-130-Ural-4320-destroyed.png took 0.3786504630006675 seconds to run

[==================================================] 100.00%

OCR returns: 13.11.2022|CHIRYPIBKA,MWKONAIBCbKAO5A
Running OCR on https://i.postimg.cc/N0nx31kj/UA-GAZ-66-Zil-130-Ural-4320-destroyed.png took 15.00628637400041 seconds to run
8831
8832
Grabbing the full link at https://i.postimg.cc/sXdtcb7F/2022-11-13-UA-Zi-L-130-destroyed-x2.jpg took 0.3726422170002479 seconds to run

Connecting to https://i.postimg.cc/sXdtcb7F/2022-11-13-UA-Zi-L-130-destroyed-x2.jpg ...
Downloading 2022-11-13-UA-Zi-L-130-destroyed-x2.jpg ...
[==================================================] 100.00%

OCR returns: WM Blood|13/11/2022|https://t.me/winua22|Kherson Airport
Running OCR on https://i.postimg.cc/sXdtcb7F/2022-11-13-UA-Zi-L-130-destroyed-x2.jpg took 28.341492235998885 seconds to run
8832
8833

Connecting to https://i.postimg.cc/sXdtcb7F/2022-11-13-UA-Zi-L-130-destroyed-x2.jpg ...
Downloading 2022-11-13-UA-Zi-L-130-destroyed-x2.jpg ...
[                                                  ] 1.26%

Grabbing the full link at https://i.postimg.cc/sXdtcb7F/2022-11-13-UA-Zi-L-130-destroyed-x2.jpg took 0.5287823359994945 seconds to run

[==================================================] 100.00%

OCR returns: WM Blood|13/11/2022|https://t.me/winua22|Kherson Airport
Running OCR on https://i.postimg.cc/sXdtcb7F/2022-11-13-UA-Zi-L-130-destroyed-x2.jpg took 27.043460934000905 seconds to run
8833
8834
Grabbing the full link at https://i.postimg.cc/c1FLhkGQ/65.png took 0.4996752930001094 seconds to run

Connecting to https://i.postimg.cc/c1FLhkGQ/65.png ...
Downloading 65.png ...
[==================================================] 100.00%

OCR returns: 15/4/2023|21.1Kviews|0:41/1:13|d
Running OCR on https://i.postimg.cc/c1FLhkGQ/65.png took 27.01927201699982 seconds to run
8834
8835

Connecting to https://i.postimg.cc/c1FLhkGQ/65.png ...
Downloading 65.png ...
[                                                  ] 0.27%

Grabbing the full link at https://i.postimg.cc/c1FLhkGQ/65.png took 0.9455738919987198 seconds to run

[==================================================] 100.00%

OCR returns: 15/4/2023|21.1Kviews|0:41/1:13|d
Running OCR on https://i.postimg.cc/c1FLhkGQ/65.png took 26.34841853999933 seconds to run
8835
8836
Grabbing the full link at https://i.postimg.cc/xdyPzpbY/2011-Zi-L-130-destr-07-05-22.jpg took 0.4142843230001745 seconds to run
8836
8837
Grabbing the full link at https://i.postimg.cc/sfqwNcRq/2006-Zi-L-130-06-07-22.jpg took 0.38835618600023736 seconds to run
8837
8838
Grabbing the full link at https://i.postimg.cc/NfvK04vJ/2000-DAF-YAD-4442-NT-destr-26-05-24.jpg took 0.4463830529984989 seconds to run
8838
8839
Grabbing the full link at https://i.postimg.cc/MG1hndts/2020-Zi-L-130-destr-06-09-24.jpg took 0.4022441470006015 seconds to run
8839
8840
Grabbing the full link at https://i.postimg.cc/0Q3G4V0j/2019-Zi-L-130-destr-05-10-24.jpg took 0.3838440580002498 seconds to run
8840
8841
Grabbing the full link at https://i.postimg.cc/sx55mJmq/2016-Zi-L-130-destr-26-01-25.jpg took 0.43166395200023544 seconds to run
8841
8842
Grabbing the full link at https://i.postimg.cc/gkwyNygW/2005-Zi-L-130-destr-14-06-22.jpg took 0.40848239900151384 seconds to run
8842
8843
Grabbing the full link at https://i.postimg.cc/bvx6VD4x/2006-Zi-L-130-destr-18-03-25.jpg took 0.5696714229998179 seconds to run
8843
8844
Grabbing the full link at https://i.postimg.cc/NFY7ntN8/2005-zil130-capt-28-02-22.jpg took 0.5962645470008283 seconds to run
8844
8845
Grabbing the full link at https://i.postimg.cc/Ss70j0Vj/Tanker-destroyed.png took 1.6414716919989587 seconds to run

Connecting to https://i.postimg.cc/Ss70j0Vj/Tanker-destroyed.png ...
Downloading Tanker-destroyed.png ...
[==================================================] 100.00%

OCR returns: 4.10.2022|TikTok|@rovromanvsvova2021
Running OCR on https://i.postimg.cc/Ss70j0Vj/Tanker-destroyed.png took 28.167256938999344 seconds to run
8845
8846
Grabbing the full link at https://i.postimg.cc/1R26krMn/2003-Zi-L-130-tanker-destr-30-07-23.jpg took 0.37050120899948524 seconds to run
8846
8847
Grabbing the full link at https://i.postimg.cc/t4mkVgHr/36.png took 0.3713473679999879 seconds to run

Connecting to https://i.postimg.cc/t4mkVgHr/36.png ...
Downloading 36.png ...
[==================================================] 100.00%

OCR returns: 24/02/2022|OHOnNUIMAPIYNONA|[5302K6]|II|0:07 / 0:55|中
Running OCR on https://i.postimg.cc/t4mkVgHr/36.png took 27.594653197000298 seconds to run
8847
8848
Grabbing the full link at https://i.postimg.cc/Cx2cSyPG/2014-Zi-L-131-destr-21-02-24.jpg took 0.3701705879993824 seconds to run
8848
8849
Grabbing the full link at https://i.postimg.cc/yxvN7tc3/69.png took 0.36348873200040543 seconds to run

Connecting to https://i.postimg.cc/yxvN7tc3/69.png ...
Downloading 69.png ...
[==================================================] 100.00%

OCR returns: 25/02/2022
Running OCR on https://i.postimg.cc/yxvN7tc3/69.png took 20.83864175599956 seconds to run
8849
8850
Grabbing the full link at https://i.postimg.cc/TPjprZk7/g7889.png took 0.3711292419993697 seconds to run

Connecting to https://i.postimg.cc/TPjprZk7/g7889.png ...
Downloading g7889.png ...
[==================================================] 100.00%

OCR returns: 02/3/2022
Running OCR on https://i.postimg.cc/TPjprZk7/g7889.png took 26.58462929199959 seconds to run
8850
8851
Grabbing the full link at https://i.postimg.cc/3wXqjPj0/Screenshot-8077.png took 0.41155659099968034 seconds to run

Connecting to https://i.postimg.cc/3wXqjPj0/Screenshot-8077.png ...
Downloading Screenshot-8077.png ...
[==================================================] 100.00%

OCR returns: 25/02/2022|11.7K views|0:28/ 0:46|0
Running OCR on https://i.postimg.cc/3wXqjPj0/Screenshot-8077.png took 26.95932632899894 seconds to run
8851
8852
Grabbing the full link at https://i.postimg.cc/K8Zh5MxD/ty.png took 0.3971204649988067 seconds to run

Connecting to https://i.postimg.cc/K8Zh5MxD/ty.png ...
Downloading ty.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction-15km long.Crimeafront line.Russia Ukraine War2022 0225|0|Y|Onewkn,|XepcoH.|25.02.22|TikTok|▶|1|1:21/ 13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/K8Zh5MxD/ty.png took 34.371492054000555 seconds to run
8852
8853

Connecting to https://i.postimg.cc/qqgqjtjy/16.png ...
Downloading 16.png ...
[                                                  ] 0.82%

Grabbing the full link at https://i.postimg.cc/qqgqjtjy/16.png took 0.3766983870009426 seconds to run

[==================================================] 100.00%

OCR returns: 30/3/2022
Running OCR on https://i.postimg.cc/qqgqjtjy/16.png took 15.495662046998405 seconds to run
8853
8854

Connecting to https://i.postimg.cc/zfNvWFGV/1010.png ...
Downloading 1010.png ...
[                                                  ] 0.39%

Grabbing the full link at https://i.postimg.cc/zfNvWFGV/1010.png took 0.3677787119995628 seconds to run

[==================================================] 100.00%

OCR returns: 06.03.2022
Running OCR on https://i.postimg.cc/zfNvWFGV/1010.png took 25.58837628100082 seconds to run
8854
8855
Grabbing the full link at https://i.postimg.cc/x1L3Q8pt/2003-zil131-destr-03-03-23.jpg took 0.9658001110001351 seconds to run
8855
8856
Grabbing the full link at https://i.postimg.cc/kMyYwYw2/f25.png took 0.5297712900010083 seconds to run

Connecting to https://i.postimg.cc/kMyYwYw2/f25.png ...
Downloading f25.png ...
[==================================================] 100.00%

OCR returns: 03/5/2022
Running OCR on https://i.postimg.cc/kMyYwYw2/f25.png took 14.470551499000067 seconds to run
8856
8857

Connecting to https://i.postimg.cc/kMyYwYw2/f25.png ...
Downloading f25.png ...
[                                                  ] 0.35%

Grabbing the full link at https://i.postimg.cc/kMyYwYw2/f25.png took 0.5675874399985332 seconds to run

[==================================================] 100.00%

OCR returns: 03/5/2022
Running OCR on https://i.postimg.cc/kMyYwYw2/f25.png took 13.472162840000237 seconds to run
8857
8858
Grabbing the full link at https://i.postimg.cc/FKs7bJSX/2004-ZIL-131-truck-with-ZU-23-2-destr-11-11-23.jpg took 0.3950416829993628 seconds to run
8858
8859
Grabbing the full link at https://i.postimg.cc/FKs7bJSX/2004-ZIL-131-truck-with-ZU-23-2-destr-11-11-23.jpg took 0.43433978900065995 seconds to run
8859
8860
Grabbing the full link at https://i.postimg.cc/vmzFrynH/688.png took 0.42837869100003445 seconds to run

Connecting to https://i.postimg.cc/vmzFrynH/688.png ...
Downloading 688.png ...
[==================================================] 100.00%

OCR returns: 09/4/2022
Running OCR on https://i.postimg.cc/vmzFrynH/688.png took 23.195339619998776 seconds to run
8860
8861
Grabbing the full link at https://i.postimg.cc/g0hRyMFD/4378.png took 0.45225587700042524 seconds to run

Connecting to https://i.postimg.cc/g0hRyMFD/4378.png ...
Downloading 4378.png ...
[==================================================] 100.00%

OCR returns: @Ratnik2nd|14/4/2022
Running OCR on https://i.postimg.cc/g0hRyMFD/4378.png took 26.893086113999743 seconds to run
8861
8862

Connecting to https://i.postimg.cc/g0hRyMFD/4378.png ...
Downloading 4378.png ...
[                                                  ] 0.24%

Grabbing the full link at https://i.postimg.cc/g0hRyMFD/4378.png took 0.4719406610001897 seconds to run

[==================================================] 100.00%

OCR returns: @Ratnik2nd|14/4/2022
Running OCR on https://i.postimg.cc/g0hRyMFD/4378.png took 26.350078657000267 seconds to run
8862
8863
Grabbing the full link at https://i.postimg.cc/YC4h80sW/699.png took 0.36925729399990814 seconds to run

Connecting to https://i.postimg.cc/YC4h80sW/699.png ...
Downloading 699.png ...
[==================================================] 100.00%

OCR returns: 25/4/2022
Running OCR on https://i.postimg.cc/YC4h80sW/699.png took 6.600903006999943 seconds to run
8863
8864

Connecting to https://i.postimg.cc/YC4h80sW/699.png ...
Downloading 699.png ...
[                                                  ] 0.96%

Grabbing the full link at https://i.postimg.cc/YC4h80sW/699.png took 0.4835833570014074 seconds to run

[==================================================] 100.00%

OCR returns: 25/4/2022
Running OCR on https://i.postimg.cc/YC4h80sW/699.png took 5.577612957000383 seconds to run
8864
8865
Grabbing the full link at https://i.postimg.cc/4NWLzZWJ/2019-zil131-destr-26-03-22.jpg took 0.5278582539995114 seconds to run
8865
8866
Grabbing the full link at https://i.postimg.cc/Sxs8sWC3/39.png took 0.49616336000144656 seconds to run

Connecting to https://i.postimg.cc/Sxs8sWC3/39.png ...
Downloading 39.png ...
[==================================================] 100.00%

OCR returns: 27/4/2022
Running OCR on https://i.postimg.cc/Sxs8sWC3/39.png took 10.766645147999952 seconds to run
8866
8867

Connecting to https://i.postimg.cc/fRjwqY7k/438.png ...
Downloading 438.png ...
[                                                  ] 0.85%

Grabbing the full link at https://i.postimg.cc/fRjwqY7k/438.png took 0.503065623999646 seconds to run

[==================================================] 100.00%

OCR returns: 29/4/2022
Running OCR on https://i.postimg.cc/fRjwqY7k/438.png took 9.36639000300056 seconds to run
8867
8868
Grabbing the full link at https://i.postimg.cc/8PbzrMFn/6588.jpg took 0.44109622399992077 seconds to run

Connecting to https://i.postimg.cc/8PbzrMFn/6588.jpg ...
Downloading 6588.jpg ...
[==================================================] 100.00%

OCR returns: 11.05.2022
Running OCR on https://i.postimg.cc/8PbzrMFn/6588.jpg took 12.806196338000518 seconds to run
8868
8869
Grabbing the full link at https://i.postimg.cc/L8LbrN1L/584.png took 0.40698133000114467 seconds to run

Connecting to https://i.postimg.cc/L8LbrN1L/584.png ...
Downloading 584.png ...
[==================================================] 100.00%

OCR returns: TikTok|@.wetwetwet17|16/4/2022|00:00/00:13
Running OCR on https://i.postimg.cc/L8LbrN1L/584.png took 10.996071490999384 seconds to run
8869
8870
Grabbing the full link at https://i.postimg.cc/TY8njjkJ/2116.jpg took 0.42604278700127907 seconds to run

Connecting to https://i.postimg.cc/TY8njjkJ/2116.jpg ...
Downloading 2116.jpg ...
[==================================================] 100.00%

OCR returns: Tauride|Republic|10.07.2022
Running OCR on https://i.postimg.cc/TY8njjkJ/2116.jpg took 53.93215523800063 seconds to run
8870
8871
Grabbing the full link at https://i.postimg.cc/4ygjV7j4/2115.jpg took 0.40031572800035065 seconds to run

Connecting to https://i.postimg.cc/4ygjV7j4/2115.jpg ...
Downloading 2115.jpg ...
[==================================================] 100.00%

OCR returns: 29.06.2022|UKR IM|SAURTOTONOBHCIO|HCBO
Running OCR on https://i.postimg.cc/4ygjV7j4/2115.jpg took 24.95144703400001 seconds to run
8871
8872

Connecting to https://i.postimg.cc/4ygjV7j4/2115.jpg ...
Downloading 2115.jpg ...
[==                                                ] 4.82%

Grabbing the full link at https://i.postimg.cc/4ygjV7j4/2115.jpg took 1.099613557000339 seconds to run

[==================================================] 100.00%

OCR returns: 29.06.2022|UKR IM|SAURTOTONOBHCIO|HCBO
Running OCR on https://i.postimg.cc/4ygjV7j4/2115.jpg took 22.21284349099915 seconds to run
8872
8873

Connecting to https://i.postimg.cc/4ygjV7j4/2115.jpg ...
Downloading 2115.jpg ...
[==                                                ] 4.82%

Grabbing the full link at https://i.postimg.cc/4ygjV7j4/2115.jpg took 0.3818626009997388 seconds to run

[==================================================] 100.00%

OCR returns: 29.06.2022|UKR IM|SAURTOTONOBHCIO|HCBO
Running OCR on https://i.postimg.cc/4ygjV7j4/2115.jpg took 22.296257801999673 seconds to run
8873
8874

Connecting to https://i.postimg.cc/4ygjV7j4/2115.jpg ...
Downloading 2115.jpg ...
[==                                                ] 4.82%

Grabbing the full link at https://i.postimg.cc/4ygjV7j4/2115.jpg took 0.4276616999995895 seconds to run

[==================================================] 100.00%

OCR returns: 29.06.2022|UKR IM|SAURTOTONOBHCIO|HCBO
Running OCR on https://i.postimg.cc/4ygjV7j4/2115.jpg took 22.023591011000462 seconds to run
8874
8875

Connecting to https://i.postimg.cc/4ygjV7j4/2115.jpg ...
Downloading 2115.jpg ...
[==                                                ] 4.82%

Grabbing the full link at https://i.postimg.cc/4ygjV7j4/2115.jpg took 0.9658922199996596 seconds to run

[==================================================] 100.00%

OCR returns: 29.06.2022|UKR IM|SAURTOTONOBHCIO|HCBO
Running OCR on https://i.postimg.cc/4ygjV7j4/2115.jpg took 22.076349711000148 seconds to run
8875
8876
Grabbing the full link at https://i.postimg.cc/KzBCvKf4/2007.jpg took 0.38018571399879875 seconds to run

Connecting to https://i.postimg.cc/KzBCvKf4/2007.jpg ...
Downloading 2007.jpg ...
[==================================================] 100.00%

OCR returns: 25.06.2022
Running OCR on https://i.postimg.cc/KzBCvKf4/2007.jpg took 22.41370715499943 seconds to run
8876
8877
Grabbing the full link at https://i.postimg.cc/CKNMhdv2/f4.png took 0.5115706289998343 seconds to run

Connecting to https://i.postimg.cc/CKNMhdv2/f4.png ...
Downloading f4.png ...
[==================================================] 100.00%

OCR returns: 5/4/2022|sitphotos|epositphotos|depositphoto|depositphoto
Running OCR on https://i.postimg.cc/CKNMhdv2/f4.png took 28.1578745909992 seconds to run
8877
8878
Grabbing the full link at https://i.postimg.cc/0NBngdSQ/2022-09-27-UA-Zi-L-131-with-ZU-23.jpg took 0.41206954500012216 seconds to run

Connecting to https://i.postimg.cc/0NBngdSQ/2022-09-27-UA-Zi-L-131-with-ZU-23.jpg ...
Downloading 2022-09-27-UA-Zi-L-131-with-ZU-23.jpg ...
[==================================================] 100.00%

OCR returns: 27/09/2022|Dolnya, Donetsk Oblast|t.me/war_memoirs
Running OCR on https://i.postimg.cc/0NBngdSQ/2022-09-27-UA-Zi-L-131-with-ZU-23.jpg took 27.272433991998696 seconds to run
8878
8879
Grabbing the full link at https://i.postimg.cc/0NBngdSQ/2022-09-27-UA-Zi-L-131-with-ZU-23.jpg took 0.488691127000493 seconds to run

Connecting to https://i.postimg.cc/0NBngdSQ/2022-09-27-UA-Zi-L-131-with-ZU-23.jpg ...
Downloading 2022-09-27-UA-Zi-L-131-with-ZU-23.jpg ...
[==================================================] 100.00%

OCR returns: 27/09/2022|Dolnya, Donetsk Oblast|t.me/war_memoirs
Running OCR on https://i.postimg.cc/0NBngdSQ/2022-09-27-UA-Zi-L-131-with-ZU-23.jpg took 26.354781079999157 seconds to run
8879
8880
Grabbing the full link at https://i.postimg.cc/G2CKKhn3/2022-09-27-UA-Zi-L-131.jpg took 0.4696646540014626 seconds to run

Connecting to https://i.postimg.cc/G2CKKhn3/2022-09-27-UA-Zi-L-131.jpg ...
Downloading 2022-09-27-UA-Zi-L-131.jpg ...
[==================================================] 100.00%

OCR returns: tne/war memoirs|27/09/2022|Kharkiv Oblast
Running OCR on https://i.postimg.cc/G2CKKhn3/2022-09-27-UA-Zi-L-131.jpg took 27.068287758000224 seconds to run
8880
8881
Grabbing the full link at https://i.postimg.cc/xjvjNhqv/Zil-131-and-kung-destroyed.png took 0.385095084000568 seconds to run

Connecting to https://i.postimg.cc/xjvjNhqv/Zil-131-and-kung-destroyed.png ...
Downloading Zil-131-and-kung-destroyed.png ...
[==================================================] 100.00%

OCR returns: 4.10.2022|TikTok|@rovromanvsvova2021|拿
Running OCR on https://i.postimg.cc/xjvjNhqv/Zil-131-and-kung-destroyed.png took 28.574211455001205 seconds to run
8881
8882
Grabbing the full link at https://i.postimg.cc/K8DqjM2q/3d22.png took 0.6314274779997504 seconds to run

Connecting to https://i.postimg.cc/K8DqjM2q/3d22.png ...
Downloading 3d22.png ...
[==================================================] 100.00%

OCR returns: nPECC-CAYKEA|HAPOAHON MNANLNN|LDECNYEnNKN|mil-Inrinfo|广|02/7/2022
Running OCR on https://i.postimg.cc/K8DqjM2q/3d22.png took 29.29448129800039 seconds to run
8882
8883
Grabbing the full link at https://i.postimg.cc/Cx5mHb2y/287.png took 0.5255686420005077 seconds to run

Connecting to https://i.postimg.cc/Cx5mHb2y/287.png ...
Downloading 287.png ...
[==================================================] 100.00%

OCR returns: Z|22/11/2022
Running OCR on https://i.postimg.cc/Cx5mHb2y/287.png took 7.258893229000023 seconds to run
8883
8884
Returning non-postimg link
8884
8885
Grabbing the full link at https://i.postimg.cc/GtfsyPTp/2022-11-13-UA-Zi-L-131-destroyed-x3.jpg took 0.5033432340005675 seconds to run

Connecting to https://i.postimg.cc/GtfsyPTp/2022-11-13-UA-Zi-L-131-destroyed-x3.jpg ...
Downloading 2022-11-13-UA-Zi-L-131-destroyed-x3.jpg ...
[==================================================] 100.00%

OCR returns: WM Blood|13/11/2022|https:f/t.me/wiua22|Kherson Airport
Running OCR on https://i.postimg.cc/GtfsyPTp/2022-11-13-UA-Zi-L-131-destroyed-x3.jpg took 26.796503231000315 seconds to run
8885
8886
Grabbing the full link at https://i.postimg.cc/GtfsyPTp/2022-11-13-UA-Zi-L-131-destroyed-x3.jpg took 0.5041466449984 seconds to run

Connecting to https://i.postimg.cc/GtfsyPTp/2022-11-13-UA-Zi-L-131-destroyed-x3.jpg ...
Downloading 2022-11-13-UA-Zi-L-131-destroyed-x3.jpg ...
[==================================================] 100.00%

OCR returns: WM Blood|13/11/2022|https:f/t.me/wiua22|Kherson Airport
Running OCR on https://i.postimg.cc/GtfsyPTp/2022-11-13-UA-Zi-L-131-destroyed-x3.jpg took 29.71547201700014 seconds to run
8886
8887

Connecting to https://i.postimg.cc/GtfsyPTp/2022-11-13-UA-Zi-L-131-destroyed-x3.jpg ...
Downloading 2022-11-13-UA-Zi-L-131-destroyed-x3.jpg ...
[                                                  ] 1.36%

Grabbing the full link at https://i.postimg.cc/GtfsyPTp/2022-11-13-UA-Zi-L-131-destroyed-x3.jpg took 0.4436355529996945 seconds to run

[==================================================] 100.00%

OCR returns: WM Blood|13/11/2022|https:f/t.me/wiua22|Kherson Airport
Running OCR on https://i.postimg.cc/GtfsyPTp/2022-11-13-UA-Zi-L-131-destroyed-x3.jpg took 26.35065687399947 seconds to run
8887
8888
Grabbing the full link at https://i.postimg.cc/yN0XCGgy/2022-11-13-UA-Zi-L-131-destroyed-3.jpg took 0.483084069999677 seconds to run

Connecting to https://i.postimg.cc/yN0XCGgy/2022-11-13-UA-Zi-L-131-destroyed-3.jpg ...
Downloading 2022-11-13-UA-Zi-L-131-destroyed-3.jpg ...
[==================================================] 100.00%

OCR returns: WMBload|13/11/2022|https://t.me/winaa22|Kherson Airport
Running OCR on https://i.postimg.cc/yN0XCGgy/2022-11-13-UA-Zi-L-131-destroyed-3.jpg took 27.311064137998983 seconds to run
8888
8889
Grabbing the full link at https://i.postimg.cc/jqM6TP5m/2022-11-13-UA-Zi-L-131-destroyed-2.jpg took 0.39302878899979987 seconds to run

Connecting to https://i.postimg.cc/jqM6TP5m/2022-11-13-UA-Zi-L-131-destroyed-2.jpg ...
Downloading 2022-11-13-UA-Zi-L-131-destroyed-2.jpg ...
[==================================================] 100.00%

OCR returns: WMBlood|13/11/2022|https://t.melwinua22|Kherson Airport
Running OCR on https://i.postimg.cc/jqM6TP5m/2022-11-13-UA-Zi-L-131-destroyed-2.jpg took 27.43836845700025 seconds to run
8889
8890
Grabbing the full link at https://i.postimg.cc/9M8D6PpB/2022-11-13-UA-Zi-L-131-destroyed.jpg took 0.4908669039996312 seconds to run

Connecting to https://i.postimg.cc/9M8D6PpB/2022-11-13-UA-Zi-L-131-destroyed.jpg ...
Downloading 2022-11-13-UA-Zi-L-131-destroyed.jpg ...
[==================================================] 100.00%

OCR returns: Poecm|13/11/2022|https://t.me/wiua22|KhersonAirport
Running OCR on https://i.postimg.cc/9M8D6PpB/2022-11-13-UA-Zi-L-131-destroyed.jpg took 26.73272499000086 seconds to run
8890
8891

Connecting to https://i.postimg.cc/SNBF5gkX/2022-04-05-UA-Zi-L-131-destroyed-Irpin.jpg ...
Downloading 2022-04-05-UA-Zi-L-131-destroyed-Irpin.jpg ...
[                                                  ] 1.20%

Grabbing the full link at https://i.postimg.cc/SNBF5gkX/2022-04-05-UA-Zi-L-131-destroyed-Irpin.jpg took 0.3707670199983113 seconds to run

[==================================================] 100.00%

OCR returns: 05/04/2022|Irpin, Kyiv Oblast
Running OCR on https://i.postimg.cc/SNBF5gkX/2022-04-05-UA-Zi-L-131-destroyed-Irpin.jpg took 26.320747130999735 seconds to run
8891
8892
Grabbing the full link at https://i.postimg.cc/JhHxfMgf/2022-04-07-UA-Zi-L-131-destroyed.jpg took 0.36446202700062713 seconds to run

Connecting to https://i.postimg.cc/JhHxfMgf/2022-04-07-UA-Zi-L-131-destroyed.jpg ...
Downloading 2022-04-07-UA-Zi-L-131-destroyed.jpg ...
[==================================================] 100.00%

OCR returns: 07/04/2022|KrasyatychiKyiv Oblast
Running OCR on https://i.postimg.cc/JhHxfMgf/2022-04-07-UA-Zi-L-131-destroyed.jpg took 13.670368196000709 seconds to run
8892
8893
Grabbing the full link at https://i.postimg.cc/PJsG86G7/2022-05-03-UA-Zi-L-131-destroyed.jpg took 0.3620260749994486 seconds to run

Connecting to https://i.postimg.cc/PJsG86G7/2022-05-03-UA-Zi-L-131-destroyed.jpg ...
Downloading 2022-05-03-UA-Zi-L-131-destroyed.jpg ...
[==================================================] 100.00%

OCR returns: 03/05/2022|TikTok|KyivOblast|@illegaly.to.chernobyl
Running OCR on https://i.postimg.cc/PJsG86G7/2022-05-03-UA-Zi-L-131-destroyed.jpg took 10.851962200998969 seconds to run
8893
8894

Connecting to https://i.postimg.cc/ydqfyrT1/2022-07-21-UA-Zi-L-131-destroyed.jpg ...
Downloading 2022-07-21-UA-Zi-L-131-destroyed.jpg ...
[                                                  ] 1.21%

Grabbing the full link at https://i.postimg.cc/ydqfyrT1/2022-07-21-UA-Zi-L-131-destroyed.jpg took 0.3790405069994449 seconds to run

[==================================================] 100.00%

OCR returns: AAANRAOAE|PNAHOBOCTN|6yno|AACRRNRI|21/07/2022
Running OCR on https://i.postimg.cc/ydqfyrT1/2022-07-21-UA-Zi-L-131-destroyed.jpg took 22.821497798000564 seconds to run
8894
8895
Grabbing the full link at https://i.postimg.cc/Y024KnHf/2006-Zil131-with-Zu23-2-destr.jpg took 0.5113962479990732 seconds to run

Connecting to https://i.postimg.cc/Y024KnHf/2006-Zil131-with-Zu23-2-destr.jpg ...
Downloading 2006-Zil131-with-Zu23-2-destr.jpg ...
[==================================================] 100.00%

OCR returns: 24.11.2022
Running OCR on https://i.postimg.cc/Y024KnHf/2006-Zil131-with-Zu23-2-destr.jpg took 28.569374530999994 seconds to run
8895
8896

Connecting to https://i.postimg.cc/Y024KnHf/2006-Zil131-with-Zu23-2-destr.jpg ...
Downloading 2006-Zil131-with-Zu23-2-destr.jpg ...
[                                                  ] 0.97%

Grabbing the full link at https://i.postimg.cc/Y024KnHf/2006-Zil131-with-Zu23-2-destr.jpg took 2.6585848270005954 seconds to run

[==================================================] 100.00%

OCR returns: 24.11.2022
Running OCR on https://i.postimg.cc/Y024KnHf/2006-Zil131-with-Zu23-2-destr.jpg took 41.527464236000014 seconds to run
8896
8897
Grabbing the full link at https://i.postimg.cc/XJ8y1ZPP/1011-zil131-destr.jpg took 0.5297351749995869 seconds to run

Connecting to https://i.postimg.cc/XJ8y1ZPP/1011-zil131-destr.jpg ...
Downloading 1011-zil131-destr.jpg ...
[==================================================] 100.00%

OCR returns: 12.12.2022
Running OCR on https://i.postimg.cc/XJ8y1ZPP/1011-zil131-destr.jpg took 13.391682806000972 seconds to run
8897
8898
Grabbing the full link at https://i.postimg.cc/8PzRB6j3/2015-Zi-L-131-destr-02-03-22.jpg took 0.43838043799951265 seconds to run
8898
8899
Grabbing the full link at https://i.postimg.cc/0jdMW8cb/2020-Zi-L131-destr-27-02-22.jpg took 0.3868784139995114 seconds to run
8899
8900
Grabbing the full link at https://i.postimg.cc/MH9Q9Gtx/2007-Zi-L131-destr-24-02-22.jpg took 0.37855207699976745 seconds to run
8900
8901
Grabbing the full link at https://i.postimg.cc/VNKCnVtP/2018-Zi-L-131-destr-22-12-22.jpg took 0.3762782209996658 seconds to run
8901
8902
Grabbing the full link at https://i.postimg.cc/mZ63GKbY/2005-Zi-L-131-destr-25-02-22.jpg took 0.36960836999969615 seconds to run
8902
8903
Grabbing the full link at https://i.postimg.cc/02dLqbCw/1335.png took 0.38197896299971035 seconds to run

Connecting to https://i.postimg.cc/02dLqbCw/1335.png ...
Downloading 1335.png ...
[==================================================] 100.00%

OCR returns: 心|25/02/2022
Running OCR on https://i.postimg.cc/02dLqbCw/1335.png took 26.217207424999287 seconds to run
8903
8904

Connecting to https://i.postimg.cc/02dLqbCw/1335.png ...
Downloading 1335.png ...
[                                                  ] 0.43%

Grabbing the full link at https://i.postimg.cc/02dLqbCw/1335.png took 0.3725377209993894 seconds to run

[==================================================] 100.00%

OCR returns: 心|25/02/2022
Running OCR on https://i.postimg.cc/02dLqbCw/1335.png took 23.330487741999605 seconds to run
8904
8905
Grabbing the full link at https://i.postimg.cc/Wz0xz3Lx/132.png took 0.3646252219987218 seconds to run

Connecting to https://i.postimg.cc/Wz0xz3Lx/132.png ...
Downloading 132.png ...
[==================================================] 100.00%

OCR returns: 心|25/02/2022
Running OCR on https://i.postimg.cc/Wz0xz3Lx/132.png took 24.01361266799904 seconds to run
8905
8906
Grabbing the full link at https://i.postimg.cc/BvRtxyXG/2005-zil131-destr-13-04-22.jpg took 0.3767643879982643 seconds to run
8906
8907
Grabbing the full link at https://i.postimg.cc/T1fV0k8S/2014-zil131-destr-06-08-22.jpg took 0.36567359199943894 seconds to run
8907
8908
Grabbing the full link at https://i.postimg.cc/ncqjQ8S5/335.png took 0.3845263139992312 seconds to run

Connecting to https://i.postimg.cc/ncqjQ8S5/335.png ...
Downloading 335.png ...
[==================================================] 100.00%

OCR returns: 16/2/2023|2703 118
Running OCR on https://i.postimg.cc/ncqjQ8S5/335.png took 26.647259769999437 seconds to run
8908
8909
Grabbing the full link at https://i.postimg.cc/brSvvfHn/2001-zil131-destr-01-04-23.jpg took 0.4959359589993255 seconds to run
8909
8910

Connecting to https://i.postimg.cc/13mCkHjp/a12.png ...
Downloading a12.png ...
[                                                  ] 0.49%

Grabbing the full link at https://i.postimg.cc/13mCkHjp/a12.png took 0.4829183359997842 seconds to run

[==================================================] 100.00%

OCR returns: 17/4/2023|21K views|0:15/ 0:26|d
Running OCR on https://i.postimg.cc/13mCkHjp/a12.png took 26.430945330999748 seconds to run
8910
8911
Grabbing the full link at https://i.postimg.cc/LsWMPVPz/2012-Zi-L-131-destr-27-02-22.jpg took 0.4015331390000938 seconds to run
8911
8912
Grabbing the full link at https://i.postimg.cc/hGvDN6w5/2000-zil131-destr-29-04-23.jpg took 0.38844305299971893 seconds to run
8912
8913
Grabbing the full link at https://i.postimg.cc/9FHWyk4W/2032-Zi-L-131-destr-27-03-25.jpg took 0.3862643590000516 seconds to run
8913
8914
Grabbing the full link at https://i.postimg.cc/k5hWdBvs/2021-Zi-L-131-destr-27-04-22.jpg took 0.3975642320001498 seconds to run
8914
8915
Grabbing the full link at https://i.postimg.cc/3NQ4Kp4X/2022-Zil131-destr-16-07-22.jpg took 0.4263134049997461 seconds to run
8915
8916
Grabbing the full link at https://i.postimg.cc/MTMVZqsS/2023-Zil131-destr-21-07-22.jpg took 0.4690521129996341 seconds to run
8916
8917
Grabbing the full link at https://i.postimg.cc/ZKcBSWTN/2025-Zi-L131-destr-07-01-23.jpg took 0.5263394009998592 seconds to run
8917
8918
Grabbing the full link at https://i.postimg.cc/Qt25HwPW/2026-Zi-L131-destr-16-01-23.jpg took 0.8718049500002962 seconds to run
8918
8919
Grabbing the full link at https://i.postimg.cc/8cdFs5Mq/2036-Zi-L-131-destr-03-03-22.jpg took 0.5602294550008082 seconds to run
8919
8920
Grabbing the full link at https://i.postimg.cc/kggVX74p/2039-Zi-L-131-destr-25-11-22.jpg took 0.5538262260015472 seconds to run
8920
8921
Returning non-postimg link
8921
8922
Returning non-postimg link
8922
8923
Returning non-postimg link
8923
8924
Grabbing the full link at https://i.postimg.cc/VNDpLCkn/2003-Zi-L-131-destr-02-08-22.jpg took 0.48223545700057 seconds to run
8924
8925
Grabbing the full link at https://i.postimg.cc/4d00pRt3/2004-Zi-L-131-destr-10-04-22.jpg took 0.534258065999893 seconds to run
8925
8926
Grabbing the full link at https://i.postimg.cc/NMkFsrV7/2045-Zi-L-131-destr-01-10-24.jpg took 0.9788167599999724 seconds to run
8926
8927
Grabbing the full link at https://i.postimg.cc/9z5NNPL5/2006-Zi-L-131-destr-10-04-22.jpg took 0.5214458110003761 seconds to run
8927
8928
Grabbing the full link at https://i.postimg.cc/76hcCZ5c/2007-Zi-L-131-destr-10-04-22.jpg took 0.5199820660000114 seconds to run
8928
8929
Grabbing the full link at https://i.postimg.cc/vBhbBDtw/2019-Zi-L-131-destr-31-03-22.jpg took 0.536923924999428 seconds to run
8929
8930
Grabbing the full link at https://i.postimg.cc/6q1KrSPH/2021-Zi-L-131-destr-02-06-23.jpg took 0.592135374999998 seconds to run
8930
8931
Grabbing the full link at https://i.postimg.cc/1tBGnNmW/2014-Zi-L131-destr-31-08-22.jpg took 1.5854308620000666 seconds to run
8931
8932
Grabbing the full link at https://i.postimg.cc/NFVrm6Wx/2015-zi-L131-destr-16-09-22.jpg took 1.0652978560010524 seconds to run
8932
8933
Grabbing the full link at https://i.postimg.cc/k4ZFLnLK/2003-zil131-destr-21-12-22.jpg took 0.7656293350009946 seconds to run
8933
8934
Grabbing the full link at https://i.postimg.cc/Y9KprdG6/2019-Zi-L-131-destr-17-07-23.jpg took 0.5411939690002328 seconds to run
8934
8935
Grabbing the full link at https://i.postimg.cc/0NLN683J/2022-Zi-L-131-destr-31-05-22.jpg took 0.8735594450008648 seconds to run
8935
8936
Grabbing the full link at https://i.postimg.cc/DZLwL9kp/2023-Zi-L-131-destr-31-05-22.jpg took 0.5193596129993239 seconds to run
8936
8937
Grabbing the full link at https://i.postimg.cc/qBc7RHGz/2031-Zi-L-131-destr-31-08-22.jpg took 0.5134191249999276 seconds to run
8937
8938
Grabbing the full link at https://i.postimg.cc/QMDhNSCb/2003-Zi-L-131-destr-25-07-23.jpg took 0.4931709619995672 seconds to run
8938
8939
Grabbing the full link at https://i.postimg.cc/76Q7Y3kR/2005-Zi-L-131-destr-23-07-23.jpg took 0.4990268869987631 seconds to run
8939
8940
Grabbing the full link at https://i.postimg.cc/VvxCXz5B/2006-Zi-L-131-destr-23-07-23.jpg took 0.4481309560014779 seconds to run
8940
8941
Grabbing the full link at https://i.postimg.cc/vT0W8ctW/2005-Zi-L-131-destr-08-06-23.jpg took 0.39043666799989296 seconds to run
8941
8942
Grabbing the full link at https://i.postimg.cc/6QY011dG/2021-Zi-L-131-destr-03-06-23.jpg took 1.4334750640009588 seconds to run
8942
8943
Grabbing the full link at https://i.postimg.cc/VLGmmHpd/2015-Zi-L-131-destr-16-08-23.jpg took 0.44253175300036673 seconds to run
8943
8944
Grabbing the full link at https://i.postimg.cc/FF6mJvZM/2005-Zi-L-131-destr-27-10-23.jpg took 0.6175258839994058 seconds to run
8944
8945
Grabbing the full link at https://i.postimg.cc/xdsTSFwf/23.png took 0.5468678049983282 seconds to run

Connecting to https://i.postimg.cc/xdsTSFwf/23.png ...
Downloading 23.png ...
[==================================================] 100.00%

OCR returns: H|Spring|2022
Running OCR on https://i.postimg.cc/xdsTSFwf/23.png took 31.01467206000052 seconds to run
8945
8946
Grabbing the full link at https://i.postimg.cc/3RngBxMf/665.png took 0.3791401449998375 seconds to run

Connecting to https://i.postimg.cc/3RngBxMf/665.png ...
Downloading 665.png ...
[==================================================] 100.00%

OCR returns: 11/9/2023
Running OCR on https://i.postimg.cc/3RngBxMf/665.png took 16.880376269999033 seconds to run
8946
8947
Grabbing the full link at https://i.postimg.cc/1Rb8kBVB/4315.png took 0.39727465999931155 seconds to run

Connecting to https://i.postimg.cc/1Rb8kBVB/4315.png ...
Downloading 4315.png ...
[==================================================] 100.00%

OCR returns: 16/5/2023
Running OCR on https://i.postimg.cc/1Rb8kBVB/4315.png took 19.73755489300129 seconds to run
8947
8948
Grabbing the full link at https://i.postimg.cc/4xGdC3wc/2013-Zi-L-131-destr-21-09-23.jpg took 0.3788769599996158 seconds to run
8948
8949
Grabbing the full link at https://i.postimg.cc/T1TgzpZf/2010-Zi-L-131-destr-30-11-22.jpg took 0.40359213599913346 seconds to run
8949
8950
Grabbing the full link at https://i.postimg.cc/kXhGyS82/2012-Zi-L-131-destr-21-09-23.jpg took 0.3945143620003364 seconds to run
8950
8951
Grabbing the full link at https://i.postimg.cc/9QRMgftJ/2015-Zi-L-131-destr-12-10-23.jpg took 0.4195732180014602 seconds to run
8951
8952
Grabbing the full link at https://i.postimg.cc/HLbLHPNM/2017-Zi-L-131-destr-05-10-23.jpg took 0.42941588500070793 seconds to run
8952
8953
Grabbing the full link at https://i.postimg.cc/3rs0qq4j/2002-Zi-L-131-destr-31-03-22.jpg took 0.3823188719998143 seconds to run
8953
8954
Grabbing the full link at https://i.postimg.cc/hvVPs0yK/2004-zil131-destr-31-01-24.jpg took 0.3767639470006543 seconds to run
8954
8955
Grabbing the full link at https://i.postimg.cc/76MVZP8f/2000-Zi-L-131-destr-17-11-23.jpg took 0.3776277000015398 seconds to run
8955
8956
Grabbing the full link at https://i.postimg.cc/nVjzyD9Y/2016-Zi-L-131-destr-31-05-22.jpg took 0.41527989499991236 seconds to run
8956
8957
Grabbing the full link at https://i.postimg.cc/zfzY89tY/2017-Zi-L-131-destr-31-05-24.jpg took 0.3802465339995251 seconds to run
8957
8958
Grabbing the full link at https://i.postimg.cc/MK1GTJDn/2018-Zi-L-131-destr-31-05-24.jpg took 0.36610286500035727 seconds to run
8958
8959
Grabbing the full link at https://i.postimg.cc/W4JLZ7jq/2002-Zi-L-131-destr-11-10-23.jpg took 0.3663465270001325 seconds to run
8959
8960
Grabbing the full link at https://i.postimg.cc/26Rp7B8c/2006-Zi-L-131-destr-08-12-23.jpg took 0.37416590199973143 seconds to run
8960
8961
Grabbing the full link at https://i.postimg.cc/C1c5Gjqn/2004-Zi-L-131-destr-16-07-22.jpg took 0.42960582900013833 seconds to run
8961
8962
Grabbing the full link at https://i.postimg.cc/4NsSB5g5/2007-Zi-L-131-destr-28-07-22.jpg took 0.38554547400053707 seconds to run
8962
8963
Grabbing the full link at https://i.postimg.cc/1tGBG89B/2009-Zi-L-131-destr-10-02-24.jpg took 0.3669444030001614 seconds to run
8963
8964
Grabbing the full link at https://i.postimg.cc/QMt6G2Rs/2015-Zi-L-131-destr-16-04-22.jpg took 0.3703911499997048 seconds to run
8964
8965
Grabbing the full link at https://i.postimg.cc/GtStTZP6/2032-Zi-L-131-destr-07-04-24.jpg took 0.369647163000991 seconds to run
8965
8966
Grabbing the full link at https://i.postimg.cc/1RHF8xY7/2006-Zi-L-131-destr-20-09-23.jpg took 0.3710476749984082 seconds to run
8966
8967
Grabbing the full link at https://i.postimg.cc/xjJrQkqD/2001-Zi-L-131-destr-14-03-24.jpg took 0.3628508599995257 seconds to run
8967
8968
Grabbing the full link at https://i.postimg.cc/1tCPv11g/2017-Zi-L-131-destr-07-03-24.jpg took 0.37186142199971073 seconds to run
8968
8969
Grabbing the full link at https://i.postimg.cc/bdfGrthV/2021-2x-Zi-L-131-destr-17-05-22.jpg took 0.3772916069992789 seconds to run
8969
8970
Grabbing the full link at https://i.postimg.cc/bdfGrthV/2021-2x-Zi-L-131-destr-17-05-22.jpg took 0.3632215190009447 seconds to run
8970
8971
Grabbing the full link at https://i.postimg.cc/5NCRjvHq/2007-Zi-L-131-destr-24-08-24.jpg took 0.3655718239988346 seconds to run
8971
8972
Grabbing the full link at https://i.postimg.cc/c451HDmv/2028-Zi-L-131-destr-28-08-24.jpg took 0.37397256899930653 seconds to run
8972
8973
Grabbing the full link at https://i.postimg.cc/xTFpZDBP/2019-Zi-L-131-destr-18-05-22.jpg took 0.37449019700034114 seconds to run
8973
8974
Grabbing the full link at https://i.postimg.cc/T3LNMN6v/2020-Zi-L-131-destr-18-05-22.jpg took 0.3683877349994873 seconds to run
8974
8975
Grabbing the full link at https://i.postimg.cc/3rttyQrH/2027-Zi-L-131-destr-18-05-22.jpg took 0.37880345299890905 seconds to run
8975
8976
Grabbing the full link at https://i.postimg.cc/dtD4rNDZ/2031-Zi-L-131-destr-06-09-24.jpg took 0.3633705709999049 seconds to run
8976
8977
Grabbing the full link at https://i.postimg.cc/kXZwcNt1/2032-Zi-L-131-destr-06-09-24.jpg took 0.36978650799937895 seconds to run
8977
8978
Grabbing the full link at https://i.postimg.cc/PqL9zTtc/2014-Zi-L-131-destr-02-10-24.jpg took 0.37676293100048497 seconds to run
8978
8979
Grabbing the full link at https://i.postimg.cc/PJwbn1S4/2005-Zi-L-131-destr-12-10-24.jpg took 0.36950707100004365 seconds to run
8979
8980
Grabbing the full link at https://i.postimg.cc/SKwYGz8k/2019-Zi-L-131-destr-09-08-22.jpg took 0.3772707049993187 seconds to run
8980
8981
Grabbing the full link at https://i.postimg.cc/j2TWp0Z1/2020-Zi-L-131-destr-09-08-22.jpg took 0.3715573370009224 seconds to run
8981
8982
Grabbing the full link at https://i.postimg.cc/Kj5KFqW8/2021-Zi-L-131-destr-09-08-22.jpg took 0.3699436599999899 seconds to run
8982
8983
Grabbing the full link at https://i.postimg.cc/pX9MZmmp/2010-Zi-L-131-28-02-22.jpg took 0.36799095800051873 seconds to run
8983
8984
Grabbing the full link at https://i.postimg.cc/Y2zZpZ5Q/2011-Zi-L-131-16-11-24.jpg took 0.3725505569982488 seconds to run
8984
8985
Grabbing the full link at https://i.postimg.cc/fTRLJRL8/2039-Zi-L-131-destr-31-08-24.jpg took 0.369475716001034 seconds to run
8985
8986
Grabbing the full link at https://i.postimg.cc/KcNjGMZK/2030-Zi-L-131-destr-22-05-23.jpg took 0.36763132300075085 seconds to run
8986
8987
Grabbing the full link at https://i.postimg.cc/W4wy44Y1/2005-Zi-L-131-destr-31-08-23.jpg took 0.36408759400001145 seconds to run
8987
8988
Grabbing the full link at https://i.postimg.cc/dQhQ5krp/2014-Zi-L-131-destr-03-03-22.jpg took 0.3824739510000654 seconds to run
8988
8989
Grabbing the full link at https://i.postimg.cc/NFdw0KgX/2012-Zi-L-131-destr-29-10-24.jpg took 0.3681418330015731 seconds to run
8989
8990
Grabbing the full link at https://i.postimg.cc/P5gnNskS/2018-Zi-L-131-destr-08-10-24.jpg took 0.366356819999055 seconds to run
8990
8991
Grabbing the full link at https://i.postimg.cc/j2pM7v3C/2018-Zi-L-131-destr-13-01-25.jpg took 0.3748238070002117 seconds to run
8991
8992
Grabbing the full link at https://i.postimg.cc/c4NRHV4S/2021-Zi-L-131-destr-02-10-22.jpg took 0.37555599400002393 seconds to run
8992
8993
Grabbing the full link at https://i.postimg.cc/qMrLP4Br/2020-Zi-L-131-destr-30-09-24.jpg took 0.35962993299835944 seconds to run
8993
8994
Grabbing the full link at https://i.postimg.cc/7ZYNL9TQ/2027-Zi-L-131-destr-09-02-25.jpg took 0.36614604700116615 seconds to run
8994
8995
Grabbing the full link at https://i.postimg.cc/wBr0JPhL/2120-Zi-L-131-destr-12-03-25.jpg took 0.37747175299955416 seconds to run
8995
8996
Grabbing the full link at https://i.postimg.cc/2S2Hj3yH/2193-Zi-L-131-destr-15-04-22.jpg took 0.3870250380005018 seconds to run
8996
8997
Grabbing the full link at https://i.postimg.cc/zXwq7kWT/2033-Zi-L-131-destr-27-03-25.jpg took 0.367917702998966 seconds to run
8997
8998
Grabbing the full link at https://i.postimg.cc/QtDfz5rY/2074-Zi-L-131-destr-27-03-25.jpg took 0.3756431640013034 seconds to run
8998
8999
Grabbing the full link at https://i.postimg.cc/W3RbLncN/2004-Zi-L-131-destr-08-04-25.jpg took 0.3628642880012194 seconds to run
8999
9000
Grabbing the full link at https://i.postimg.cc/zBTH8GMc/2016-Zi-L-131-destr-01-04-25.jpg took 0.36681579600008263 seconds to run
9000
Saved at index 9000
9001
Grabbing the full link at https://i.postimg.cc/L8yTRS59/2016-Zi-L-131-destr-30-04-25.jpg took 0.357977457000743 seconds to run
9001
9002
Grabbing the full link at https://i.postimg.cc/5yLtTGDL/2010-Zi-L131-dam-12-01-23.jpg took 0.3642788590004784 seconds to run
9002
9003
Grabbing the full link at https://i.postimg.cc/tTYNBXxD/2017-Zi-L-131-dam-14-03-24.jpg took 0.3650820679995377 seconds to run
9003
9004
Grabbing the full link at https://i.postimg.cc/FFP76LtG/2033-Zi-L-131-dam-07-04-24.jpg took 0.36783187500077474 seconds to run
9004
9005
Grabbing the full link at https://i.postimg.cc/C1V03Rjg/2000-Zi-L-131-dam-29-05-24.jpg took 0.3658718520000548 seconds to run
9005
9006
Grabbing the full link at https://i.postimg.cc/0j3LGCqH/Screenshot-8103.png took 0.40302491200054646 seconds to run

Connecting to https://i.postimg.cc/0j3LGCqH/Screenshot-8103.png ...
Downloading Screenshot-8103.png ...
[==================================================] 100.00%

OCR returns: 25/02/2022|18.4K views|0:08/ 0:17|2|0
Running OCR on https://i.postimg.cc/0j3LGCqH/Screenshot-8103.png took 27.14090160199885 seconds to run
9006
9007
Grabbing the full link at https://i.postimg.cc/GtdZZwDv/2017-Zi-L-131-dam-aband-20-02-24.jpg took 0.7914074350010196 seconds to run
9007
9008
Grabbing the full link at https://i.postimg.cc/P5Y9S2VJ/d23.png took 0.5798256540001603 seconds to run

Connecting to https://i.postimg.cc/P5Y9S2VJ/d23.png ...
Downloading d23.png ...
[==================================================] 100.00%

OCR returns: 02/3/2022|Deauapnkaunn|Lneldenazi UA|0:15/0:25|4
Running OCR on https://i.postimg.cc/P5Y9S2VJ/d23.png took 27.724895948998892 seconds to run
9008
9009
Grabbing the full link at https://i.postimg.cc/FsT4y5HJ/287.png took 0.41544655299912847 seconds to run

Connecting to https://i.postimg.cc/FsT4y5HJ/287.png ...
Downloading 287.png ...
[==================================================] 100.00%

OCR returns: M3BELTHRLE|M3BECTHALE|M3BECTHR0|M3BELTH|13BECTH8|M3BECT181E|12/5/2022
Running OCR on https://i.postimg.cc/FsT4y5HJ/287.png took 11.877807732998917 seconds to run
9009
9010
Returning non-postimg link
9010
9011
Grabbing the full link at https://i.postimg.cc/Znf3n1fc/542f.png took 0.4489317999996274 seconds to run

Connecting to https://i.postimg.cc/Znf3n1fc/542f.png ...
Downloading 542f.png ...
[==================================================] 100.00%

OCR returns: HaMNTe ESCuTO BbIN M3OAHOKPaHHOO PNM|10/3/2022|U|R
Running OCR on https://i.postimg.cc/Znf3n1fc/542f.png took 31.51808702100061 seconds to run
9011
9012
Grabbing the full link at https://i.postimg.cc/x1HHQSgC/1301.png took 0.4135794760004501 seconds to run

Connecting to https://i.postimg.cc/x1HHQSgC/1301.png ...
Downloading 1301.png ...
[==================================================] 100.00%

OCR returns: 12/3/2022|CBAPENKNZ|https://t.me/svarschiki
Running OCR on https://i.postimg.cc/x1HHQSgC/1301.png took 10.11291888499909 seconds to run
9012
9013

Connecting to https://i.postimg.cc/x1HHQSgC/1301.png ...
Downloading 1301.png ...
[                                                  ] 0.81%

Grabbing the full link at https://i.postimg.cc/x1HHQSgC/1301.png took 0.45076289499957056 seconds to run

[==================================================] 100.00%

OCR returns: 12/3/2022|CBAPENKNZ|https://t.me/svarschiki
Running OCR on https://i.postimg.cc/x1HHQSgC/1301.png took 9.734225455000342 seconds to run
9013
9014
Grabbing the full link at https://i.postimg.cc/gJVGn38f/2002-Zi-L-131-capt-31-12-22.jpg took 0.41453967899906274 seconds to run
9014
9015
Grabbing the full link at https://i.postimg.cc/kXMB2DzL/43.png took 0.4070723929999076 seconds to run

Connecting to https://i.postimg.cc/kXMB2DzL/43.png ...
Downloading 43.png ...
[==================================================] 100.00%

OCR returns: Onewkn,|XepcoH.|25.02.22|TikTok|@andriiboiko93kh
Running OCR on https://i.postimg.cc/kXMB2DzL/43.png took 28.6110796189987 seconds to run
9015
9016
Grabbing the full link at https://i.postimg.cc/5tCYqTxz/5gh.png took 0.37056501699953515 seconds to run

Connecting to https://i.postimg.cc/5tCYqTxz/5gh.png ...
Downloading 5gh.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long. Crimea front line. Russia Ukraine War 2022 02 25|0|Y|OnewKn,XepcoH.|25.02.22|TikTok|！|1|0:22/13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/5tCYqTxz/5gh.png took 33.52248664000035 seconds to run
9016
9017

Connecting to https://i.postimg.cc/gJR5my9Q/769.png ...
Downloading 769.png ...
[                                                  ] 0.25%

Grabbing the full link at https://i.postimg.cc/gJR5my9Q/769.png took 0.37451482500000566 seconds to run

[==================================================] 100.00%

OCR returns: iz|19/4/2022|PRESS|0:00/1:29
Running OCR on https://i.postimg.cc/gJR5my9Q/769.png took 27.183231553999576 seconds to run
9017
9018
Grabbing the full link at https://i.postimg.cc/MpBn265v/Screenshot-8120.png took 0.6728890650010726 seconds to run

Connecting to https://i.postimg.cc/MpBn265v/Screenshot-8120.png ...
Downloading Screenshot-8120.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|Y|Onewkn,|XepcoH.|25.02.22|TikTok|c:||1|0:48/13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/MpBn265v/Screenshot-8120.png took 34.336243249999825 seconds to run
9018
9019
Grabbing the full link at https://i.postimg.cc/cHSzkJwf/1081-Zi-L-131-capt-25-02-22.jpg took 0.42888317399956577 seconds to run
9019
9020
Grabbing the full link at https://i.postimg.cc/26D3NxHS/2047-Zi-L-131-capt-26-02-22.jpg took 0.49567729999944277 seconds to run
9020
9021
Grabbing the full link at https://i.postimg.cc/52B628K8/776.png took 0.47268223100036266 seconds to run

Connecting to https://i.postimg.cc/52B628K8/776.png ...
Downloading 776.png ...
[==================================================] 100.00%

OCR returns: 04/3/2022|ZIL-131ARS-14|KraZ-260（ATZ-9|60)|raz5233|ZIL-131,ZIL-131(ZU-23)，|ZIL-131ARS-14|GAZ-66,GAZ-3307|GAZ-66|-131|2BMP-1P|URAL-375,UAZ-469,|GAZ-66
Running OCR on https://i.postimg.cc/52B628K8/776.png took 28.982378890999826 seconds to run
9021
9022

Connecting to https://i.postimg.cc/52B628K8/776.png ...
Downloading 776.png ...
[                                                  ] 0.28%

Grabbing the full link at https://i.postimg.cc/52B628K8/776.png took 0.4715802770006121 seconds to run

[==================================================] 100.00%

OCR returns: 04/3/2022|ZIL-131ARS-14|KraZ-260（ATZ-9|60)|raz5233|ZIL-131,ZIL-131(ZU-23)，|ZIL-131ARS-14|GAZ-66,GAZ-3307|GAZ-66|-131|2BMP-1P|URAL-375,UAZ-469,|GAZ-66
Running OCR on https://i.postimg.cc/52B628K8/776.png took 27.85203209700012 seconds to run
9022
9023

Connecting to https://i.postimg.cc/52B628K8/776.png ...
Downloading 776.png ...
[                                                  ] 0.28%

Grabbing the full link at https://i.postimg.cc/52B628K8/776.png took 0.5102749449997646 seconds to run

[==================================================] 100.00%

OCR returns: 04/3/2022|ZIL-131ARS-14|KraZ-260（ATZ-9|60)|raz5233|ZIL-131,ZIL-131(ZU-23)，|ZIL-131ARS-14|GAZ-66,GAZ-3307|GAZ-66|-131|2BMP-1P|URAL-375,UAZ-469,|GAZ-66
Running OCR on https://i.postimg.cc/52B628K8/776.png took 44.56494499799919 seconds to run
9023
9024
Grabbing the full link at https://i.postimg.cc/gjZJhhsy/14.png took 0.3782241389999399 seconds to run

Connecting to https://i.postimg.cc/gjZJhhsy/14.png ...
Downloading 14.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction-15km long.Crimeafront line.Russia Ukraine War2022 0225|0|?|OnewknXepcoH.|25.02.22|TikTok|1|3:39/ 13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/gjZJhhsy/14.png took 48.50510553899949 seconds to run
9024
9025

Connecting to https://i.postimg.cc/gjZJhhsy/14.png ...
Downloading 14.png ...
[                                                  ] 0.76%

Grabbing the full link at https://i.postimg.cc/gjZJhhsy/14.png took 0.5726827290000074 seconds to run

[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction-15km long.Crimeafront line.Russia Ukraine War2022 0225|0|?|OnewknXepcoH.|25.02.22|TikTok|1|3:39/ 13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/gjZJhhsy/14.png took 34.88243339499968 seconds to run
9025
9026
Grabbing the full link at https://i.postimg.cc/Fsxkm2Wh/71.png took 0.41285013200104004 seconds to run

Connecting to https://i.postimg.cc/Fsxkm2Wh/71.png ...
Downloading 71.png ...
[==================================================] 100.00%

OCR returns: AHTOHOBCKNN|MOCT.|25.02.22|akTyanbHag|AP|no|NOBOAy|cnTyaunn.|TikTok|@andriiboiko93kh
Running OCR on https://i.postimg.cc/Fsxkm2Wh/71.png took 28.684975997999572 seconds to run
9026
9027
Grabbing the full link at https://i.postimg.cc/W3WjXwXL/Screenshot-8114.png took 0.5083763870006806 seconds to run

Connecting to https://i.postimg.cc/W3WjXwXL/Screenshot-8114.png ...
Downloading Screenshot-8114.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|Y|Onewkn,|XepcOH.|25.02.22|TikTok|1|0:33/13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/W3WjXwXL/Screenshot-8114.png took 34.029339909000555 seconds to run
9027
9028
Grabbing the full link at https://i.postimg.cc/WpqbXQL5/Screenshot-8113.png took 0.37284423199889716 seconds to run

Connecting to https://i.postimg.cc/WpqbXQL5/Screenshot-8113.png ...
Downloading Screenshot-8113.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long. Crimea front line. Russia Ukraine War 2022 02 25|0|Y|Onewkn,|XepcOH.|25.02.22|TikTok|1|0:30/13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/WpqbXQL5/Screenshot-8113.png took 33.78229223000017 seconds to run
9028
9029
Grabbing the full link at https://i.postimg.cc/YCr7KPZK/Screenshot-8156.png took 0.36868027899981826 seconds to run

Connecting to https://i.postimg.cc/YCr7KPZK/Screenshot-8156.png ...
Downloading Screenshot-8156.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|Y|AoporaHaXepcoH|yepe3AHTOHOBCKN|MOCT.|Onewkn|25.02.22|TikTok|1|4:39/ 13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/YCr7KPZK/Screenshot-8156.png took 38.821174544000314 seconds to run
9029
9030
Grabbing the full link at https://i.postimg.cc/SxghyrbX/Screenshot-8159.png took 0.47551384500002314 seconds to run

Connecting to https://i.postimg.cc/SxghyrbX/Screenshot-8159.png ...
Downloading Screenshot-8159.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|?|AoporaHa|XepcoH|yepe3|AHTOHOBCKN|MOCT.|Onewkn|25.02.22|TikTok|1|6:07/ 13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/SxghyrbX/Screenshot-8159.png took 33.71372684800008 seconds to run
9030
9031

Connecting to https://i.postimg.cc/jdK0P9sw/Screenshot-8123.png ...
Downloading Screenshot-8123.png ...
[                                                  ] 1.21%

Grabbing the full link at https://i.postimg.cc/jdK0P9sw/Screenshot-8123.png took 0.43792143300015596 seconds to run

[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 0225|0|Y|Onewkn|XepcoH.|25.02.22|ikTo|▶|1|1:06/ 13:25|@andriiboiko93kh|D|E|*|1
Running OCR on https://i.postimg.cc/jdK0P9sw/Screenshot-8123.png took 34.70632092999949 seconds to run
9031
9032
Grabbing the full link at https://i.postimg.cc/Dwx8tLC6/Screenshot-8135.png took 0.4228177950008103 seconds to run

Connecting to https://i.postimg.cc/Dwx8tLC6/Screenshot-8135.png ...
Downloading Screenshot-8135.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|Y|Onewkn,|XepcOH.|25.02.22|TikTok|1:50/13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/Dwx8tLC6/Screenshot-8135.png took 32.50291954000022 seconds to run
9032
9033
Grabbing the full link at https://i.postimg.cc/tTXvY0dp/Screenshot-8143.png took 0.383046987999478 seconds to run

Connecting to https://i.postimg.cc/tTXvY0dp/Screenshot-8143.png ...
Downloading Screenshot-8143.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|Y|Onewkn,|XepcoH.|25.02.22|TikTok|1|3:02 / 13:25|.|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/tTXvY0dp/Screenshot-8143.png took 33.771959159999824 seconds to run
9033
9034
Grabbing the full link at https://i.postimg.cc/5tJ4Dk4r/2001-zil131-capt-04-03-22.jpg took 0.3711288260001311 seconds to run
9034
9035
Grabbing the full link at https://i.postimg.cc/kgKM1dm8/2002-zil131-capt-04-03-22.jpg took 0.38254333099939686 seconds to run
9035
9036
Grabbing the full link at https://i.postimg.cc/7YDGd3yD/2024-Zi-L-131-dam-capt-29-08-22.jpg took 0.4681844620008633 seconds to run
9036
9037
Grabbing the full link at https://i.postimg.cc/0NJk1TQ5/2027-Zi-L-131-capt-19-04-22.jpg took 0.37649697800043214 seconds to run
9037
9038
Grabbing the full link at https://i.postimg.cc/CMqVxGPy/tt3.png took 0.37507826200089767 seconds to run

Connecting to https://i.postimg.cc/CMqVxGPy/tt3.png ...
Downloading tt3.png ...
[==================================================] 100.00%

OCR returns: 17/4/2022|t.me/MSGazdiev|t.me/Murad_Gazdiey|0:31 / 1:43|4
Running OCR on https://i.postimg.cc/CMqVxGPy/tt3.png took 27.77167827899939 seconds to run
9038
9039
Grabbing the full link at https://i.postimg.cc/66Rmy0HF/37.png took 0.4229236999999557 seconds to run

Connecting to https://i.postimg.cc/66Rmy0HF/37.png ...
Downloading 37.png ...
[==================================================] 100.00%

OCR returns: 25/4/2022
Running OCR on https://i.postimg.cc/66Rmy0HF/37.png took 27.571896298000865 seconds to run
9039
9040
Grabbing the full link at https://i.postimg.cc/66Rmy0HF/37.png took 0.4530235879992688 seconds to run

Connecting to https://i.postimg.cc/66Rmy0HF/37.png ...
Downloading 37.png ...
[==================================================] 100.00%

OCR returns: 25/4/2022
Running OCR on https://i.postimg.cc/66Rmy0HF/37.png took 26.55254965399945 seconds to run
9040
9041
Grabbing the full link at https://i.postimg.cc/BbS3BJ4w/668.jpg took 0.3706024849998357 seconds to run

Connecting to https://i.postimg.cc/BbS3BJ4w/668.jpg ...
Downloading 668.jpg ...
[==================================================] 100.00%

OCR returns: 29.04.2022
Running OCR on https://i.postimg.cc/BbS3BJ4w/668.jpg took 22.569504129998677 seconds to run
9041
9042
Grabbing the full link at https://i.postimg.cc/KzPKpVCk/Screenshot-8115.png took 0.46839687099964067 seconds to run

Connecting to https://i.postimg.cc/KzPKpVCk/Screenshot-8115.png ...
Downloading Screenshot-8115.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction-15km long.Crimeafront line.Russia Ukraine War2022 0225|0|Y|Onewkn,|XepcOH.|25.02.22|TikTok|▶:|1|0:35/13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/KzPKpVCk/Screenshot-8115.png took 36.020628439000575 seconds to run
9042
9043
Grabbing the full link at https://i.postimg.cc/CMbncvXm/2029-Zi-L-131-dam-capt-29-08-22.jpg took 0.36607927799923345 seconds to run
9043
9044

Connecting to https://i.postimg.cc/7LSW8dKp/35.png ...
Downloading 35.png ...
[                                                  ] 0.34%

Grabbing the full link at https://i.postimg.cc/7LSW8dKp/35.png took 0.3664513009989605 seconds to run

[==================================================] 100.00%

OCR returns: 04/3/2022|enNMBCeBO3MOKHyIOTeXHNKY,
Running OCR on https://i.postimg.cc/7LSW8dKp/35.png took 27.491844195999875 seconds to run
9044
9045

Connecting to https://i.postimg.cc/fL9yXJ40/bf.png ...
Downloading bf.png ...
[                                                  ] 0.27%

Grabbing the full link at https://i.postimg.cc/fL9yXJ40/bf.png took 0.5937518629998522 seconds to run

[==================================================] 100.00%

OCR returns: iz|05/3/2022|3,603views|0:38/1:18
Running OCR on https://i.postimg.cc/fL9yXJ40/bf.png took 27.337351590000253 seconds to run
9045
9046
Grabbing the full link at https://i.postimg.cc/nzGPytGg/1080-zil131-capt-25-02-22.jpg took 0.40036135900118097 seconds to run
9046
9047
Grabbing the full link at https://i.postimg.cc/R0SXMspN/s1.png took 0.39471005800078274 seconds to run

Connecting to https://i.postimg.cc/R0SXMspN/s1.png ...
Downloading s1.png ...
[==================================================] 100.00%

OCR returns: 05/3/2022
Running OCR on https://i.postimg.cc/R0SXMspN/s1.png took 20.441942249999556 seconds to run
9047
9048

Connecting to https://i.postimg.cc/fLFKfwz9/s4.png ...
Downloading s4.png ...
[                                                  ] 0.39%

Grabbing the full link at https://i.postimg.cc/fLFKfwz9/s4.png took 0.41707418500118365 seconds to run

[==================================================] 100.00%

OCR returns: _|国|05/3/2022
Running OCR on https://i.postimg.cc/fLFKfwz9/s4.png took 20.39302397100073 seconds to run
9048
9049

Connecting to https://i.postimg.cc/cChFLXF9/4333.png ...
Downloading 4333.png ...
[                                                  ] 0.23%

Grabbing the full link at https://i.postimg.cc/cChFLXF9/4333.png took 0.46007729599841696 seconds to run

[==================================================] 100.00%

OCR returns: iz|112E6|19/4/2022|0:01/1:29
Running OCR on https://i.postimg.cc/cChFLXF9/4333.png took 49.197266767001565 seconds to run
9049
9050
Grabbing the full link at https://i.postimg.cc/vH6XjZGt/4f6.png took 1.2946302549989923 seconds to run

Connecting to https://i.postimg.cc/vH6XjZGt/4f6.png ...
Downloading 4f6.png ...
[==================================================] 100.00%

OCR returns: 13/3/2023|295854
Running OCR on https://i.postimg.cc/vH6XjZGt/4f6.png took 17.767105607999838 seconds to run
9050
9051
Grabbing the full link at https://i.postimg.cc/VkykBdTy/887k.png took 0.37318401399897994 seconds to run

Connecting to https://i.postimg.cc/VkykBdTy/887k.png ...
Downloading 887k.png ...
[==================================================] 100.00%

OCR returns: 12/4/2022|21546
Running OCR on https://i.postimg.cc/VkykBdTy/887k.png took 26.31529386300099 seconds to run
9051
9052
Grabbing the full link at https://i.postimg.cc/ryZpzJjd/2013-zil131-capt-04-03-22.jpg took 0.4308506279994617 seconds to run
9052
9053
Grabbing the full link at https://i.postimg.cc/h4TsZfBM/2012-Zi-L-131-capt-23-04-22.jpg took 0.4314049860004161 seconds to run
9053
9054
Grabbing the full link at https://i.postimg.cc/VLFR1p5C/2010-Zi-L-131-capt-23-04-22.jpg took 0.46798659700107237 seconds to run
9054
9055
Grabbing the full link at https://i.postimg.cc/Bb3Fnx8v/bl.png took 0.47083593199931784 seconds to run

Connecting to https://i.postimg.cc/Bb3Fnx8v/bl.png ...
Downloading bl.png ...
[==================================================] 100.00%

OCR returns: iz|EPN BAYHU|05/3/2022|3,603 views|0:11/1:18
Running OCR on https://i.postimg.cc/Bb3Fnx8v/bl.png took 29.00351549900006 seconds to run
9055
9056
Grabbing the full link at https://i.postimg.cc/NGnqbnGg/2011-KT-L-and-Zi-L131-tanker-destr-11-06-22.jpg took 0.40185565299907466 seconds to run
9056
9057
Grabbing the full link at https://i.postimg.cc/HL3B8Y48/2040-Zi-L-131-tanker-destr-07-01-23.jpg took 0.4856122960009088 seconds to run
9057
9058
Grabbing the full link at https://i.postimg.cc/0NKd9XFP/43.png took 0.408125967001979 seconds to run

Connecting to https://i.postimg.cc/0NKd9XFP/43.png ...
Downloading 43.png ...
[==================================================] 100.00%

OCR returns: 12/7/2023|3921
Running OCR on https://i.postimg.cc/0NKd9XFP/43.png took 27.408597740002733 seconds to run
9058
9059
Grabbing the full link at https://i.postimg.cc/MpR6pXC4/2001-Zi-L-131-tanker-destr-16-02-24.jpg took 0.4947731440006464 seconds to run
9059
9060
Grabbing the full link at https://i.postimg.cc/g2FJtkrh/2005-Zil-131-tanker-dam-15-07-23.jpg took 0.525399751997611 seconds to run
9060
9061

Connecting to https://i.postimg.cc/bvh79gN2/d240.png ...
Downloading d240.png ...
[                                                  ] 1.05%

Grabbing the full link at https://i.postimg.cc/bvh79gN2/d240.png took 0.4658705590009049 seconds to run

[==================================================] 100.00%

OCR returns: 10/3/2022|TenerpaMMKaHan|XapbKOB·Life|0:12 / 0:15|4
Running OCR on https://i.postimg.cc/bvh79gN2/d240.png took 27.943667416002427 seconds to run
9061
9062

Connecting to https://i.postimg.cc/vBpfYjxd/g8.png ...
Downloading g8.png ...
[                                                  ] 0.68%

Grabbing the full link at https://i.postimg.cc/vBpfYjxd/g8.png took 0.4884209980009473 seconds to run

[==================================================] 100.00%

OCR returns: 04/3/2022|BUA
Running OCR on https://i.postimg.cc/vBpfYjxd/g8.png took 14.967876005001017 seconds to run
9062
9063
Grabbing the full link at https://i.postimg.cc/pL2R6nY4/2030-Zi-L-131-tanker-capt-16-03-22.jpg took 0.4293005420004192 seconds to run
9063
9064
Grabbing the full link at https://i.postimg.cc/05h304Pd/Screenshot-8143.png took 0.6506888040021295 seconds to run

Connecting to https://i.postimg.cc/05h304Pd/Screenshot-8143.png ...
Downloading Screenshot-8143.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|Y|Onewkn,|XepcoH.|25.02.22|TikTok|1|3:02 / 13:25|.|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/05h304Pd/Screenshot-8143.png took 35.027717111999664 seconds to run
9064
9065
Grabbing the full link at https://i.postimg.cc/W3b21FJ6/2000-zil157-capt-04-03-22.jpg took 0.38663223600087804 seconds to run
9065
9066
Grabbing the full link at https://i.postimg.cc/4dh6yP2f/d1.png took 0.36759225399873685 seconds to run

Connecting to https://i.postimg.cc/4dh6yP2f/d1.png ...
Downloading d1.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction-15km long.Crimea front line.Russia Ukraine War2022 0225|0|Y|Onewkn,|XepcoH.|25.02.22|TikTok|!|1|1:28/ 13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/4dh6yP2f/d1.png took 36.25095741500263 seconds to run
9066
9067
Grabbing the full link at https://i.postimg.cc/pVwYY1d1/2020-Zi-L-4331-destr-05-10-24.jpg took 0.5189540070023213 seconds to run
9067
9068
Grabbing the full link at https://i.postimg.cc/jdwPsc1f/1012.jpg took 0.49325371099985205 seconds to run

Connecting to https://i.postimg.cc/jdwPsc1f/1012.jpg ...
Downloading 1012.jpg ...
[==================================================] 100.00%

OCR returns: 25.02.2022|06.03.2022|AHTOHOBCKNN|MOCT.|25.02.22|akTyanbHa|APOPArn|nO nOBOAy|cnTyaunn.|TikTok|@andriiboiko93kh
Running OCR on https://i.postimg.cc/jdwPsc1f/1012.jpg took 27.452310490003583 seconds to run
9068
9069
Grabbing the full link at https://i.postimg.cc/KYnsJT3S/22.png took 0.5008210069972847 seconds to run

Connecting to https://i.postimg.cc/KYnsJT3S/22.png ...
Downloading 22.png ...
[==================================================] 100.00%

OCR returns: 14/4/2022|7|military_politik
Running OCR on https://i.postimg.cc/KYnsJT3S/22.png took 25.439477944000828 seconds to run
9069
9070
Grabbing the full link at https://i.postimg.cc/PrGqVsJ6/2003-Ural-375-D-destr-02-04-24.jpg took 0.6114783319972048 seconds to run
9070
9071
Grabbing the full link at https://i.postimg.cc/NFTJCRZH/2028-Ural-375-D-destr-05-05-24.jpg took 0.6032610289985314 seconds to run
9071
9072
Grabbing the full link at https://i.postimg.cc/90crT04r/776.png took 1.210903959999996 seconds to run

Connecting to https://i.postimg.cc/90crT04r/776.png ...
Downloading 776.png ...
[==================================================] 100.00%

OCR returns: 04/3/2022|ZIL-131ARS-14|KraZ-260(ATZ-9.3-260）|KraZ-5233|ZIL-131,ZIL-131（ZU-23）,|ZIL-131ARS-14|GAZ-66,GAZ-3307|GAZ-66|ZIL-131|2BMP-1P|URAL375,UAZ-469,|GAZ-66
Running OCR on https://i.postimg.cc/90crT04r/776.png took 30.64186615699873 seconds to run
9072
9073

Connecting to https://i.postimg.cc/cHZMXQ6m/Screenshot-8149.png ...
Downloading Screenshot-8149.png ...
[                                                  ] 1.22%

Grabbing the full link at https://i.postimg.cc/cHZMXQ6m/Screenshot-8149.png took 0.47969891899992945 seconds to run

[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|Y|Onewkn,|XepcoH|25.02.22|TikTok|1|3:07 / 13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/cHZMXQ6m/Screenshot-8149.png took 34.59873985100057 seconds to run
9073
9074
Grabbing the full link at https://i.postimg.cc/3wrx1NYG/Screenshot-8113.png took 0.38340577200142434 seconds to run

Connecting to https://i.postimg.cc/3wrx1NYG/Screenshot-8113.png ...
Downloading Screenshot-8113.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long. Crimea front line. Russia Ukraine War 2022 02 25|0|Y|Onewkn,|XepcOH.|25.02.22|TikTok|1|0:30/13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/3wrx1NYG/Screenshot-8113.png took 34.783362931997544 seconds to run
9074
9075
Grabbing the full link at https://i.postimg.cc/NM5JHFdK/4331.png took 0.37225047199899564 seconds to run

Connecting to https://i.postimg.cc/NM5JHFdK/4331.png ...
Downloading 4331.png ...
[==================================================] 100.00%

OCR returns: 28/3/2022|161
Running OCR on https://i.postimg.cc/NM5JHFdK/4331.png took 23.168256990000373 seconds to run
9075
9076
Grabbing the full link at https://i.postimg.cc/tT4XMQ4W/6665.jpg took 0.38766676999875926 seconds to run

Connecting to https://i.postimg.cc/tT4XMQ4W/6665.jpg ...
Downloading 6665.jpg ...
[==================================================] 100.00%

OCR returns: 城|30/03/2022|N
Running OCR on https://i.postimg.cc/tT4XMQ4W/6665.jpg took 23.97616217199902 seconds to run
9076
9077

Connecting to https://i.postimg.cc/vHvy3FYx/31.png ...
Downloading 31.png ...
[                                                  ] 0.22%

Grabbing the full link at https://i.postimg.cc/vHvy3FYx/31.png took 0.48720566100018914 seconds to run

[==================================================] 100.00%

OCR returns: RVvoenkor|#|RusVesnaSu|02/5/2022
Running OCR on https://i.postimg.cc/vHvy3FYx/31.png took 26.01421944899994 seconds to run
9077
9078
Grabbing the full link at https://i.postimg.cc/P5WfMppV/399.png took 0.3844318130031752 seconds to run

Connecting to https://i.postimg.cc/P5WfMppV/399.png ...
Downloading 399.png ...
[==================================================] 100.00%

OCR returns: 11/5/2022
Running OCR on https://i.postimg.cc/P5WfMppV/399.png took 24.930428499999834 seconds to run
9078
9079

Connecting to https://i.postimg.cc/3wXqjPj0/Screenshot-8077.png ...
Downloading Screenshot-8077.png ...
[                                                  ] 0.84%

Grabbing the full link at https://i.postimg.cc/3wXqjPj0/Screenshot-8077.png took 0.4057561599984183 seconds to run

[==================================================] 100.00%

OCR returns: 25/02/2022|11.7K views|0:28/ 0:46|0
Running OCR on https://i.postimg.cc/3wXqjPj0/Screenshot-8077.png took 27.17695722800272 seconds to run
9079
9080

Connecting to https://i.postimg.cc/vmqnP67C/223.png ...
Downloading 223.png ...
[                                                  ] 0.28%

Grabbing the full link at https://i.postimg.cc/vmqnP67C/223.png took 0.5371916789990792 seconds to run

[==================================================] 100.00%

OCR returns: NPECC-C/IYK6A|HAPOAHONMNnNLNN|CKONHAPOAHONPECNYENKM|mil-Inr.info|03/2/2022
Running OCR on https://i.postimg.cc/vmqnP67C/223.png took 29.77668758299842 seconds to run
9080
9081
Grabbing the full link at https://i.postimg.cc/rshQS3MH/f4.png took 0.3717249690016615 seconds to run

Connecting to https://i.postimg.cc/rshQS3MH/f4.png ...
Downloading f4.png ...
[==================================================] 100.00%

OCR returns: 02/3/2022|297554
Running OCR on https://i.postimg.cc/rshQS3MH/f4.png took 21.662137630999496 seconds to run
9081
9082
Grabbing the full link at https://i.postimg.cc/GmRQzM1X/g8k.png took 0.3826151969988132 seconds to run

Connecting to https://i.postimg.cc/GmRQzM1X/g8k.png ...
Downloading g8k.png ...
[==================================================] 100.00%

OCR returns: 06.03.2022|06/3/2022|T.ME/FACEOFW
Running OCR on https://i.postimg.cc/GmRQzM1X/g8k.png took 32.77679151600023 seconds to run
9082
9083
Grabbing the full link at https://i.postimg.cc/YStP5QYc/16.png took 0.8341489849990467 seconds to run

Connecting to https://i.postimg.cc/YStP5QYc/16.png ...
Downloading 16.png ...
[==================================================] 100.00%

OCR returns: 30/3/2022
Running OCR on https://i.postimg.cc/YStP5QYc/16.png took 42.051732880998316 seconds to run
9083
9084
Returning non-postimg link
9084
9085
Grabbing the full link at https://i.postimg.cc/TY5V8GDn/36.png took 0.5010152870017919 seconds to run

Connecting to https://i.postimg.cc/TY5V8GDn/36.png ...
Downloading 36.png ...
[==================================================] 100.00%

OCR returns: RVvoenkor|01/6/2022|RusVesna Su
Running OCR on https://i.postimg.cc/TY5V8GDn/36.png took 35.22347128399997 seconds to run
9085
9086
Grabbing the full link at https://i.postimg.cc/JzB6VTpG/1009.png took 0.4314950330008287 seconds to run

Connecting to https://i.postimg.cc/JzB6VTpG/1009.png ...
Downloading 1009.png ...
[==================================================] 100.00%

OCR returns: 24.02.2022|TikTok|@litvinenko.milla09
Running OCR on https://i.postimg.cc/JzB6VTpG/1009.png took 10.899861491998308 seconds to run
9086
9087
Grabbing the full link at https://i.postimg.cc/RZ29PkHs/54799.png took 0.5040096929988067 seconds to run

Connecting to https://i.postimg.cc/RZ29PkHs/54799.png ...
Downloading 54799.png ...
[==================================================] 100.00%

OCR returns: RVvoenkor|01/6/2022|RusVesna Su
Running OCR on https://i.postimg.cc/RZ29PkHs/54799.png took 28.13342143599948 seconds to run
9087
9088
Grabbing the full link at https://i.postimg.cc/RZ29PkHs/54799.png took 0.38315815099849715 seconds to run

Connecting to https://i.postimg.cc/RZ29PkHs/54799.png ...
Downloading 54799.png ...
[==================================================] 100.00%

OCR returns: RVvoenkor|01/6/2022|RusVesna Su
Running OCR on https://i.postimg.cc/RZ29PkHs/54799.png took 27.49290794099943 seconds to run
9088
9089
Grabbing the full link at https://i.postimg.cc/W1yLc2Qj/1011.png took 0.42677103800087934 seconds to run

Connecting to https://i.postimg.cc/W1yLc2Qj/1011.png ...
Downloading 1011.png ...
[==================================================] 100.00%

OCR returns: 06.03.2022
Running OCR on https://i.postimg.cc/W1yLc2Qj/1011.png took 5.187859583002137 seconds to run
9089
9090
Grabbing the full link at https://i.postimg.cc/rm84TwFg/2022-09-16-UA-Ural-4320.png took 0.36491011699763476 seconds to run

Connecting to https://i.postimg.cc/rm84TwFg/2022-09-16-UA-Ural-4320.png ...
Downloading 2022-09-16-UA-Ural-4320.png ...
[==================================================] 100.00%

OCR returns: TikTok|16/09/2022|@a.rokytna|Kharkiv Oblast|Banaknia Ta l3lom
Running OCR on https://i.postimg.cc/rm84TwFg/2022-09-16-UA-Ural-4320.png took 11.539660034999542 seconds to run
9090
9091
Grabbing the full link at https://i.postimg.cc/6p203Qjd/7.png took 0.36828833400068106 seconds to run

Connecting to https://i.postimg.cc/6p203Qjd/7.png ...
Downloading 7.png ...
[==================================================] 100.00%

OCR returns: During spring 2022, Kharkiv region
Running OCR on https://i.postimg.cc/6p203Qjd/7.png took 28.673584224998194 seconds to run
9091
9092
Grabbing the full link at https://i.postimg.cc/HxyLd7jM/1018-unkn-truck-2x.jpg took 0.4838178190002509 seconds to run

Connecting to https://i.postimg.cc/HxyLd7jM/1018-unkn-truck-2x.jpg ...
Downloading 1018-unkn-truck-2x.jpg ...
[==================================================] 100.00%

OCR returns: 07.09.2022
Running OCR on https://i.postimg.cc/HxyLd7jM/1018-unkn-truck-2x.jpg took 20.216930334998324 seconds to run
9092
9093

Connecting to https://i.postimg.cc/HxyLd7jM/1018-unkn-truck-2x.jpg ...
Downloading 1018-unkn-truck-2x.jpg ...
[=                                                 ] 3.04%

Grabbing the full link at https://i.postimg.cc/HxyLd7jM/1018-unkn-truck-2x.jpg took 0.3938575989996025 seconds to run

[==================================================] 100.00%

OCR returns: 07.09.2022
Running OCR on https://i.postimg.cc/HxyLd7jM/1018-unkn-truck-2x.jpg took 19.7687413019994 seconds to run
9093
9094

Connecting to https://i.postimg.cc/xqr34p57/10-13-2022-UA-Ural-4320-destroyed.png ...
Downloading 10-13-2022-UA-Ural-4320-destroyed.png ...
[                                                  ] 0.30%

Grabbing the full link at https://i.postimg.cc/xqr34p57/10-13-2022-UA-Ural-4320-destroyed.png took 0.3968192230022396 seconds to run

[==================================================] 100.00%

OCR returns: 13.10.2022|十|十
Running OCR on https://i.postimg.cc/xqr34p57/10-13-2022-UA-Ural-4320-destroyed.png took 17.44555891699929 seconds to run
9094
9095

Connecting to https://i.postimg.cc/N0nx31kj/UA-GAZ-66-Zil-130-Ural-4320-destroyed.png ...
Downloading UA-GAZ-66-Zil-130-Ural-4320-destroyed.png ...
[                                                  ] 0.41%

Grabbing the full link at https://i.postimg.cc/N0nx31kj/UA-GAZ-66-Zil-130-Ural-4320-destroyed.png took 0.39406759000121383 seconds to run

[==================================================] 100.00%

OCR returns: 13.11.2022|CHIRYPIBKA,MWKONAIBCbKAO5A
Running OCR on https://i.postimg.cc/N0nx31kj/UA-GAZ-66-Zil-130-Ural-4320-destroyed.png took 15.194763920000696 seconds to run
9095
9096
Grabbing the full link at https://i.postimg.cc/90y4R2Ph/2022-02-25-Ural-4320-D-30-destroyed.jpg took 0.37376625500110094 seconds to run

Connecting to https://i.postimg.cc/90y4R2Ph/2022-02-25-Ural-4320-D-30-destroyed.jpg ...
Downloading 2022-02-25-Ural-4320-D-30-destroyed.jpg ...
[==================================================] 100.00%

OCR returns: 25/02/2022|Kyiv
Running OCR on https://i.postimg.cc/90y4R2Ph/2022-02-25-Ural-4320-D-30-destroyed.jpg took 16.961426084999403 seconds to run
9096
9097

Connecting to https://i.postimg.cc/k48Z8b22/2022-02-27-UA-Ural-4320-destroyed-Kyiv.jpg ...
Downloading 2022-02-27-UA-Ural-4320-destroyed-Kyiv.jpg ...
[                                                  ] 1.35%

Grabbing the full link at https://i.postimg.cc/k48Z8b22/2022-02-27-UA-Ural-4320-destroyed-Kyiv.jpg took 0.36336469700108864 seconds to run

[==================================================] 100.00%

OCR returns: 27/02/2022|CURRENT|Kyiv|KABA|TAObAH|KADA|CAnMSH|KANSRN
Running OCR on https://i.postimg.cc/k48Z8b22/2022-02-27-UA-Ural-4320-destroyed-Kyiv.jpg took 28.914329526000074 seconds to run
9097
9098
Grabbing the full link at https://i.postimg.cc/9FRHJ655/2022-04-05-UA-Ural-4320-destroyed-Hostomel.jpg took 0.5165130040004442 seconds to run

Connecting to https://i.postimg.cc/9FRHJ655/2022-04-05-UA-Ural-4320-destroyed-Hostomel.jpg ...
Downloading 2022-04-05-UA-Ural-4320-destroyed-Hostomel.jpg ...
[==================================================] 100.00%

OCR returns: KPAIN|PTWPM|EHTPI|TEHA|75550|CAPTE|0980081000|CITY|CBOR KBAPTNPA|NA3EPHE NIKVBAHHRBAPMKO3V|Emm|7777|anTeka|2oporope|ROZETKA|0050|四|EEEELEE|05/04/2022|Hostomel,Kyiv Oblast
Running OCR on https://i.postimg.cc/9FRHJ655/2022-04-05-UA-Ural-4320-destroyed-Hostomel.jpg took 34.42607744500128 seconds to run
9098
9099
Grabbing the full link at https://i.postimg.cc/qBmNfyT3/2022-04-08-UA-Ural-4320-destroyed.jpg took 0.4943907090018911 seconds to run

Connecting to https://i.postimg.cc/qBmNfyT3/2022-04-08-UA-Ural-4320-destroyed.jpg ...
Downloading 2022-04-08-UA-Ural-4320-destroyed.jpg ...
[==================================================] 100.00%

OCR returns: 08/04/2022|Kyiv Oblast
Running OCR on https://i.postimg.cc/qBmNfyT3/2022-04-08-UA-Ural-4320-destroyed.jpg took 13.394580403000873 seconds to run
9099
9100
Grabbing the full link at https://i.postimg.cc/k4SDJXvg/2022-09-21-UA-Ural-4320-destroyed-Mykolaiv.jpg took 0.48241926099944976 seconds to run

Connecting to https://i.postimg.cc/k4SDJXvg/2022-09-21-UA-Ural-4320-destroyed-Mykolaiv.jpg ...
Downloading 2022-09-21-UA-Ural-4320-destroyed-Mykolaiv.jpg ...
[==================================================] 100.00%

OCR returns: 21/09/2022|Mykolaiv
Running OCR on https://i.postimg.cc/k4SDJXvg/2022-09-21-UA-Ural-4320-destroyed-Mykolaiv.jpg took 23.67332810100197 seconds to run
9100
9101
Grabbing the full link at https://i.postimg.cc/Jnw887kn/2005-ural4320-destr-25-12-22.jpg took 0.4372473959992931 seconds to run
9101
9102
Grabbing the full link at https://i.postimg.cc/BbbMfnST/2000-ural4320-destr-10-02-23.jpg took 0.41496729100254015 seconds to run
9102
9103
Grabbing the full link at https://i.postimg.cc/7Z91k8Qd/2008-ural4320-destr-08-03-23.jpg took 0.3781315380001615 seconds to run
9103
9104
Grabbing the full link at https://i.postimg.cc/dVX6rmH2/2001-ural4320-destr-13-04-22.jpg took 0.37372467599925585 seconds to run
9104
9105
Grabbing the full link at https://i.postimg.cc/RZS6tgpJ/5g3.png took 0.369971603002341 seconds to run

Connecting to https://i.postimg.cc/RZS6tgpJ/5g3.png ...
Downloading 5g3.png ...
[==================================================] 100.00%

OCR returns: 29/12/2022
Running OCR on https://i.postimg.cc/RZS6tgpJ/5g3.png took 29.207492530997115 seconds to run
9105
9106
Grabbing the full link at https://i.postimg.cc/GpC9Lftt/4f3.png took 0.46763172700229916 seconds to run

Connecting to https://i.postimg.cc/GpC9Lftt/4f3.png ...
Downloading 4f3.png ...
[==================================================] 100.00%

OCR returns: 15/4/2022|military politik
Running OCR on https://i.postimg.cc/GpC9Lftt/4f3.png took 27.35294790899934 seconds to run
9106
9107
Grabbing the full link at https://i.postimg.cc/6QqYyLGV/y6.png took 0.5330523160009761 seconds to run

Connecting to https://i.postimg.cc/6QqYyLGV/y6.png ...
Downloading y6.png ...
[==================================================] 100.00%

OCR returns: 06/4/2023|2,508 views|0:04/ 0:13|d
Running OCR on https://i.postimg.cc/6QqYyLGV/y6.png took 27.894643275001727 seconds to run
9107
9108
Grabbing the full link at https://i.postimg.cc/mD0XN4yv/2028-Ural-4320-destr-02-05-23.jpg took 0.4861447050025163 seconds to run
9108
9109
Grabbing the full link at https://i.postimg.cc/prz0sS0p/2029-Ural-4320-destr-02-05-23.jpg took 0.4498886670007778 seconds to run
9109
9110
Grabbing the full link at https://i.postimg.cc/gJN2VqPT/2011-ural4320-destr-04-05-23.jpg took 0.5013703579970752 seconds to run
9110
9111
Grabbing the full link at https://i.postimg.cc/fybZ0Z8t/2020-Ural-4320-destr-31-03-22.jpg took 0.4782902160004596 seconds to run
9111
9112
Grabbing the full link at https://i.postimg.cc/nc7mqDmk/1048-ural4320-destr-08-06-23.jpg took 0.4474084089997632 seconds to run
9112
9113
Grabbing the full link at https://i.postimg.cc/FRXkJ0qT/2029-ural4320-destr-14-06-23.jpg took 0.3674979399984295 seconds to run
9113
9114
Grabbing the full link at https://i.postimg.cc/wBxthXbD/1018-ural4320-destr-08-03-23.jpg took 0.4307889730007446 seconds to run
9114
9115
Grabbing the full link at https://i.postimg.cc/j2jvK62T/2001-ural4320-destr-08-07-23.jpg took 0.4336648529970262 seconds to run
9115
9116
Grabbing the full link at https://i.postimg.cc/3wHBWQNn/2010-ural4320-destr-07-05-22.jpg took 0.3923127359994396 seconds to run
9116
9117
Grabbing the full link at https://i.postimg.cc/3RkYFPMQ/2024-Ural-4320-destr-29-04-22.jpg took 0.4589424379992124 seconds to run
9117
9118
Grabbing the full link at https://i.postimg.cc/jjdsLDZ5/2025-Ural-4320-07-05-22.jpg took 0.4634269880007196 seconds to run
9118
9119
Grabbing the full link at https://i.postimg.cc/kggF9J30/2001-URAL-4320-destr-26-07-23.jpg took 0.5060126659991511 seconds to run
9119
9120
Grabbing the full link at https://i.postimg.cc/Pf2zCj16/549.png took 0.4399450599994452 seconds to run

Connecting to https://i.postimg.cc/Pf2zCj16/549.png ...
Downloading 549.png ...
[==================================================] 100.00%

OCR returns: 17/8/2023
Running OCR on https://i.postimg.cc/Pf2zCj16/549.png took 18.993819389001146 seconds to run
9120
9121
Grabbing the full link at https://i.postimg.cc/Nf1n6LYk/433.png took 0.4556649739970453 seconds to run

Connecting to https://i.postimg.cc/Nf1n6LYk/433.png ...
Downloading 433.png ...
[==================================================] 100.00%

OCR returns: 21/3/2022
Running OCR on https://i.postimg.cc/Nf1n6LYk/433.png took 19.007270939997397 seconds to run
9121
9122

Connecting to https://i.postimg.cc/Nf1n6LYk/433.png ...
Downloading 433.png ...
[                                                  ] 0.25%

Grabbing the full link at https://i.postimg.cc/Nf1n6LYk/433.png took 0.3694448780006496 seconds to run

[==================================================] 100.00%

OCR returns: 21/3/2022
Running OCR on https://i.postimg.cc/Nf1n6LYk/433.png took 18.64531824399819 seconds to run
9122
9123
Grabbing the full link at https://i.postimg.cc/FH8fhSsM/2003-Ural-4320-destr-19-10-23.jpg took 0.5182820400004857 seconds to run
9123
9124
Grabbing the full link at https://i.postimg.cc/3RJ72JzT/2003-Ural-4320-destr-25-02-22.jpg took 0.5236053449989413 seconds to run
9124
9125
Grabbing the full link at https://i.postimg.cc/43pnBG5B/2009-Ural-4320-destr-31-10-23.jpg took 0.5051730579980358 seconds to run
9125
9126
Grabbing the full link at https://i.postimg.cc/nrmjF8wp/3360.png took 0.5309195020017796 seconds to run

Connecting to https://i.postimg.cc/nrmjF8wp/3360.png ...
Downloading 3360.png ...
[==================================================] 100.00%

OCR returns: 30/11/2022
Running OCR on https://i.postimg.cc/nrmjF8wp/3360.png took 17.442191318001278 seconds to run
9126
9127
Grabbing the full link at https://i.postimg.cc/8zK5jh3z/2005-ural4320-destr-15-06-23.jpg took 0.5016288900005748 seconds to run
9127
9128
Grabbing the full link at https://i.postimg.cc/DzLyDwWY/2009-Ural-4320-destr-18-10-23.jpg took 1.4861697989981622 seconds to run
9128
9129
Grabbing the full link at https://i.postimg.cc/8Cj4KMDm/2024-Ural-4320-destr-01-03-22.jpg took 0.46067856599984225 seconds to run
9129
9130
Grabbing the full link at https://i.postimg.cc/6QMJ3Yg2/2000-Ural-4320-destr-10-11-23.jpg took 0.4265219190019707 seconds to run
9130
9131
Grabbing the full link at https://i.postimg.cc/jSQrVshh/2013-Ural-4320-destr-31-05-22.jpg took 0.8528226310008904 seconds to run
9131
9132
Grabbing the full link at https://i.postimg.cc/LXpBK135/1038-Ural-4320-destr-31-08-23.jpg took 0.4838351379985397 seconds to run
9132
9133
Grabbing the full link at https://i.postimg.cc/MTCq8BF0/2006-Ural-4320-destr-20-01-23.jpg took 0.5336197530014033 seconds to run
9133
9134
Grabbing the full link at https://i.postimg.cc/TPXKf2x1/2001-Ural-4320-destr-05-03-24.jpg took 0.8898482250006055 seconds to run
9134
9135
Grabbing the full link at https://i.postimg.cc/7hzMymX2/2000-Ural-4320-destr-07-12-23.jpg took 0.5697087609987648 seconds to run
9135
9136
Grabbing the full link at https://i.postimg.cc/2SbGHKwG/2033-Ural-4320-destr-12-10-23.jpg took 0.4570470539983944 seconds to run
9136
9137
Grabbing the full link at https://i.postimg.cc/8PhzqKrT/2006-Ural-4320-destr-30-03-24.jpg took 0.47272666600110824 seconds to run
9137
9138
Grabbing the full link at https://i.postimg.cc/httf0yQ0/2020-Ural-4320-destr-29-02-24.jpg took 0.45206298400080414 seconds to run
9138
9139
Grabbing the full link at https://i.postimg.cc/cLZKyxxH/2002-unkn-truck-12-01-23.jpg took 0.4191658100025961 seconds to run
9139
9140
Grabbing the full link at https://i.postimg.cc/XvcvkZcf/2037-Ural-4320-destr-24-05-22.jpg took 0.4005122799972014 seconds to run
9140
9141
Grabbing the full link at https://i.postimg.cc/Px64PRCj/2003-Ural-4320-destr-25-02-22.jpg took 0.4057885960028216 seconds to run
9141
9142
Grabbing the full link at https://i.postimg.cc/G3fdYRjV/2015-Ural-4320-destr-30-06-24.jpg took 0.3838872340020316 seconds to run
9142
9143
Grabbing the full link at https://i.postimg.cc/mk1RPPhM/2014-Ural-4320-destr-06-07-24.jpg took 0.3828599070002383 seconds to run
9143
9144
Grabbing the full link at https://i.postimg.cc/j2Pf5KbQ/2000-Ural-4320-destr-31-05-23.jpg took 0.3893917919995147 seconds to run
9144
9145
Grabbing the full link at https://i.postimg.cc/bNNd821k/2005-Ural-4320-destr-09-07-24.jpg took 0.45929025300210924 seconds to run
9145
9146
Grabbing the full link at https://i.postimg.cc/T3MpwtPb/2008-Ural-4320-destr-31-12-23.jpg took 0.4727508100004343 seconds to run
9146
9147
Grabbing the full link at https://i.postimg.cc/fyR5HBKF/2025-Ural-4320-destr-18-05-22.jpg took 0.37658348199693137 seconds to run
9147
9148
Grabbing the full link at https://i.postimg.cc/QNPNmCNy/2010-Ural-4320-destr-16-09-24.jpg took 0.40398794900102075 seconds to run
9148
9149
Grabbing the full link at https://i.postimg.cc/rwZrKHwd/2008-Ural-4320-destr-26-10-24.jpg took 0.4873023830004968 seconds to run
9149
9150
Grabbing the full link at https://i.postimg.cc/kgn6xvNT/2002-Ural-4320-destr-03-07-23.jpg took 0.44647637700109044 seconds to run
9150
9151
Grabbing the full link at https://i.postimg.cc/YSPvBc5P/2026-Ural-4320-destr-02-11-24.jpg took 0.44178512199869147 seconds to run
9151
9152
Grabbing the full link at https://i.postimg.cc/R0hWYCDf/2027-Ural-4320-destr-02-11-24.jpg took 0.4646395300005679 seconds to run
9152
9153
Grabbing the full link at https://i.postimg.cc/90bnJwdL/2009-Ural-4320-destr-16-11-24.jpg took 0.44802394599901163 seconds to run
9153
9154
Grabbing the full link at https://i.postimg.cc/tJZcFH1v/2016-Ural-4320-destr-03-03-22.jpg took 0.42077234399766894 seconds to run
9154
9155
Grabbing the full link at https://i.postimg.cc/Fz40h4Qs/2022-Ural-4320-destr-22-12-24.jpg took 0.41554289600026095 seconds to run
9155
9156
Grabbing the full link at https://i.postimg.cc/pTgcN7rR/2094-Ural-4320-destr-25-02-25.jpg took 0.3864208630002395 seconds to run
9156
9157
Grabbing the full link at https://i.postimg.cc/GpTphcbN/2010-Ural-4320-destr-19-03-25.jpg took 0.3796742919985263 seconds to run
9157
9158
Grabbing the full link at https://i.postimg.cc/qMFZNd83/2002-Ural-4320-destr-27-02-25.jpg took 0.4313927520015568 seconds to run
9158
9159
Grabbing the full link at https://i.postimg.cc/nzQJDKpj/2065-Ural-4320-destr-18-03-25.jpg took 0.4261139970003569 seconds to run
9159
9160
Grabbing the full link at https://i.postimg.cc/j2Kw5rYd/2021-Ural-4320-destr-25-02-25.jpg took 0.42803724499754026 seconds to run
9160
9161
Grabbing the full link at https://i.postimg.cc/mrv1vHd9/2017-Ural-4320-destr-16-04-25.jpg took 0.37732046299788635 seconds to run
9161
9162
Grabbing the full link at https://i.postimg.cc/Dy1BbWB0/2003-Ural-4320-destr-09-05-25.jpg took 0.39823160599917173 seconds to run
9162
9163
Grabbing the full link at https://i.postimg.cc/dQm5x9Gn/2010-Ural-4320-destr-30-06-25.jpg took 0.4307811250000668 seconds to run
9163
9164
Grabbing the full link at https://i.postimg.cc/MH0p4XKm/Ukrainian-Ural-4320.png took 0.3723841800019727 seconds to run

Connecting to https://i.postimg.cc/MH0p4XKm/Ukrainian-Ural-4320.png ...
Downloading Ukrainian-Ural-4320.png ...
[==================================================] 100.00%

OCR returns: 5.10.2022
Running OCR on https://i.postimg.cc/MH0p4XKm/Ukrainian-Ural-4320.png took 13.308654797998315 seconds to run
9164
9165
Grabbing the full link at https://i.postimg.cc/yYNW9jJq/2013-Ural-4320-dam-15-10-23.jpg took 0.39173533100256464 seconds to run
9165
9166
Grabbing the full link at https://i.postimg.cc/xTQq7jMn/2004-ural4320-dam-29-11-22.jpg took 0.4362089539972658 seconds to run
9166
9167
Grabbing the full link at https://i.postimg.cc/Xq745b5L/2008-Ural-4320-dam-aband-26-12-24.jpg took 0.4027409859991167 seconds to run
9167
9168
Grabbing the full link at https://i.postimg.cc/GmVqtBjC/328.png took 0.4079914200010535 seconds to run

Connecting to https://i.postimg.cc/GmVqtBjC/328.png ...
Downloading 328.png ...
[==================================================] 100.00%

OCR returns: PRES|iz|PoMaH|NonbwakoB|19/4/2022|KOPpeCnOHAOHT|"M3BeCTHM"|ESS|0:05/1:29
Running OCR on https://i.postimg.cc/GmVqtBjC/328.png took 29.72105804899911 seconds to run
9168
9169
Grabbing the full link at https://i.postimg.cc/FR1JZVbd/2000-ural4320-capt-25-02-22.png took 1.3355144429988286 seconds to run
9169
9170
Grabbing the full link at https://i.postimg.cc/02n6DFYg/314.png took 0.9700378600027761 seconds to run

Connecting to https://i.postimg.cc/02n6DFYg/314.png ...
Downloading 314.png ...
[==================================================] 100.00%

OCR returns: 28/3/2022|838|2032E6
Running OCR on https://i.postimg.cc/02n6DFYg/314.png took 33.45293659899835 seconds to run
9170
9171
Grabbing the full link at https://i.postimg.cc/2yMp268K/tt1.png took 0.4067699699990044 seconds to run

Connecting to https://i.postimg.cc/2yMp268K/tt1.png ...
Downloading tt1.png ...
[==================================================] 100.00%

OCR returns: 17/4/2022|t.me/MSGaz|t.me/Murad Cazd|0:42/1:43|4
Running OCR on https://i.postimg.cc/2yMp268K/tt1.png took 45.661652132999734 seconds to run
9171
9172
Grabbing the full link at https://i.postimg.cc/JnpvdY9K/32.png took 0.38172853300056886 seconds to run

Connecting to https://i.postimg.cc/JnpvdY9K/32.png ...
Downloading 32.png ...
[==================================================] 100.00%

OCR returns: 19|MiG41|27/4/2022
Running OCR on https://i.postimg.cc/JnpvdY9K/32.png took 26.84371367100175 seconds to run
9172
9173

Connecting to https://i.postimg.cc/JnpvdY9K/32.png ...
Downloading 32.png ...
[                                                  ] 0.19%

Grabbing the full link at https://i.postimg.cc/JnpvdY9K/32.png took 1.07469194299847 seconds to run

[==================================================] 100.00%

OCR returns: 19|MiG41|27/4/2022
Running OCR on https://i.postimg.cc/JnpvdY9K/32.png took 23.88263771199854 seconds to run
9173
9174
Grabbing the full link at https://i.postimg.cc/zGXd5NXk/Screenshot-8015.png took 0.4661873420009215 seconds to run

Connecting to https://i.postimg.cc/zGXd5NXk/Screenshot-8015.png ...
Downloading Screenshot-8015.png ...
[==================================================] 100.00%

OCR returns: 小|24/02/2022|602 views|0:03/ 0:23|☆
Running OCR on https://i.postimg.cc/zGXd5NXk/Screenshot-8015.png took 28.010366891998274 seconds to run
9174
9175
Grabbing the full link at https://i.postimg.cc/jdRM3Vky/f30.png took 1.476632605001214 seconds to run

Connecting to https://i.postimg.cc/jdRM3Vky/f30.png ...
Downloading f30.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|Y|Onewkn,|XepcOH.|25.02.22|TikTok|2:52 / 13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/jdRM3Vky/f30.png took 33.16112125699874 seconds to run
9175
9176
Grabbing the full link at https://i.postimg.cc/4y6PXBMj/Screenshot-8166.png took 0.37671658800172736 seconds to run

Connecting to https://i.postimg.cc/4y6PXBMj/Screenshot-8166.png ...
Downloading Screenshot-8166.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|Y|AHTOHOBCKNN|MOCT.|25.02.22|akTyanbHaa|A|no|nOBOAy|cnTyaunn.|TikTok|1|7:34/ 13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/4y6PXBMj/Screenshot-8166.png took 33.809414781997475 seconds to run
9176
9177
Grabbing the full link at https://i.postimg.cc/t4SNn63R/2011-Ural-4320-capt-23-04-22.jpg took 0.48191719799797283 seconds to run
9177
9178
Grabbing the full link at https://i.postimg.cc/J7FyKqtr/2022-11-13-UA-Ural-4320-tanker-destroyed.jpg took 0.4322815109990188 seconds to run

Connecting to https://i.postimg.cc/J7FyKqtr/2022-11-13-UA-Ural-4320-tanker-destroyed.jpg ...
Downloading 2022-11-13-UA-Ural-4320-tanker-destroyed.jpg ...
[==================================================] 100.00%

OCR returns: 13/11/2022|KhersonAirport|M Blood|httpsjlt.mefwinua22
Running OCR on https://i.postimg.cc/J7FyKqtr/2022-11-13-UA-Ural-4320-tanker-destroyed.jpg took 27.59517557700019 seconds to run
9178
9179
Grabbing the full link at https://i.postimg.cc/fRrqJbt0/2022-02-25-UA-Ural-4320-tanker.jpg took 0.40327835000061896 seconds to run

Connecting to https://i.postimg.cc/fRrqJbt0/2022-02-25-UA-Ural-4320-tanker.jpg ...
Downloading 2022-02-25-UA-Ural-4320-tanker.jpg ...
[==================================================] 100.00%

OCR returns: 25/02/2022
Running OCR on https://i.postimg.cc/fRrqJbt0/2022-02-25-UA-Ural-4320-tanker.jpg took 26.704563932999008 seconds to run
9179
9180
Grabbing the full link at https://i.postimg.cc/MpjY6qVZ/2022-04-14-UA-Ural-4320-destroyed.jpg took 1.5671449090004899 seconds to run

Connecting to https://i.postimg.cc/MpjY6qVZ/2022-04-14-UA-Ural-4320-destroyed.jpg ...
Downloading 2022-04-14-UA-Ural-4320-destroyed.jpg ...
[==================================================] 100.00%

OCR returns: 14/04/2022|Rudnya-Sydorivska,Kyiv Oblast
Running OCR on https://i.postimg.cc/MpjY6qVZ/2022-04-14-UA-Ural-4320-destroyed.jpg took 13.966837911000766 seconds to run
9180
9181
Grabbing the full link at https://i.postimg.cc/wjbtb4cc/2013-ural4320-tanker-destr-16-04-22.jpg took 0.5014433830001508 seconds to run
9181
9182
Grabbing the full link at https://i.postimg.cc/WpJ41Xjt/436.png took 0.41343192000204 seconds to run

Connecting to https://i.postimg.cc/WpJ41Xjt/436.png ...
Downloading 436.png ...
[==================================================] 100.00%

OCR returns: 3ANOPOKCKNPOHT|3ANOPOKCKNM POHT|3ANOPOKCKNΦPOHT|23/3/2023|T.ME/ZA_FROHT|T.ME/ZA_FROHT|T.ME/ZA_FROHT
Running OCR on https://i.postimg.cc/WpJ41Xjt/436.png took 12.390480795002077 seconds to run
9182
9183
Grabbing the full link at https://i.postimg.cc/cC8VFZHw/2014-Ural-4320-tanker-destr-31-05-22.jpg took 0.38735049000024446 seconds to run
9183
9184
Grabbing the full link at https://i.postimg.cc/Kj0zwkHs/2009-Ural-4320-tanker-destr-18-10-23.jpg took 0.4183619899995392 seconds to run
9184
9185
Grabbing the full link at https://i.postimg.cc/SjbM6RYK/2007-4x-ural-tanker-destr-03-01-24.jpg took 0.4207127269983175 seconds to run
9185
9186
Grabbing the full link at https://i.postimg.cc/SjbM6RYK/2007-4x-ural-tanker-destr-03-01-24.jpg took 0.41047274800075684 seconds to run
9186
9187
Grabbing the full link at https://i.postimg.cc/SjbM6RYK/2007-4x-ural-tanker-destr-03-01-24.jpg took 0.37994112399974256 seconds to run
9187
9188
Grabbing the full link at https://i.postimg.cc/SjbM6RYK/2007-4x-ural-tanker-destr-03-01-24.jpg took 0.4103375619997678 seconds to run
9188
9189
Grabbing the full link at https://i.postimg.cc/59h8tbjD/2014-Ural-4320-tanker-destr-02-01-24.jpg took 0.39053835300001083 seconds to run
9189
9190
Grabbing the full link at https://i.postimg.cc/wjx0NnGP/2023-Ural-4320-tanker-destr-01-03-22.jpg took 0.4337575889985601 seconds to run
9190
9191
Grabbing the full link at https://i.postimg.cc/7Z5KjsRC/2006-ural-tanker-destr-31-12-22.png took 0.3638738889967499 seconds to run
9191
9192
Grabbing the full link at https://i.postimg.cc/VNMCJTLF/2003-Ural-4320-tanker-destr-21-05-24.jpg took 0.37319142499836744 seconds to run
9192
9193
Grabbing the full link at https://i.postimg.cc/rwQdgRQM/2042-Ural-4320-tanker-destr-07-03-22.jpg took 0.36721713799852296 seconds to run
9193
9194
Grabbing the full link at https://i.postimg.cc/44KhhvH0/2048-Ural-4320-tanker-destr-01-06-24.jpg took 0.37202097800036427 seconds to run
9194
9195
Grabbing the full link at https://i.postimg.cc/Cxf47JWs/2008-Ural-4320-fuel-tanker-destr-15-02-25.jpg took 0.3669849560028524 seconds to run
9195
9196
Grabbing the full link at https://i.postimg.cc/tCpV1x4P/2003-2x-ural-tanker-dam-27-02-22.jpg took 0.3718502429983346 seconds to run
9196
9197
Grabbing the full link at https://i.postimg.cc/tCpV1x4P/2003-2x-ural-tanker-dam-27-02-22.jpg took 0.37238202300068224 seconds to run
9197
9198
Grabbing the full link at https://i.postimg.cc/2SzvZzbq/443.png took 0.44367067399798543 seconds to run

Connecting to https://i.postimg.cc/2SzvZzbq/443.png ...
Downloading 443.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|Y|AHTOHOBCKNN|MOCT.|25.02.22|akTyanbHag|NHOPMaNnonOBoay|CnTyaunn.|TikTok|1|7:57/13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/2SzvZzbq/443.png took 41.12871521300258 seconds to run
9198
9199
Grabbing the full link at https://i.postimg.cc/3JrJjW1H/Screenshot-8172.png took 0.37571667700103717 seconds to run

Connecting to https://i.postimg.cc/3JrJjW1H/Screenshot-8172.png ...
Downloading Screenshot-8172.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long. Crimea front line. Russia Ukraine War 2022 02 25|0|?|一|AHTOHOBCKNN|MOCT|25.02.22|akTyanbhag|Aorn|no|nOBOAy|CaTyaynn.|Ti|1|8:16/ 13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/3JrJjW1H/Screenshot-8172.png took 36.60677938899971 seconds to run
9199
9200
Grabbing the full link at https://i.postimg.cc/L8n977GC/Screenshot-8173.png took 0.4426764659983746 seconds to run

Connecting to https://i.postimg.cc/L8n977GC/Screenshot-8173.png ...
Downloading Screenshot-8173.png ...
[==================================================] 100.00%

OCR returns: AHTOHOBCKN|MOCT.|25.02.22|akTyanbHag|Are|no|nOBOAy|cuTyaunn.|TikTok|@andriiboiko93kh
Running OCR on https://i.postimg.cc/L8n977GC/Screenshot-8173.png took 29.93502710499888 seconds to run
9200
9201
Grabbing the full link at https://i.postimg.cc/C5t52NPf/Screenshot-8111.png took 0.38896243999988656 seconds to run

Connecting to https://i.postimg.cc/C5t52NPf/Screenshot-8111.png ...
Downloading Screenshot-8111.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|Y|国|Onewkn,|XepcOH|25.02.22|TikTok|1|0:23/13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/C5t52NPf/Screenshot-8111.png took 37.0803105720006 seconds to run
9201
9202
Grabbing the full link at https://i.postimg.cc/SQtnjSSN/Screenshot-8112.png took 0.4421205349972297 seconds to run

Connecting to https://i.postimg.cc/SQtnjSSN/Screenshot-8112.png ...
Downloading Screenshot-8112.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|Y|Onewkn,|XepcOH.|25.02.22|TikTok|▶|1|0:27/13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/SQtnjSSN/Screenshot-8112.png took 45.875376295000024 seconds to run
9202
9203
Grabbing the full link at https://i.postimg.cc/5tqNnVFZ/f3.png took 0.48564485799943213 seconds to run

Connecting to https://i.postimg.cc/5tqNnVFZ/f3.png ...
Downloading f3.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction-15 km long.Crimea front line. Russia Ukraine War 2022 0225|0|7|@andriiboiko93kh|Onewkn,|XepcoH.|25.02.22|▶|1|0:00/13:25|0|日|*|非
Running OCR on https://i.postimg.cc/5tqNnVFZ/f3.png took 33.52551107799809 seconds to run
9203
9204
Grabbing the full link at https://i.postimg.cc/nrdDz39r/5g2.png took 0.5870942100009415 seconds to run

Connecting to https://i.postimg.cc/nrdDz39r/5g2.png ...
Downloading 5g2.png ...
[==================================================] 100.00%

OCR returns: Ukrainian military convoy destruction- 15 km long.Crimea front line. Russia Ukraine War 2022 02 25|0|Y|OnewKN,|XepcOH.|25.02.22|TikTok|▶|1|0:44/13:25|@andriiboiko93kh|0|日|*|非
Running OCR on https://i.postimg.cc/nrdDz39r/5g2.png took 35.104888382000354 seconds to run
9204
9205

Connecting to https://i.postimg.cc/fbMMYwct/10-10-2022-UA-Kamaz-6x6-destroyed.png ...
Downloading 10-10-2022-UA-Kamaz-6x6-destroyed.png ...
[                                                  ] 0.26%

Grabbing the full link at https://i.postimg.cc/fbMMYwct/10-10-2022-UA-Kamaz-6x6-destroyed.png took 0.6281156969998847 seconds to run

[==================================================] 100.00%

OCR returns: 10.10.2022|WM.Blood
Running OCR on https://i.postimg.cc/fbMMYwct/10-10-2022-UA-Kamaz-6x6-destroyed.png took 26.5656694399986 seconds to run
9205
9206
Grabbing the full link at https://i.postimg.cc/4y2CCd1m/1007-kamaz6x6-destr.jpg took 0.5159842160028347 seconds to run

Connecting to https://i.postimg.cc/4y2CCd1m/1007-kamaz6x6-destr.jpg ...
Downloading 1007-kamaz6x6-destr.jpg ...
[==================================================] 100.00%

OCR returns: 26.11.2022
Running OCR on https://i.postimg.cc/4y2CCd1m/1007-kamaz6x6-destr.jpg took 13.46882356900096 seconds to run
9206
9207
Grabbing the full link at https://i.postimg.cc/BQtxtBxM/2022-02-26-UA-Kam-AZ.jpg took 0.4079855829986627 seconds to run

Connecting to https://i.postimg.cc/BQtxtBxM/2022-02-26-UA-Kam-AZ.jpg ...
Downloading 2022-02-26-UA-Kam-AZ.jpg ...
[==================================================] 100.00%

OCR returns: 26/02/2022|Kyiv
Running OCR on https://i.postimg.cc/BQtxtBxM/2022-02-26-UA-Kam-AZ.jpg took 16.627168603998143 seconds to run
9207
9208
Grabbing the full link at https://i.postimg.cc/c6GNfy1L/2001-Kam-AZ-6x6-destr-02-03-22.jpg took 0.4693378769989067 seconds to run
9208
9209
Grabbing the full link at https://i.postimg.cc/Qtz2G1VB/1031-kamaz6x6-destr-21-06-22.jpg took 0.49354882600164274 seconds to run
9209
9210
Returning non-postimg link
9210
9211
Grabbing the full link at https://i.postimg.cc/sDDyzPWP/373.png took 0.4684889309974096 seconds to run

Connecting to https://i.postimg.cc/sDDyzPWP/373.png ...
Downloading 373.png ...
[==================================================] 100.00%

OCR returns: 18/4/2023
Running OCR on https://i.postimg.cc/sDDyzPWP/373.png took 25.20833367999876 seconds to run
9211
9212
Grabbing the full link at https://i.postimg.cc/76B5VmYh/2013-Kam-AZ-6x6-destr-01-06-22.jpg took 0.4238560049998341 seconds to run
9212
9213
Grabbing the full link at https://i.postimg.cc/XY7dcFJR/2008-Kam-AZ-6x6-tanker-23-05-22.jpg took 0.38908490800167783 seconds to run
9213
9214
Grabbing the full link at https://i.postimg.cc/qqmJmgNx/2002-kamaz6x6-destr-20-06-22.jpg took 0.40080116099852603 seconds to run
9214
9215
Grabbing the full link at https://i.postimg.cc/8C5tCgVZ/2012-Kam-AZ-6x6-destr-02-07-23.jpg took 0.38203392899959 seconds to run
9215
9216
Grabbing the full link at https://i.postimg.cc/1RVL5bNs/3277.png took 0.37685217799662496 seconds to run

Connecting to https://i.postimg.cc/1RVL5bNs/3277.png ...
Downloading 3277.png ...
[==================================================] 100.00%

OCR returns: 05/9/2023
Running OCR on https://i.postimg.cc/1RVL5bNs/3277.png took 43.540483900000254 seconds to run
9216
9217
Grabbing the full link at https://i.postimg.cc/J4RXX01Z/3362.png took 0.4620106600013969 seconds to run

Connecting to https://i.postimg.cc/J4RXX01Z/3362.png ...
Downloading 3362.png ...
[==================================================] 100.00%

OCR returns: 08/9/2023|ANEICHEN|EME/RUSICHARM|TME/RUSICH_ARMY|AKNECHENG|AEANECHNE|ME/RUSICH_ARM|TME/RUSICH ARMY
Running OCR on https://i.postimg.cc/J4RXX01Z/3362.png took 20.921296504002385 seconds to run
9217
9218
Grabbing the full link at https://i.postimg.cc/vHPKn9HB/2006-Kam-AZ-6x6-destr-16-11-24.jpg took 0.40461001500079874 seconds to run
9218
9219
Grabbing the full link at https://i.postimg.cc/7ZpZm2L2/2012-Kam-AZ-6x6-destr-12-05-23.jpg took 0.4494231030002993 seconds to run
9219
9220
Grabbing the full link at https://i.postimg.cc/kM81PQSj/2025-Kam-AZ-6x6-destr-18-01-24.jpg took 0.37405310300164274 seconds to run
9220
9221
Grabbing the full link at https://i.postimg.cc/L4qWQF4C/kaaamazzzzz2.png took 0.4426490890000423 seconds to run

Connecting to https://i.postimg.cc/L4qWQF4C/kaaamazzzzz2.png ...
Downloading kaaamazzzzz2.png ...
[==================================================] 100.00%

OCR returns: 09/4/2022
Running OCR on https://i.postimg.cc/L4qWQF4C/kaaamazzzzz2.png took 15.152962633997959 seconds to run
9221
9222
Grabbing the full link at https://i.postimg.cc/HsytXpWm/kaaamazzzzz1.png took 0.457727259999956 seconds to run

Connecting to https://i.postimg.cc/HsytXpWm/kaaamazzzzz1.png ...
Downloading kaaamazzzzz1.png ...
[==================================================] 100.00%

OCR returns: 09/4/2022
Running OCR on https://i.postimg.cc/HsytXpWm/kaaamazzzzz1.png took 29.727098715000466 seconds to run
9222
9223
Grabbing the full link at https://i.postimg.cc/76yKJnSV/2016-Kam-AZ-6x6-destr-02-04-24.jpg took 0.5116057670020382 seconds to run
9223
9224
Grabbing the full link at https://i.postimg.cc/NfhzYqHp/2008-Kam-AZ-6x6-destr-17-07-24.jpg took 0.4510872920000111 seconds to run
9224
9225
Grabbing the full link at https://i.postimg.cc/1tNphk4W/2007-Kam-AZ-6x6-destr-03-07-22.jpg took 0.39410965500064776 seconds to run
9225
9226
Grabbing the full link at https://i.postimg.cc/3wpHwKYQ/2004-Kam-AZ-6x6-destr-26-09-24.jpg took 0.5372384580005019 seconds to run
9226
9227
Grabbing the full link at https://i.postimg.cc/YCGwp2T4/2017-Kam-AZ-6x6-destr-08-10-24.jpg took 0.4456613509973977 seconds to run
9227
9228
Grabbing the full link at https://i.postimg.cc/3W5hWxKx/2002-Kam-AZ-6x6-destr-22-04-25.jpg took 0.4130857259988261 seconds to run
9228
9229
Grabbing the full link at https://i.postimg.cc/DfP3kL0g/2007-Kam-AZ-6x6-destr-30-03-25.jpg took 0.41448253199996543 seconds to run
9229
9230
Grabbing the full link at https://i.postimg.cc/tJHJYQBt/2022-09-21-UA-Kam-AZ-damaged-Mykolaiv.jpg took 0.4898156970011769 seconds to run

Connecting to https://i.postimg.cc/tJHJYQBt/2022-09-21-UA-Kam-AZ-damaged-Mykolaiv.jpg ...
Downloading 2022-09-21-UA-Kam-AZ-damaged-Mykolaiv.jpg ...
[==================================================] 100.00%

OCR returns: 21/09/2022|Mykolaiv
Running OCR on https://i.postimg.cc/tJHJYQBt/2022-09-21-UA-Kam-AZ-damaged-Mykolaiv.jpg took 23.007569052999315 seconds to run
9230
9231

Connecting to https://i.postimg.cc/yx42BBdm/u1.png ...
Downloading u1.png ...
[                                                  ] 0.18%

Grabbing the full link at https://i.postimg.cc/yx42BBdm/u1.png took 0.41963003799901344 seconds to run

[==================================================] 100.00%

OCR returns: 23/3/2022|RVvoenkor|KAMAZ|2940|A2
Running OCR on https://i.postimg.cc/yx42BBdm/u1.png took 23.69549597099831 seconds to run
9231
9232
Grabbing the full link at https://i.postimg.cc/KYnsJT3S/22.png took 0.36583493999933125 seconds to run

Connecting to https://i.postimg.cc/KYnsJT3S/22.png ...
Downloading 22.png ...
[==================================================] 100.00%

OCR returns: 14/4/2022|7|military_politik
Running OCR on https://i.postimg.cc/KYnsJT3S/22.png took 26.598952316999203 seconds to run
9232
9233

Connecting to https://i.postimg.cc/2yMp268K/tt1.png ...
Downloading tt1.png ...
[                                                  ] 0.58%

Grabbing the full link at https://i.postimg.cc/2yMp268K/tt1.png took 0.3692146630019124 seconds to run

[==================================================] 100.00%

OCR returns: 17/4/2022|t.me/MSGaz|t.me/Murad Cazd|0:42/1:43|4
Running OCR on https://i.postimg.cc/2yMp268K/tt1.png took 27.644065872998908 seconds to run
9233
9234
Grabbing the full link at https://i.postimg.cc/cLZWjvBp/tt2.png took 0.5239980019978248 seconds to run

Connecting to https://i.postimg.cc/cLZWjvBp/tt2.png ...
Downloading tt2.png ...
[==================================================] 100.00%

OCR returns: 17/4/2022|t.me/MSGazdiev|t.me/Murad_Gazdiev|0:05/1:43|2
Running OCR on https://i.postimg.cc/cLZWjvBp/tt2.png took 28.27155559700259 seconds to run
9234
9235
Grabbing the full link at https://i.postimg.cc/Gp3Z9kmX/4t5.png took 0.46458005500244326 seconds to run

Connecting to https://i.postimg.cc/Gp3Z9kmX/4t5.png ...
Downloading 4t5.png ...
[==================================================] 100.00%

OCR returns: DMMTPNA|图|06/4/2022|ZMMEHKMH|310|N3BELTHA
Running OCR on https://i.postimg.cc/Gp3Z9kmX/4t5.png took 26.25190581300194 seconds to run
9235
9236
Grabbing the full link at https://i.postimg.cc/Lsc0nTNL/2003-kamaz6x6-dam-capt-28-03-22.jpg took 0.3882464529997378 seconds to run
9236
9237
Grabbing the full link at https://i.postimg.cc/bNGwntVm/2012-kamaz6x6-capt-04-03-22.jpg took 0.36931805799758877 seconds to run
9237
9238
Grabbing the full link at https://i.postimg.cc/KYP5YYX1/2027-kamaz6x6-capt-25-07-22.jpg took 0.418088958998851 seconds to run
9238
9239
Grabbing the full link at https://i.postimg.cc/PJWMCF40/2013-Kam-AZ-6x6-capt-23-04-22.jpg took 0.8241704619977099 seconds to run
9239
9240
Grabbing the full link at https://i.postimg.cc/MG9m76cy/2016-Kam-AZ-6x4-destr-05-10-24.jpg took 0.4708813889992598 seconds to run
9240
9241
Grabbing the full link at https://i.postimg.cc/nzMYTy7N/2018-Kam-AZ-6x4-destr-30-09-24.jpg took 0.49040311700082384 seconds to run
9241
9242
Grabbing the full link at https://i.postimg.cc/1RJRbTtP/2008-Kam-AZ-6x6-destr-25-10-23.jpg took 0.40793390000180807 seconds to run
9242
9243
Grabbing the full link at https://i.postimg.cc/VLDSVhM7/2023-Kam-AZ-6x6-destr-11-10-24.jpg took 0.42566978999821004 seconds to run
9243
9244
Grabbing the full link at https://i.postimg.cc/D0rnMvQc/44f2.png took 0.4228583850017458 seconds to run

Connecting to https://i.postimg.cc/D0rnMvQc/44f2.png ...
Downloading 44f2.png ...
[==================================================] 100.00%

OCR returns: 15/4/2022|military_politik
Running OCR on https://i.postimg.cc/D0rnMvQc/44f2.png took 27.7653263980028 seconds to run
9244
9245
Grabbing the full link at https://i.postimg.cc/JzhDxCJz/2012-kamaz-tanker-capt-16-04-22.jpg took 0.36914844599959906 seconds to run
9245
9246
Grabbing the full link at https://i.postimg.cc/Gpy9dg2r/2027-unkn-Kam-AZ-destr-22-04-22.jpg took 0.37188500100091915 seconds to run
9246
9247

Connecting to https://i.postimg.cc/25RJZzWf/Screenshot-8076.png ...
Downloading Screenshot-8076.png ...
[                                                  ] 0.84%

Grabbing the full link at https://i.postimg.cc/25RJZzWf/Screenshot-8076.png took 0.3665605329988466 seconds to run

[==================================================] 100.00%

OCR returns: 25/02/2022|11.7K views|0:19/ 0:46|2|0
Running OCR on https://i.postimg.cc/25RJZzWf/Screenshot-8076.png took 27.736682848000783 seconds to run
9247
9248
Grabbing the full link at https://i.postimg.cc/Tw3W4kVd/2004-off-road-tractor-MAZ-537-destr-04-05-23.jpg took 1.173632271002134 seconds to run
9248
9249
Grabbing the full link at https://i.postimg.cc/rwqng0jD/2034-MAZ-537-destr-02-05-24.jpg took 1.1335026509987074 seconds to run
9249
9250

Connecting to https://i.postimg.cc/7LSW8dKp/35.png ...
Downloading 35.png ...
[                                                  ] 0.34%

Grabbing the full link at https://i.postimg.cc/7LSW8dKp/35.png took 0.5776940230025502 seconds to run

[==================================================] 100.00%

OCR returns: 04/3/2022|enNMBCeBO3MOKHyIOTeXHNKY,
Running OCR on https://i.postimg.cc/7LSW8dKp/35.png took 27.49466995599869 seconds to run
9250
Saved at index 9250
9251
Grabbing the full link at https://i.postimg.cc/RVw1PQ6C/2045-MAZ-5337-fuel-tanker-destr-10-10-24.jpg took 0.4359336779998557 seconds to run
9251
9252
Grabbing the full link at https://i.postimg.cc/KvcykdqJ/2016-MAZ-6317-destr-21-08-24.jpg took 0.38908270199681283 seconds to run
9252
9253
Grabbing the full link at https://i.postimg.cc/9fTzkkYk/2044-MAZ-6317-destr-26-09-24.jpg took 0.3770802500002901 seconds to run
9253
9254
Grabbing the full link at https://i.postimg.cc/BZV8PYVw/2009-MAZ-TZ-500-tanker-destr-13-11-22.jpg took 0.39281212800051435 seconds to run
9254
9255
Grabbing the full link at https://i.postimg.cc/GmXZ5RDV/64.png took 0.44733330400049454 seconds to run

Connecting to https://i.postimg.cc/GmXZ5RDV/64.png ...
Downloading 64.png ...
[==================================================] 100.00%

OCR returns: imeafrontline.RussiaUkraineWar20220225|AHTONOBCKHH MOCT|AHTOHOBCKN|MOCT.|25.02.22 axyanbHan|25.02.22|akTyanbHa|WHPOpMauMR no noBoY|NHoPmuoBo|TikTok|CnTyaunn.|tindriiko93kl|@andriiboiko93kh
Running OCR on https://i.postimg.cc/GmXZ5RDV/64.png took 25.226058374002605 seconds to run
9255
9256
Grabbing the full link at https://i.postimg.cc/J4w5QC4c/2004-MAZ-500-tanker-capt-02-03-22.jpg took 0.5214636550008436 seconds to run
9256
9257
Grabbing the full link at https://i.postimg.cc/NMBk2XZX/2006-Mobile-field-bathhouse-based-on-MAZ-6317-chassis-capt-10-07-22.jpg took 0.536662141999841 seconds to run
9257
9258
Grabbing the full link at https://i.postimg.cc/x1xtm4D1/2003-Oshkosh-FMTV-M1083-A1-P2-truck-destr.jpg took 0.5703961489998619 seconds to run

Connecting to https://i.postimg.cc/x1xtm4D1/2003-Oshkosh-FMTV-M1083-A1-P2-truck-destr.jpg ...
Downloading 2003-Oshkosh-FMTV-M1083-A1-P2-truck-destr.jpg ...
[==================================================] 100.00%

OCR returns: 02.11.2022
Running OCR on https://i.postimg.cc/x1xtm4D1/2003-Oshkosh-FMTV-M1083-A1-P2-truck-destr.jpg took 23.854267946997425 seconds to run
9258
9259
Grabbing the full link at https://i.postimg.cc/26b4MCdZ/2003-m777-truck-destr.jpg took 0.4077154890001111 seconds to run

Connecting to https://i.postimg.cc/26b4MCdZ/2003-m777-truck-destr.jpg ...
Downloading 2003-m777-truck-destr.jpg ...
[==================================================] 100.00%

OCR returns: 11.11.2022|CAaΔKOB|BAKOB
Running OCR on https://i.postimg.cc/26b4MCdZ/2003-m777-truck-destr.jpg took 17.407178225999814 seconds to run
9259
9260
Grabbing the full link at https://i.postimg.cc/PrDcsPX5/2001.jpg took 0.3725668000006408 seconds to run

Connecting to https://i.postimg.cc/PrDcsPX5/2001.jpg ...
Downloading 2001.jpg ...
[==================================================] 100.00%

OCR returns: 13.07.2022
Running OCR on https://i.postimg.cc/PrDcsPX5/2001.jpg took 23.53321496600256 seconds to run
9260
9261
Returning non-postimg link
9261
9262
Returning non-postimg link
9262
9263
Grabbing the full link at https://i.postimg.cc/yx1RhRmv/2002-Oshkosh-FMTV-M1083-A1-P2-destr-18-01-23.jpg took 0.3743780529985088 seconds to run
9263
9264
Grabbing the full link at https://i.postimg.cc/0N0M69Tp/2008-Oshkosh-FMTV-M1083-A1-P2-truck-destr-24-05-23.jpg took 0.3898403610000969 seconds to run
9264
9265
Grabbing the full link at https://i.postimg.cc/MTyCJbSr/2001-FMTV-M1083-A1-P2-destr-24-07-23.jpg took 0.37368483699901844 seconds to run
9265
9266
Grabbing the full link at https://i.postimg.cc/JzYR4N7d/2007-Oshkosh-FMTV-M1083-A1-P2-truck-destr-03-11-23.jpg took 0.3764018430010765 seconds to run
9266
9267
Grabbing the full link at https://i.postimg.cc/GmnbK01m/2026-Oshkosh-FMTV-M1083-A1-P2-truck-destr-30-10-23.jpg took 0.37071280100281 seconds to run
9267
9268
Grabbing the full link at https://i.postimg.cc/0yBZpcG0/2026-Oshkosh-M1083-A1-P2-MTV-dam-12-06-24.jpg took 0.36757967899757205 seconds to run
9268
9269
Grabbing the full link at https://i.postimg.cc/J7gL04Rj/2011-Oshkosh-M1083-A1-P2-MTV-destr-20-08-24.jpg took 0.37756716199874063 seconds to run
9269
9270
Grabbing the full link at https://i.postimg.cc/26hb98Fv/2009-Oshkosh-M1083-A1-P2-MTV-destr-30-04-24.jpg took 0.3746021810002276 seconds to run
9270
9271
Grabbing the full link at https://i.postimg.cc/WbbF4XsD/2033-Oshkosh-M1083-A1-P2-MTV-destr-23-11-24.jpg took 0.38737191000109306 seconds to run
9271
9272
Grabbing the full link at https://i.postimg.cc/65VjSMXx/2036-Oshkosh-M1083-A1-P2-MTV-destr-08-03-25.jpg took 0.37268318299902603 seconds to run
9272
9273
Grabbing the full link at https://i.postimg.cc/K8Hz2KhB/2006-Oshkosh-M1083-A1-P2-MTV-destr-19-03-25.jpg took 0.37787954099985654 seconds to run
9273
9274
Grabbing the full link at https://i.postimg.cc/vZxY7fhh/2004-Oshkosh-M1083-A1-P2-MTV-destr-29-04-25.jpg took 0.3865391200015438 seconds to run
9274
9275
Grabbing the full link at https://i.postimg.cc/LsrGyJk1/2004-Oshkosh-M1083-A1-P2-MTV-destr-17-07-25.jpg took 0.37642128999868874 seconds to run
9275
9276
Grabbing the full link at https://i.postimg.cc/52rdB2gp/2000-Oshkosh-FMTV-M1083-A1-P2-dam-aband-24-07-23.jpg took 0.3717312669978128 seconds to run
9276
9277
Returning non-postimg link
9277
9278
Grabbing the full link at https://i.postimg.cc/9MzwXm7T/2007-Jelcz-P882-53-truck-destr-22-04-23.jpg took 0.3642396409995854 seconds to run
9278
9279
Grabbing the full link at https://i.postimg.cc/zfHjyW8Y/2001-unimog.jpg took 0.376525000003312 seconds to run

Connecting to https://i.postimg.cc/zfHjyW8Y/2001-unimog.jpg ...
Downloading 2001-unimog.jpg ...
[==================================================] 100.00%

OCR returns: 07.10.2022|@georgia_man|pysnHcKnnPoXo
Running OCR on https://i.postimg.cc/zfHjyW8Y/2001-unimog.jpg took 14.076115399999253 seconds to run
9279
9280
Grabbing the full link at https://i.postimg.cc/0ybV7HS8/2003-Mercedes-Benz-Unimog-U1300-L-ambulance-destr-25-01-23.jpg took 0.36900470899854554 seconds to run
9280
9281
Grabbing the full link at https://i.postimg.cc/VvJT0FLM/2010-Mercedes-Benz-Unimog-U1300-L-ambulance-destr-02-05-24.jpg took 0.3685583529986616 seconds to run
9281
9282
Returning non-postimg link
9282
9283
Grabbing the full link at https://i.postimg.cc/tTBNrdGT/2002-Pinzgauer-Vector-718-destr-15-01-24.jpg took 0.37158821300181444 seconds to run
9283
9284
Grabbing the full link at https://i.postimg.cc/SxQrwRy1/2017-Pinzgauer-Vector-PPV-destr-06-06-25.jpg took 0.3643370860008872 seconds to run
9284
9285
Grabbing the full link at https://i.postimg.cc/Bb85pvw6/2000-Pinzgauer-Vector-718.jpg took 0.3647265450017585 seconds to run

Connecting to https://i.postimg.cc/Bb85pvw6/2000-Pinzgauer-Vector-718.jpg ...
Downloading 2000-Pinzgauer-Vector-718.jpg ...
[==================================================] 100.00%

OCR returns: 26.09.2022
Running OCR on https://i.postimg.cc/Bb85pvw6/2000-Pinzgauer-Vector-718.jpg took 26.453357092999795 seconds to run
9285
9286
Grabbing the full link at https://i.postimg.cc/RhtL6vNB/2000-Pinzgauer-Vector-718-PPV-dam.jpg took 0.5520866769984423 seconds to run

Connecting to https://i.postimg.cc/RhtL6vNB/2000-Pinzgauer-Vector-718-PPV-dam.jpg ...
Downloading 2000-Pinzgauer-Vector-718-PPV-dam.jpg ...
[==================================================] 100.00%

OCR returns: 11.11.2022
Running OCR on https://i.postimg.cc/RhtL6vNB/2000-Pinzgauer-Vector-718-PPV-dam.jpg took 24.110261387999344 seconds to run
9286
9287
Grabbing the full link at https://i.postimg.cc/vmz81KcL/2001-Pinzgauer-Vector-protected-patrol-vehicle-capt-02-03-24.jpg took 0.40113913100140053 seconds to run
9287
9288
Grabbing the full link at https://i.postimg.cc/v8fYJRDb/46f.png took 1.443972285997006 seconds to run

Connecting to https://i.postimg.cc/v8fYJRDb/46f.png ...
Downloading 46f.png ...
[==================================================] 100.00%

OCR returns: UKRIM|19/7/2022
Running OCR on https://i.postimg.cc/v8fYJRDb/46f.png took 20.010074328001792 seconds to run
9288
9289

Connecting to https://i.postimg.cc/zfZgczbq/446.png ...
Downloading 446.png ...
[                                                  ] 0.32%

Grabbing the full link at https://i.postimg.cc/zfZgczbq/446.png took 0.45970496599693433 seconds to run

[==================================================] 100.00%

OCR returns: @fiftnmls|@fiftnmls|347|UAS|DEFENDER|10/3/2023
Running OCR on https://i.postimg.cc/zfZgczbq/446.png took 30.160215856998548 seconds to run
9289
9290
Grabbing the full link at https://i.postimg.cc/ydyWpJkc/57.png took 0.41954328599967994 seconds to run

Connecting to https://i.postimg.cc/ydyWpJkc/57.png ...
Downloading 57.png ...
[==================================================] 100.00%

OCR returns: 09/4/2023
Running OCR on https://i.postimg.cc/ydyWpJkc/57.png took 19.003059689999645 seconds to run
9290
9291
Grabbing the full link at https://i.postimg.cc/8zK88btq/2025-Land-Rover-destr-28-04-23.jpg took 0.4139953369995055 seconds to run
9291
9292
Grabbing the full link at https://i.postimg.cc/2jF259Y7/2037-Land-Rover-Snatch-destr-07-06-23.jpg took 0.3775686199987831 seconds to run
9292
9293
Grabbing the full link at https://i.postimg.cc/ydW0DNmC/2001-Land-Rover-30-04-23.jpg took 0.37001673199847573 seconds to run
9293
9294
Grabbing the full link at https://i.postimg.cc/zXTLrcn0/2027-Land-Rover-Snatch-destr-08-04-23.jpg took 0.36586861700197915 seconds to run
9294
9295
Grabbing the full link at https://i.postimg.cc/cJjqGD9M/2013-Land-Rover-Snatch-destr-25-09-24.jpg took 0.36711938200096483 seconds to run
9295
9296
Grabbing the full link at https://i.postimg.cc/Z5CMxRCL/2014-Land-Rover-Snatch-destr-15-11-24.jpg took 0.3635803719989781 seconds to run
9296
9297
Grabbing the full link at https://i.postimg.cc/t4ss3JZp/2022-Land-Rover-Snatch-destr-29-11-24.jpg took 0.39595245700184023 seconds to run
9297
9298
Grabbing the full link at https://i.postimg.cc/yxSBY8df/2056-Land-Rover-Snatch-destr-31-12-24.jpg took 0.37192159999904106 seconds to run
9298
9299
Grabbing the full link at https://i.postimg.cc/9QBrXZ2z/2014-Land-Rover-Snatch-destr-14-02-25.jpg took 0.3641195019990846 seconds to run
9299
9300
Grabbing the full link at https://i.postimg.cc/k4PZ7CpC/2022-Land-Rover-Snatch-destr-31-12-24.jpg took 0.3934337360005884 seconds to run
9300
9301
Grabbing the full link at https://i.postimg.cc/yxjY9zH0/2017-Land-Rover-Snatch-destr-22-06-25.jpg took 0.36641989900090266 seconds to run
9301
9302
Grabbing the full link at https://i.postimg.cc/wMQLvG65/2021-Land-Rover-Snatch-dam-18-01-25.jpg took 0.36651475799953914 seconds to run
9302
9303
Grabbing the full link at https://i.postimg.cc/brHHZNMs/2038-Land-Rover-Snatch-dam-aband-25-07-25.jpg took 0.3736410530000285 seconds to run
9303
9304
Grabbing the full link at https://i.postimg.cc/zG4V0NKW/2010-Land-Rover-Snatch-capt-05-12-24.jpg took 0.36138300799939316 seconds to run
9304
9305
Grabbing the full link at https://i.postimg.cc/631S7QQG/2001-Land-Rover-Snatch-capt-31-12-23.jpg took 0.37382471300225006 seconds to run
9305
9306
Grabbing the full link at https://i.postimg.cc/y8tjbpnB/2028-Land-Rover-Snatch-dam-capt-07-04-25.jpg took 0.3700370799997472 seconds to run
9306
9307
Grabbing the full link at https://i.postimg.cc/Kc5kxLHn/hh6.jpg took 0.36554135999904247 seconds to run

Connecting to https://i.postimg.cc/Kc5kxLHn/hh6.jpg ...
Downloading hh6.jpg ...
[==================================================] 100.00%

OCR returns: Ukraine's foreign legion ready to fight Russians back in Sievierodonetsk|Sun|THE|Reuters|D|0:06/3:38|06.06.22Severodonetsk.|G
Running OCR on https://i.postimg.cc/Kc5kxLHn/hh6.jpg took 62.50288121400081 seconds to run
9307
9308
Grabbing the full link at https://i.postimg.cc/k5mD2Xc6/76.jpg took 0.40300366500014206 seconds to run

Connecting to https://i.postimg.cc/k5mD2Xc6/76.jpg ...
Downloading 76.jpg ...
[==================================================] 100.00%

OCR returns: OTPAA|《几OH》|31.05.22IzyumfronttowardsVelykaKomyshuvakha,butfilmedearrlier.
Running OCR on https://i.postimg.cc/k5mD2Xc6/76.jpg took 35.37998847700146 seconds to run
9308
9309
Grabbing the full link at https://i.postimg.cc/3R9d5LPR/2000.jpg took 0.4684556579995842 seconds to run

Connecting to https://i.postimg.cc/3R9d5LPR/2000.jpg ...
Downloading 2000.jpg ...
[==================================================] 100.00%

OCR returns: Ukraine War: Time running out for Lysychansk|2
Running OCR on https://i.postimg.cc/3R9d5LPR/2000.jpg took 18.87138628700268 seconds to run
9309
9310
Grabbing the full link at https://i.postimg.cc/BQndX72n/2003-uaz452-kozak2-destr.jpg took 0.3790428760003124 seconds to run

Connecting to https://i.postimg.cc/BQndX72n/2003-uaz452-kozak2-destr.jpg ...
Downloading 2003-uaz452-kozak2-destr.jpg ...
[==================================================] 100.00%

OCR returns: 27.10.2022|中
Running OCR on https://i.postimg.cc/BQndX72n/2003-uaz452-kozak2-destr.jpg took 24.963463493000745 seconds to run
9310
9311
Grabbing the full link at https://i.postimg.cc/brrtrVJM/2022-11-13-UA-UAZ-452-destroyed.jpg took 0.5057429139997112 seconds to run

Connecting to https://i.postimg.cc/brrtrVJM/2022-11-13-UA-UAZ-452-destroyed.jpg ...
Downloading 2022-11-13-UA-UAZ-452-destroyed.jpg ...
[==================================================] 100.00%

OCR returns: WM Blood|13/11/2022|https:f/t.me/wiua22|Kherson Airport
Running OCR on https://i.postimg.cc/brrtrVJM/2022-11-13-UA-UAZ-452-destroyed.jpg took 27.46736207199865 seconds to run
9311
9312
Grabbing the full link at https://i.postimg.cc/90FYgx9C/1013-uaz452-destr.jpg took 0.45088498299810453 seconds to run

Connecting to https://i.postimg.cc/90FYgx9C/1013-uaz452-destr.jpg ...
Downloading 1013-uaz452-destr.jpg ...
[==================================================] 100.00%

OCR returns: 28.12.2022|福
Running OCR on https://i.postimg.cc/90FYgx9C/1013-uaz452-destr.jpg took 18.038444753001386 seconds to run
9312
9313
Grabbing the full link at https://i.postimg.cc/DwXXRtKz/2006-uaz452-destr-27-02-23.jpg took 0.430277171999478 seconds to run
9313
9314
Grabbing the full link at https://i.postimg.cc/P5hpX8MP/2004-UAZ-452-destr-06-01-24.jpg took 0.47755870499895536 seconds to run
9314
9315
Grabbing the full link at https://i.postimg.cc/SNGXwDtW/2006-uaz452-destr-12-03-23.jpg took 0.5187516939986381 seconds to run
9315
9316
Grabbing the full link at https://i.postimg.cc/fbVBSgZf/2006-uaz452-destr-15-03-23.png took 0.44007500499719754 seconds to run
9316
9317
Grabbing the full link at https://i.postimg.cc/c4gF8Hd0/2004-ua452-destr-07-03-23.jpg took 0.9124883250005951 seconds to run
9317
9318
Grabbing the full link at https://i.postimg.cc/MTZSxKxv/4f21.png took 0.45211208800174063 seconds to run

Connecting to https://i.postimg.cc/MTZSxKxv/4f21.png ...
Downloading 4f21.png ...
[==================================================] 100.00%

OCR returns: 29/3/2023|3,954 views|0:05/ 0:06
Running OCR on https://i.postimg.cc/MTZSxKxv/4f21.png took 27.603923529000895 seconds to run
9318
9319
Grabbing the full link at https://i.postimg.cc/0QTzDNNn/2002-uaz452-destr-20-03-23.jpg took 0.45831914600057644 seconds to run
9319
9320
Grabbing the full link at https://i.postimg.cc/Gphj6Dxr/549.png took 0.49841631800154573 seconds to run

Connecting to https://i.postimg.cc/Gphj6Dxr/549.png ...
Downloading 549.png ...
[==================================================] 100.00%

OCR returns: 10/4/2023
Running OCR on https://i.postimg.cc/Gphj6Dxr/549.png took 12.021687999000278 seconds to run
9320
9321
Grabbing the full link at https://i.postimg.cc/5NpMjjVq/763.png took 0.37494919799792115 seconds to run

Connecting to https://i.postimg.cc/5NpMjjVq/763.png ...
Downloading 763.png ...
[==================================================] 100.00%

OCR returns: 24/2/2023
Running OCR on https://i.postimg.cc/5NpMjjVq/763.png took 25.341153444001975 seconds to run
9321
9322
Grabbing the full link at https://i.postimg.cc/zBL2gvKw/2003-uaz452-destr-05-05-23.jpg took 0.41901352599961683 seconds to run
9322
9323
Grabbing the full link at https://i.postimg.cc/QNPmbqzH/2002-UAZ-452-destr-24-01-23.jpg took 0.3849394909993862 seconds to run
9323
9324
Grabbing the full link at https://i.postimg.cc/Ss1rHLN1/2032-UAZ-452-destr-23-04-23.jpg took 0.37920472499899915 seconds to run
9324
9325
Grabbing the full link at https://i.postimg.cc/QM8QrmVt/2011-UAZ-452-destr-25-12-23.jpg took 0.3813392429983651 seconds to run
9325
9326
Grabbing the full link at https://i.postimg.cc/kMyTfYBh/2030-UAZ-452-destr-21-11-22.jpg took 0.39001191799980006 seconds to run
9326
9327
Grabbing the full link at https://i.postimg.cc/2yTTyysf/2032-UAZ-452-destr-03-06-23.jpg took 0.3774537820027035 seconds to run
9327
9328
Grabbing the full link at https://i.postimg.cc/G2xhyXrN/2006-uaz452-destr-10-06-23.jpg took 0.3719739940024738 seconds to run
9328
9329
Grabbing the full link at https://i.postimg.cc/FFqfPxBy/2009-uaz452-destr-21-01-23.jpg took 0.37006923999797436 seconds to run
9329
9330
Grabbing the full link at https://i.postimg.cc/RhFFXZXP/2008-uaz452-destr-23-11-22.jpg took 0.3761598290002439 seconds to run
9330
9331
Grabbing the full link at https://i.postimg.cc/SQZDdP1x/2003-uaz452-destr-15-04-22.jpg took 0.39630781700179796 seconds to run
9331
9332
Grabbing the full link at https://i.postimg.cc/Y9MbDBwh/2014-uaz452-destr-09-06-23.jpg took 0.37306504099979065 seconds to run
9332
9333
Grabbing the full link at https://i.postimg.cc/YC3NMNJp/2004-UAZ-452-destr-17-07-22.jpg took 0.37499605099947075 seconds to run
9333
9334
Grabbing the full link at https://i.postimg.cc/kXbTXsdk/2022-UAZ-452-destr-30-04-23.jpg took 0.3733976639996399 seconds to run
9334
9335
Grabbing the full link at https://i.postimg.cc/6QHg5QjX/443k.png took 0.37259641800119425 seconds to run

Connecting to https://i.postimg.cc/6QHg5QjX/443k.png ...
Downloading 443k.png ...
[==================================================] 100.00%

OCR returns: 15/7/2023
Running OCR on https://i.postimg.cc/6QHg5QjX/443k.png took 24.99180456999966 seconds to run
9335
9336
Grabbing the full link at https://i.postimg.cc/DwTzQGQT/480.png took 0.3669052939985704 seconds to run

Connecting to https://i.postimg.cc/DwTzQGQT/480.png ...
Downloading 480.png ...
[==================================================] 100.00%

OCR returns: 28/3/2023
Running OCR on https://i.postimg.cc/DwTzQGQT/480.png took 13.604259742998693 seconds to run
9336
9337
Grabbing the full link at https://i.postimg.cc/mZjttJgN/2011-uaz452-destr-12-10-23.jpg took 0.38129896499958704 seconds to run
9337
9338
Grabbing the full link at https://i.postimg.cc/Hk2hS82z/2006-UAZ-452-destr-24-03-23.jpg took 0.3923227779996523 seconds to run
9338
9339
Grabbing the full link at https://i.postimg.cc/pTSrSytB/2019-UAZ-452-destr-10-05-22.jpg took 0.46185710999998264 seconds to run
9339
9340
Grabbing the full link at https://i.postimg.cc/V5Q2TTrT/2015-UAZ-452-destr-31-05-22.jpg took 0.39328070400006254 seconds to run
9340
9341
Grabbing the full link at https://i.postimg.cc/3w2LWyNL/2022-UAZ-452-destr-18-05-22.jpg took 0.4266978209998342 seconds to run
9341
9342
Grabbing the full link at https://i.postimg.cc/ydPvXwFc/2023-UAZ-452-destr-18-05-22.jpg took 1.5429937290027738 seconds to run
9342
9343
Grabbing the full link at https://i.postimg.cc/W3Z8MdTH/2015-UAZ-452-destr-15-12-24.jpg took 0.5057324070003233 seconds to run
9343
9344
Grabbing the full link at https://i.postimg.cc/sXSKmM88/2024-UAZ-452-destr-20-02-25.jpg took 0.4856546579976566 seconds to run
9344
9345
Grabbing the full link at https://i.postimg.cc/fL7PLPG9/2018-UAZ-452-destr-01-06-25.jpg took 0.5125115209993965 seconds to run
9345
9346
Grabbing the full link at https://i.postimg.cc/CKqXy5JJ/2019-UAZ-452-destr-01-06-25.jpg took 0.5190525600010005 seconds to run
9346
9347
Grabbing the full link at https://i.postimg.cc/QxtH06yD/2000-uaz452-dam-06-01-23.jpg took 0.8026870050016441 seconds to run
9347
9348
Grabbing the full link at https://i.postimg.cc/JzqN8r59/2053-UAZ-452-dam-12-10-24.jpg took 0.4901388610014692 seconds to run
9348
9349
Grabbing the full link at https://i.postimg.cc/T3K9sgbT/32770.png took 0.519213651001337 seconds to run

Connecting to https://i.postimg.cc/T3K9sgbT/32770.png ...
Downloading 32770.png ...
[==================================================] 100.00%

OCR returns: Before September 2023|1:55/2:20|0|0
Running OCR on https://i.postimg.cc/T3K9sgbT/32770.png took 29.87986457000079 seconds to run
9349
9350
Grabbing the full link at https://i.postimg.cc/NFjnSrgK/bl.png took 0.40391971899953205 seconds to run

Connecting to https://i.postimg.cc/NFjnSrgK/bl.png ...
Downloading bl.png ...
[==================================================] 100.00%

OCR returns: iz|EPNBAYHU|05/3/2022|3,603 views|0:11/1:18
Running OCR on https://i.postimg.cc/NFjnSrgK/bl.png took 28.68629109700123 seconds to run
9350
9351
Grabbing the full link at https://i.postimg.cc/d0vnz2LL/2dh.png took 0.38063096100086113 seconds to run

Connecting to https://i.postimg.cc/d0vnz2LL/2dh.png ...
Downloading 2dh.png ...
[==================================================] 100.00%

OCR returns: Onewkn,|XepcoH.|25.02.22|S|TikTok|@andriiboiko93kh
Running OCR on https://i.postimg.cc/d0vnz2LL/2dh.png took 29.388920823999797 seconds to run
9351
9352
Returning non-postimg link
9352
9353
Grabbing the full link at https://i.postimg.cc/C5hRYrst/4f76.png took 0.401881804002187 seconds to run

Connecting to https://i.postimg.cc/C5hRYrst/4f76.png ...
Downloading 4f76.png ...
[==================================================] 100.00%

OCR returns: 12/5/2022|gettyimages|Anadolu Agency|1240946882
Running OCR on https://i.postimg.cc/C5hRYrst/4f76.png took 30.29427692399986 seconds to run
9353
9354
Grabbing the full link at https://i.postimg.cc/t48z389M/2000-UAZ-469-destr.jpg took 0.38037645899748895 seconds to run

Connecting to https://i.postimg.cc/t48z389M/2000-UAZ-469-destr.jpg ...
Downloading 2000-UAZ-469-destr.jpg ...
[==================================================] 100.00%

OCR returns: 19.10.2022
Running OCR on https://i.postimg.cc/t48z389M/2000-UAZ-469-destr.jpg took 19.969327964001423 seconds to run
9354
9355
Grabbing the full link at https://i.postimg.cc/7Y4rSh5Q/2014-uaz469-capt-04-03-22.jpg took 0.37075464299778105 seconds to run
9355
9356
Grabbing the full link at https://i.postimg.cc/ZK4tppqj/2025-uaz469-destr-08-07-23.jpg took 0.3829117489985947 seconds to run
9356
9357
Grabbing the full link at https://i.postimg.cc/CMc5vmGT/2004-uaz469-destr-28-11-23.jpg took 0.3778495139995357 seconds to run
9357
9358
Grabbing the full link at https://i.postimg.cc/fy8VmvKs/2011-uaz469-destr-20-06-23.jpg took 0.36607179199927486 seconds to run
9358
9359
Grabbing the full link at https://i.postimg.cc/jjZLzZgm/2016-uaz469-destr-28-09-22.jpg took 0.395313504999649 seconds to run
9359
9360
Grabbing the full link at https://i.postimg.cc/WpGVCJVL/324.png took 0.3679477810001117 seconds to run

Connecting to https://i.postimg.cc/WpGVCJVL/324.png ...
Downloading 324.png ...
[==================================================] 100.00%

OCR returns: @PYBAR|Before September 2023|0:39/1:09|号|0
Running OCR on https://i.postimg.cc/WpGVCJVL/324.png took 31.475800262996927 seconds to run
9360
9361
Grabbing the full link at https://i.postimg.cc/kGck4KM2/257.png took 0.40219082700059516 seconds to run

Connecting to https://i.postimg.cc/kGck4KM2/257.png ...
Downloading 257.png ...
[==================================================] 100.00%

OCR returns: Before September 2023|-|1:33 / 2:20|dx|0
Running OCR on https://i.postimg.cc/kGck4KM2/257.png took 29.304247435000434 seconds to run
9361
9362
Grabbing the full link at https://i.postimg.cc/HLT8ySnD/1014.jpg took 0.5392930889975105 seconds to run

Connecting to https://i.postimg.cc/HLT8ySnD/1014.jpg ...
Downloading 1014.jpg ...
[==================================================] 100.00%

OCR returns: TikTok|31.03.2022|shamrai01|TikTok|@max.alhimov
Running OCR on https://i.postimg.cc/HLT8ySnD/1014.jpg took 11.962469026999315 seconds to run
9362
9363
Grabbing the full link at https://i.postimg.cc/tgpMs65F/Screenshot-8026.png took 0.42408908099969267 seconds to run

Connecting to https://i.postimg.cc/tgpMs65F/Screenshot-8026.png ...
Downloading Screenshot-8026.png ...
[==================================================] 100.00%

OCR returns: 24/02/2022|602 views|0:20/0:23|1|☆
Running OCR on https://i.postimg.cc/tgpMs65F/Screenshot-8026.png took 27.82685308500004 seconds to run
9363
9364

Connecting to https://i.postimg.cc/kXMB2DzL/43.png ...
Downloading 43.png ...
[                                                  ] 1.63%

Grabbing the full link at https://i.postimg.cc/kXMB2DzL/43.png took 0.5258905329974368 seconds to run

[==================================================] 100.00%

OCR returns: Onewkn,|XepcoH.|25.02.22|TikTok|@andriiboiko93kh
Running OCR on https://i.postimg.cc/kXMB2DzL/43.png took 28.16381843400086 seconds to run
9364
9365

Connecting to https://i.postimg.cc/90crT04r/776.png ...
Downloading 776.png ...
[                                                  ] 0.29%

Grabbing the full link at https://i.postimg.cc/90crT04r/776.png took 1.4225983030009957 seconds to run

[==================================================] 100.00%

OCR returns: 04/3/2022|ZIL-131ARS-14|KraZ-260(ATZ-9.3-260）|KraZ-5233|ZIL-131,ZIL-131（ZU-23）,|ZIL-131ARS-14|GAZ-66,GAZ-3307|GAZ-66|ZIL-131|2BMP-1P|URAL375,UAZ-469,|GAZ-66
Running OCR on https://i.postimg.cc/90crT04r/776.png took 30.276490435000596 seconds to run
9365
9366

Connecting to https://i.postimg.cc/vHXz28qN/3f.jpg ...
Downloading 3f.jpg ...
[=                                                 ] 2.07%

Grabbing the full link at https://i.postimg.cc/vHXz28qN/3f.jpg took 0.48814652399960323 seconds to run

[==================================================] 100.00%

OCR returns: 13.04.2022
Running OCR on https://i.postimg.cc/vHXz28qN/3f.jpg took 17.862433387999772 seconds to run
9366
9367
Grabbing the full link at https://i.postimg.cc/zvQDMzvw/2015-uaz469-capt-28-02-22.jpg took 0.4929143590015883 seconds to run
9367
9368
Grabbing the full link at https://i.postimg.cc/jSpgs6xw/2021-UAZ-3303-destr-18-05-22.jpg took 0.5184525830009079 seconds to run
9368
9369
Grabbing the full link at https://i.postimg.cc/x8DLK4J5/2004-UAZ-31514-destr-05-06-23.jpg took 0.4763345270002901 seconds to run
9369
9370
Grabbing the full link at https://i.postimg.cc/MGb51frk/2014-UAZ-3151-destr-19-07-23.jpg took 0.4709776259987848 seconds to run
9370
9371
Grabbing the full link at https://i.postimg.cc/FHLpnfy9/2036-UAZ-39094-Fermer-destr-21-08-24.jpg took 0.39682810199883534 seconds to run
9371
9372
Grabbing the full link at https://i.postimg.cc/tgB7S9GQ/65.png took 0.5158457180004916 seconds to run

Connecting to https://i.postimg.cc/tgB7S9GQ/65.png ...
Downloading 65.png ...
[==================================================] 100.00%

OCR returns: KAHANCNELNANbHOTOHAZHAUEHNA|12/5/2022
Running OCR on https://i.postimg.cc/tgB7S9GQ/65.png took 47.66197275900049 seconds to run
9372
9373
Grabbing the full link at https://i.postimg.cc/FRwKF7qJ/2007-MAN-KAT-4x4-destr-28-01-24.jpg took 0.4431206289991678 seconds to run
9373
9374
Grabbing the full link at https://i.postimg.cc/zv5n06bV/2014-MAN-KAT1-4x4-destr-08-03-24.jpg took 0.4126499550002336 seconds to run
9374
9375
Grabbing the full link at https://i.postimg.cc/6qwtLM1L/2000-MAN-KAT1-4x4-destr-16-04-24.jpg took 0.4255790139977762 seconds to run
9375
9376
Grabbing the full link at https://i.postimg.cc/J0rLhS6Y/2008-MAN-HX81-tank-transporter-destr-11-06-24.jpg took 0.4375334800024575 seconds to run
9376
9377
Grabbing the full link at https://i.postimg.cc/qRn9WxGt/2100-RMMV-HX81-tank-transporter-destr-21-01-25.jpg took 0.39329012999951374 seconds to run
9377
9378
Grabbing the full link at https://i.postimg.cc/ydyQk73v/2019-MAN-Multi-A4-FSA-destr-30-05-25.jpg took 0.39937906400155043 seconds to run
9378
9379
Grabbing the full link at https://i.postimg.cc/tg7fqhKX/2105-RMMV-HX-4x4-destr-20-08-24.jpg took 0.4966700620025222 seconds to run
9379
9380
Grabbing the full link at https://i.postimg.cc/858VvLhv/2007-RMMV-HX-4x4-destr-12-01-25.jpg took 0.49326358899998013 seconds to run
9380
9381
Grabbing the full link at https://i.postimg.cc/RZDZGmPn/2002-RMMV-TG-MIL-6x6-destr-15-04-25.jpg took 0.422903196002153 seconds to run
9381
9382
Grabbing the full link at https://i.postimg.cc/mr125nqp/2001-Fiat-Fullback-pickup-truck-destr-17-05-24.jpg took 0.4231690990018251 seconds to run
9382
9383
Grabbing the full link at https://i.postimg.cc/g2J0vjKW/2000-Fiat-Fullback-pickup-truck-dam-16-11-24.jpg took 0.44173107399910805 seconds to run
9383
9384
Grabbing the full link at https://i.postimg.cc/02vqMs8b/6690.jpg took 0.46211385899732704 seconds to run

Connecting to https://i.postimg.cc/02vqMs8b/6690.jpg ...
Downloading 6690.jpg ...
[==================================================] 100.00%

OCR returns: 10.04.2022
Running OCR on https://i.postimg.cc/02vqMs8b/6690.jpg took 38.603658209998684 seconds to run
9384
9385

Connecting to https://i.postimg.cc/02vqMs8b/6690.jpg ...
Downloading 6690.jpg ...
[                                                  ] 1.26%

Grabbing the full link at https://i.postimg.cc/02vqMs8b/6690.jpg took 0.3884520150022581 seconds to run

[==================================================] 100.00%

OCR returns: 10.04.2022
Running OCR on https://i.postimg.cc/02vqMs8b/6690.jpg took 31.59063614399929 seconds to run
9385
9386
Grabbing the full link at https://i.postimg.cc/Vsn8k6Px/6689.jpg took 0.3668342450000637 seconds to run

Connecting to https://i.postimg.cc/Vsn8k6Px/6689.jpg ...
Downloading 6689.jpg ...
[==================================================] 100.00%

OCR returns: 10.04.2022
Running OCR on https://i.postimg.cc/Vsn8k6Px/6689.jpg took 26.988249945999996 seconds to run
9386
9387
Grabbing the full link at https://i.postimg.cc/gjQnYBXn/87.jpg took 0.48240521299885586 seconds to run

Connecting to https://i.postimg.cc/gjQnYBXn/87.jpg ...
Downloading 87.jpg ...
[==================================================] 100.00%

OCR returns: 20.04.2022
Running OCR on https://i.postimg.cc/gjQnYBXn/87.jpg took 21.70428974400056 seconds to run
9387
9388

Connecting to https://i.postimg.cc/gjQnYBXn/87.jpg ...
Downloading 87.jpg ...
[                                                  ] 1.64%

Grabbing the full link at https://i.postimg.cc/gjQnYBXn/87.jpg took 0.45744167000157177 seconds to run

[==================================================] 100.00%

OCR returns: 20.04.2022
Running OCR on https://i.postimg.cc/gjQnYBXn/87.jpg took 21.179135939000844 seconds to run
9388
9389
Grabbing the full link at https://i.postimg.cc/pXJ1kz84/2000-Armed-pickup-truck-destr-13-06-22.jpg took 0.5590044490018045 seconds to run
9389
9390
Grabbing the full link at https://i.postimg.cc/gkd4DQVG/2000-Peugeot-P4.jpg took 0.5099123969994253 seconds to run

Connecting to https://i.postimg.cc/gkd4DQVG/2000-Peugeot-P4.jpg ...
Downloading 2000-Peugeot-P4.jpg ...
[==================================================] 100.00%

OCR returns: 01.08.2022
Running OCR on https://i.postimg.cc/gkd4DQVG/2000-Peugeot-P4.jpg took 19.740560217000166 seconds to run
9390
9391
Grabbing the full link at https://i.postimg.cc/3J1L3hvM/2000-Peugeot-P4-destr-30-12-22.jpg took 0.4968748030005372 seconds to run
9391
9392
Grabbing the full link at https://i.postimg.cc/Prwt1X97/2002-Renault-TRM-2000-destr-24-11-23.png took 0.45034914200005005 seconds to run
9392
9393
Grabbing the full link at https://i.postimg.cc/qqTw5kH7/2025-Renault-TRM-2000-dam-13-02-25.jpg took 0.5171337979991222 seconds to run
9393
9394
Grabbing the full link at https://i.postimg.cc/bJp5VY8K/2003-YAD-4442-NT-destr-21-06-23.jpg took 0.4543404089999967 seconds to run
9394
9395
Grabbing the full link at https://i.postimg.cc/Hs4M6ys0/2020-YAD-4442-NT-destr-04-06-23.jpg took 0.5357672459977039 seconds to run
9395
9396
Grabbing the full link at https://i.postimg.cc/B6H7VvNy/2030-DAF-YAD-4442-NT-destr-11-06-24.jpg took 0.5389037999993889 seconds to run
9396
9397
Grabbing the full link at https://i.postimg.cc/y8g1SFQv/2024-DAF-YAD-4442-NT-destr-28-08-24.jpg took 0.44681593399945996 seconds to run
9397
9398
Grabbing the full link at https://i.postimg.cc/BbwwvxD0/2007-Iveco-Magirus-90-16-AW-4x4-destr-23-06-23.jpg took 0.4074593589975848 seconds to run
9398
9399
Grabbing the full link at https://i.postimg.cc/nL67YYgm/2007-Iveco-Magirus-90-16-AW-4x4-destr-04-12-24.jpg took 0.43272051899839425 seconds to run
9399
9400
Grabbing the full link at https://i.postimg.cc/VNW4W9Jw/443f3.png took 0.3984857010000269 seconds to run

Connecting to https://i.postimg.cc/VNW4W9Jw/443f3.png ...
Downloading 443f3.png ...
[==================================================] 100.00%

OCR returns: 18/8/2023
Running OCR on https://i.postimg.cc/VNW4W9Jw/443f3.png took 21.542636881000362 seconds to run
9400
9401
Grabbing the full link at https://i.postimg.cc/tJNRNYdN/2006-Iveco-VM90-destr-26-04-24.jpg took 0.48793119200126966 seconds to run
9401
9402
Grabbing the full link at https://i.postimg.cc/htZNdfqT/2013-Iveco-ACM-90-destr-30-09-24.jpg took 0.49479192400031025 seconds to run
9402
9403
Grabbing the full link at https://i.postimg.cc/760Rd9Jn/2016-Iveco-ACM-90-dam-03-12-23.jpg took 0.4306923679978354 seconds to run
9403
9404
Grabbing the full link at https://i.postimg.cc/RF6QN70Y/2024-Iveco-VM90-dam-05-11-23.jpg took 0.4646982990016113 seconds to run
9404
9405
Grabbing the full link at https://i.postimg.cc/gJ68NVLw/2001-downgraded-Mowag-Eagle-II-destr-09-08-23.jpg took 0.5027332909994584 seconds to run
9405
9406
Grabbing the full link at https://i.postimg.cc/jSHGqxFL/2007-Polycar-Bus-Truck-destr-07-05-24.jpg took 0.454106781999144 seconds to run
9406
9407
Grabbing the full link at https://i.postimg.cc/bJJMRQNt/2024-DAF-Leyland-45-150-destr-07-05-24.jpg took 0.3943235350016039 seconds to run
9407
9408
Grabbing the full link at https://i.postimg.cc/26CRTsyg/2040-Leyland-DAF-45-150-destr-03-04-25.jpg took 0.6759864310006378 seconds to run
9408
9409
Grabbing the full link at https://i.postimg.cc/Mp4NrV0v/2001-Leyland-DAF-45-150-destr-15-06-25.jpg took 0.40262732900009723 seconds to run
9409
9410
Grabbing the full link at https://i.postimg.cc/FRwtbJkp/2025-Daewoo-Novus-destr-01-06-24.jpg took 0.49268947599921376 seconds to run
9410
9411
Grabbing the full link at https://i.postimg.cc/NM5SLKxX/2015-Daewoo-Novus-destr-01-08-24.jpg took 0.41083270499802893 seconds to run
9411
9412
Grabbing the full link at https://i.postimg.cc/76fFmNSt/2012-Daewoo-Novus-destr-18-09-24.jpg took 0.42028484600086813 seconds to run
9412
9413
Grabbing the full link at https://i.postimg.cc/JhyqWHn0/2002-Daewoo-Novus-destr-02-11-24.jpg took 0.4044725460007612 seconds to run
9413
9414
Grabbing the full link at https://i.postimg.cc/dVV64xc8/2018-Daewoo-Novus-destr-24-08-24.jpg took 0.3879436089991941 seconds to run
9414
9415
Grabbing the full link at https://i.postimg.cc/0j4RvsBk/2006-Daewoo-Novus-destr-06-11-24.jpg took 0.3882520219995058 seconds to run
9415
9416
Grabbing the full link at https://i.postimg.cc/CLMtdJ0X/2010-Daewoo-Novus-destr-16-11-24.jpg took 0.47523790700142854 seconds to run
9416
9417
Grabbing the full link at https://i.postimg.cc/0yQDknhm/2027-Daewoo-Novus-destr-14-01-25.jpg took 0.41130278399941744 seconds to run
9417
9418
Grabbing the full link at https://i.postimg.cc/J4TPbzks/2006-Daewoo-Novus-destr-03-04-25.jpg took 0.5111523119994672 seconds to run
9418
9419
Grabbing the full link at https://i.postimg.cc/DZq29W93/2011-Daewoo-Novus-destr-08-04-25.jpg took 0.9287750559997221 seconds to run
9419
9420
Grabbing the full link at https://i.postimg.cc/zBG52GwN/2006-Daewoo-Novus-destr-24-05-25.jpg took 1.017753102001734 seconds to run
9420
9421
Grabbing the full link at https://i.postimg.cc/nr2pNxG4/2016-MAN-TGS-destr-31-08-24.jpg took 0.48763800999950035 seconds to run
9421
9422
Grabbing the full link at https://i.postimg.cc/ZRGr6Q86/2003-MAN-TG-4x4-destr-31-01-25.jpg took 0.45294640000065556 seconds to run
9422
9423
Grabbing the full link at https://i.postimg.cc/y6Rh7VKj/2013-MAN-TG-4x4-destr-31-08-24.jpg took 0.4302953760015953 seconds to run
9423
9424
Grabbing the full link at https://i.postimg.cc/K86ZbP3V/2013-MAN-TG-4x4-destr-18-05-25.jpg took 0.5626414219987055 seconds to run
9424
9425
Grabbing the full link at https://i.postimg.cc/cJw5VVnv/2017-MAN-TG-6x6-destr-26-05-25.jpg took 0.45098314700226183 seconds to run
9425
9426
Grabbing the full link at https://i.postimg.cc/KYV4F3Rh/2004-MAN-TG-6x6-destr-10-07-25.jpg took 0.48509633599678637 seconds to run
9426
9427
Grabbing the full link at https://i.postimg.cc/x1VfrZzG/2031-Mercedes-Benz-Zetros-destr-30-09-24.jpg took 0.41904102499756846 seconds to run
9427
9428
Grabbing the full link at https://i.postimg.cc/N002BZ7p/2124-Mercedes-Benz-Zetros-destr-09-10-24.jpg took 0.4880223939981079 seconds to run
9428
9429
Returning non-postimg link
9429
9430
Grabbing the full link at https://i.postimg.cc/0248xXPs/2000-Petra-Toyota-Land-Cruiser-79-series-destr-15-11-24.jpg took 0.5216073209994647 seconds to run
9430
9431
Grabbing the full link at https://i.postimg.cc/ZYXb2bLR/2033-Petra-Toyota-Land-Cruiser-79-series-destr-18-12-24.jpg took 0.4962297120000585 seconds to run
9431
9432
Grabbing the full link at https://i.postimg.cc/NMGz2wZ7/2017-DDA-66-mobile-disinfection-shower-capt-27-02-22.jpg took 0.47518688600030146 seconds to run
9432
9433
Grabbing the full link at https://i.postimg.cc/8CvcQmFc/2013-M922-field-artillery-ammunition-supply-vehicle-destr-20-03-25.jpg took 0.419139620000351 seconds to run
9433
9434
Grabbing the full link at https://i.postimg.cc/d0jcH5hy/542.png took 0.4248208489989338 seconds to run

Connecting to https://i.postimg.cc/d0jcH5hy/542.png ...
Downloading 542.png ...
[==================================================] 100.00%

OCR returns: PeKNMN|Cnabi cnrHan GPS (Makc...|33'52"R |PeKNMN|CnabIn cnrHan GPS(Makc..|28'53″ll8：|02/9/2023|9|28.0|17,0×|AF|口|口|TenerpaM-KaHanDambiev|TenerpaM-kaHan Dambiev|AUTD
Running OCR on https://i.postimg.cc/d0jcH5hy/542.png took 18.41155544600042 seconds to run
9434
9435
Grabbing the full link at https://i.postimg.cc/4yz0rXTH/6h6.jpg took 0.3680315370002063 seconds to run

Connecting to https://i.postimg.cc/4yz0rXTH/6h6.jpg ...
Downloading 6h6.jpg ...
[==================================================] 100.00%

OCR returns: 12-06-2022|KPbIM BECTNKPbIM
Running OCR on https://i.postimg.cc/4yz0rXTH/6h6.jpg took 24.75456444199881 seconds to run
9435
9436
Grabbing the full link at https://i.postimg.cc/ryd7kXqN/1013.png took 0.37316015499891364 seconds to run

Connecting to https://i.postimg.cc/ryd7kXqN/1013.png ...
Downloading 1013.png ...
[==================================================] 100.00%

OCR returns: Onewkn,|XepcOH.|25.02.22
Running OCR on https://i.postimg.cc/ryd7kXqN/1013.png took 9.127185170000303 seconds to run
9436
9437
Grabbing the full link at https://i.postimg.cc/QdnM0gx9/4fh.png took 0.3854259190011362 seconds to run

Connecting to https://i.postimg.cc/QdnM0gx9/4fh.png ...
Downloading 4fh.png ...
[==================================================] 100.00%

OCR returns: 06/3/2022
Running OCR on https://i.postimg.cc/QdnM0gx9/4fh.png took 14.756750053998985 seconds to run
9437
9438
Grabbing the full link at https://i.postimg.cc/BnNpxWwv/33.jpg took 0.368128099002206 seconds to run

Connecting to https://i.postimg.cc/BnNpxWwv/33.jpg ...
Downloading 33.jpg ...
[==================================================] 100.00%

OCR returns: 18/03/2022
Running OCR on https://i.postimg.cc/BnNpxWwv/33.jpg took 25.650849505000224 seconds to run
9438
9439

Connecting to https://i.postimg.cc/BnNpxWwv/33.jpg ...
Downloading 33.jpg ...
[=                                                 ] 2.53%

Grabbing the full link at https://i.postimg.cc/BnNpxWwv/33.jpg took 0.41098884099847055 seconds to run

[==================================================] 100.00%

OCR returns: 18/03/2022
Running OCR on https://i.postimg.cc/BnNpxWwv/33.jpg took 25.345069068996963 seconds to run
9439
9440

Connecting to https://i.postimg.cc/BnNpxWwv/33.jpg ...
Downloading 33.jpg ...
[=                                                 ] 2.53%

Grabbing the full link at https://i.postimg.cc/BnNpxWwv/33.jpg took 0.8908109700023488 seconds to run

[==================================================] 100.00%

OCR returns: 18/03/2022
Running OCR on https://i.postimg.cc/BnNpxWwv/33.jpg took 25.40975178699955 seconds to run
9440
9441
Grabbing the full link at https://i.postimg.cc/Jzs5YmSh/2005-Unknown-truck-destr-14-09-24.jpg took 0.40909515200110036 seconds to run
9441
9442
Grabbing the full link at https://i.postimg.cc/RCpCY8cX/8i.png took 0.3775765169993974 seconds to run

Connecting to https://i.postimg.cc/RCpCY8cX/8i.png ...
Downloading 8i.png ...
[==================================================] 100.00%

OCR returns: M3HAHKA|N3HAHKA|23/8/2023|t.me/The_Wrong_Side|t.me/The|Wrong|Side|N3HAHKA|N3HAHKA|t.me/The_Wrong_Side|t.me/The_Wrong_Side
Running OCR on https://i.postimg.cc/RCpCY8cX/8i.png took 26.347209767001914 seconds to run
9442
9443
Returning non-postimg link
9443
9444
Grabbing the full link at https://i.postimg.cc/xTtBCC95/6hk.jpg took 0.48685039399788366 seconds to run

Connecting to https://i.postimg.cc/xTtBCC95/6hk.jpg ...
Downloading 6hk.jpg ...
[==================================================] 100.00%

OCR returns: 21/03/2022
Running OCR on https://i.postimg.cc/xTtBCC95/6hk.jpg took 18.10359625699857 seconds to run
9444
9445

Connecting to https://i.postimg.cc/xTtBCC95/6hk.jpg ...
Downloading 6hk.jpg ...
[=                                                 ] 3.02%

Grabbing the full link at https://i.postimg.cc/xTtBCC95/6hk.jpg took 0.38353482200182043 seconds to run

[==================================================] 100.00%

OCR returns: 21/03/2022
Running OCR on https://i.postimg.cc/xTtBCC95/6hk.jpg took 18.13165574999948 seconds to run
9445
9446

Connecting to https://i.postimg.cc/xTtBCC95/6hk.jpg ...
Downloading 6hk.jpg ...
[=                                                 ] 3.02%

Grabbing the full link at https://i.postimg.cc/xTtBCC95/6hk.jpg took 0.36971396599983564 seconds to run

[==================================================] 100.00%

OCR returns: 21/03/2022
Running OCR on https://i.postimg.cc/xTtBCC95/6hk.jpg took 17.651221537998936 seconds to run
9446
9447
Grabbing the full link at https://i.postimg.cc/nV9FvX5k/f60.jpg took 0.36518593200162286 seconds to run

Connecting to https://i.postimg.cc/nV9FvX5k/f60.jpg ...
Downloading f60.jpg ...
[==================================================] 100.00%

OCR returns: 23/05/2022
Running OCR on https://i.postimg.cc/nV9FvX5k/f60.jpg took 8.277167068998097 seconds to run
9447
9448

Connecting to https://i.postimg.cc/nV9FvX5k/f60.jpg ...
Downloading f60.jpg ...
[===                                               ] 6.34%

Grabbing the full link at https://i.postimg.cc/nV9FvX5k/f60.jpg took 0.3880690330006473 seconds to run

[==================================================] 100.00%

OCR returns: 23/05/2022
Running OCR on https://i.postimg.cc/nV9FvX5k/f60.jpg took 7.740623482000956 seconds to run
9448
9449

Connecting to https://i.postimg.cc/xjHhH1Wr/ku4.png ...
Downloading ku4.png ...
[                                                  ] 0.56%

Grabbing the full link at https://i.postimg.cc/xjHhH1Wr/ku4.png took 0.36351947100047255 seconds to run

[==================================================] 100.00%

OCR returns: 25/3/2022
Running OCR on https://i.postimg.cc/xjHhH1Wr/ku4.png took 12.246030612997856 seconds to run
9449
9450
Grabbing the full link at https://i.postimg.cc/mkDzPGdT/te2.png took 0.5061806089979655 seconds to run

Connecting to https://i.postimg.cc/mkDzPGdT/te2.png ...
Downloading te2.png ...
[==================================================] 100.00%

OCR returns: 02/4/2023|5,165 views|0:13/ 0:13|d
Running OCR on https://i.postimg.cc/mkDzPGdT/te2.png took 28.288178407998203 seconds to run
9450
9451
Grabbing the full link at https://i.postimg.cc/J0bFWpb7/ku3.png took 0.5377005590016779 seconds to run

Connecting to https://i.postimg.cc/J0bFWpb7/ku3.png ...
Downloading ku3.png ...
[==================================================] 100.00%

OCR returns: 25/3/2022
Running OCR on https://i.postimg.cc/J0bFWpb7/ku3.png took 12.921072615001322 seconds to run
9451
9452
Grabbing the full link at https://i.postimg.cc/fLSF8zy9/ku1.png took 0.4066966569989745 seconds to run

Connecting to https://i.postimg.cc/fLSF8zy9/ku1.png ...
Downloading ku1.png ...
[==================================================] 100.00%

OCR returns: 25/3/2022
Running OCR on https://i.postimg.cc/fLSF8zy9/ku1.png took 12.49844126699827 seconds to run
9452
9453
Grabbing the full link at https://i.postimg.cc/8PB853th/477.png took 0.41208027999891783 seconds to run

Connecting to https://i.postimg.cc/8PB853th/477.png ...
Downloading 477.png ...
[==================================================] 100.00%

OCR returns: 28/2/2022|理|花迎|DV
Running OCR on https://i.postimg.cc/8PB853th/477.png took 17.563296897998953 seconds to run
9453
9454
Grabbing the full link at https://i.postimg.cc/L8GZd2sh/321.png took 0.4082996450015344 seconds to run

Connecting to https://i.postimg.cc/L8GZd2sh/321.png ...
Downloading 321.png ...
[==================================================] 100.00%

OCR returns: 07/4/2022|X03|0227.0
Running OCR on https://i.postimg.cc/L8GZd2sh/321.png took 13.227006820998213 seconds to run
9454
9455
Grabbing the full link at https://i.postimg.cc/vB4Tf41M/764.jpg took 0.4873426880003535 seconds to run

Connecting to https://i.postimg.cc/vB4Tf41M/764.jpg ...
Downloading 764.jpg ...
[==================================================] 100.00%

OCR returns: 国|09-04-2022
Running OCR on https://i.postimg.cc/vB4Tf41M/764.jpg took 10.70094217499718 seconds to run
9455
9456
Returning non-postimg link
9456
9457
Grabbing the full link at https://i.postimg.cc/xdxy9bDS/t1.jpg took 0.42594172800090746 seconds to run

Connecting to https://i.postimg.cc/xdxy9bDS/t1.jpg ...
Downloading t1.jpg ...
[==================================================] 100.00%

OCR returns: 31-03-2022|日|口
Running OCR on https://i.postimg.cc/xdxy9bDS/t1.jpg took 13.46639655800027 seconds to run
9457
9458
Grabbing the full link at https://i.postimg.cc/nzXKrcp9/t2.jpg took 0.4039006629973301 seconds to run

Connecting to https://i.postimg.cc/nzXKrcp9/t2.jpg ...
Downloading t2.jpg ...
[==================================================] 100.00%

OCR returns: 31-03-2022|2|0
Running OCR on https://i.postimg.cc/nzXKrcp9/t2.jpg took 12.966848144998949 seconds to run
9458
9459
Grabbing the full link at https://i.postimg.cc/mg7VFFRp/668.jpg took 0.41232590199797414 seconds to run

Connecting to https://i.postimg.cc/mg7VFFRp/668.jpg ...
Downloading 668.jpg ...
[==================================================] 100.00%

OCR returns: 19-04-2022|TG:|TG:|山|parbut|parbut
Running OCR on https://i.postimg.cc/mg7VFFRp/668.jpg took 39.11589548399934 seconds to run
9459
9460
Grabbing the full link at https://i.postimg.cc/43LVkGpZ/378.png took 0.37551239599997643 seconds to run

Connecting to https://i.postimg.cc/43LVkGpZ/378.png ...
Downloading 378.png ...
[==================================================] 100.00%

OCR returns: 13/4/2022|私|86-98E6|0:10/1:19|2
Running OCR on https://i.postimg.cc/43LVkGpZ/378.png took 40.93676442400101 seconds to run
9460
9461
Grabbing the full link at https://i.postimg.cc/8CzFgs7w/g1.jpg took 0.3750785740012361 seconds to run

Connecting to https://i.postimg.cc/8CzFgs7w/g1.jpg ...
Downloading g1.jpg ...
[==================================================] 100.00%

OCR returns: 24-04-2022|9KH/4|55.|55|nP
Running OCR on https://i.postimg.cc/8CzFgs7w/g1.jpg took 13.265292067997507 seconds to run
9461
9462
Grabbing the full link at https://i.postimg.cc/4nRZf2Bs/g2.jpg took 0.522895491001691 seconds to run

Connecting to https://i.postimg.cc/4nRZf2Bs/g2.jpg ...
Downloading g2.jpg ...
[==================================================] 100.00%

OCR returns: 24-04-202212/4|54|53
Running OCR on https://i.postimg.cc/4nRZf2Bs/g2.jpg took 13.205944121000357 seconds to run
9462
9463
Grabbing the full link at https://i.postimg.cc/zvgJtQfW/2002.jpg took 0.5234009439991496 seconds to run

Connecting to https://i.postimg.cc/zvgJtQfW/2002.jpg ...
Downloading 2002.jpg ...
[==================================================] 100.00%

OCR returns: 07.07.2022
Running OCR on https://i.postimg.cc/zvgJtQfW/2002.jpg took 14.681448947998433 seconds to run
9463
9464
Returning non-postimg link
9464
9465
Returning non-postimg link
9465
9466
Returning non-postimg link
9466
9467
Grabbing the full link at https://i.postimg.cc/wBz7ZMVW/2004-unkn-truck-destr-27-02-23.png took 0.45820978099800413 seconds to run
9467
9468
Grabbing the full link at https://i.postimg.cc/xjXn2ZG9/2005-P-18-ML-long-range-surveillance-VHF-radar-destr-09-04-24.jpg took 0.4696603890006372 seconds to run
9468
9469
Returning non-postimg link
9469
9470
Grabbing the full link at https://i.postimg.cc/cLkpDG61/2004.jpg took 0.4154518979994464 seconds to run

Connecting to https://i.postimg.cc/cLkpDG61/2004.jpg ...
Downloading 2004.jpg ...
[==================================================] 100.00%

OCR returns: 25.06.2022
Running OCR on https://i.postimg.cc/cLkpDG61/2004.jpg took 17.300447906000045 seconds to run
9470
9471
Grabbing the full link at https://i.postimg.cc/nr15B66J/2005.jpg took 0.4933941290000803 seconds to run

Connecting to https://i.postimg.cc/nr15B66J/2005.jpg ...
Downloading 2005.jpg ...
[==================================================] 100.00%

OCR returns: M|25.06.2022
Running OCR on https://i.postimg.cc/nr15B66J/2005.jpg took 14.886414316999435 seconds to run
9471
9472
Grabbing the full link at https://i.postimg.cc/gkNQJbVy/2006.jpg took 0.4035774059993855 seconds to run

Connecting to https://i.postimg.cc/gkNQJbVy/2006.jpg ...
Downloading 2006.jpg ...
[==================================================] 100.00%

OCR returns: 25.06.2022|2|WAR|1|WAR
Running OCR on https://i.postimg.cc/gkNQJbVy/2006.jpg took 18.10740360300042 seconds to run
9472
9473
Returning non-postimg link
9473
9474
Returning non-postimg link
9474
9475
Grabbing the full link at https://i.postimg.cc/15GCKJtS/2003-unkn-truck.jpg took 0.3788173059983819 seconds to run

Connecting to https://i.postimg.cc/15GCKJtS/2003-unkn-truck.jpg ...
Downloading 2003-unkn-truck.jpg ...
[==================================================] 100.00%

OCR returns: 06.08.2022
Running OCR on https://i.postimg.cc/15GCKJtS/2003-unkn-truck.jpg took 27.175232154000696 seconds to run
9475
9476
Grabbing the full link at https://i.postimg.cc/gjNYh2K4/d35.png took 0.3689820969993889 seconds to run

Connecting to https://i.postimg.cc/gjNYh2K4/d35.png ...
Downloading d35.png ...
[==================================================] 100.00%

OCR returns: 274|166|4|BCy|N3HAHKA|Lme/The Wrong_Side|N3HAHKA|tme/The WrongSide|08/8/2022|6.412views
Running OCR on https://i.postimg.cc/gjNYh2K4/d35.png took 20.05200127900025 seconds to run
9476
9477
Grabbing the full link at https://i.postimg.cc/W3smp5Yr/4ff2.png took 0.36866178099808167 seconds to run

Connecting to https://i.postimg.cc/W3smp5Yr/4ff2.png ...
Downloading 4ff2.png ...
[==================================================] 100.00%

OCR returns: 08/8/2022|Giazint_Z|Giazint_Z|1,866 vlews
Running OCR on https://i.postimg.cc/W3smp5Yr/4ff2.png took 17.448771880001004 seconds to run
9477
9478
Grabbing the full link at https://i.postimg.cc/pVF1Q2cT/2092-Unknown-truck-destr-27-02-25.jpg took 0.5342021709984692 seconds to run
9478
9479
Grabbing the full link at https://i.postimg.cc/Yqv4XN4z/2006-truck.jpg took 0.9588637800006836 seconds to run

Connecting to https://i.postimg.cc/Yqv4XN4z/2006-truck.jpg ...
Downloading 2006-truck.jpg ...
[==================================================] 100.00%

OCR returns: 07.09.2022|HNK
Running OCR on https://i.postimg.cc/Yqv4XN4z/2006-truck.jpg took 17.493852753999818 seconds to run
9479
9480
Grabbing the full link at https://i.postimg.cc/CM63zFgJ/443.png took 0.4635783040030219 seconds to run

Connecting to https://i.postimg.cc/CM63zFgJ/443.png ...
Downloading 443.png ...
[==================================================] 100.00%

OCR returns: 13/9/2022|t.me/HersonVesthik|4,981views|1:51/2:14|2
Running OCR on https://i.postimg.cc/CM63zFgJ/443.png took 29.20463137799743 seconds to run
9480
9481

Connecting to https://i.postimg.cc/CM63zFgJ/443.png ...
Downloading 443.png ...
[                                                  ] 0.22%

Grabbing the full link at https://i.postimg.cc/CM63zFgJ/443.png took 0.4994968870014418 seconds to run

[==================================================] 100.00%

OCR returns: 13/9/2022|t.me/HersonVesthik|4,981views|1:51/2:14|2
Running OCR on https://i.postimg.cc/CM63zFgJ/443.png took 28.46282249899741 seconds to run
9481
9482
Grabbing the full link at https://i.postimg.cc/K8kwYzYC/3d21.png took 0.5555412840003555 seconds to run

Connecting to https://i.postimg.cc/K8kwYzYC/3d21.png ...
Downloading 3d21.png ...
[==================================================] 100.00%

OCR returns: 02/5/2022
Running OCR on https://i.postimg.cc/K8kwYzYC/3d21.png took 24.109861709999677 seconds to run
9482
9483

Connecting to https://i.postimg.cc/K8kwYzYC/3d21.png ...
Downloading 3d21.png ...
[                                                  ] 0.21%

Grabbing the full link at https://i.postimg.cc/K8kwYzYC/3d21.png took 0.3791717519998201 seconds to run

[==================================================] 100.00%

OCR returns: 02/5/2022
Running OCR on https://i.postimg.cc/K8kwYzYC/3d21.png took 23.595282677000796 seconds to run
9483
9484
Returning non-postimg link
9484
9485
Returning non-postimg link
9485
9486
Grabbing the full link at https://i.postimg.cc/4NDBkRtF/3326.png took 0.5714387929983786 seconds to run

Connecting to https://i.postimg.cc/4NDBkRtF/3326.png ...
Downloading 3326.png ...
[==================================================] 100.00%

OCR returns: KACKAA|KACKAA|04/11/2022|ABTOMONnbnpOTNBHNKa|t.me/obtf_kaskad|t.me/obtf_kaskad
Running OCR on https://i.postimg.cc/4NDBkRtF/3326.png took 15.82578227400154 seconds to run
9486
9487
Grabbing the full link at https://i.postimg.cc/yNPWshtg/53.png took 0.5218259499997657 seconds to run

Connecting to https://i.postimg.cc/yNPWshtg/53.png ...
Downloading 53.png ...
[==================================================] 100.00%

OCR returns: 08/11/2022|KACKAA|KACKAA|00|$|t.me/obtf_kaskad|S|t.me/obtf_kaskad|E|E|0:08/0:37|0:11/0:370
Running OCR on https://i.postimg.cc/yNPWshtg/53.png took 15.984027167000022 seconds to run
9487
9488
Grabbing the full link at https://i.postimg.cc/90Ff8tcv/4776.png took 1.036856495000393 seconds to run

Connecting to https://i.postimg.cc/90Ff8tcv/4776.png ...
Downloading 4776.png ...
[==================================================] 100.00%

OCR returns: 25/5/2022
Running OCR on https://i.postimg.cc/90Ff8tcv/4776.png took 17.946872980999615 seconds to run
9488
9489
Grabbing the full link at https://i.postimg.cc/cLFyTZKs/2022-08-07-UA-unknown-truck-destroyed.jpg took 0.4397916979978618 seconds to run

Connecting to https://i.postimg.cc/cLFyTZKs/2022-08-07-UA-unknown-truck-destroyed.jpg ...
Downloading 2022-08-07-UA-unknown-truck-destroyed.jpg ...
[==================================================] 100.00%

OCR returns: 07/08/2022|RUDENKO
Running OCR on https://i.postimg.cc/cLFyTZKs/2022-08-07-UA-unknown-truck-destroyed.jpg took 25.18823441800123 seconds to run
9489
9490
Grabbing the full link at https://i.postimg.cc/J496djT1/43.png took 0.4233453430024383 seconds to run

Connecting to https://i.postimg.cc/J496djT1/43.png ...
Downloading 43.png ...
[==================================================] 100.00%

OCR returns: 04/12/2022
Running OCR on https://i.postimg.cc/J496djT1/43.png took 17.68400845100041 seconds to run
9490
9491
Grabbing the full link at https://i.postimg.cc/YSK3kWPc/2014-unkn-truck-destr-14-05-23.jpg took 1.4799512499994307 seconds to run
9491
9492
Grabbing the full link at https://i.postimg.cc/J4WYJ5jj/2004-unkn-truck-destr-26-05-23.jpg took 0.4102884090025327 seconds to run
9492
9493
Grabbing the full link at https://i.postimg.cc/mDRm9bFT/2024-Unknown-truck-destr-18-05-22.jpg took 0.41104822299894295 seconds to run
9493
9494
Grabbing the full link at https://i.postimg.cc/0NFfLjyR/2021-3x-unkn-truck-destr-15-03-22.jpg took 0.3796782470017206 seconds to run
9494
9495
Grabbing the full link at https://i.postimg.cc/0NFfLjyR/2021-3x-unkn-truck-destr-15-03-22.jpg took 0.3936904180009151 seconds to run
9495
9496
Grabbing the full link at https://i.postimg.cc/0NFfLjyR/2021-3x-unkn-truck-destr-15-03-22.jpg took 0.4119186570023885 seconds to run
9496
9497
Grabbing the full link at https://i.postimg.cc/QdzytG7k/2004-unkn-truck-destr-22-11-23.jpg took 0.4571322730007523 seconds to run
9497
9498
Grabbing the full link at https://i.postimg.cc/qvbcP69N/2005-unkn-truck-destr-23-02-24.jpg took 0.42063972300093155 seconds to run
9498
9499
Grabbing the full link at https://i.postimg.cc/sDQ2nKNs/2009-Unknown-truck-destr-01-03-24.jpg took 0.44925493999835453 seconds to run
9499
9500
Grabbing the full link at https://i.postimg.cc/QCsQQt5Z/2002-Unknown-truck-destr-01-08-24.jpg took 0.39331074300207547 seconds to run
9500
Saved at index 9500
9501
Grabbing the full link at https://i.postimg.cc/KjNnJ2rk/2003-Unknown-truck-destr-01-08-24.jpg took 0.3979883139982121 seconds to run
9501
9502
Grabbing the full link at https://i.postimg.cc/QdGXYsbF/2020-Unknown-truck-destr-09-08-24.jpg took 0.4181418449988996 seconds to run
9502
9503
Grabbing the full link at https://i.postimg.cc/NjShnLgz/2021-Unknown-truck-destr-22-08-24.jpg took 0.3780459390000033 seconds to run
9503
9504
Grabbing the full link at https://i.postimg.cc/rp462csF/2022-Unknown-truck-destr-22-08-24.jpg took 0.3961045309988549 seconds to run
9504
9505
Grabbing the full link at https://i.postimg.cc/W1B2mhxj/2025-Unknown-truck-destr-28-08-24.jpg took 0.4073458560014842 seconds to run
9505
9506
Grabbing the full link at https://i.postimg.cc/5NtNfcwc/2026-Unknown-truck-destr-28-08-24.jpg took 0.3912416530001792 seconds to run
9506
9507
Grabbing the full link at https://i.postimg.cc/fLKpKyGm/2008-Unknown-truck-destr-03-09-24.jpg took 0.3977463759983948 seconds to run
9507
9508
Grabbing the full link at https://i.postimg.cc/8PKFfMCZ/2041-Unknown-truck-destr-02-11-24.jpg took 0.41996933999689645 seconds to run
9508
9509
Grabbing the full link at https://i.postimg.cc/50wF7RFc/2039-Unknown-truck-destr-14-01-25.jpg took 0.36624675799976103 seconds to run
9509
9510
Grabbing the full link at https://i.postimg.cc/0NMJXfCx/2013-Unknown-truck-destr-14-04-25.jpg took 0.3778753240003425 seconds to run
9510
9511
Grabbing the full link at https://i.postimg.cc/vZmnfMg4/2014-Unknown-truck-destr-14-04-25.jpg took 0.3911239570006728 seconds to run
9511
9512
Grabbing the full link at https://i.postimg.cc/P5FwMcY2/2015-Unknown-truck-destr-14-04-25.jpg took 0.3760503749981581 seconds to run
9512
9513
Grabbing the full link at https://i.postimg.cc/k5Vyp6DS/2020-Unknown-truck-destr-14-06-25.jpg took 0.3658335330001137 seconds to run
9513
9514
Grabbing the full link at https://i.postimg.cc/Mpp51rSd/2018-Unknown-truck-destr-13-06-25.jpg took 0.36880253700292087 seconds to run
9514
9515
Grabbing the full link at https://i.postimg.cc/kG5ddcCk/2015-Unknown-truck-destr-23-06-24.jpg took 0.37854905299900565 seconds to run
9515
9516
Grabbing the full link at https://i.postimg.cc/BZxCYM64/2020-Unknown-truck-destr-28-06-25.jpg took 0.3851225329999579 seconds to run
9516
9517
Grabbing the full link at https://i.postimg.cc/4xBF4TJG/37.jpg took 0.37062517100275727 seconds to run

Connecting to https://i.postimg.cc/4xBF4TJG/37.jpg ...
Downloading 37.jpg ...
[==================================================] 100.00%

OCR returns: 20/03/2022
Running OCR on https://i.postimg.cc/4xBF4TJG/37.jpg took 12.148555375002616 seconds to run
9517
9518
Grabbing the full link at https://i.postimg.cc/4xBF4TJG/37.jpg took 0.3753986100018665 seconds to run

Connecting to https://i.postimg.cc/4xBF4TJG/37.jpg ...
Downloading 37.jpg ...
[==================================================] 100.00%

OCR returns: 20/03/2022
Running OCR on https://i.postimg.cc/4xBF4TJG/37.jpg took 12.040800645001582 seconds to run
9518
9519
Grabbing the full link at https://i.postimg.cc/3Jzj3bLL/bnm.png took 0.37361203100226703 seconds to run

Connecting to https://i.postimg.cc/3Jzj3bLL/bnm.png ...
Downloading bnm.png ...
[==================================================] 100.00%

OCR returns: 27/02/2022|TikTok|@12345.so|18.5K views|0:43/2:00|0
Running OCR on https://i.postimg.cc/3Jzj3bLL/bnm.png took 27.5509312840004 seconds to run
9519
9520
Grabbing the full link at https://i.postimg.cc/JnP8Cxr0/Screenshot-8249.png took 0.5140071069981786 seconds to run

Connecting to https://i.postimg.cc/JnP8Cxr0/Screenshot-8249.png ...
Downloading Screenshot-8249.png ...
[==================================================] 100.00%

OCR returns: 26/02/2022|12.1K views|0:12/ 0:15|2|0
Running OCR on https://i.postimg.cc/JnP8Cxr0/Screenshot-8249.png took 27.62001897099981 seconds to run
9520
9521
Grabbing the full link at https://i.postimg.cc/c1Dj5KT3/3557.png took 0.48362482499942416 seconds to run

Connecting to https://i.postimg.cc/c1Dj5KT3/3557.png ...
Downloading 3557.png ...
[==================================================] 100.00%

OCR returns: M9004|13/4/2022
Running OCR on https://i.postimg.cc/c1Dj5KT3/3557.png took 25.112885878999805 seconds to run
9521
9522

Connecting to https://i.postimg.cc/c1Dj5KT3/3557.png ...
Downloading 3557.png ...
[                                                  ] 0.20%

Grabbing the full link at https://i.postimg.cc/c1Dj5KT3/3557.png took 0.41713050000180374 seconds to run

[==================================================] 100.00%

OCR returns: M9004|13/4/2022
Running OCR on https://i.postimg.cc/c1Dj5KT3/3557.png took 23.318053854000027 seconds to run
9522
9523
Returning non-postimg link
9523
9524
Grabbing the full link at https://i.postimg.cc/W3bxTvB5/2007-Unknown-tanker-destr-16-05-24.jpg took 0.4262422179999703 seconds to run
9524
9525
Grabbing the full link at https://i.postimg.cc/Hnqh2PXY/2015-Unknown-tanker-destr-03-03-22.jpg took 0.4743508190003922 seconds to run
9525
9526
Returning non-postimg link
9526
9527
Returning non-postimg link
9527
9528
Returning non-postimg link
9528
9529
Returning non-postimg link
9529
9530
Grabbing the full link at https://i.postimg.cc/8zp60hrh/32.jpg took 0.4036907510017045 seconds to run

Connecting to https://i.postimg.cc/8zp60hrh/32.jpg ...
Downloading 32.jpg ...
[==================================================] 100.00%

OCR returns: 27.03.2022
Running OCR on https://i.postimg.cc/8zp60hrh/32.jpg took 18.911219527999492 seconds to run
9530
9531

Connecting to https://i.postimg.cc/8zp60hrh/32.jpg ...
Downloading 32.jpg ...
[==                                                ] 5.14%

Grabbing the full link at https://i.postimg.cc/8zp60hrh/32.jpg took 0.40422693499931484 seconds to run

[==================================================] 100.00%

OCR returns: 27.03.2022
Running OCR on https://i.postimg.cc/8zp60hrh/32.jpg took 18.53228982300061 seconds to run
9531
9532
Grabbing the full link at https://i.postimg.cc/ZqBzP3Qx/5gj.png took 0.3718724780010234 seconds to run

Connecting to https://i.postimg.cc/ZqBzP3Qx/5gj.png ...
Downloading 5gj.png ...
[==================================================] 100.00%

OCR returns: 26/3/2022
Running OCR on https://i.postimg.cc/ZqBzP3Qx/5gj.png took 26.654454113999236 seconds to run
9532
9533

Connecting to https://i.postimg.cc/ZqBzP3Qx/5gj.png ...
Downloading 5gj.png ...
[                                                  ] 0.19%

Grabbing the full link at https://i.postimg.cc/ZqBzP3Qx/5gj.png took 0.5548556159992586 seconds to run

[==================================================] 100.00%

OCR returns: 26/3/2022
Running OCR on https://i.postimg.cc/ZqBzP3Qx/5gj.png took 25.75302479899983 seconds to run
9533
9534
Grabbing the full link at https://i.postimg.cc/3Nzz7rkv/u1.jpg took 0.44466350299990154 seconds to run

Connecting to https://i.postimg.cc/3Nzz7rkv/u1.jpg ...
Downloading u1.jpg ...
[==================================================] 100.00%

OCR returns: 29/03/2022|18:55|0.5
Running OCR on https://i.postimg.cc/3Nzz7rkv/u1.jpg took 17.211592981002468 seconds to run
9534
9535
Grabbing the full link at https://i.postimg.cc/G3fWvKXm/u2.jpg took 0.3755659189992002 seconds to run

Connecting to https://i.postimg.cc/G3fWvKXm/u2.jpg ...
Downloading u2.jpg ...
[==================================================] 100.00%

OCR returns: 29/03/2022|13
Running OCR on https://i.postimg.cc/G3fWvKXm/u2.jpg took 16.892724350000208 seconds to run
9535
9536
Grabbing the full link at https://i.postimg.cc/4xzRw6Y0/2018-Unknown-vehicle-27-05-24.jpg took 0.49444249299995136 seconds to run
9536
9537
Grabbing the full link at https://i.postimg.cc/RVCJ72dZ/u1.jpg took 0.5012822110002162 seconds to run

Connecting to https://i.postimg.cc/RVCJ72dZ/u1.jpg ...
Downloading u1.jpg ...
[==================================================] 100.00%

OCR returns: 113|心|KADV JS|09-04-2022
Running OCR on https://i.postimg.cc/RVCJ72dZ/u1.jpg took 13.01061831500192 seconds to run
9537
9538
Grabbing the full link at https://i.postimg.cc/wjyvFzmg/446.jpg took 0.39729927699954715 seconds to run

Connecting to https://i.postimg.cc/wjyvFzmg/446.jpg ...
Downloading 446.jpg ...
[==================================================] 100.00%

OCR returns: 09-04-2022|日
Running OCR on https://i.postimg.cc/wjyvFzmg/446.jpg took 12.739332936002029 seconds to run
9538
9539
Grabbing the full link at https://i.postimg.cc/W43yHnyk/f6.jpg took 0.37267491500097094 seconds to run

Connecting to https://i.postimg.cc/W43yHnyk/f6.jpg ...
Downloading f6.jpg ...
[==================================================] 100.00%

OCR returns: 12-04-2022|MHTOPMAUNOHHbIPOHT|VOZME3ANE|WH中OPMAUMOHHbIPOHT|VOZME3ANE|-0.3|-0.4
Running OCR on https://i.postimg.cc/W43yHnyk/f6.jpg took 14.608992601002683 seconds to run
9539
9540
Grabbing the full link at https://i.postimg.cc/pT562dRV/f7.jpg took 0.5449470759995165 seconds to run

Connecting to https://i.postimg.cc/pT562dRV/f7.jpg ...
Downloading f7.jpg ...
[==================================================] 100.00%

OCR returns: 12-04-2022|MH中OPMAUHOHHbIM中POHT|MH中OPMAUHOHHbIM中POHT|VOZME3ANE|VOZME3ANE|0|6
Running OCR on https://i.postimg.cc/pT562dRV/f7.jpg took 15.131750033000571 seconds to run
9540
9541
Grabbing the full link at https://i.postimg.cc/d0y9nJW1/33y.png took 0.9333889139998064 seconds to run

Connecting to https://i.postimg.cc/d0y9nJW1/33y.png ...
Downloading 33y.png ...
[==================================================] 100.00%

OCR returns: 13/3/2023
Running OCR on https://i.postimg.cc/d0y9nJW1/33y.png took 15.828934499000752 seconds to run
9541
9542
Grabbing the full link at https://i.postimg.cc/yNgPRr5v/t12.jpg took 0.5033863729986479 seconds to run

Connecting to https://i.postimg.cc/yNgPRr5v/t12.jpg ...
Downloading t12.jpg ...
[==================================================] 100.00%

OCR returns: 12-04-2022|★|★|日|4
Running OCR on https://i.postimg.cc/yNgPRr5v/t12.jpg took 13.14132212000186 seconds to run
9542
9543
Grabbing the full link at https://i.postimg.cc/qvjrSD3d/779.jpg took 0.3933821099999477 seconds to run

Connecting to https://i.postimg.cc/qvjrSD3d/779.jpg ...
Downloading 779.jpg ...
[==================================================] 100.00%

OCR returns: 18-04-2022|S|MBIJIHP|MBAIHP|W|E
Running OCR on https://i.postimg.cc/qvjrSD3d/779.jpg took 13.684743735000666 seconds to run
9543
9544
Grabbing the full link at https://i.postimg.cc/RFTN92sS/4467.jpg took 0.5054035189969 seconds to run

Connecting to https://i.postimg.cc/RFTN92sS/4467.jpg ...
Downloading 4467.jpg ...
[==================================================] 100.00%

OCR returns: 20-4-2022
Running OCR on https://i.postimg.cc/RFTN92sS/4467.jpg took 16.663768708000134 seconds to run
9544
9545
Grabbing the full link at https://i.postimg.cc/GphX6Wjv/2001.jpg took 0.4753381839982467 seconds to run

Connecting to https://i.postimg.cc/GphX6Wjv/2001.jpg ...
Downloading 2001.jpg ...
[==================================================] 100.00%

OCR returns: 26.07.2022
Running OCR on https://i.postimg.cc/GphX6Wjv/2001.jpg took 16.643207442000858 seconds to run
9545
9546
Grabbing the full link at https://i.postimg.cc/Jhn6fS3J/2006-unkn-vehicle-destr-31-12-23.jpg took 0.445761314000265 seconds to run
9546
9547
Returning non-postimg link
9547
9548
Grabbing the full link at https://i.postimg.cc/Hn0ndS94/2007-unkn-veh-destr.jpg took 0.4006106839988206 seconds to run

Connecting to https://i.postimg.cc/Hn0ndS94/2007-unkn-veh-destr.jpg ...
Downloading 2007-unkn-veh-destr.jpg ...
[==================================================] 100.00%

OCR returns: 14.10.2022|十|t.me/xronikabpla
Running OCR on https://i.postimg.cc/Hn0ndS94/2007-unkn-veh-destr.jpg took 27.34302801299782 seconds to run
9548
9549
Grabbing the full link at https://i.postimg.cc/VN6x5cGB/477.png took 0.3659495239990065 seconds to run

Connecting to https://i.postimg.cc/VN6x5cGB/477.png ...
Downloading 477.png ...
[==================================================] 100.00%

OCR returns: 06/11/2022|yn|NOBEPHYTbIE|NOBEPHyTbIE|HA BONHE|HA BONHE|863 vlews
Running OCR on https://i.postimg.cc/VN6x5cGB/477.png took 19.574851158002275 seconds to run
9549
9550
Grabbing the full link at https://i.postimg.cc/nr1bj67m/4318.png took 0.37440835400047945 seconds to run

Connecting to https://i.postimg.cc/nr1bj67m/4318.png ...
Downloading 4318.png ...
[==================================================] 100.00%

OCR returns: 06/11/2022|NOBEPHVTGIE|HA BONHE|9r|NOBEPHVTbIE|HA BOMHE
Running OCR on https://i.postimg.cc/nr1bj67m/4318.png took 18.527452811998955 seconds to run
9550
9551
Grabbing the full link at https://i.postimg.cc/FKjwYM0x/287.png took 0.38436872999955085 seconds to run

Connecting to https://i.postimg.cc/FKjwYM0x/287.png ...
Downloading 287.png ...
[==================================================] 100.00%

OCR returns: 20/6/2022|OCBEAOMNTE|HbIN|OCBeAoMNTe|t.me/milinfolive|t.me/milinfolive
Running OCR on https://i.postimg.cc/FKjwYM0x/287.png took 18.928593745997205 seconds to run
9551
9552
Grabbing the full link at https://i.postimg.cc/xdJMgQ6K/4366.png took 0.3919473419991846 seconds to run

Connecting to https://i.postimg.cc/xdJMgQ6K/4366.png ...
Downloading 4366.png ...
[==================================================] 100.00%

OCR returns: Br|OBO|6KC|6KO|PAC|HBr|OBO|6KC|6KO|PAC|130|60|60|130|16.0|106km/4|90|106KM/4|87|21/5/2022|5437987|5437987|7300400N|ynp|7300400M|ynp|AH|CK/O|ny|HABA|AC|CKAH|CKAO|ny|HABN|AC
Running OCR on https://i.postimg.cc/xdJMgQ6K/4366.png took 27.947780252001394 seconds to run
9552
9553
Grabbing the full link at https://i.postimg.cc/Fs3MkFsD/5g3.png took 0.3866899499989813 seconds to run

Connecting to https://i.postimg.cc/Fs3MkFsD/5g3.png ...
Downloading 5g3.png ...
[==================================================] 100.00%

OCR returns: RVvoenkory|16/11/2022|RVvoenkory|RusVesna SU
Running OCR on https://i.postimg.cc/Fs3MkFsD/5g3.png took 18.381119539000792 seconds to run
9553
9554
Grabbing the full link at https://i.postimg.cc/QCrq2DGd/f2f.png took 0.4486775139994279 seconds to run

Connecting to https://i.postimg.cc/QCrq2DGd/f2f.png ...
Downloading f2f.png ...
[==================================================] 100.00%

OCR returns: RVvoenkory|16/11/2022|-3.0|39|RusVesna SU|RVvoenkory|-3.0|39|RusVesna|SU
Running OCR on https://i.postimg.cc/QCrq2DGd/f2f.png took 19.880042382003012 seconds to run
9554
9555
Grabbing the full link at https://i.postimg.cc/5ynFsWfG/f2fo.png took 0.43872675400052685 seconds to run

Connecting to https://i.postimg.cc/5ynFsWfG/f2fo.png ...
Downloading f2fo.png ...
[==================================================] 100.00%

OCR returns: S0m9|17/11/2022
Running OCR on https://i.postimg.cc/5ynFsWfG/f2fo.png took 17.646448940999107 seconds to run
9555
9556
Grabbing the full link at https://i.postimg.cc/3wPcHfKr/47.png took 0.40093719300057273 seconds to run

Connecting to https://i.postimg.cc/3wPcHfKr/47.png ...
Downloading 47.png ...
[==================================================] 100.00%

OCR returns: RVvoenkory|14/11/2022|RusVesna|RVvoenkory|RusVesna SU
Running OCR on https://i.postimg.cc/3wPcHfKr/47.png took 18.31699446299899 seconds to run
9556
9557
Grabbing the full link at https://i.postimg.cc/BnFFVmwB/370.png took 0.37293870499706827 seconds to run

Connecting to https://i.postimg.cc/BnFFVmwB/370.png ...
Downloading 370.png ...
[==================================================] 100.00%

OCR returns: RVvoenko|14/11/2022|RusVesna|RVvoenkor|3|EE|RusVesnaSU
Running OCR on https://i.postimg.cc/BnFFVmwB/370.png took 18.894506331998855 seconds to run
9557
9558
Grabbing the full link at https://i.postimg.cc/J79Z5wpz/5879.png took 0.49924172399914823 seconds to run

Connecting to https://i.postimg.cc/J79Z5wpz/5879.png ...
Downloading 5879.png ...
[==================================================] 100.00%

OCR returns: 14/11/2022|56|901|-0.6
Running OCR on https://i.postimg.cc/J79Z5wpz/5879.png took 15.749730659998022 seconds to run
9558
9559
Grabbing the full link at https://i.postimg.cc/05Fc9zXP/438.png took 0.42492412900173804 seconds to run

Connecting to https://i.postimg.cc/05Fc9zXP/438.png ...
Downloading 438.png ...
[==================================================] 100.00%

OCR returns: 23/11/2022|0|Lme/razved_dozor
Running OCR on https://i.postimg.cc/05Fc9zXP/438.png took 18.55562119500246 seconds to run
9559
9560
Grabbing the full link at https://i.postimg.cc/JhSGsCfD/479.png took 0.3903563280000526 seconds to run

Connecting to https://i.postimg.cc/JhSGsCfD/479.png ...
Downloading 479.png ...
[==================================================] 100.00%

OCR returns: 23/11/2022|0|0.3|tme/razveddozor
Running OCR on https://i.postimg.cc/JhSGsCfD/479.png took 19.368570211998303 seconds to run
9560
9561
Grabbing the full link at https://i.postimg.cc/XqCKrg13/43770.png took 1.012136807999923 seconds to run

Connecting to https://i.postimg.cc/XqCKrg13/43770.png ...
Downloading 43770.png ...
[==================================================] 100.00%

OCR returns: 23/11/2022|0.2|0.3|t.me/razved|dozor
Running OCR on https://i.postimg.cc/XqCKrg13/43770.png took 18.436577216998558 seconds to run
9561
9562
Grabbing the full link at https://i.postimg.cc/KYLDHLBh/5590.png took 0.44042362099935417 seconds to run

Connecting to https://i.postimg.cc/KYLDHLBh/5590.png ...
Downloading 5590.png ...
[==================================================] 100.00%

OCR returns: RVvoenkory|RusVesna SU|RVvoenkory|05/12/2022|EEI|RusVesna SU
Running OCR on https://i.postimg.cc/KYLDHLBh/5590.png took 18.667303602000175 seconds to run
9562
9563
Grabbing the full link at https://i.postimg.cc/K8GfvVxC/265.png took 0.3681576929993753 seconds to run

Connecting to https://i.postimg.cc/K8GfvVxC/265.png ...
Downloading 265.png ...
[==================================================] 100.00%

OCR returns: 10/12/2022
Running OCR on https://i.postimg.cc/K8GfvVxC/265.png took 17.302254144997278 seconds to run
9563
9564
Grabbing the full link at https://i.postimg.cc/bY1908vK/f38.png took 0.5156661319997511 seconds to run

Connecting to https://i.postimg.cc/bY1908vK/f38.png ...
Downloading f38.png ...
[==================================================] 100.00%

OCR returns: gn|14/12/2022|NOBEPHyTbIE|HA BONHE|NOBEPHYTbIE|HA BOMHE
Running OCR on https://i.postimg.cc/bY1908vK/f38.png took 16.289984040999116 seconds to run
9564
9565
Grabbing the full link at https://i.postimg.cc/Xv1XW6wq/2002-2x-BMP-1s-BMP-2-BMP-1-2-T-64-BV-Zr-2017-T-72-AV-Unkn-Vehicle-destr-31-07-23.jpg took 0.5314785019982082 seconds to run
9565
9566
Grabbing the full link at https://i.postimg.cc/wBqwr1B5/6653.png took 0.4455610120021447 seconds to run

Connecting to https://i.postimg.cc/wBqwr1B5/6653.png ...
Downloading 6653.png ...
[==================================================] 100.00%

OCR returns: 18/7/2023|国|E
Running OCR on https://i.postimg.cc/wBqwr1B5/6653.png took 13.309672270999727 seconds to run
9566
9567
Grabbing the full link at https://i.postimg.cc/Sx0pWTx8/2002-Unknown-vehicle-destr-26-05-24.jpg took 0.42233695599861676 seconds to run
9567
9568
Grabbing the full link at https://i.postimg.cc/XYL7vr8h/2005-Unknown-vehicle-destr-03-04-24.jpg took 0.38366151999798603 seconds to run
9568
9569
Grabbing the full link at https://i.postimg.cc/kXJ72hS7/2010-Unknown-vehicle-dam-18-04-24.jpg took 0.3862301250010205 seconds to run
9569
9570
Grabbing the full link at https://i.postimg.cc/mZ0bWK1S/2002-Unknown-vehicle-destr-11-05-24.jpg took 0.45229623400155106 seconds to run
9570
9571
Grabbing the full link at https://i.postimg.cc/KjY4zZTn/2016-Unknown-vehicle-destr-14-05-24.jpg took 0.5073963670001831 seconds to run
9571
9572
Grabbing the full link at https://i.postimg.cc/ryPYtBwn/2016-Unknown-vehicle-destr-16-09-24.jpg took 0.4341578959974868 seconds to run
9572
9573
Grabbing the full link at https://i.postimg.cc/DzWbscSx/2018-Unknown-vehicle-destr-23-10-24.jpg took 0.43060066500038374 seconds to run
9573
9574
Grabbing the full link at https://i.postimg.cc/7Yw92PcK/2018-Unknown-vehicle-destr-17-12-24.jpg took 0.5010515110006963 seconds to run
9574
9575
Grabbing the full link at https://i.postimg.cc/Vsj4v07S/2019-Unknown-vehicle-destr-17-12-24.jpg took 0.4384775919970707 seconds to run
9575
9576
Grabbing the full link at https://i.postimg.cc/m26sf1pf/2015-Unknown-vehicle-destr-31-08-24.jpg took 0.41323712799930945 seconds to run
9576
9577
Grabbing the full link at https://i.postimg.cc/90kdczFK/2022-Unknown-truck-destr-31-01-25.jpg took 0.37541150999823003 seconds to run
9577
9578
Grabbing the full link at https://i.postimg.cc/y8pPjX6B/2012-Unknown-vehicle-destr-09-06-25.jpg took 0.3761287140005152 seconds to run
9578
9579
Grabbing the full link at https://i.postimg.cc/d3KjQT5b/2018-Unknown-vehicle-destr-24-07-25.jpg took 0.4136741419970349 seconds to run
9579
9580
Grabbing the full link at https://i.postimg.cc/zBbfbNTb/2008-unkn-vehicle-dam-30-01-24.jpg took 0.4494299830003001 seconds to run
9580
Saved at the end